### ISSUE TITLE
Tools/c_osx.py doesn't have a way to copy custom frameworks to the resulting bundle

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waf-project/waf#1302]
```
>> operating system:
OSX

>> waf version (or svn revision):
1.7.10

The attached patch proposes a `mac_frameworks' option for mac applications, 
which allows copying specified frameworks to the resulting bundle.  The method 
requires a new `copytree' method of Build class (to copy everything from the 
source bundle, including symlinks).

```

Original issue reported on code.google.com by `caw...@gmail.com` on 28 Apr 2013 at 5:14

Attachments:
* [0001-c_osx.py-extension-to-copy-local-frameworks.patch](https://storage.googleapis.com/google-code-attachments/waf/issue-1302/comment-0/0001-c_osx.py-extension-to-copy-local-frameworks.patch)

**Comment by ita1024** [comment]
This is probably solved in Issue 1586
