### ISSUE TITLE
waf clean doesn't remove directories that are not empty that were build targets

### ISSUE THREAD

**Issue by mattaw** [waf-project/waf#1556]
I have used waf to create a build system for tools that ouput a "library". This "library" is a directory on disk and the tools create and destroy mysterious files under the directory with no user involvement.

Waf clean doesn't currently remove a directory if it is a build target and if it has files underneath.

I am not entirely sure if this is a bug or a feature - please decide and amend appropriately.

PS Thanks for waf from an ex-SCons developer - I had replicated the functionality I built with SCons over several months in two days and finished the core in about two weeks.

**Comment by ita1024** [comment]
This is intentional: if waf has no data on the files present it will not remove them.

Either run "waf distclean" to do that, or add the functionality in either the build() function (if cmd=='clean') or in a subclass of CleanContext.

**Comment by mattaw** [comment]
Thanks! Do you have a link to that? I have been searching for several days for a clean way to extend the standard build / clean / install commands and the cmd=='clean' concept looks like a solution to the problem. 
Thanks, M

**Comment by ita1024** [comment]
In [The Waf Book](https://waf.io/book) search for CleanContext and for subclassing in general ("class one")
