### ISSUE TITLE
Project maintainer contact information

### ISSUE THREAD

**Issue by TheFriendlyCoder** [waf-project/waf#1557]
I just came across your project while looking for different build tools and had a few questions about this project, however I don't see any forums, contact information or anything that would help me direct my questions. Have I missed this information somewhere? If not could someone perhaps provide me with the information?

**Comment by ita1024** [comment]
Answers to technical matters or advice is only provided on public channels such as irc or the mailing-list so that the information is provided for everyone.

For other matters such as the website: tnagy@waf.io or webmaster@waf.io

Thomas

**Comment by TheFriendlyCoder** [comment]
Could you provide me with links for these contacts? I didn't notice any on the project web page or within the github project.

Thanks

Kevin

**Comment by ita1024** [comment]
https://waf.io/projects_using_waf.html for example
I received a message from one of your colleagues recently.

Thomas

**Comment by ita1024** [comment]
At the bottom of most pages (waf.io is still in construction):
https://waf.io/projects_using_waf.html
