### ISSUE TITLE
how to provide appropriate verb (Task.keyword)

### ISSUE THREAD

**Issue by jason-sachs** [waf-project/waf#1558]
[`Task.keyword`](https://github.com/waf-project/waf/blob/master/waflib/Task.py#L452) seems to be rather narrow-minded, assuming things like `Linking` and `Compiling` are the right ways to describe a task step.

	def keyword(self):
		name=self.__class__.__name__
		if name.endswith('lib')or name.endswith('program'):
			return'Linking'
		if len(self.inputs)==1 and len(self.outputs)==1:
			return'Compiling'
		if not self.inputs:
			if self.outputs:
				return'Creating'
			else:
				return'Running'
		return'Processing'

I am using other custom rules and would like to provide an appropriate verb in the display. How can I do this? There doesn't seem to be a keyword option. I would like to display "Stripping debug information" or "Copying" instead, rather than allowing waf to pick from the Linking/Compiling/Creating/Running set, since those are inaccurate.

    bld(rule='${STRIP} ${STRIPFLAGS} -o ${TGT} ${SRC}', source=library_internal, target=library)
    bld(rule='copy ${SRC} ${TGT}', source=library, target='gratuitous_copy.lib')

**Comment by jason-sachs** [comment]
I would like this behavior instead:

	def keyword(self):
		name=self.__class__.__name__
                # allow generator to override
		try:
		    return self.generator.verb
		except:
		    pass
		if name.endswith('lib')or name.endswith('program'):
			return'Linking'
		if len(self.inputs)==1 and len(self.outputs)==1:
			return'Compiling'
		if not self.inputs:
			if self.outputs:
				return'Creating'
			else:
				return'Running'
		return'Processing'

but I don't know how to repackage waf (we keep the "waf" script in source control, then it unpacks itself on each computer), and I don't know how to monkey-patch Task to do this after the fact.

**Comment by jason-sachs** [comment]
hmm... well, this monkeypatch works for me, but I want to know the right way to do what I want.

```
def monkeypatch_task_keyword():
    import waflib
    kw0 = waflib.Task.Task.keyword
    def kw1(self):
        try:
            return self.generator.verb
        except:
            return kw0(self)
    waflib.Task.Task.keyword = kw1
```

**Comment by ita1024** [comment]
That way is fine, but can affect other classes. Something more accurate would be:

        bld(rule='echo ${ST:FOO}', always=True, shell=1, features='name_groking')

        from waflib import TaskGen
        @TaskGen.after('process_rule')
        @TaskGen.feature('name_groking') # slightly longer but more accurate than '*'
        def bind_names(self):
                if not getattr(self, 'rule', None):
                        return
                def keyword(self):
                        return "Groking"
                self.tasks[-1].__class__.keyword = keyword

A task class has nothing to do with a generator, so I am not convinced that the functionality should be provided as you described above. Data could be obtained from a tsk.env for instance.

Note: replace "except:" by "except AttributeError" and it should be alright.

**Comment by jason-sachs** [comment]
Hmmm. I don't quite understand your intent... so `bind_names` runs in all tasks that have generators with the `name_groking` feature? I guess the issue here is that `name_groking` represents an extra level of (unnecessary?) indirection. If I have several rules:

   bld(rule='compute_capital_gains ${SRC} ${TGT}', always=True, shell=1, verb='Computing capital gains')
   bld(rule='fix_errors ${SRC} ${TGT}', always=True, shell=1, verb='Fixing errors')
   bld(rule='file_taxes ${SRC}', always=True, shell=1, verb='Filing taxes')

then the verb (or to generalize, the display specification) is appropriately specified at the point of declaring the rule itself. Not sure how to do this with the `@TaskGen.feature` approach, unless I create separate ones for each rule that needs a custom verb.

**Comment by ita1024** [comment]
No, bind_names is used by task generators (not tasks) that have the corresponding feature. This provides a better separation of concerns than changing the default class.
