### ISSUE TITLE
deleted issues?

### ISSUE THREAD

**Issue by jason-sachs** [waf-project/waf#1559]
Why are all the issues before #1296 deleted? I was searching for something about INCPATHS in google and it pulled up issue #929 but the details are now deleted :-1:

**Comment by ita1024** [comment]
This is due to the move to github.

Thomas

**Comment by jason-sachs** [comment]
so they were deleted earlier prior to the github migration? or the migration from google code caused them to be deleted?

**Comment by johan-boule** [comment]
No idea, but trying to migrate again today causes the following error :

> Aw, Snap!
> 
> There was an error migrating waf to GitHub.
> 
> The error is as follows:
> 
> Project: waf
> Error migrating issues.
> 
> You can delete the GitHub repo and export the project again, read our FAQ for any known issues, or contact Google for assistance.

This is the "price to pay" when you give up control/maintenance of your data to a free service hosted by a company. It's only okay as long as they care.

**Comment by kirbyfan64** [comment]
Why not contact for assistance...

**Comment by ita1024** [comment]
https://waf.io/apidocs/tools/ccroot.html?highlight=apply_incpaths#waflib.Tools.ccroot.apply_incpaths
