### ISSUE TITLE
Generating MSVS project through Cygwin

### ISSUE THREAD

**Issue by Basez** [waf-project/waf#1562]
I am a Windows based developer and just started to work with waf. At the moment I created a very simple c++ project that can be build and linked into an executable. The next step for me is to generate a visual studio project, however I encountered an issue which I am currently unable to solve.

I tried generating a visual Studio project through cygwin64, using the ./waf configure msvs command.  This process works mostly just fine and generates absolute paths inside the .vcxproj files. The problem lies in the fact that it uses unix paths since it is done through cygwin. This means a path will be "/c/projects/myproject/myproject.vcxproj" instead of "c:\projects\myproject\myproject.vcxproj" which visual studio doesn't understand. This seems like an easy thing to fix but this can become tedious very quickly if you have to scan through all the files each time you generate a project!

Is there any workaround currently available? I couldn't find much help on the internet, it seems to be a Cygwin related issue.

**Comment by ita1024** [comment]
Try rde6b9bde38c0ada782984beafa0cb77893913e78

**Comment by Basez** [comment]
Yes that fixed the issue! Thanks for the quick response and fix :)
