### ISSUE TITLE
Create lockfile in out directory

### ISSUE THREAD

**Issue by lilrc** [waf-project/waf#1563]
I would like to suggest that the lockfile should be created in the out directory (the one given with the `--out` argument). This would make it possible to compile multiple builds from the same source directory simultaneously without copying (or hardlinking) the source directory.

This feature would make it possible to write-protect the entire source tree to ensure that no build alters the sources, which is a nice QA feature.

AFAIK both CMake and autotools have this feature.

**Comment by ita1024** [comment]
It is up to the project to set that up:
        conf.env.NO_LOCK_IN_RUN = True
        conf.env.NO_LOCK_IN_TOP = True
etc.

**Comment by lilrc** [comment]
Wouldn't it be better to change the default to putting the lockfile in the out directory? Why is putting it in the toplevel source directory preferred?

I would like to motivate my view a little further. Downstream at Gentoo our package manager compiles our packages from source on the computers that are to run them (source based distribution as opposed to binary based distro). Sometimes it is necessary to compile our packages for both 32-bit and 64-bit. This is done in the way I pointed out. As downstream one of the following is in that case necessary:

(1) Patch the build system for each package that is not aware of the NO_LOCK_IN_* options. This is a rather big maintainence burden.
(2) Change the default to putting it in out directory so that the packages that insist on putting it in top can be isolated.
(3) Introduce a switch (environment var, or option) so that we can explicitly specify exactly where the lockfile is.
(4) Copy the source tree.

I do prefer (2) since it is less work and a clean default. (1) is just a lot of work. (3) is good but requires more knobs and code (which can be somewhat noisy if it is an option). (4) is just stupid; imagine the situation for large projects. We currently do (4), though.

**Comment by ita1024** [comment]
The main workflow for developers is "waf configure" and then just "waf". Not writing a lock file would force developers to either:
* run "waf" in the build directory or
* or to always provide a command-line switch such as --out=".."
This is undesirable.

The safest option is indeed to copy the source tree. Even though a build directory encourages users to do the right thing, quite a lot of projects will still write files in the source directory.

The lock files in the top-level pose no problems can only occur on incremental builds: just run all the commands at once "waf configure build" instead of "waf configure; waf build". Some simplification can be made so that the command is run at once, for example "waf configure --top=/foo --out=bar" can now be executed from any folder (d4ec554cdfeaff2b582b91442753d14081f5c29e)

**Comment by lilrc** [comment]
Isn't it possible to check whether the current directory is a source directory and in that case use the lock in the default build directory. This would not force devs to do any of the measures you mentioned at the same time it would be possible to create the lockfile in the out directory by default. The check could be something like this (this is some kind of python-pseudocode):

```python
if directory_has_a_wscript:   
    # this directory is a source directory, building in source directories is bad
    use_lock_in_dir(default_build_directory)
else:
     # this directory is somewhere else so it must contain a lock
     use_lock_in_dir(current_directory)
```

**Comment by ita1024** [comment]
No, the lack of lock file would create additional problems:
* variants: without lock file, running "waf configure --out=myvariant" would have no effect on subsequent execution. There is no way to know what was configured.
* multiple configurations and partial builds: with several wscript files in a tree, finding out which project should be built is guaranteed to be ambiguous. When calling waf from a sub-folder, only the targets below that folder should be built.

As I mentioned earlier, a lock file is *NEVER* a problem for concurrent build processes:
* commands can be chained (waf configure build) to avoiding reliance on a lock file
* or commands can be executed by using the build directory lock file (waf configure; cd build; waf build)

The only case where writing a lock file might be annoying is Selinux-like access controls. A switch for conf.env.NO_LOCK_IN_TOP might be an idea, try:
"waf configure --top=/foo --no-lock-in-top --no-lock-in-run --out=/bar configure build"
with 9fdfec763dcb9765d7838bcff90487f6411d7b18

**Comment by lilrc** [comment]
Works like a charm! That addresses my initial problem! Thank you!

**Comment by hmijail** [comment]
This was an instructive discussion! IMO, how/why the lock file is used by waf should be better documented in the waf book (why is it even called a lock file? it doesn't seem to lock anything). 

Also, it doesn't mention that the build directory does contain a lock file, which opens the great possibilities of "waf configure -o mybuild; cd mybuild; waf mybuild" and of pointing WAFLOCK to the lock file in the build directory.
