### ISSUE TITLE
exec_cfg() lacks examples

### ISSUE THREAD

**Issue by MoSal** [waf-project/waf#1565]
hello.

Unlike check_cfg(), I can't find an example of exec_cfg() usage anywhere.

I can't get check_cfg() to work. Always getting unexpected keyword argument errors.

Maybe I'm missing something obvious. But having at least one working example as a starting point would be very helpful.

**Comment by ita1024** [comment]
The function "exec_cfg" is low-level, it is hardly ever used directly.

Read your config.log file? [check_cfg](https://waf.io/apidocs/tools/c_config.html?highlight=check_cfg#waflib.Tools.c_config.check_cfg) works for us.

**Comment by MoSal** [comment]
Thank you.
Reading the source of check_cfg() helped. And I got it working.

I'm using exec_cfg() to get the includedir using the variables parameter. I'm not aware of a better way to get the value of that variable.

**Comment by ita1024** [comment]
conf.check_cfg(package='gtk+-2.0', variables=['includedir', 'prefix'], uselib_store='FOO')
        print(conf.env.FOO_includedir)

**Comment by MoSal** [comment]
Thank you for clarifying.
This issue can be closed.
