### ISSUE TITLE
duplicated LINKFLAGS if both C and C++ compilers are configured

### ISSUE THREAD

**Issue by che2** [waf-project/waf#1574]
The contents of LINKFLAGS or LDFLAGS environment variables are duplicated if both a c compiler and a c++ compiler are configured using:

    def configure(ctx):
        ctx.load('compiler_c')
        ctx.load('compiler_cxx')

The reason is that both of the c and c++ compiler plugins (say gcc.py and gxx.py) calls the function conf.link_add_flags(), which is defined in c_config.py:

    def link_add_flags(conf):
        """
        Add LINKFLAGS / LDFLAGS from os.environ to conf.env
	"""
        conf.add_os_flags('LINKFLAGS')
        conf.add_os_flags('LDFLAGS')

This results in LINKFLAGS being added twice to ctx.env.

    $ LINKFLAGS='-lblah' waf configure
    $ cat build/c4che/_cache.py
      ...
      LINKFLAGS = ['-lblah', '-lblah']
      ...

**Comment by ita1024** [comment]
Does this actually pose a problem?

**Comment by che2** [comment]
This is not a deal breaker,  but it is confusing and obtrusive to debugging by unnecessarily increasing the length of the link line.  I think changing the behavior so that the LINKFLAGS is no longer duplicated makes a lot of sense.

**Comment by che2** [comment]
I have attempted to create a fix at #1575.  The fix simply prevents flags from being imported more than once. I think this should be safe, as I can't think of a reason why you would want to ever duplicate an environment flag.

**Comment by ita1024** [comment]
That pull request introduced a new problem and changed the meaning of "add_os_flags". Adding a new parameter is necessary, try f048d6d20f3b274e65d397ee87b25927346f0ff5

**Comment by che2** [comment]
Confirmed that commit f048d6d works. Thanks.
