### ISSUE TITLE
Could Fortran scans create dependencies instead of just "sorting" the already declared ones?

### ISSUE THREAD

**Issue by azag0** [waf-project/waf#1576]
Hi, I learned about waf two days ago and it's amazing.

I'm involved in a ~400k Fortran scientific codebase. (It is a mess.) Is there some design decision for why the module dependencies are only returned abstractly as `USE@module` and then used in the `runnable_status` method as opposed to explicitly returning dependency on `*.mod` nodes which could then potentially trigger an extension chain `.f90 -> .mod`? Am I wrong that this would be potentially more general as in the absence of such a chain rule, current behaviour would be retained (all dependencies must be declared) and with such a rule, the module dependencies would be declared automatically?

I'm really new to the waf codebase, so I'm not sure whether I didn't miss something fundamental.

**Comment by ita1024** [comment]
Parallel builds: Fortran .mod files can be both produced and consumed, so the build order must be calculated first.

**Comment by azag0** [comment]
Ah, I didn't realize that the `scan` function is called by the individual `Runner`s. Do you see some efficient way how to reuse the already existing scanning code to pre-scan the input Fortran source files to generate the tasks for the module dependencies? I think I could do the actual programming, I would just need hints how to assemble the pieces.

**Comment by ita1024** [comment]
Which tasks do you want to generate? Have you tried the examples in demos/fortran?

**Comment by azag0** [comment]
Yes, I have. And I have already successfully compiled the big project with waf. But currently, I'm creating tasks for all the relevant fortran source files, including the . I was wondering whether it would be possible to create manually just tasks for the program file and files containing non-module subroutines and let waf automatically figure out which fortran source files containing modules should be compiled and linked as well.

Say I have a program in `main.f90` which uses a module in `module.f90`. What would need to be added to waf to be able to create just `ctx(source='main.f90', target='program')` and let waf figure out that it should also compile and link `module.f90`?

**Comment by ita1024** [comment]
The description seems to match the case in playground/dynamic_recursive_tasks/wscript

Such practice is discouraged as it creates unnecessary coupling to the source files and makes the build process difficult to understand.

**Comment by azag0** [comment]
Thanks for the tip! Can be closed. Btw, is there a better place to raise such questions which aren't exactly issues? Or is it fine here?

P.S. Yes, I realise it's not a very systematic approach. But that's how our build process works now and if I'm to "sell" waf to the main package maintainer, I will first have to demonstrate that it's easily as powerful as the current build process.

**Comment by ita1024** [comment]
Prefer the mailing-list for questions.
