### ISSUE TITLE
Error building protoc target in a directory

### ISSUE THREAD

**Issue by jchia** [waf-project/waf#1579]
1. Setup test case source directory by cloning from https://github.com/jchia/badprotoc.
2. waf configure
2. Use waf to build targets Foo, bar/Bar and bar/Baz respectively, and see that everything works except bar/Bar. Somehow a protoc target fails to build if it's in a directory. Even the C++ target in a directory, bar/Baz builds successfully.

$ ~/src/waf/waf --target Foo
Waf: Entering directory `/home/jchia/git/badprotoc/build'
[1/2] Processing Foo.proto
[2/2] Compiling build/Foo.pb.cc
Waf: Leaving directory `/home/jchia/git/badprotoc/build'
'build' finished successfully (0.209s)

$ ~/src/waf/waf --target bar/Bar
Waf: Entering directory `/home/jchia/git/badprotoc/build'
[1/2] Processing bar/Bar.proto
Waf: Leaving directory `/home/jchia/git/badprotoc/build'
Build failed
-> missing file: '/home/jchia/git/badprotoc/build/bar/Bar.pb.cc'

$ ~/src/waf/waf --target bar/Baz
Waf: Entering directory `/home/jchia/git/badprotoc/build'
[1/1] Compiling bar/Baz.cpp
Waf: Leaving directory `/home/jchia/git/badprotoc/build'
'build' finished successfully (0.030s)

**Comment by ita1024** [comment]
f6b61914806d4ed664cfa1394c8d781282257322

**Comment by ita1024** [comment]
This is likely to be broken on Gentoo due to compiler limitations.
