### ISSUE TITLE
Static linkage of qt4 bindings?

### ISSUE THREAD

**Issue by rr-** [waf-project/waf#1588]
Like in title - when I try to cross compile Qt project to Windows against static Qt libraries, I get errors from i686-w64-mingw32-g++ that it can't find `_imp_whatever`. This is because I don't have dynamic libraries. How can I tell waf to use static qt4 libraries rather than dynamic ones?

Is it possible at all?

My wscript looks mostly like this: https://github.com/waf-project/waf/blob/master/demos/qt4/wscript

**Comment by ita1024** [comment]
The Qt detection is imperfect.

Inspect the config.log file should be a start point. As a workaround, look into the related variables:
print(conf.env) or read the _cache.py file.

To add the library, either complete the relevant variables:
  conf.env.append_value('QTCORE_STLIB', 'whatever.lib')
use the lowercase attributes:
  bld(..., stlib=..., stlibpath=...)
or define the environment variables LDFLAGS/LINKFLAGS

As it is, we cannot take any action.

**Comment by rr-** [comment]
After I compiled also shared version of qt, it works fine. Requiring both builds of qt to be available in order for detection to work properly is reasonable and I don't mind it.

However I still wish it used static version rather than dynamic one. I believe I could do it either via:

- tell waf's qt4 to pass `--static` option to `pkg-config`
- rather than adding `uselib = 'QTCORE QTGUI QTOPENGL QTSVG'`, use some other directive
- or rather than using `uselib = ='QTCORE ...'`, have `uselib = 'QTCORE_STLIB'`, but this causes compilation error (it can't find `QApplication` in `#include` statements).

I'm not sure which approach is the right one and what options/strings to use. I'd like to avoid detecting qt on my own, if possible. Given the correct options that  "should work" i.e. should link to static version, I'll be able to work my way through any other errors.

Thanks

**Comment by ita1024** [comment]
A fix for Qt5 is present in ef0cf35cb10956ac57030a093d8063226f270dda
Re-open if you need a backport for Qt4
