### ISSUE TITLE
Building in subdirectory broke in 1.8.10

### ISSUE THREAD

**Issue by aaron628** [waf-project/waf#1590]
I believe that this change: https://github.com/waf-project/waf/commit/d4ec554cdfeaff2b582b91442753d14081f5c29e broke the 'climb' code to find the root of the build tree when in a subdirectory containing a 'wscript' file.

I think instead of:
```
while cur and not Context.run_dir:
    ...
```
what was probably meant was:
```
if not Context.run_dir:
    while cur:
        ...
```
because if you're in a directory with a wscript then within the loop Context.run_dir gets set and the loop exits before finding the lockfile.

A very simple 2-level wscript shows that this worked in 1.8.9 and stopped working in 1.8.10.

**Comment by ita1024** [comment]
Or rather, Context.top_dir
