### ISSUE TITLE
enforcing minimum Vala version documented incorrectly

### ISSUE THREAD

**Issue by dffischer** [waf-project/waf#1594]
[The docstring of the vala tool configuration function](https://github.com/waf-project/waf/blob/master/waflib/Tools/vala.py#L315) states that a minimum version of the compiler should be ensured by skipping this configuration function and instead invoking `check_vala` manually. However, this also skips `load('gnu_dirs')`, `check_vala_deps()` and the setting of expected `VALAFLAGS`. The latter breaks compilation since 1e08320.

I suggest to fix this by removing the call to `check_vala` from the `configure` function, passing responsibility to invoke it to the user and document this in the module docstring. Then, skipping the `configure` function would not be necessary any more. Other tools already use this approach. [Python](https://github.com/waf-project/waf/blob/master/waflib/Tools/python.py#L14) for example expects `check_python_version` and `check_python_headers` to be called.

This comes at the costs of a slight API break, as all users of the Vala tool have to add `check_vala()` to their configuration functions after load('vala'). If this is alright, I would continue to implement the the former paragraph and file a pull request.

**Comment by ita1024** [comment]
No API changes can happen before waf 1.9. You may use conf.env values though.

**Comment by ita1024** [comment]
The following does not require any change to the API and can be backported to waf 1.8:
89ac2f0215de62b2f3fc170a9693a810949a09dd

What do you think?

**Comment by ita1024** [comment]
Waf 1.9.0 was released so we can close this now.
