### ISSUE TITLE
Generated doxygen output is installed twice if another build group is added

### ISSUE THREAD

**Issue by q-p** [waf-project/waf#1596]
When installation of generated doxygen combination is used in combination with another build-group (which is done in the swig-playground for example so the generated python files can be installed using feature='py'), then the files are installed twice (if the group is added after the doxygen build command).

See the following example adapted from the playground to reproduce the issue.

```python
from waflib import Build
def build(bld):
	# if the documentation is to packed, simply set doxy_tar to the filename
	bld(
		features='doxygen',
		doxyfile='test.conf',
		install_path='${PREFIX}/doc')

	# another group, e.g. as required by swig when installing its python files
	bld.post_mode = Build.POST_LAZY
	bld.add_group()

	# and additional targets
	bld(features='cxx cxxshlib', source='subdir/c.cpp', target='somelib')
```

**Comment by ita1024** [comment]
Update your copy 4949c0d894ccd4cc679b47d6fdc5993a5a5d7075

**Comment by ita1024** [comment]
reopen if still broken
