### ISSUE TITLE
Issue with detection of -march=native

### ISSUE THREAD

**Issue by rivanvx** [waf-project/waf#1597]
Hello,

we recently upgraded ns-3 to Waf 1.8 from 1.7. Waf 1.7 and 1.8 differ in detection of -march=native as supported compiler flag. Specifically, on KVM virtual machine running Ubuntu 14.04 the results are:

* Waf 1.7: Checking for compilation flag -march=native... support : not found
* Waf 1.8: Checking for compilation flag -march=native... support : ok

The related ns-3 thread is here: http://mailman.isi.edu/pipermail/ns-developers/2015-July/012889.html

Any ideas? Is this a Waf bug, or is this a bug in our wscripts? If it is a bug in wscripts, what would be the way to fix it and avoid detecting we are running GCC <4.9 inside a KVM virtual machine?

**Comment by ita1024** [comment]
Do you have the config.log file by any chance?

**Comment by rivanvx** [comment]
I have reached out to Hajime Tazaki on ns-developers thread to see if he can provide it.

**Comment by ita1024** [comment]
I see it now - there is an "env" object but it is not even used:
retval = conf.check(compiler=mode, fragment='int main() { return 0; }', features='c', env=env)

Do not forget to read the config.log file!

**Comment by rivanvx** [comment]
So, our wscript is wrong here? How do I fix it? Also, what made Waf 1.7 work correctly?

**Comment by ita1024** [comment]
Highlighted in *bold* above.

**Comment by ita1024** [comment]
Oh, and the code looks wrong for Waf 1.7 too.

**Comment by rivanvx** [comment]
Sorry, I just noticed we used conf.run_c_code() instead of conf.check() while we used Waf 1.7. Thanks for your help.

**Comment by ita1024** [comment]
*run_c_code* has been replaced by *run_build* in waf 1.8 so that [full builds](https://waf.io/apidocs/tools/c_config.html#waflib.Tools.c_config.check) can be declared in [configuration tests](https://github.com/waf-project/waf/blob/master/demos/tex/wscript#L20)
