### ISSUE TITLE
check_cfg and check_cc leave inconsistent environment

### ISSUE THREAD

**Issue by rr-** [waf-project/waf#1600]
Running `check_cfg` like this:

    ctx.check_cfg(
        package = 'libpng',
        args = '--cflags --libs',
        uselib_store = 'LIBPNG',
        mandatory = True)

Defines `HAVE_LIBPNG` inside `env` like so:

    'HAVE_LIBPNG' 1

At the same time, running `check_cc` like this:

    ctx.check_cc(
        header_name = 'Windows.h',
        uselib_store = 'WINDOWS',
        mandatory = False)

Defines `HAVE_WINDOWS_H` inside `DEFINES` like so:

    'DEFINES' ['HAVE_WINDOWS_H=1']

These are inconsistent. In case of `check_cc`, it is difficult to test the configuration without doing some parsing. (The test is feasible when manually deciding which modules to compile.)

**Comment by rr-** [comment]
Additionally I'm not sure how to compile modules conditionally: I use `uselib_store` and then `use` that inside an `.objects` group, but when that module is unavailable, the group is still compiled.
For now, I check for `env.HAVE_X` and `env.DEFINES['HAVE_*=1']` inside `wscript`, but this feels wrong.

**Comment by ita1024** [comment]
The inconsistency will be resolved in Waf 1.9. Passing "global_define=True" to conf.check_cfg lifts the ambiguity (call conf.get_define('HAVE_LIBPNG_H')).

The build section should not require changes when libraries are missing. The recommended approach is to configure conditionally by catching exceptions and adding sub-routines.

Headers detection was provided as a limited compatibility with autoconf detection macros, but the approach does not really work in practice. If possible, prefer code fragments or [write more elaborate tests](https://github.com/waf-project/waf/blob/master/demos/tex/wscript#L20).

**Comment by rr-** [comment]
>The build section should not require changes when libraries are missing.

This is what I'd like to achieve, but how can I tell waf not to compile `optional_module.c` if its dependency is missing? I can think of two use cases:

1. OS specific implementations

    - `module.h`
    - `module_win32.c`
    - `module_linux.c`
    - `module_osx.c`

2. Optional plugins

    - `plugin_twitter.c` (that depends on OpenSSL)
    - `plugin_http.c` (that depends on some JSON library)
    - etc.

    and inside some `plugin_container.c`, reference them with preprocessor checks:

        Plugin plugin[] = {
        #if HAVE_OPENSSL
            TwitterModule....
        #endif
        #if HAVE_SOME_JSON
            JsonModule...
        #endif
        }

    (at least that's the approach I'm used to, I wonder if there are better implementations...)

>The recommended approach is to configure conditionally by catching exceptions and adding sub-routines.

Then, should I do:

    try:
        bld.objects(source='module_win32.c', ...)
    except:
        pass

or should I filter the source files out at `configure()` level? (This sounds bad, because I'd need to reconfigure the project every time new files are added.)

>The inconsistency will be resolved in Waf 1.9. Passing "global_define=True" to conf.check_cfg lifts the ambiguity (call conf.get_define('HAVE_LIBPNG_H')).

Thank you.

**Comment by ita1024** [comment]
The comment on catching exceptions was meant for configuration tests.

The configure() level should set the relevant defines for point 2 (config.h or other). The build section should list the same files if possible as that eliminates a source of platform-specific build issues. There general guidelines can reduce complexity but other approaches are also possible.

**Comment by ita1024** [comment]
uselib_store and define_ret are also inconsistent - to be fixed in waf 1.9

**Comment by ita1024** [comment]
Waf 1.9.0 was released today, so we can finally close this.
