### ISSUE TITLE
Build fails when two targets have common sources for the vala plugin

### ISSUE THREAD

**Issue by arteymix** [waf-project/waf#1601]
I already investigated the bug and it happens to be related to moved files in the `valac` task. If one task moves the file, the other will fail doing so.

Here's the line: https://github.com/waf-project/waf/blob/master/waflib/Tools/vala.py#L35

Here's the trace:

```
Waf: Leaving directory `/home/guillaume/Projets/valum/build'
Build failed
Traceback (most recent call last):
  File "/home/guillaume/Projets/valum/.waf-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Task.py", line 110, in process
    ret=self.run()
  File "/home/guillaume/Projets/valum/.waf-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Tools/vala.py", line 20, in run
    shutil.move(self.outputs[0].parent.abspath()+os.sep+x.name,x.abspath())
  File "/usr/lib64/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/guillaume/Projets/valum/build/cookies.c'
```

I attempted to fix the issue by replacing `shutil.move` with `shutil.copy`, but I think it can be better solved with correct dependency handling.

**Comment by ita1024** [comment]
With the following 8ba068670a973f6064faad104d8a37bb6f5abccd it is possible to add a `vala_dir` parameter to output the files in a separate folder. See https://github.com/waf-project/waf/blob/master/demos/vala/stlib/wscript_build#L11

**Comment by arteymix** [comment]
Reusing `directory` as a name to reflect the option was not possible?

The initial problem still persist though, but I like to have the option, especially as it will speed up the build by avoiding unnecessary move operations.

I'll use that for now, thanks ;)

**Comment by ita1024** [comment]
The name "directory" is too common. This one is specific to vala.

Regarding the initial problem:

1. Speeding up the build by sharing tasks would mean that:
    * This assumes that the vala outputs will be exactly the same for a given vala file when producing a program/library, currently or in the future. There is no such guarantee.
    * This also assumes that task generators must be sharing vala task information implicitly. This has an impact on partial builds with `--target` (point 1 further below).
2. Creating intermediate folders automatically assumes a dependency between task generators with would either:
    * Force to always create an intermediate directory based on some sort of hash. This will break existing builds that assume a particular position for the header files. Devising a suitable hash function is also problematic.
    * Or force posting all vala task generators to see if a vala file is shared (one cannot know before the build starts)

The current change can already introduce issues for existing projects: vala files are now processed on a folder basis and not from the existing folder structure anymore. There is a minor risk that existing builds depend on this, but I think that this is a good trade-off.

**Comment by arteymix** [comment]
The speedup was more related to the idea that we let `valac` produce the files directly where they should be rather than moving them.

It's perfectly understandable that we cannot share the result of two different tasks as there's no guarantee they would produce the same output.

I have integrated the change and it works really nicely. I can now run Valum's tests and examples seamlessly.
