### ISSUE TITLE
gccdeps fails to handle some paths with .. components

### ISSUE THREAD

**Issue by mattfischer** [waf-project/waf#1602]
This is a very specific edge case, but it comes up quite a bit in some of the generated files that we use in our project, so it's a problem that I need to find a solution to.  When gccdeps is processing an include path which uses '..' to escape from the build directory and go down into the source directory, it's possible for the file lookup to fail.

As a concrete example, say we have a header file `foo/header.h`, and a generated .c file `build/foo/generated.c`, which says `#include "../../foo/header.h"` in it.  The dump from GCC will list the file dependency as `"foo/../../foo/header.h"`, since it is operating relative to the root of the build tree.  The code in gccdeps will then try to call bldnode.find_resource() on this string.

Here's the problem:  since we're searching from the build node, find_resource() will do a simple search_node(), which doesn't actually check the disk, it assumes that the nodes are already in the node tree.  That's a good assumption for the build nodes, but since we ..'ed out to the source tree, it's possible that nobody put `foo/header.h` into the node tree yet.  To be sure that the lookup succeeds, we would instead need find_resource() to actually call find_node(), to go search disk for the file.

My immediate fix was just to change gccdeps to call find_node() instead of find_resource(), which guarantees that it will always search disk, and find any files that weren't already in the node tree.  I'm not sure if that is the correct fix or not--it seems like the real issue is that find_resource() should be smart enough to realize that it's actually looking in the source tree after processing all of the ..'s, and switch over to a mode where it actually examines the disk for files.  However, that would be a bigger change and I'm not sure if there would be any side effects from doing it.  Any thoughts on how best to solve this problem?

**Comment by ita1024** [comment]
Calling find_node will be slow.

It would be best to simplify the ".." paths first, call "find_resource" and fallback to "find_node" only if really necessary. Start by preparing a testcase.

**Comment by ita1024** [comment]
Are you generating headers without declaring them to the build? Prepare a testcase first.

**Comment by mattfischer** [comment]
The headers are regular headers in the source tree, not generated files.
The problem is that the ..'s can allow the path to escape the build
directory and enter the source directory.

It does look like the problem could be solved by handling all of the ..'s
before calling find_resource, which is basically what the code around line
137 is trying to do.  That code only handles ..'s at the beginning of the
path, though, not in the middle.  I'll try modifying that code so that it
can handle them in the middle as well, and see if that fixes my problem.

**Comment by ita1024** [comment]
Testcase please.

**Comment by mattfischer** [comment]
Here's a test case which exhibits the problem:

###### wscript
```
def configure(cfg):
    cfg.load('gcc gccdeps')

def build(bld):
    bld.recurse('foo')
```

###### foo/wscript
```
from waflib.TaskGen import feature, before_method
from waflib import Utils, Task

class make_generated(Task.Task):
    def run(self):
        self.outputs[0].write('#include "../../foo/header.h"')
        return 0

@feature('generated')
@before_method('process_source')
def make_file(tgen):
    output = tgen.path.find_or_declare('generated.c')
    tgen.create_task('make_generated', None, output)

    tgen.source = Utils.to_list(getattr(tgen, 'source', []))
    tgen.source.append(output)

def build(bld):
    bld.program(target='test', source='test.c', features='generated')
```

###### foo/test.c
```
int main(int argc, char *argv[])
{
	return 0;
}
```

###### foo/header.h
```
/* Blank */
```

When this is run with the current gccdeps tool, it fails with the error:

```
Build failed
Traceback (most recent call last):
  File "d:\Projects\temp\waf-gccdeps-test\waf-1.8.0-2901d0a54bc6fba8679cf0cea043cf31\waflib\Task.py", line 119, in process
    self.post_run()
  File "d:\Projects\temp\waf-gccdeps-test\waf-1.8.0-2901d0a54bc6fba8679cf0cea043cf31\waflib\extras\gccdeps.py", line 82, in post_run
    raise ValueError('could not find %r for %r'%(x,self))
ValueError: could not find ['foo', '..', '..', 'foo', 'header.h'] for
        {task 40175248: c generated.c -> generated.c.1.o}
```

Following your suggestion to make it handle .. within paths, I think I've developed a fix that will work.  Have a look at https://github.com/waf-project/waf/pull/1604 and let me know if you think it's right.

**Comment by ita1024** [comment]
The pull request has been merged.

Thanks
