### ISSUE TITLE
Fortran build without features="fc" fails with "no attribute 'includes_nodes'"

### ISSUE THREAD

**Issue by mbeachy** [waf-project/waf#1603]
Without an explicit features="fc", an attempt to build an object file fails with "'task_gen' object has no attribute 'includes_nodes'". This is despite the fact that Tools/fc.py is found and being used.

One fix for this (that works) is to add checks for Fortran file suffixes in [sniff_features](https://github.com/waf-project/waf/blob/92f584fd8f4319d45b9f51e5c76af4197870eda3/waflib/Tools/c_aliases.py#L28) and I can post a pull request to add this. I don't know if this is the _right_ fix, or if some modification to the fc class(es) or simply a more helpful error message is more appropriate.

**Comment by ita1024** [comment]
Adding features="fc" is necessary. There are many cases where the aliases (bld.program/bld.shlib) are unable to detect what the intention is.

Modifying sniff_features can be a possibility for fortran applications, but which linker should be used in programs/libraries mixing fortran, c and c++?

**Comment by mbeachy** [comment]
If a program library mixes all three then the c++ linker is necessary. If it's just fortran/c then the c linker suffices. Linking in some fortran libraries explicitly in either case is often required.

**Comment by mbeachy** [comment]
Eh, maybe I spoke too soon. It looks like we're using fortran for linking shared libs on Linux, c++ on Windows.

**Comment by ita1024** [comment]
Ok. There does not seem to be any change required then.

**Comment by ita1024** [comment]
Re-open if this is not the case.

**Comment by mbeachy** [comment]
An alternate approach to this; improve error reporting: https://github.com/waf-project/waf/pull/1610

I see now that it was probably not intended for bld.program, shlib etc. to be used with Fortran. In that case the error reporting can be modified, but some extension of it would be much appreciated.
