### ISSUE TITLE
clang_compilation_database fails when compilation fails

### ISSUE THREAD

**Issue by kuchars** [waf-project/waf#1606]
I've wanned to get clang compilation database for a project to run include-what-you-use but it didn't work because my project did not link successfully. So I've checked what I could and it looks like everything worked except running write_compilation_database at the end of compilation even if it fails.

So for example if the initial compilation of a project (or after addition of few new files) something fails clang compilation database entries for those tasks will be lost because post_build is not invoked if exception was caught by try ... finnally statement (which is what's is done when compiler/linker fails).

Adding missing entries to compilation db won't work later because already compiled tasks won't have valid last_cmd value set.

By looks of it moving post_build into finally block solves that issue but I don't know how it will effect other waf stuff.

Lukasz

**Comment by ita1024** [comment]
Testcase?

**Comment by ita1024** [comment]
No example / testcase, cannot take any action on this.
