### ISSUE TITLE
use_config doesn't work anymore due to definition changes

### ISSUE THREAD

**Issue by srouquette** [waf-project/waf#1608]
use_config redefine load_tool, but the function definition has changed, and the 3rd parameter isn't ctx anymore. ctx is still used though, in download_tool.

**Comment by ita1024** [comment]
Sorry for that - 41bd22ebfaca7c46717fa04a9feac2cabb2820e2

**Comment by ita1024** [comment]
Works for me, reopen if still broken.

**Comment by srouquette** [comment]
it works, thanks.
