### ISSUE TITLE
The exclusive_link tool in playground does not play well with shlib

### ISSUE THREAD

**Issue by epaul13** [waf-project/waf#1609]
I use waf 1.7 and I use the exclusive_link tool found in playground because I have a lot of big exe to link.

I recently added a shared lib in my build and end up with a dead lock. Here the minimal wscript: 

```python
def options(opt):
	opt.load("compiler_cxx")

def configure(conf):
	conf.load("compiler_cxx")
	conf.load("exclusive", tooldir = "waf/playground/exclusive_link")

def build(bld):
	bld.shlib(source = "x.cpp", target = "mylib")
	bld.program(source = "y.cpp", target = "myexe")

```

It works if you build a static lib, objects or another program. I think it comes from the fact that cxxshlib inherits from cxxprogram, so method runnable_status is monkeypatched 2 times, but not the run method. 

Eric.

**Comment by ita1024** [comment]
Yes, it was not really meant to be re-entrant. Use 48504f2c3d53a8b3409a89bc2e2a10687cfdff29

**Comment by ita1024** [comment]
(just re-open if there are other issues)

**Comment by epaul13** [comment]
Thanks. Works perfectly.

    Eric.

2015-08-28 22:10 GMT+02:00 ita1024 <notifications@github.com>:
