### ISSUE TITLE
msvc configure checks environment for all installed compilers and targets

### ISSUE THREAD

**Issue by shoover** [waf-project/waf#1611]
msvc configure autodetection runs vcvarsall.bat for the product of all architectures and installed compilers. On a system with several versions of Visual Studio this can easily result in 50 checks and take 6+ seconds, even on an SSD. Further, specifying a compiler version or target using the environment keys MSVC_VERSIONS and MSVC_TARGETS does not short-circuit this search.

Since the first compiler and architecture that works is taken, a suggestion is to locate all the combinations but make the actual checks lazy. Most of the time the first one tried will work and the job is done in half a second.

I have a patch that implements the lazy/memoized solution for most compilers but currently breaks winphone and Smartphone. If there is interest in the approach, I can clean it up and email or pull request.

**Comment by ita1024** [comment]
A patch that does not break anything woul dbe best.

**Comment by shoover** [comment]
Pull request #1612

**Comment by ita1024** [comment]
This will take a bit of time to review as several changes unrelated to caching seem to be gathered in one single patch:
* Why change to quiet=Context.STDOUT?
* Why adding MSVC_VERSIONS/MSVC_TARGETS from os.environ to conf.env?
* Changing command-line options can break user scripts. We are not allowed to do that before waf 1.9
* The existing API must be conserved, else the whole matter will have to wait for waf 1.9.
* An improvement can be to create "target" objects that can be evaluated later. Adding new code/API is OK.

**Comment by shoover** [comment]
Thanks for the quick once-over. I will back up and break this down properly
for consideration.

On Aug 29, 2015 12:46 PM, "ita1024" <notifications@github.com> wrote:
>
> This will take a bit of time to review as several changes unrelated to
caching seem to be gathered in one single patch:
>
> Why change to quiet=Context.STDOUT?
The command only checks that the exe runs. The /help output was not used
but fills the build log. I can revert this if the log is otherwise needed.

> Why adding MSVC_VERSIONS/MSVC_TARGETS from os.environ to conf.env?

Just trying to make it behave like other CC variables. Bad idea?

> Changing command-line options can break user scripts. We are not allowed
to do that before waf 1.9
> The existing API must be conserved, else the whole matter will have to
wait for waf 1.9.

No problem. I will fix it.

> An improvement can be to create "target" objects that can be evaluated
later. Adding new code/API is OK.

I had that but it broke the build command because the targets get saved to
the config set. Is there a way to do it and make the objects serializable?

Thanks.
Shawn

**Comment by ita1024** [comment]
* The purpose of config.log is to get filled with troubleshooting information.
* About the CC variables: that should not be discussed here, but yes, it is a questionable idea.
* Evaluating configurations lazily is a possibility, but I do not want to have magic objects evaluated during the build. After the configuration step the data must be properly written.
* Have you also thought of not running "waf configure" for every build (Configure.autoconfig)?

**Comment by shoover** [comment]
On Sat, Aug 29, 2015 at 5:03 PM, ita1024 <notifications@github.com> wrote:

>
>    - The purpose of config.log is to get filled with troubleshooting
>    information.
>
> Understood. With 50 checks, the log was filled with 50 copies of cl.exe's
complete options list. At least with the patch it's down to one copy and
there is some signal left. I will revert the change. Sorry for the noise.

>
>    - About the CC variables: that should not be discussed here, but yes,
>    it is a questionable idea.
>
> I will revert the change. Sorry for the noise.

>
>    - Evaluating configurations lazily is a possibility, but I do not want
>    to have magic objects evaluated during the build. After the configuration
>    step the data must be properly written.
>
> The objects were used in configure, but as soon as I realized that they
didn't serialize, I replaced them with plain dicts. In any case, nothing
new is evaluated during the build. Previously configure would quickly
discover all installed combinations from the registry and, along the way,
run vcvarsall and check the environment for all of them. With the patch,
configure discovers all combinations as before but instead of checking them
all saves a few useful keys and only does the slow part one at a time until
it finds one that matches the user's options. The MSVC_INSTALLED_VERSIONS
list saved in the config set still contains all the discovered combinations
of compilers, versions, and platforms but now without the path, libdirs,
and incdirs for the combinations that were not needed after the one to use
was found.

>
>    - Have you also thought of not running "waf configure" for every build
>    (Configure.autoconfig)?
>
> It's not like that. It's something happens and takes 6 seconds because
vcvarsall.bat*50 is slow. The question is whether cutting the time for step
1 is useful. Let me clean this up to a focused patch and see what the
answer is.

**Comment by shoover** [comment]
Ok, I get it, almost every function involved is attached to the configuration context and is therefore an API. Updating all the `gather_*_versions` functions as I did to store information needed to run the batch files later instead of running it and storing the environment can't be done without breaking the return type of many functions that are technically APIs.

Back to the possibility of new code that lazily evaluates targets, could that even be used by autodetect? `conf.load('compiler_c')` with autodetection based on `MSVC_VERSIONS` and `MSVC_TARGETS` (or just the first one from the full list that works) is the use case I wanted to speed up. But as a side effect of autodetect, `conf.env['MSVC_INSTALLED_VERSIONS']` currently gets saved with the environment variables for every compiler/target. So changing autodetect breaks that data structure.

**Comment by ita1024** [comment]
Yes :-)

I think that what we should do is to add an alternate execution path: if a particular environment variable (one that is unlikely to be already used), a command-line option or a configuration context attribute is set, then the detection could skip to the desired compiler.

In waf 1.9 we would just make this behaviour the default and instead provide the partial list if the user wants it.

There are two ways to perform such detection:
1. Obtain the list of compilers lazily as you did, then evaluate them at the end. The existing implementation inserts a tuple, maybe we can add some kind of lazy tuple in the list.
2. Or avoid calling more compiler detections once the first one is found. This may execute a few more compilers than necessary.

Will this be satisfactory, or do you see something else?

**Comment by shoover** [comment]
Yes, that would work.

If I understand you correctly, (1) is how the patch generally worked (other
than breaking the API) and has shown effective in my testing.

**Comment by ita1024** [comment]
Yes.

Try and see if the following can be used to avoid breaking the current API, if it works we can then try to make it a real subclass of tuple/list later on:

```python
class lazytup(object):
        def __init__(self, *args):
                self.args = args
                # raise the ConfigurationErrors by default to keep API compatibility:
                #if not_lazy: execute_immmediately()
        def __len__(self):
                return len(self.args)
        def __iter__(self):
                for i, v in enumerate(self.args):
                        if i == len(self.args) - 1:
                                print('--> calculate iter')
                        yield v
        def __getitem__(self, i):
                if i == len(self.args) - 1:
                        print('--> calculate getitem')
                return self.args[i]

print('starting')
f = lazytup(1, 2, 3)
print('using the contents')
a, b, c = f
print('done')
```

**Comment by shoover** [comment]
That works brilliantly. I implemented __repr__ because the data needs to be saved to the config set. A default value is given with the same shape for saving unevaluated targets with the same structure.

Shall I push a new branch for a fresh look?

**Comment by ita1024** [comment]
Yes.

**Comment by shoover** [comment]
#1614 shows what it looks like with a lazy parameter threaded through the gather functions. The lazytup works fine. It did require overriding `repr` so saving to the config set works right.

There is one issue to consider: the checking of targets for each msvc compiler works with a brute force method rather than knowing ahead of time which targets to try for each compiler. In the current master, the targets are all checked and the ones that fail (because vcvarsall.bat returns an error for bad target flags) get stripped. In the patch, those have to be kept around with empty data since they have not been evaluated and failed.

conf.print_all_msvc_detected() before:

```
wsdk 7.1
	x64
	x86
	ia64
STANDARDSDK_500 9.0
	armv4i
STANDARDSDK_500 9.0
	mipsii
STANDARDSDK_500 9.0
	mipsii_fp
STANDARDSDK_500 9.0
	mipsiv
STANDARDSDK_500 9.0
	mipsiv_fp
STANDARDSDK_500 9.0
	sh4
STANDARDSDK_500 9.0
	x86
msvc 6.0
	x86
msvc 8.0
	x86_amd64
	x86
	x64
msvc 9.0
	x86
msvc 10.0
	x86_ia64
	x86_amd64
	x86
	x64
msvc 11.0
	x86_arm
	x86_amd64
	x86
	x64
msvc 12.0
	amd64_arm
	amd64_x86
	x86_arm
	x86_amd64
	x86
	x64
```

And with the patch and the lazy flag set:

```
wsdk 7.1
	x64
	x86
	ia64
	x86_amd64
	x86_ia64
	x86_arm
	amd64_x86
	amd64_arm
STANDARDSDK_500 9.0
	armv4i
STANDARDSDK_500 9.0
	mipsii
STANDARDSDK_500 9.0
	mipsii_fp
STANDARDSDK_500 9.0
	mipsiv
STANDARDSDK_500 9.0
	mipsiv_fp
STANDARDSDK_500 9.0
	sh4
STANDARDSDK_500 9.0
	x86
msvc 6.0
	x86
msvc 8.0
	amd64_arm
	amd64_x86
	x86_arm
	x86_ia64
	x86_amd64
	ia64
	x86
	x64
msvc 9.0
	amd64_arm
	amd64_x86
	x86_arm
	x86_ia64
	x86_amd64
	ia64
	x86
	x64
msvc 10.0
	amd64_arm
	amd64_x86
	x86_arm
	x86_ia64
	x86_amd64
	ia64
	x86
	x64
msvc 11.0
	amd64_arm
	amd64_x86
	x86_arm
	x86_ia64
	x86_amd64
	ia64
	x86
	x64
msvc 12.0
	amd64_arm
	amd64_x86
	x86_arm
	x86_ia64
	x86_amd64
	ia64
	x86
	x64
```

Similarly, in the saved config set (MSVC_INSTALLED_VERSIONS), before you would see every checked target with its bindirs, incdirs, and libdirs filled in. Now you see the full list of unevaluated targets with empty variables, plus any selected and tested target with variables filled in.

Is this enough of an issue to torpedo the lazy evaluation scheme?

**Comment by shoover** [comment]
2:04 configure down to 0:12 on a clunky ThinkPad L512 with eight compilers installed.

**Comment by ita1024** [comment]
If `lazy` is set, then `conf.print_all_msvc_detected()` could just return 1 single entry (the one actually detected) instead of all entries. But I do not think that this matters that much.

**Comment by shoover** [comment]
36e07b3eaf6195bdbf15e683dc58557f568e4191

**Comment by shoover** [comment]
Reopening this to say, yeah, I'm realizing it's quite misleading to print all the untested architectures, especially when we know ahead of time that many combinations are not supported. Ideally we would only even test the known supported combinations, and then printing the unevaluated list would be mostly accurate (practically, a particular compiler could be installed but not run, so it could be tested and skipped).

However, that's a larger change than I may want to get into to. For the purposes of this issue, I like your suggestion. What if we printed all the installed compilers but print the targets that have been tested, like this:

```
$ ../../waf configure --msvc_lazy_autodetect --msvc_version="msvc 11.0" --msvc_targets="x64"
Setting top to                           : C:\Users\Shawn\dev\external\waf\demos\c
Setting out to                           : C:\Users\Shawn\dev\external\waf\demos\c\build
Checking for 'msvc' (C compiler)         : C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\amd64\CL.exe
wsdk 7.1
STANDARDSDK_500 9.0
msvc 6.0
msvc 8.0
msvc 9.0
msvc 10.0
msvc 11.0
        x64
msvc 12.0
...
```

**Comment by ita1024** [comment]
I would rather leave MSVC_INSTALLED_VERSIONS empty when the `lazy` detection is enabled than provide a "mostly accurate" list.

**Comment by shoover** [comment]
* Ok, if empty is ok for `MSVC_INSTALLED_VERSIONS`, that's easy enough. Saving the one entry as you mentioned above or saving all the installed compilers and just the one detected target as I showed is possible by filter the list after detection returns.
* What should `get_msvc_versions` return when lazy detection is enabled? Currently it returns the full list of unevaluated lazytups, which can throw exceptions when evaluated. Is this considered breakage or ok since it doesn't break if the lazy option is disabled? `get_msvc_versions` could be made to evaluate the lazytups if called directly to maintain the API.
* Is there a more idiomatic way of managing the option than checking the option and context variable in multiple places?
