### ISSUE TITLE
msvc WinCE detection loop structure prints strange, breaks detecting some WinCE targets

### ISSUE THREAD

**Issue by shoover** [waf-project/waf#1616]
What shows up as duplicate WinCE version keys in the print list:

```
STANDARDSDK_500 9.0
        armv4i
STANDARDSDK_500 9.0
        mipsii
STANDARDSDK_500 9.0
        mipsii_fp
STANDARDSDK_500 9.0
        mipsiv
STANDARDSDK_500 9.0
        mipsiv_fp
STANDARDSDK_500 9.0
        sh4
STANDARDSDK_500 9.0
        x86
```

Also breaks searching for certain targets:

```
>..\..\waf.bat configure --msvc_lazy_autodetect --msvc_version="STANDARDSDK_500 9.0" --msvc_targets="mipsiv"
Setting top to                           : c:\Users\Shawn\dev\external\waf\demos\c
Setting out to                           : c:\Users\Shawn\dev\external\waf\demos\c\build
Checking for 'msvc' (C compiler)         : not found
```

I don't know if anyone uses it, it's just something I found in testing. winphone 8.0 has similar issues.

**Comment by shoover** [comment]
Somewhat related, I found it only works if I run "c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcvarsall.bat" in my shell before configuring.

It has to do with the way the VC and SDK environments are combined in `gather_wince_supported_platforms`. The VC and SDK bin dirs are combined, but for the lib dirs and inc dirs, only the SDK environment is used.

Only by combining the VC and SDK dirs for all three variables, and ensuring the VC lib dirs and inc dirs come first, does it configure in a clean environment (without vcvars).

**Comment by ita1024** [comment]
The windows CE support was added in 20011, and then the windows phone detection was for the version 8 of the compiler. It is possible that the code is just outdated now.

Patches will be welcome.
