### ISSUE TITLE
build cache and templates

### ISSUE THREAD

**Issue by azag0** [waf-project/waf#1621]
I've been recently thinking about a build system for running scientific calculations. Although Waf has clearly not been designed for this purpose, the Task and TaskGenerator APIs and a lot of Waf internals would be actually perfect for this purpose. After a bit of thinking, I miss mainly three things:

1. In case of general builds, not software builds, it seems that rather than having everything in one build directory which mirrors the source directory, it would be better for each task to be local and associated with its own directory.
1. A related problem is that of caching the individual tasks. In calculation builds, in contrast to software builds, one would often want to check all the in-between build step results across different builds, akin to diffs in git. I was actually thinking about something like a git's objects database that would keep stored task builds according to their hashes.
1. In calculations, one often calculates (builds) some stuff several times with slight variations. A single task generator with a template file would generate many tasks, each with it's own build. If some other task depends on the template task, it automatically forks this dependent task.

My question is, if I were to fork Waf and try to work in these ideas, how big changes in the internals would it require? Maybe the templates could be worked in on top of current Waf, I'm not sure. Or would I be better of starting from scratch? I really like how Waf is designed, so I'd love to build on top of it.

**Comment by ita1024** [comment]
1 and 3 do not require any modification. The point 2 is rather ambiguous: if you want a database, you should use a database. Python is too memory hungry to keep millions of objects in memory at once.

Consider this [blog post](https://waf.io/blog/2010/09/order-in-archive-and-compression-ratio.html) and [the code example](https://github.com/waf-project/waf/tree/master/playground/compress)

There are also [library usage examples](https://github.com/waf-project/waf/tree/master/build_system_kit) in case you want to setup your own build system

**Comment by azag0** [comment]
I've been going through the codebase and I see that 1. and 3. could be implemented simply by defining my own Task and TaskGen classes.

As for 2., I didn't mean the database should live in memory. It would live on the hard drive, as in case of Git. Waf would just verify that the task in question is already cached and would reuse it without running it, and if not, it would run the task. Instead of looking for the hash in its own internal database, it would look whether a directory named as that hash exists. Thus hashes and their original contents would be permanent.

**Comment by azag0** [comment]
Thanks for the links, I'll sure have a look at them.

**Comment by ita1024** [comment]
Python will become slow once the task count reaches 500K. Just saying.
