### ISSUE TITLE
inconsistent use of tabs and spaces - msvc

### ISSUE THREAD

**Issue by hotvic** [waf-project/waf#1627]
Latest commit from git:

> *** Sorry: TabError: inconsistent use of tabs and spaces in indentation (msvc.py, line 358)

Looking at msvc.py there's a lot of inconsistency, most part of it is tab-indented but there's a lot of spaces too.

**Comment by ita1024** [comment]
We will add a filter for this (Python 3). The builds are unaffected as the files are re-indented when the Waf file is created (Waf 1.8.14).

**Comment by ita1024** [comment]
f9f5e856167df245c8b3831f953985583673d3e4
