### ISSUE TITLE
bld.get_tgen_by_name slow performance as task_gen_cache_names is reset each time we add a new taskgen

### ISSUE THREAD

**Issue by digiways** [waf-project/waf#1628]
I use bld.get_tgen_by_name in a number of custom waf scripts, and its performance seems to be quite slow.
Maybe I'm missing some implementation details, but looks like we reset self.task_gen_cache_names in BuildContext (Build.py) each time we add a new taskgen (in __call__). And then it's recreated in the next bld.get_tgen_by_name call.
Wouldn't it be much more efficient not to reset it in __call_, but instead add it to self.task_gen_cache_names straight away? Then bld.get_tgen_by_name will become a simple lookup.

**Comment by ita1024** [comment]
In the most common case, task generators are all declared at once and their corresponding tasks are created at once when the build starts.

It seems that you have an unusual workload, so I would like to see a profile. In the meantime, you can also implement your optimizations in a BuildContext subclass.

**Comment by digiways** [comment]
Thanks for the quick response. I'm trying to isolate the performance problem right now, looks like get_tgen_by_name is not actually the problem by itself, I just call it too many times. 
Would you agree that the optimization that I mentioned would still make sense, or it can potentially break something?

**Comment by ita1024** [comment]
If the cache is too aggressive, then task generators created after the build has started would be invisible. I suggest you isolate the problem first.

**Comment by digiways** [comment]
That's a very good point, I didn't think of that. Thanks !
