### ISSUE TITLE
BuildContext.get_group_idx performance - any suggestions how to override/optimise it?

### ISSUE THREAD

**Issue by digiways** [waf-project/waf#1629]
I'm trying to migrate a rather large project (over 5000 taskgens) to WAF, and even when no files has changed, e.g. nothing to do, WAF still takes about a minute. Out of that, 36 seconds are spent in BuildContext.get_group_idx (profiling info below).
In my project I don't use groups (e.g. I end up having default None group).

Looking at the current implementation of BuildContext.get_group_idx, it iterates over all the taskgens in all the groups, and doesn't return until ID of the argument taskgen is the same as what we have in the group.
````python
  se = id(tg)
    for i in range(len(self.groups)):
      for t in self.groups[i]:
        if id(t) == se:
          return i
  return None
````

I can definitely override this function in my wscript, and just set it to always return 0.
Any reasons not to do that, can that break something?

Would it be possible to put that optimisation in WAF ? E.g. just return 0 if we only have one group, and in case of more then one group, have a more efficient mapping?

I just tested the same setup, overriding BuildContext.get_group_idx with a function that always returns 0, and build time (when no files have changed) jumped from 65 seconds to 28 !

Any other guidelines/tricks to optimise WAF for large projects? Ideally I need to get that down to a few seconds, that's what the original in-house build system (that I'm migrating from) provided.

Thanks

````
         144068288 function calls (143699850 primitive calls) in 64.899 CPU seconds

   Ordered by: cumulative time
   List reduced from 1354 to 50 due to restriction <50>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   64.899   64.899 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Scripting.py:368(execute)
        1    0.000    0.000   64.899   64.899 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Build.py:100(execute)
        1    0.000    0.000   64.101   64.101 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Build.py:105(execute_build)
        1    0.003    0.003   62.411   62.411 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Tools/errcheck.py:121(check_compile)
        1    0.000    0.000   62.182   62.182 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Build.py:168(compile)
        1    0.050    0.050   62.182   62.182 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Runner.py:173(start)
69378/984    0.252    0.000   50.634    0.051 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/TaskGen.py:59(post)
    11903    0.011    0.000   49.003    0.004 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Runner.py:71(refill_task_list)
        2    0.002    0.001   48.991   24.495 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Build.py:398(get_build_iterator)
        1    0.006    0.006   48.800   48.800 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Build.py:353(post_group)
  855/768    1.632    0.002   45.198    0.059 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Tools/ccroot.py:152(process_use)
137303/4108    0.620    0.000   40.950    0.010 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Tools/errcheck.py:130(use_rec)
137303/4108    1.333    0.000   39.632    0.010 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Tools/ccroot.py:118(use_rec)
   274606   25.954    0.000   36.631    0.000 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Build.py:303(get_group_idx)
    11902    0.014    0.000   13.039    0.001 /build/.waf-1.8.12-df9387678894529b8b4e3870bb638b7f/waflib/Runner.py:154(task_status)





````

**Comment by ita1024** [comment]
It seems my comment was lost.

The recommended way to optimize is to profile, identify the bottlenecks, try the modules provided in waflib/extras (gccdeps, win32_opts, etc) and then to optimize.

But first start by profiling without the -v option.

Are you certain that so many task generators are necessary? How many tasks are there? I would like to see a full profile, please sort the profile by time or function call (waflib/Scripting.py).

**Comment by digiways** [comment]
Thanks, looks like I ran profiling with "-v" indeed. BuildContext.get_group_idx is not an issue without "-v".
As you can see, I'm profiling (with cProfile) to identify the bottlenecks. I plan to try gccdeps later, but at this point, doing a "no op" build when no input files have changed, I don't think it would change anything.
Also, I quoted a wrong number of task generators. There are 925 task generators, which generate almost 5,000 tasks (all .cpp files, shared/static libs and executables, all on Linux). This is a rather large software suite.

Below I include profiling stats (without -v), with base paths replaced with [skipped] and [codebase].
I include profiling stats both, sorted by time, and by cumulative time, as I think the second also gives a good picture of where the time is spent.

I appreciate that my idl_task_dependency_updater takes 4 seconds out of the total 25, I can definitely optimise it, but the remaining code still takes 20 seconds (it's a few seconds less without cProfile).

I see that ccroot.process_use takes almost 7 seconds, do you think it might be possible to either optimise it, or just store it's output (in cache) between builds?

````
         30930227 function calls (30695839 primitive calls) in 25.209 seconds

   Ordered by: cumulative time
   List reduced from 1340 to 50 due to restriction <50>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   25.209   25.209[SKIPPED]/waflib/Scripting.py:368(execute)
        1    0.000    0.000   25.209   25.209[SKIPPED]/waflib/Build.py:100(execute)
        1    0.000    0.000   24.337   24.337[SKIPPED]/waflib/Build.py:105(execute_build)
        1    0.000    0.000   22.740   22.740[SKIPPED]/waflib/Build.py:168(compile)
        1    0.046    0.046   22.740   22.740[SKIPPED]/waflib/Runner.py:167(start)
    11436    0.013    0.000   11.760    0.001[SKIPPED]/waflib/Runner.py:148(task_status)
69378/984    0.195    0.000   11.016    0.011[SKIPPED]/waflib/TaskGen.py:59(post)
    11437    0.010    0.000   10.852    0.001[SKIPPED]/waflib/Runner.py:71(refill_task_list)
        2    0.002    0.001   10.840    5.420[SKIPPED]/waflib/Build.py:398(get_build_iterator)
        1    0.005    0.005   10.662   10.662[SKIPPED]/waflib/Build.py:353(post_group)
  855/768    1.418    0.002    6.708    0.009[SKIPPED]/waflib/Tools/ccroot.py:152(process_use)
     8954    0.052    0.000    6.561    0.001[SKIPPED]/waflib/Task.py:307(runnable_status)
     4733    0.043    0.000    6.447    0.001[SKIPPED]/waflib/Task.py:293(signature)
     3877    0.017    0.000    4.646    0.001[SKIPPED]/waflib/Task.py:380(sig_implicit_deps)
     3877    1.171    0.000    4.574    0.001[SKIPPED]/waflib/Task.py:419(compute_sig_implicit_deps)
     5947    1.516    0.000    4.313    0.001 ./buildSystem/waf_scripts/idl/idl_task_dependency_updater.py:58(runnable_status_override)
  2208914    3.397    0.000    3.397    0.000 {method 'update' of '_md5.md5' objects}
     9432    0.058    0.000    3.250    0.000[SKIPPED]/waflib/Utils.py:112(h_file)
137303/4108    1.108    0.000    2.923    0.001[SKIPPED]/waflib/Tools/ccroot.py:118(use_rec)
   508252    1.873    0.000    2.626    0.000[SKIPPED]/waflib/ConfigSet.py:29(__getitem__)
  3788889    1.673    0.000    2.334    0.000[SKIPPED]/waflib/Node.py:70(__eq__)
      855    0.614    0.001    2.241    0.003[SKIPPED]/waflib/Tools/ccroot.py:241(propagate_uselib_vars)
  2125181    0.594    0.000    2.193    0.000[SKIPPED]/waflib/Node.py:452(get_bld_sig)
     3877    0.908    0.000    1.643    0.000[SKIPPED]/waflib/Task.py:426(are_implicit_nodes_ready)
    39072    0.397    0.000    1.637    0.000 [codebase]/wscript:80(to_incnodes)
    945/1    0.021    0.000    1.597    1.597[SKIPPED]/waflib/Context.py:101(recurse)
        1    0.000    0.000    1.597    1.597 [codebase]/wscript:453(build)
    942/2    0.002    0.000    1.513    0.756 [codebase]/wscript:429(process_subdirectory)
     4733    0.083    0.000    1.381    0.000[SKIPPED]/waflib/Task.py:344(sig_explicit_deps)
      777    0.016    0.000    1.320    0.002[SKIPPED]/waflib/Node.py:285(ant_glob)
9214/4629    0.081    0.000    1.025    0.000[SKIPPED]/waflib/Node.py:255(ant_iter)
 11315862    1.021    0.000    1.021    0.000 {id}
       69    0.002    0.000    0.999    0.014[SKIPPED]/waflib/Tools/ccroot.py:389(process_lib)
        1    0.000    0.000    0.921    0.921 [codebase]/fx/wscript_build:1(<module>)
        1    0.000    0.000    0.920    0.920 [codebase]/fx/cpp/src/wscript_build:2(<module>)
        1    0.000    0.000    0.868    0.868 [codebase]/wscript:47(restore_all_build_data)
        1    0.002    0.002    0.867    0.867[SKIPPED]/waflib/Build.py:119(restore)
        1    0.780    0.780    0.836    0.836 {cPickle.loads}
  2238757    0.605    0.000    0.811    0.000[SKIPPED]/waflib/Node.py:68(__hash__)
       64    0.000    0.000    0.762    0.012[SKIPPED]/waflib/Tools/ccroot.py:367(runnable_status)
    11304    0.026    0.000    0.681    0.000[SKIPPED]/waflib/Node.py:327(accept)
        1    0.002    0.002    0.666    0.666 [codebase]/common/wscript_build:1(<module>)
    22608    0.384    0.000    0.655    0.000[SKIPPED]/waflib/Node.py:312(filtre)
    45350    0.349    0.000    0.612    0.000[SKIPPED]/waflib/Node.py:193(path_from)
        1    0.000    0.000    0.592    0.592 [codebase]/common/cpp/src/wscript_build:2(<module>)
    24277    0.585    0.000    0.585    0.000 {method 'read' of 'file' objects}
    31552    0.283    0.000    0.581    0.000[SKIPPED]/waflib/Node.py:370(get_bld)
   484180    0.570    0.000    0.572    0.000[SKIPPED]/waflib/ConfigSet.py:42(__getattr__)
   105933    0.340    0.000    0.496    0.000[SKIPPED]/waflib/Node.py:164(make_node)
      983    0.008    0.000    0.433    0.000[SKIPPED]/waflib/TaskGen.py:229(process_source)


Thu Oct  1 09:18:52 2015    waf_profiling_data

         30930227 function calls (30695839 primitive calls) in 25.209 seconds

   Ordered by: internal time
   List reduced from 1340 to 50 due to restriction <50>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  2208914    3.397    0.000    3.397    0.000 {method 'update' of '_md5.md5' objects}
   508252    1.873    0.000    2.626    0.000[SKIPPED]/waflib/ConfigSet.py:29(__getitem__)
  3788889    1.673    0.000    2.334    0.000[SKIPPED]/waflib/Node.py:70(__eq__)
     5947    1.516    0.000    4.313    0.001 ./buildSystem/waf_scripts/idl/idl_task_dependency_updater.py:58(runnable_status_override)
  855/768    1.418    0.002    6.708    0.009[SKIPPED]/waflib/Tools/ccroot.py:152(process_use)
     3877    1.171    0.000    4.574    0.001[SKIPPED]/waflib/Task.py:419(compute_sig_implicit_deps)
137303/4108    1.108    0.000    2.923    0.001[SKIPPED]/waflib/Tools/ccroot.py:118(use_rec)
 11315862    1.021    0.000    1.021    0.000 {id}
     3877    0.908    0.000    1.643    0.000[SKIPPED]/waflib/Task.py:426(are_implicit_nodes_ready)
        1    0.780    0.780    0.836    0.836 {cPickle.loads}
      855    0.614    0.001    2.241    0.003[SKIPPED]/waflib/Tools/ccroot.py:241(propagate_uselib_vars)
  2238757    0.605    0.000    0.811    0.000[SKIPPED]/waflib/Node.py:68(__hash__)
  2125181    0.594    0.000    2.193    0.000[SKIPPED]/waflib/Node.py:452(get_bld_sig)
    24277    0.585    0.000    0.585    0.000 {method 'read' of 'file' objects}
   484180    0.570    0.000    0.572    0.000[SKIPPED]/waflib/ConfigSet.py:42(__getattr__)
    39072    0.397    0.000    1.637    0.000 [codebase]/wscript:80(to_incnodes)
    22608    0.384    0.000    0.655    0.000[SKIPPED]/waflib/Node.py:312(filtre)
    45350    0.349    0.000    0.612    0.000[SKIPPED]/waflib/Node.py:193(path_from)
   105933    0.340    0.000    0.496    0.000[SKIPPED]/waflib/Node.py:164(make_node)
    31552    0.283    0.000    0.581    0.000[SKIPPED]/waflib/Node.py:370(get_bld)
   666295    0.280    0.000    0.280    0.000 {getattr}
   145534    0.270    0.000    0.270    0.000[SKIPPED]/waflib/Node.py:97(height)
   614812    0.233    0.000    0.233    0.000 {isinstance}
  1186943    0.228    0.000    0.228    0.000 {method 'get' of 'dict' objects}
  1432100    0.219    0.000    0.219    0.000 {method 'append' of 'list' objects}
69378/984    0.195    0.000   11.016    0.011[SKIPPED]/waflib/TaskGen.py:59(post)
    39700    0.190    0.000    0.235    0.000[SKIPPED]/waflib/Node.py:348(is_bld)
   340935    0.178    0.000    0.178    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
    19317    0.158    0.000    0.158    0.000 {posix.stat}
189074/168491    0.156    0.000    0.156    0.000[SKIPPED]/waflib/Node.py:221(abspath)
     1554    0.132    0.000    0.278    0.000[SKIPPED]/waflib/Node.py:291(to_pat)
    95173    0.126    0.000    0.165    0.000[SKIPPED]/waflib/ConfigSet.py:77(_get_list_value_for_modification)
    10384    0.125    0.000    0.125    0.000 {open}
   394670    0.107    0.000    0.157    0.000 {method 'add' of 'set' objects}
    45347    0.104    0.000    0.202    0.000[SKIPPED]/waflib/ConfigSet.py:101(append_unique)
     4733    0.100    0.000    0.330    0.000[SKIPPED]/waflib/Build.py:216(hash_env_vars)
   146024    0.099    0.000    0.116    0.000[SKIPPED]/waflib/Build.py:236(get_tgen_by_name)
    80015    0.096    0.000    0.096    0.000 {method 'values' of 'dict' objects}
     1715    0.091    0.000    0.110    0.000[SKIPPED]/waflib/Utils.py:308(h_list)
      945    0.083    0.000    0.083    0.000 {compile}
     4733    0.083    0.000    1.381    0.000[SKIPPED]/waflib/Task.py:344(sig_explicit_deps)
9214/4629    0.081    0.000    1.025    0.000[SKIPPED]/waflib/Node.py:255(ant_iter)
        1    0.078    0.078    0.153    0.153[SKIPPED]/waflib/Task.py:472(set_file_constraints)
   127275    0.078    0.000    0.141    0.000[SKIPPED]/waflib/TaskGen.py:56(to_list)
    49826    0.077    0.000    0.209    0.000[SKIPPED]/waflib/ConfigSet.py:92(append_value)
    27417    0.074    0.000    0.193    0.000[SKIPPED]/waflib/Node.py:248(is_child_of)
 5672/983    0.069    0.000    0.111    0.000 ./buildSystem/waf_scripts/tools/recursive_use.py:65(get_use_recursive)
   119188    0.066    0.000    0.066    0.000 {method 'split' of 'str' objects}
    16352    0.066    0.000    0.114    0.000[SKIPPED]/waflib/Task.py:273(uid)
     9432    0.058    0.000    3.250    0.000[SKIPPED]/waflib/Utils.py:112(h_file)
     
````

**Comment by digiways** [comment]
I optimised my  idl_task_dependency_updater code, trying to identify any bottlenecks I could optimise in Waf. I attach the full profiling tree below.
I can also shave off a few more seconds by changing
```python
feature_uselib = self.features + self.to_list(getattr(self, 'uselib', []))
```
to
```python
feature_uselib = self.features# + self.to_list(getattr(self, 'uselib', []))
```
as I don't use any per lib settings via environment (by the way, any idea how to implement this optimisation generically without hacking Waf) ?

I'm also thinking of some solution to avoid rebuilding the taskgen/task tree if none of my wscript files have changed, and no new files were added (that would affect ant_glob, etc patterns), by caching more data in waf cache. 
I'm ok with the time spent reading files and constructing hashes, but currently that's less than 20% of the time taken by a "no op" WAF run.

![g](https://cloud.githubusercontent.com/assets/14886402/10219866/82f47ff2-683a-11e5-9ce8-4d73585ced3a.png)

**Comment by ita1024** [comment]
A build of that size should not take more than 5 seconds on a relatively recent PC, and the amount of function calls should not go exceed 10M. I also notice that processing task status takes as much time as creating task objects. Are you on older hardware with `Python <= 2.6`? Can you compare your project build time to that of the [Samba build](https://www.samba.org/)?

The amount of calls to `Node.py:164(make_node)` looks worrying, and I suspect that your dependency calculation has some unintended side effects.

I think you should to narrow the issue more clearly before trying any [optimization](https://github.com/ita1024/samba/blob/master/buildtools/wafsamba/samba_optimisation.py#L192) yourself. Try the following tools to narrow the issue: [lazy file hash calculation](https://github.com/waf-project/waf/blob/master/waflib/extras/md5_tstamp.py) and [unity builds](https://github.com/waf-project/waf/blob/master/waflib/extras/unity.py).

**Comment by digiways** [comment]
Using python 2.7.8 (I used 2.6.4 by mistake a few times, but was getting the same performance).
Running this on a server with 40 of "Intel(R) Xeon(R) CPU E7- 4870  @ 2.40GHz" cores with 128Gb RAM, so yes, it's somewhat slow per core, but the original setup (cmake+ninja) still completed "noop" builds in under a second. I understand that it doesn't do hashes, but they only take a few seconds since all the files are in the cache anyway.
Is it still relevant to try the Samba build to compare the time?

I debugged calls to Node.py (make_node), and it looks like Node.ant_iter creates nodes for files, even if they don't match the pattern. I use .ant_glob("**/*.cpp") in most wscript_build files, and some of the subdirectories, together with .cpp/.hpp files also include text, python, and a bunch of other files that are not used in the build. I can optimise this function, or add my own one to avoid creation of nodes that don't match the pattern, do you think this would make sense?

Trying out lazy file hash calculation now. I can definitely try out unity builds for the sake of performance comparison, but I can't use them long term due to C++ implications (overloads, template specializations, etc in one .cpp file can completely change the behaviour of other .cpp files if included "unity build style").

Thanks for the link to the samba optimisations file, reading it now, very useful !

I also experimented a bit optimising process_use and use_rec in ccroot.py, I can get a few more seconds off by caching the current "recursive use" list for every taskgen, instead of doing the full depth recursive traversal for every taskgen. Is there a reason WAF does this full traversal (with full depth) for every taskgen, instead of just caching the "recursive use list" for every taskgen?

**Comment by digiways** [comment]
I managed to shave another second off by replacing Node.ant_glob calls (in my wscript_build files) with my own function calls that has a very similar implementation, but just checks for ".cpp" files, without regexes, etc. I should have done that from the beginning I guess.

Another interesting point - looking at the apache WAF optimisations, I noticed how they concatenate multiple strings before feeding them to md5.update, instead of calling md5.update multiple times. The result is the same, but indeed, concatenating strings yourself is much faster, I guess this is due to the slow performance of python->C calls for md5.update. 
So, having the same optimisation in mind, I patched Task.compute_sig_implicit_deps, replacing
```python
		for k in bld.node_deps.get(self.uid(), []):
			upd(k.get_bld_sig())
```
with
```python
		sig = ''.join([k.get_bld_sig() for k in bld.node_deps.get(self.uid(), [])])
		if len(sig) != 0:
			upd(sig)
```
and got another second off the no-op build. Do you think this patch can be made to the main WAF branch? I don't see how it can break anything, and definitely a performance improvement.

**Comment by ita1024** [comment]
Python performance on a slow core will be terrible. If possible, focus on reducing the amount of function calls. Try also `waflib/extras/mem_reducer.py` and a recent version of Pypy or Python 3.5. For the full build, `waflib/extras/prefork.py` will also be useful.

The string concatenation optimization is very Python2-specific and makes the code unreadable.

Caching the "recursive use list" for every taskgen assumes that the objects do not change after the build has started. This is not necessarily the case.

**Comment by digiways** [comment]
Thanks for your responses, I have definitely learned a lot about WAF !

I appreciate that caching "recursive use list" makes too many assumptions to be generic, so I just overrode it for my use case.

Another question - why do you define __eq__ and __hash__ in Node?
```python
	def __hash__(self):
		"Node hash, used for storage in dicts. This hash is not persistent."
		return id(self)

	def __eq__(self, node):
		"Node comparison, based on the IDs"
		return id(self) == id(node)
```
?
How is this any better than default python implementations of these functions, given that if you don't override them, python will just use low level C call instead of interpreting your code (precompiled, but still interpreted) ?

I got a significant speed by just adding these 3 lines to my wscript !

```python
from waflib import Node
del Node.Node.__eq__
del Node.Node.__hash__
```

I will try mem_reducer and prefork next.

**Comment by ita1024** [comment]
The methods __hash__ and __eq__ are needed in older python versions at least, or the full trees are getting compared (and this was really, really slow). We will not be removing them at this time, but i would like to know what you mean by "significant speed up".

"prefork" is only for the full build times.

**Comment by ita1024** [comment]
To save some memory, consider discarding the commands passed to `tsk.last_cmd` in Task.py. There does not seem to be any further action to take on this question, closing now.
