### ISSUE TITLE
using the 'build_logs' extra on Windows causes the console to lose color and see the terminal codes instead

### ISSUE THREAD

**Issue by jason-s** [waf-project/waf#1631]
Using the 'build_logs' extra on Windows causes the console to lose color and see the terminal codes instead

see 

https://groups.google.com/forum/#!searchin/waf-users/log/waf-users/wY1Rax6dzYs/lCba2yUeaS8J

I've been able to reproduce on my system (Windows 7 using waf 1.8.14)

**Comment by ita1024** [comment]
Update your copy to 807a193db66c253784365647d7121545f8ba25b3
