### ISSUE TITLE
Implicit uselib from packages for Vala tasks

### ISSUE THREAD

**Issue by arteymix** [waf-project/waf#1632]
It is very redundant to write the `packages` and `uselib` when the latter can be inferred easily from the first.

Determining the flags should be performed after the package resolution in case of task dependencies (with `use`), so that child task does not have to specify `uselib` for its parent task.

It wouldn't break anything since you have to specify `uselib` in order to build correctly.

**Comment by arteymix** [comment]
The `package` in `check_cfg` refers to the `pkg-config` file whereas the `packages` in `program` refers to the VAPI name. They are typically named the same, but does not reefer to the same concept.

`valac` automatically resolves that by looking at the basename, so it's a sane default for `waf`.

It might be necessary to store additional information in the configure step so that flags for a package can be resolved at the build step and potentially omit the `uselib_store` option.

**Comment by ita1024** [comment]
It is late and I don't really get it. Patches welcome! :-)

**Comment by arteymix** [comment]
@ita1024 there's a little distinction between packages from `check_pkg`  (pkg-config) and Vala packages (VAPI) that have to be taken care of in the implementation

I'll start something now that I have a much better understanding of waf's internals.

**Comment by ita1024** [comment]
I still fail to understand how to enable such a thing and no one is going to do it so i will close the issue now.

**Comment by arteymix** [comment]
It's a my fault: I did not know about `use` back in the time so I ended up with explicit dependencies for all my targets.
