### ISSUE TITLE
allow generating a task without requiring an extension mapping

### ISSUE THREAD

**Issue by jason-s** [waf-project/waf#1633]
I have a type of task I want to run that file extensions don't matter, so I figured I'd use `TaskGen.feature()` to handle them, but it fails:

```
APPNAME = 'test1'
VERSION = '0.01'

top = '.'
out = 'build'

import time
from waflib import Task, TaskGen

@Task.always_run
class Timestamp(Task.Task):
    def run(self):
        print "COOL: outputs=\n", self.outputs

def timestamp(tsk):
    for out in tsk.outputs:
        out.write("I am a timestamp! time=%d\n" % time.time())
        
@TaskGen.feature('remove_chocolate')
def remove_chocolate(self, source, target):
    print source, target
        
def configure(ctx):
    print "_conf"
    
def build(bld):
    print "_build"
    t1 = Timestamp(env=bld.env, target='strawberry.txt')
    bld.add_to_group(t1)
    
    bld(rule=timestamp, target='pistachio.txt', always = True, update_outputs = True, color='GREEN')
    # always: make sure this always runs
    # update_outputs: affects downstream dependencies so they are triggered when this output changes
    bld(rule=timestamp, target='chocolate.txt', update_outputs = True, color='GREEN')
    bld(features='remove_chocolate', source='chocolate.txt', target='vanilla.txt', always = True, update_outputs = True, color='GREEN')
```

This produces:

```
File C:\path\to\mydir\build\chocolate.txt has no mapping in ['.pc.in'] (have you forgotten to load a waf tool?)
```

There doesn't seem to be a way to get around this. I don't care about the extension, there may not even be one.

**Comment by ita1024** [comment]
Task generator methods are executed in a certain order. Have you specified any particular order? How can you find out which methods are executed?

**Comment by jason-s** [comment]
Hmm. I can get around it, not too hard, but it would help to document this I think.

    bld(features='remove_chocolate', source='chocolate.txt', target='vanilla.txt', always = True, update_outputs = True, color='GREEN', mappings={'': (lambda self, node : None)})

Alternatively, accept this:

    bld(features='remove_chocolate', source='chocolate.txt', target='vanilla.txt', always = True, update_outputs = True, color='GREEN', mappings=None)

by changing TaskGen.task_gen to this:

	def get_hook(self, node):
		"""
		:param node: Input file to process
		:type node: :py:class:`waflib.Tools.Node.Node`
		:return: A method able to process the input node by looking at the extension
		:rtype: function
		"""
		name = node.name
                if self.mappings is None:
			return lambda self, node: None
		if self.mappings:
			for k in self.mappings:
				if name.endswith(k):
					return self.mappings[k]
		for k in task_gen.mappings:
			if name.endswith(k):
				return task_gen.mappings[k]
		raise Errors.WafError("File %r has no mapping in %r (have you forgotten to load a waf tool?)" % (node, task_gen.mappings.keys()))

**Comment by ita1024** [comment]
Or do not use the attribute "source"?

**Comment by jason-s** [comment]
hmm.. I may have a bunch of files, and my feature knows how to turn `source` files into `target` files; `source` and `target` are still important to dictate dependency interaction with other rules.

Trying to think of a more concrete example I can give that's not too complex.

**Comment by jason-s** [comment]
working wscript example: vanilla.txt gets rebuilt if zippy.h changes, or chocolate.txt gets removed (and rebuilt before vanilla.txt is rebuilt)

```
APPNAME = 'test1'
VERSION = '0.01'

top = '.'
out = 'build'

import time
from waflib import Task, TaskGen

@Task.always_run
class Timestamp(Task.Task):
    def run(self):
        print "COOL: outputs=\n", self.outputs

def timestamp(tsk):
    for out in tsk.outputs:
        out.write("I am a timestamp! time=%d\n" % time.time())
        
class ChocolateRemover(Task.Task):
    def run(self):
        print 'Running ChocolateRemover!'
        for out in self.outputs:
            out.write("removed chocolate")

# adapted from TaskGen.process_rule
def create_taskgen_task(self, task_classname):        
    tsk = self.create_task(task_classname)

    if getattr(self, 'target', None):
        if isinstance(self.target, str):
            self.target = self.target.split()
        if not isinstance(self.target, list):
            self.target = [self.target]
        for x in self.target:
            if isinstance(x, str):
                tsk.outputs.append(self.path.find_or_declare(x))
            else:
                x.parent.mkdir() # if a node was given, create the required folders
                tsk.outputs.append(x)
        if getattr(self, 'install_path', None):
            self.bld.install_files(self.install_path, tsk.outputs)

    if getattr(self, 'source', None):
        tsk.inputs = self.to_nodes(self.source)
        # bypass the execution of process_source by setting the source to an empty list
        self.source = []

    if getattr(self, 'cwd', None):
        tsk.cwd = self.cwd
    return tsk
        
@TaskGen.feature('remove_chocolate')
def remove_chocolate(self):
    print "setting up remove chocolate\ninputs=%s\noutputs=%s" % (self.source, self.target)
    t = create_taskgen_task(self, 'ChocolateRemover')
        
def configure(ctx):
    print "_conf"
    
def build(bld):
    print "_build"
    t1 = Timestamp(env=bld.env, target='strawberry.txt')
    bld.add_to_group(t1)
    
    bld(rule=timestamp, target='pistachio.txt', always = True, update_outputs = True, color='GREEN')
    # always: make sure this always runs
    # update_outputs: affects downstream dependencies so they are triggered when this output changes
    bld(rule=timestamp, target='chocolate.txt', update_outputs = True, color='GREEN')
    bld(features='remove_chocolate', source='chocolate.txt zippy.h', target='vanilla.txt', always = True, update_outputs = True, color='GREEN', mappings={'': (lambda self, node : None)})
```

**Comment by jason-s** [comment]
I guess I could use `@TaskGen.before_method( 'process_source' )`  also:

@TaskGen.feature('remove_chocolate')
@TaskGen.before_method( 'process_source' ) 
def remove_chocolate(self):
    print "setting up remove chocolate\ninputs=%s\noutputs=%s" % (self.source, self.target)
    self.mappings={'': (lambda self, node : None)}
    t = create_taskgen_task(self, 'ChocolateRemover')
