### ISSUE TITLE
factor out task-setup convenience logic so it can be used outside of TaskGen.process_rule

### ISSUE THREAD

**Issue by jason-s** [waf-project/waf#1634]
The stuff in `TaskGen.process_rule` is really helpful if I'm using rule-based definitions like

    bld(rule='${MUNGE} ${SRC} ${TGT}', source='foo.txt', target='bar.txt')

but if I'm not using rule-based definitions, I have to manually duplicate that work. In particular it's the source and target string -> node processing:

from https://github.com/waf-project/waf/blob/master/waflib/TaskGen.py#L602:

	# now create one instance
	tsk = self.create_task(name)

	if getattr(self, 'target', None):
		if isinstance(self.target, str):
			self.target = self.target.split()
		if not isinstance(self.target, list):
			self.target = [self.target]
		for x in self.target:
			if isinstance(x, str):
				tsk.outputs.append(self.path.find_or_declare(x))
			else:
				x.parent.mkdir() # if a node was given, create the required folders
				tsk.outputs.append(x)
		if getattr(self, 'install_path', None):
			self.bld.install_files(self.install_path, tsk.outputs)

	if getattr(self, 'source', None):
		tsk.inputs = self.to_nodes(self.source)
		# bypass the execution of process_source by setting the source to an empty list
		self.source = []

	if getattr(self, 'cwd', None):
		tsk.cwd = self.cwd

In my case I would like to create my own Task classes instead, but still use a string -> node convenience feature to setup the source and target nodes properly.

**Comment by ita1024** [comment]
Then just do that?

**Comment by ita1024** [comment]
When *not* using the rule definitions, duplication of code is not the only possibility: wrapping task generator definition and extension-based processing are other simple possibilities. Else functionality can be duplicated, and it is likely that it will be cherry-picked for efficiency reasons.
