### ISSUE TITLE
bld(rule='some expression here') can fail with shell=False due to Nod3 class; str() is missing in Task.compile_fun_noshell?

### ISSUE THREAD

**Issue by jason-s** [waf-project/waf#1635]
This works:

```
top = '.'
out = 'build'

def configure(ctx):
	pass

def build(bld):
    bld(rule='echo RULE is ${TGT[0]} ${SRC}', 
              source=['file1.txt','file2.txt'],
              target=['zark.h'],
              shell=True,
              color='GREEN', always=True)

```

and prints out:

    RULE is zark.h ..\file1.txt ..\file2.txt

but if you change to `shell=False` you get an error:

```
Traceback (most recent call last):
  File "C:\tmp\waf\test4\waf-1.8.14-7d91ad6f638c7699369d1dae6bcada57\waflib\Task.py", line 110, in process
    ret=self.run()
  File "<string>", line 15, in f
  File "C:\tmp\waf\test4\waf-1.8.14-7d91ad6f638c7699369d1dae6bcada57\waflib\Task.py", line 95, in exec_command
    return bld.exec_command(cmd,**kw)
  File "C:\tmp\waf\test4\waf-1.8.14-7d91ad6f638c7699369d1dae6bcada57\waflib\Context.py", line 173, in exec_command
    raise Errors.WafError('Execution failure: %s'%str(e),ex=e)
WafError: Execution failure: argument of type 'Nod3' is not iterable
```

It looks like the bug might be here in line 62 of Task.py:

```
COMPILE_TEMPLATE_NOSHELL = '''
def f(tsk):
	env = tsk.env
	gen = tsk.generator
	bld = gen.bld
	wd = getattr(tsk, 'cwd', None)
	def to_list(xx):
		if isinstance(xx, str): return [xx]
		return xx
	tsk.last_cmd = lst = []
	%s
	lst = [x for x in lst if x]              # <------------------
	return tsk.exec_command(lst, cwd=wd, env=env.env or None)
'''
```

Should it be this instead?

	lst = [str(x) for x in lst if x]             

If I make this change, the command-line construction works and I just get an error because it can't find an "echo" command (but that's expected); waf build -v shows this:

     18:05:03 runner ['echo', 'RULE', 'is', 'zark.h', '..\\file1.txt', '..\\file2.txt']

which looks correct.

**Comment by ita1024** [comment]
"TGT[0]" is equivalent to "task.outputs[0]" which is a Node object. You can call methods on that object.

**Comment by jason-s** [comment]
That's true, but my point is that with shell=True. the substituted values all get stringified. Either they should both stringify substituted values, or neither should.

**Comment by ita1024** [comment]
And the answer is no. Accidental stringification does not mandate an expensive cast to string for everything else
