### ISSUE TITLE
namespace collision: waflib.TaskGen decorators associate information with function __name__, not identity

### ISSUE THREAD

**Issue by jason-s** [waf-project/waf#1637]
The waflib.TaskGen decorators associate information with function __name__, not identity, and are stored directly as attributes under `waflib.TaskGen.task_gen`. What this means is **there is an implicit requirement that each decorated function have a unique name** and that decorated functions **must not have the same name as an internal method of task_gen**. This breaks in at least three cases:

- There is a name conflict where there are two decorated functions with the same name in different places.

```
   myfile1.py:
   @feature('foo')
   def mxyzptlk(self):
       ...

   myfile2.py:
   @feature('bar'):
   def mxyzptlk(self):
       ...
```

- Closures are used for higher-order procedures:

```
def do_stuff_with_feature(func, featurename)
   @feature(featurename)
   def f(self):
     func(self)
     other_stuff_happens_here(self)
```

- I happen to use a function name that is shared with the internal attributes of `waflib.TaskGen.task_gen`, like `mappings` or `prec` or `get_name` or `post`.

These are true because of the implementations of `feature` and `before_method` and the other decorators:

```
def feature(*k):
	"""
	Decorator: register a task generator method that will be executed when the
	object attribute 'feature' contains the corresponding key(s)::
		from waflib.Task import feature
		@feature('myfeature')
		def myfunction(self):
			print('that is my feature!')
		def build(bld):
			bld(features='myfeature')
	:param k: feature names
	:type k: list of string
	"""
	def deco(func):
		setattr(task_gen, func.__name__, func)              # <----- problem
		for name in k:
			feats[name].update([func.__name__])        # <----- problem
		return func
	return deco
```

The last point here (collisions between `task_gen`'s internal attributes, and external decorated functions) can be fixed by assigning to a private dictionary within `task_gen`, that is used for no other purpose; the name collision issue could be fixed using `id(func)` instead of `func.__name__` (and fixing up any other references to function names)

**Comment by jason-s** [comment]
for example, this works (waf book section 9.3.3 Task generator features):

```
top = '.'
out = 'build'

def configure(conf):
        pass

def build(bld):
        bld(features='ping')
        bld(features='ping pong')

from waflib import TaskGen

@TaskGen.feature('ping')
def ping(self):
        print('ping')

@TaskGen.feature('pong')
def pong(self):
        print('pong')
```

but if you change the last function to

```
@TaskGen.feature('pong')
def post(self):
        print('pong')
```

it wrecks the functionality of waflib.TaskGen.task_gen.

**Comment by jason-s** [comment]
For the closure case (which is where I ran into this bug), I think I can get around it for now by assigning a function name myself (see below), but otherwise this seems like it's something I should not have to worry about.

```
# alter a function's __name__ attribute
def rename(x):
   def deco(f):
     f.__name__ = x
     return f
   return deco

def do_stuff_with_feature(func, featurename, unique_function_name)
   @feature(featurename)
   @rename(unique_function_name)
   def f(self):
     func(self)
     other_stuff_happens_here(self)
```

**Comment by ita1024** [comment]
This is completely intentional: function names must be unique. Same thing with module names and class names.

**Comment by jason-s** [comment]
>This is completely intentional: function names must be unique.

Then could you please document that when using these decorators (taskgen_method feature before_method before after_method after extension), decorated function names must be unique, and that waf users are responsible for ensuring that the decorated function names should not conflict with any of `waflib.TaskGen.task_gen`'s internal implementation attributes, or the decorated function names used elsewhere in waflib?

I counted 92 function names in various places (core classes and tools) in waf 1.8.14 that use these decorators (list below), which waf users need to avoid.

I respect your sense of architectural integrity in waf, but I really think you should reconsider on this one. It may be intentional, but I'd consider it a design flaw.

```
accept_node_to_link
add_dbus_file
add_enums
add_enums_from_template
add_lang
add_lua
add_marshal_file
add_objects_from_tgen
add_pcfile
add_settings_enums
add_settings_schemas
add_test_results
add_those_o_files
apply_bundle
apply_cs
apply_flags_msvc
apply_implib
apply_incpaths
apply_intltool_in_f
apply_intltool_po
apply_java
apply_link
apply_manifest
apply_msgfmt
apply_nasm_vars
apply_qt4
apply_qt5
apply_ruby_so_name
apply_tex
apply_vnum
asm_hook
big_bison
create_bundle_dirs
create_compiled_task
create_javadoc
create_rcc_task
create_task_macapp
create_task_macplist
create_uic_task
cxx_hook
d_hook
debug_cs
dummy
ensure_localedir
fc_hook
feature_py
generate_header
get_uselib_vars
grep_for_endianness_fun
init_perlext
init_pyembed
init_pyext
init_rubyext
init_vala_task
jar_files
link_lib_test_fun
link_main_routines_tg_method
make_test
make_windows_app
make_winphone_app
process
process_dbus
process_enums
process_gresource_bundle
process_gresource_source
process_header
process_lib
process_marshal
process_objs
process_py
process_rule
process_settings
process_source
process_subst
process_use
propagate_uselib_vars
rc_file
sequence_order
set_bundle
set_classpath
set_full_paths_hpux
set_lib_pat
set_macosx_deployment_target
test_exec_fun
to_incnodes
to_nodes
use_cs
use_jar_files
use_javac_files
use_rec
vala_file
xsubpp_file
```

**Comment by ita1024** [comment]
The name "task generator method" hints at class methods. This is actually hinted in many more places: `The method could be bound by using setattr directly, like for binding any new method on a python class`.

Now the design is absolutely intentional:
1. The method name is significant in order to process task generator methods
2. Least surprise: features having a different definition of methods would lead to untractable behaviour. The feature declaration is unbounded by any object such as a context class or an existing class.
3. Consistency: the behaviour is the same as `@conf`
4. Flexibility: modules such as `compat15.py` rebind methods to change the behaviour of existing code
5. Simplicity: there is only one method of a name defined once the build has started
6. Performance in method lookup

Do you have any actual usecase that would justify the addition of an extra dimension?

Warnings would show up in legitimate cases for method replacement, so that will not happen.
