### ISSUE TITLE
Enhancement: Remove boilerplate by caching `options` behaviour.

### ISSUE THREAD

**Issue by Parakleta** [waf-project/waf#1638]
I'm not confident with the waf tool yet but there seems to be some boilerplate that could be removed if actions were cached, and there is already some caching but it seems a little inconsistent.

Given that the `options` function is always called before any other action it seems that this would be the ideal place to do the caching.

The repeated actions / boilerplate that I've come across so far seems to be that for an `opt.load` should always be paired with a `conf.load`, and a `conf.recurse` should be paired with a `bld.recurse` (and may be preceded by a `opt.recurse`).  Obviously this will vary by project.

Regarding existing caching it seems that `opt.load` caches into `Context.Context.tools` but this is hidden from `ConfigurationContext` because it creates its own `tools` element to prevent double loading and to provide automatic loading in the `build` rules.  There is no prevention of double loading that I can see in the `options` based `Context.load`.

In the case of recursion `ConfigurationContext.post_recurse` caches recursed configurations which are then stored in the default `ConfigSet` in the lock file, but this information is not made generally available.  It would be possible to make this information available to the `OptionsContext` so that only the options related to recursed configurations are loaded and shown, but I think this would get messy with multiple runs showing different options (cached from the previous run).  I think probably the better option is to make the list of recursed `options` available to `configure` and the combined list available to `build`.

The idea would then be that a possible implementation would be:
```
def options(opt):
    opt.load(tool_list)
    opt.recurse(subdir_list)

def configure(cnf):
    cnf.load(cnf.tools) # currently cnf.load(Context.tools.keys()) works
    cnf.recurse(cnf.subdirs, mandatory=False)

def build(bld):
    bld.recurse(bld.subdirs, mandatory=False)
```

In this way just the `options` method is required for setting up tools and subdirectories and `configure` and `build` can just piggyback on the work done in `options`.  There would be no requirement for the new behaviour to be used, but it would give a few more options for managing hierarchical builds.

**Comment by ita1024** [comment]
In general, `opt.load` does not require that `conf.load` and `bld.load` are written. Not all Waf tools provide both options and configuration options either.

The information stored by `ConfigurationContext` is kept for automatic project reconfiguration. It is also too late to parse options once the configuration is initiated.

Such a feature would add quite a lot of magic to the build scripts, so I am rather unsure it is necessary.

**Comment by Parakleta** [comment]
Magic is only misunderstood technology.  A lot of `waf` looks like magic to me at the moment but as I work through the documentation and source it becomes clearer.  My examples were more to show what would be possible, not required.

What I am really asking for is just that there be some way to get a list of the loaded tools and the loaded sub-scripts in some consistent fashion.  Given that the sequence always seems to be `opt -> conf` or `opt -> build` or `opt -> conf -> build` it makes sense to me to at least initialise this list/cache in the `options` process and store it in the parent Context class so it's available to all the others.

Once I have those lists available it's up to me what to do with it.  I could for example query if a tool was loaded by a subscript and take some action, or I could optionally load a sub-script in `configure` based on some rule and then in `build` query if the script has been loaded.  It's really just about knowing the environment in which the build is occurring at each step (i.e. the context).  If something modifies my build I want to know programatically what it is.

**Comment by ita1024** [comment]
Wrong label...

**Comment by ita1024** [comment]
There is no clear solution for this, and the benefits are limited so we are closing this issue now.
