### ISSUE TITLE
build progress indicator [i/n] has concurrency problems (just in indicator, tasks run fine)

### ISSUE THREAD

**Issue by jason-s** [waf-project/waf#1641]
wscript:

```
import time

top = '.'
out = 'build'

def configure(ctx):
	pass

def build(bld):
	def codegen(task):
		for out in task.outputs:
			time.sleep(0.1)
			out.write('I am an output file')
		return 0
		
	for k in xrange(30):
		bld(
			rule   = codegen,
			target = '%d.c' % k,
			update_outputs = True,
			color='green'
		)
```

Results using waf 1.8.14 on Windows 7 on an 8-core Lenovo laptop:

```
C:\tmp\waf\test8>waf configure build
Setting top to                           : C:\tmp\waf\test8
Setting out to                           : C:\tmp\waf\test8\build
'configure' finished successfully (0.000s)
Waf: Entering directory `C:\tmp\waf\test8\build'
[ 2/30] Creating build\0.c
[ 2/30] Creating build\1.c
[ 3/30] Creating build\2.c
[ 4/30] Creating build\3.c
[ 6/30] Creating build\4.c
[ 6/30] Creating build\5.c
[ 7/30] Creating build\6.c
[ 8/30] Creating build\7.c
[10/30] Creating build\8.c
[10/30] Creating build\9.c
[12/30] Creating build\10.c
[12/30] Creating build\11.c
[15/30] Creating build\12.c
[16/30] Creating build\13.c
[16/30] Creating build\14.c
[16/30] Creating build\15.c
[19/30] Creating build\16.c
[21/30] Creating build\17.c
[21/30] Creating build\18.c
[22/30] Creating build\19.c
[23/30] Creating build\20.c
[24/30] Creating build\21.c
[24/30] Creating build\23.c
[24/30] Creating build\22.c
[25/30] Creating build\24.c
[27/30] Creating build\25.c
[29/30] Creating build\26.c
[30/30] Creating build\27.c
[30/30] Creating build\28.c
[30/30] Creating build\29.c
Waf: Leaving directory `C:\tmp\waf\test8\build'
'build' finished successfully (0.468s)
```

**Comment by jason-s** [comment]
problem possibly in the `Task.display.cur()` function.

```
	def display(self):
		col1=Logs.colors(self.color)
		col2=Logs.colors.NORMAL
		master=self.master
		def cur():
			tmp=-1
			if hasattr(master,'ready'):
				tmp-=master.ready.qsize()
			return master.processed+tmp
		if self.generator.bld.progress_bar==1:
			return self.generator.bld.progress_line(cur(),master.total,col1,col2)
		if self.generator.bld.progress_bar==2:
			ela=str(self.generator.bld.timer)
			try:
				ins=','.join([n.name for n in self.inputs])
			except AttributeError:
				ins=''
			try:
				outs=','.join([n.name for n in self.outputs])
			except AttributeError:
				outs=''
			return'|Total %s|Current %s|Inputs %s|Outputs %s|Time %s|\n'%(master.total,cur(),ins,outs,ela)
		s=str(self)
		if not s:
			return None
		total=master.total
		n=len(str(total))
		fs='[%%%dd/%%%dd] %%s%%s%%s%%s\n'%(n,n)
		kw=self.keyword()
		if kw:
			kw+=' '
		return fs%(cur(),total,kw,col1,s,col2)
```

**Comment by jason-s** [comment]
either that or the line in `Task.process` that calls `self.log_display()` should be protected by a thread lock.

**Comment by ita1024** [comment]
Locks affect performance negatively, so we will not be doing that. You can also wrap the execution or run the build with -j1 if the exact count is important for you.

**Comment by jason-s** [comment]
ok, no big deal, just thought I'd file a report. 

What matters the most here in my opinion is that it is a very visible part of waf, and if engineers who aren't familiar with waf see the build output in a CI server like Jenkins, they will experience Doubt and not accept waf because they're not sure they can trust it. I've had to tell my team "ignore the flaky progress counter".

It seems like locks just for the log output (I am not talking about locks for anything else) shouldn't affect performance significantly... but then again, I'm not using `waf` to build projects with thousands of build steps. I don't remember whether Python's `sys.stdout` or its logging mechanism grabs the GIL, so even if your policy is "we don't want locks, they hurt performance", you may be getting one anyway when you print these messages.

**Comment by ita1024** [comment]
I think you are associating the numbers with the exact task being processed. The main purposes of this output are to know whether the build is stuck and to provide a useful indication of the build status when waiting for a build to finish. The counters (total/processed) are modified by the main thread, so the main thread also has to be locked in order to prevent further tasks from getting added and change the counter.

The only robust way to have a strictly increasing counter with distinct number is to have messages displayed by the main thread (this was in Waf 1.4). Since tasks are waiting in a queue, the build would print a lot of messages to the console at once (waiting queue size), while no commands were actually being processed. For example, one would think that the build is already linking object files while compilations are still being processed in queue.

**Comment by jason-s** [comment]
huh, ok... it sounds like there are some subtleties here I hadn't thought of.

**Comment by ita1024** [comment]
Verified working around e6bb4693cb54a3665012dc7742cb80c6c844004e on the waf-1.9 branch

**Comment by ita1024** [comment]
Use waf 1.9.0
