### ISSUE TITLE
How to check for a minimum version of a python module during configure?

### ISSUE THREAD

**Issue by stiffupperlip** [waf-project/waf#1642]
In addition to check for presence of a particular python module during `./waf configure`, I need to also check for it to be of minimum version number. How can I achieve this?

**Comment by ita1024** [comment]
Python module version numbers do not seem to follow any particular standard. Run your own command by running commands, for example:
`ret = conf.cmd_and_log(conf.env['PYTHON'] + ['-c', 'some code here']`

**Comment by stiffupperlip** [comment]
Thanks. That solved the problem.

For the record I ended up with:

    conf.cmd_and_log(conf.env['PYTHON'] + ['-c', 'import sys, mymodule; from distutils.version import StrictVersion; sys.exit(0 if StrictVersion(mymodule.__version__) >= StrictVersion("0.1") else 1)'])
