### ISSUE TITLE
Incorrect directory name in bld.recurse() leads to confusing error

### ISSUE THREAD

**Issue by BuildMonkey** [waf-project/waf#1643]
If a user accidentally makes a typo in a directory name within bld.recurse('NON-EXISTENT_DIR'), the returned error message is
  No wscript file in directory /DIR/NON-EXISTENT-DIR

My users find this message a bit confusing and asked if I could log with you to see if a message that the directory does not exist instead.

Thanks.

**Comment by ita1024** [comment]
e3ac7630eb0bf07873f7c461e6758173fbf81dd8
