### ISSUE TITLE
How to suppress a build command's console output in waf?

### ISSUE THREAD

**Issue by stiffupperlip** [waf-project/waf#1644]
How can I suppress output of a command from being printed to console, during build? The command is an external OS command and is invoked like this:

    bld(rule='cmd ${SRC} ${TGT}', source='input.txt', target='output.txt')

Besides adding shell redirection to command, is there any waf option to accomplish this? How to suppress both stdout and stderr streams of command?

**Comment by ita1024** [comment]
`rule=<python function>` and call `cmd_and_log` as you already did
