### ISSUE TITLE
sphinx theme error

### ISSUE THREAD

**Issue by thmo** [waf-project/waf#1645]
Building docs against Sphinx < 1.3 fails with the following error:
```
Theme error:
no theme named 'classic' found (missing theme.conf?)
```
This is caused by c6f98f80.

Maybe one could make this a conditional like this (untested):
```python
from sphinx import version_info
if (1, 3) <= version_info:
  html_theme = 'classic'
else
  html_theme = 'default'
```

**Comment by thmo** [comment]
Oops, wrong project, sorry.

**Comment by ita1024** [comment]
Could you test that and perhaps open a pull request? I only have Sphinx 1.3.
