### ISSUE TITLE
subst feature does not honor attributes chmod, always when fun attribute is used

### ISSUE THREAD

**Issue by BuildMonkey** [waf-project/waf#1650]
bld(feature='subst', fun='anotherSubstFunction', chmod=Utils.O755, always=True)

The chmod and always attributes are ignored when using the fun attribute. Is there a way for them to be honored or a reason they are not used?

Thanks.

**Comment by ita1024** [comment]
That's a bit complicated. Since new function is implemented, calling `os.chmod` in it is certainly possible, is it not?

**Comment by ita1024** [comment]
And the `always` attribute is never used by 'subst'.

**Comment by BuildMonkey** [comment]
I tried in my fun=myFunction to use os.chmod but when the file is installed, the permissions from the file in the build/ subdirectory are not transferred over to the installed directory.

**Comment by ita1024** [comment]
The `rule` and `subst` systems are completely different beasts that should not get mixed up.

Use c2605e4dbb54da930bbc3845343cf57269ef8ac9 to have the chmod settings applied.

**Comment by BuildMonkey** [comment]
I'll wait for the next iteration to try out this change.

Thanks.

**Comment by ita1024** [comment]
You have not really tried, have you?
