### ISSUE TITLE
ifort version check failed

### ISSUE THREAD

**Issue by tailriver** [waf-project/waf#1655]
For localized Intel Fortran Compiler, it may print localized version information and fail to match the version string defined in `waflib/Tools/ifort.py`.

    $ ./waf --version
    waf 1.8.16 (30336cd9ba1a1c47c52edf69967457afd7967978)

    $ ./waf --check-fortran-compiler=ifort -vv
    (snip)
      File "/.../wscript", line 18, in configure
        conf.load('compiler_fc')
      File "/.../.waf-1.8.16-62b1bd1a26843637845309e604a98bca/waflib/Configure.py", line 153, in load
        if type(func)is type(Utils.readf):func(self)
      File "/.../.waf-1.8.16-62b1bd1a26843637845309e604a98bca/waflib/Tools/compiler_fc.py", line 32, in configure
        conf.fatal('could not configure a Fortran compiler!')
      File "/.../.waf-1.8.16-62b1bd1a26843637845309e604a98bca/waflib/Context.py", line 253, in fatal
        raise self.errors.ConfigurationError(msg,ex=ex)
    (snip)
 
    $ LANG=C ./waf --check-fortran-compiler=ifort
    (it's ok)

    $ ifort -logo
    インテル(R) 64 対応インテル(R) Fortran コンパイラー XE (インテル(R) 64 対応アプリケーション用)、バージョン 15.0.3.187 ビルド 20150407
    (C) 1985-2015 Intel Corporation.  無断での引用、転載を禁じます。

    $ LANG=C ifort -logo
    Intel(R) Fortran Intel(R) 64 Compiler XE for applications running on Intel(R) 64, Version 15.0.3.187 Build 20150407
    Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.

**Comment by ita1024** [comment]
Try a46cb274a74e309bda8f7837356179c5d1e7f4bd

**Comment by ita1024** [comment]
..

**Comment by ita1024** [comment]
Use waf 1.8.18 and reopen if broken.
