### ISSUE TITLE
unittest run before symlinking

### ISSUE THREAD

**Issue by ieei** [waf-project/waf#1656]
`waf_unit_tests.py` uses `@after_method('apply_link')`

My example test application is testing a library which you can see from the following is first linked, then run. I'm building this library using `vnum` and the test application is then linking in libmylib.1.dylib on osx, but theres a race here. task 72 of 72 is actually creating the symlinks, but in this case it hasn't been run yet. Which causes the build to fail

```
...
[70/72] Linking _build_/debug/test/mytest
[71/72] Running test _build_/debug/test/mytest
Waf: Leaving directory `/path/_build_/debug'
Ran '['/path/_build_/debug/test/mytest']' ret: -5
err: 
dyld: Library not loaded: /usr/local/lib/libmylib.1.dylib
  Referenced from: /path/_build_/debug/test/mytest
  Reason: image not found
Build failed
...
```

If this is intended or if I'm doing something wrong please just close this issue and educate me! :) Thanks.

**Comment by ieei** [comment]
No, - I am mistaken here! Running waf from my dev setup with modifications. Sorry

**Comment by ita1024** [comment]
This would have surprised me: the `utest` class has the constraint `after = ['vnum', 'inst']` to make it wait for symlinks.

**Comment by ieei** [comment]
@ita1024 sorry, don't mind me ;)
