### ISSUE TITLE
Incorrect dependency cache when header file is renamed

### ISSUE THREAD

**Issue by digiways** [waf-project/waf#1660]
I just noticed an issue with WAF where incorrect dependency is cached if a header file is removed, and readded.
Example:
== test.cpp ==
```cpp
#include "test.hpp"
int main() {}
```
== test.hpp ==
```cpp
void foobar() {}
```
== wscript ==
```python
VERSION='0.0.1'
APPNAME='cxx_test'
top = '.'
out = 'build'
def options(opt):
	opt.load('compiler_cxx')
def configure(conf):
	conf.load('compiler_cxx')
def build(bld):
	bld.program(source='test.cpp', target='test')
```

Step 1. We run ./waf configure & ./waf, and it all builds fine. 
Step 2. We rename "test.hpp" to "test.hpp.tmp" and rerun the build. Build fails.
Step 3. We rename "test.hpp.tmp" back to "test.hpp" and rerun the build. Build succeeds.
Step 4. Now we have incorrect dependency cached, and if we modify "test.hpp", nothing gets recompiled.

Any ideas how to fix this? This seems like a valid user behaviour.

**Comment by ita1024** [comment]
Update your copy:
6c34e2a654f54574a89f2e4f9cc6d38baddbaf8a

**Comment by digiways** [comment]
Beautiful, thank you so much !!
