### ISSUE TITLE
task_gen.idx increment logic problem?

### ISSUE THREAD

**Issue by martijnthe** [waf-project/waf#1661]
Hi,

I'm having an issue where a source file that is used by two targets (each with different environment and each defined in different wscripts) get recompiled twice (expected) but with the same target path.

My source folder structure:

```
- wscript   <= main, just recurses into a/ and b/
- shared.c
- a/
  - a.c
  - wscript  <= defines target for a.c + shared.c
- b/
  - b.c
  - wscript  <= defines target for b.c + shared.c
```

[The code that increments task_gen.idx](https://github.com/waf-project/waf/blob/waf-1.7/waflib/TaskGen.py#L91), keeps an index value *per wscript folder* and increments it.
This can result in the same idx value being used when compiling shared.c, if it's used from multiple wscript / folders.

In my case, shared.2.o would get written in *the same place* for both targets, creating this problem: if the shared.2.o object file for "a" would get overwritten by "b", before "a" was finished linking, the end result of "a" would contain the shared.2.o with the environment/configuration of "b"...

Maybe you're not supposed to use waf like this, but there's nothing to prevent you from doing so.

I think the fix is to just keep an index per *source node*, not per wscript folder, and increment it every time it's sourced?

**Comment by ita1024** [comment]
If a global index were set, then adding just one target would cause a full rebuild of the **entire** project. We do not want that.

It is easy enough to have the declarations in a single wscript file or to provide an idx attribute manually: `bld.program(..., idx=8989)`.

**Comment by martijnthe** [comment]
Sorry,  I meant to write "keep an index per source node", not target node.

Manually setting the `idx` sounds like it's prone to human error. One would need some way to know there will be no overlaps.

**Comment by ita1024** [comment]
And global settings have the potential of triggering spooky rebuilds. This said, we could enable something like that in Waf 1.9.

**Comment by ita1024** [comment]
One index per source node will cause rebuilds when executing partial builds such as "waf --targets=", and obtaining the list of all source files is something that we want to avoid in such a case.
