### ISSUE TITLE
Could not build a python embedded interpreter

### ISSUE THREAD

**Issue by dfroger** [waf-project/waf#1663]
I often "randomly" have this error when using swig:

    Getting pyembed flags from python-config                           : Could not build a python embedded interpreter

Here is a minimal `wscript`:

    #! /usr/bin/env python

    def options(opt):
        opt.load('compiler_c python')

    def configure(conf):
        conf.load('compiler_c python')
        conf.check_python_version((2,4,2))
        conf.check_python_headers()

        conf.load('swig')
        if conf.check_swig_version() < (1, 2, 27):
            conf.fatal('this swig version is too old')

I'm using waf 1.8.16.

My environment is this [vagrant box](https://atlas.hashicorp.com/inria-pro-sed/boxes/conda-build-osx-10.9) ([recipe](https://github.com/sed-pro-inria/conda-build-osx-10.9)), using Python and SWIG from conda repo:

    conda create -n swig python=2.7 swig
    source activate swig

This works:

    waf configure

But setting CFLAGS makes it fail (on another OS X  install of the same version, it works):

    CFLAGS='' waf configure

    Setting top to                           : /Users/vagrant/repo/dfroger/quickstart/bug
    Setting out to                           : /Users/vagrant/repo/dfroger/quickstart/bug/build
    Checking for 'clang' (C compiler)        : /usr/local/ccache/bin/clang
    Checking for program 'python'            : /Users/vagrant/miniconda3/envs/swig/bin/python
    Checking for python version              : (2, 7, 10, 'final', 0)
    python-config                            : /Users/vagrant/miniconda3/envs/swig/bin/python-config Asking python-config for pyembed '--cflags --libs --ldflags' flags : yes 
    Testing pyembed configuration                                      : Could not build a python embedded interpreter
    Testing pyembed configuration                                      : Could not build a python embedded interpreter
    The configuration failed
    (complete log in /Users/vagrant/repo/dfroger/quickstart/bug/build/config.log)

As we can see in /Users/vagrant/repo/dfroger/quickstart/bug/build/config.log, waf is trying to use /Developer/SDKs/MacOSX10.5.sdk without reason:

    # project  configured on Mon Nov 30 23:25:40 2015 by
    # waf 1.8.16 (abi 98, python 2070af0 on darwin)
    # using /Users/vagrant/miniconda3/envs/swig/bin/waf configure
    #
    ----------------------------------------
    Setting top to
    /Users/vagrant/repo/dfroger/quickstart/bug
    ----------------------------------------
    Setting out to
    /Users/vagrant/repo/dfroger/quickstart/bug/build
    ----------------------------------------
    Checking for 'clang' (C compiler)
    find program=['clang'] paths=['/Users/vagrant/miniconda3/envs/swig/bin', '/usr/local/ccache/bin', '/usr/bin', '/bin', '/usr/sbin', '/sbin', '/usr/local/bin'] var='CC' -> ['/usr/local/ccache/bin/clang']
    ['/usr/local/ccache/bin/clang', '-dM', '-E', '-']
    out: #define OBJC_NEW_PROPERTIES 1
    #define _LP64 1
    #define __APPLE_CC__ 6000
    #define __APPLE__ 1
    #define __ATOMIC_ACQUIRE 2
    #define __ATOMIC_ACQ_REL 4
    #define __ATOMIC_CONSUME 1
    #define __ATOMIC_RELAXED 0
    #define __ATOMIC_RELEASE 3
    #define __ATOMIC_SEQ_CST 5
    #define __BLOCKS__ 1
    #define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
    #define __CHAR16_TYPE__ unsigned short
    #define __CHAR32_TYPE__ unsigned int
    #define __CHAR_BIT__ 8
    #define __CONSTANT_CFSTRINGS__ 1
    #define __DBL_DENORM_MIN__ 4.9406564584124654e-324
    #define __DBL_DIG__ 15
    #define __DBL_EPSILON__ 2.2204460492503131e-16
    #define __DBL_HAS_DENORM__ 1
    #define __DBL_HAS_INFINITY__ 1
    #define __DBL_HAS_QUIET_NAN__ 1
    #define __DBL_MANT_DIG__ 53
    #define __DBL_MAX_10_EXP__ 308
    #define __DBL_MAX_EXP__ 1024
    #define __DBL_MAX__ 1.7976931348623157e+308
    #define __DBL_MIN_10_EXP__ (-307)
    #define __DBL_MIN_EXP__ (-1021)
    #define __DBL_MIN__ 2.2250738585072014e-308
    #define __DECIMAL_DIG__ 21
    #define __DYNAMIC__ 1
    #define __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ 1090
    #define __FINITE_MATH_ONLY__ 0
    #define __FLT_DENORM_MIN__ 1.40129846e-45F
    #define __FLT_DIG__ 6
    #define __FLT_EPSILON__ 1.19209290e-7F
    #define __FLT_EVAL_METHOD__ 0
    #define __FLT_HAS_DENORM__ 1
    #define __FLT_HAS_INFINITY__ 1
    #define __FLT_HAS_QUIET_NAN__ 1
    #define __FLT_MANT_DIG__ 24
    #define __FLT_MAX_10_EXP__ 38
    #define __FLT_MAX_EXP__ 128
    #define __FLT_MAX__ 3.40282347e+38F
    #define __FLT_MIN_10_EXP__ (-37)
    #define __FLT_MIN_EXP__ (-125)
    #define __FLT_MIN__ 1.17549435e-38F
    #define __FLT_RADIX__ 2
    #define __GCC_ATOMIC_BOOL_LOCK_FREE 2
    #define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 2
    #define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 2
    #define __GCC_ATOMIC_CHAR_LOCK_FREE 2
    #define __GCC_ATOMIC_INT_LOCK_FREE 2
    #define __GCC_ATOMIC_LLONG_LOCK_FREE 2
    #define __GCC_ATOMIC_LONG_LOCK_FREE 2
    #define __GCC_ATOMIC_POINTER_LOCK_FREE 2
    #define __GCC_ATOMIC_SHORT_LOCK_FREE 2
    #define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
    #define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 2
    #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 1
    #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_16 1
    #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 1
    #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 1
    #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 1
    #define __GNUC_MINOR__ 2
    #define __GNUC_PATCHLEVEL__ 1
    #define __GNUC_STDC_INLINE__ 1
    #define __GNUC__ 4
    #define __GXX_ABI_VERSION 1002
    #define __GXX_RTTI 1
    #define __INT16_TYPE__ short
    #define __INT32_TYPE__ int
    #define __INT64_C_SUFFIX__ LL
    #define __INT64_TYPE__ long long int
    #define __INT8_TYPE__ char
    #define __INTMAX_MAX__ 9223372036854775807L
    #define __INTMAX_TYPE__ long int
    #define __INTMAX_WIDTH__ 64
    #define __INTPTR_TYPE__ long int
    #define __INTPTR_WIDTH__ 64
    #define __INT_MAX__ 2147483647
    #define __LDBL_DENORM_MIN__ 3.64519953188247460253e-4951L
    #define __LDBL_DIG__ 18
    #define __LDBL_EPSILON__ 1.08420217248550443401e-19L
    #define __LDBL_HAS_DENORM__ 1
    #define __LDBL_HAS_INFINITY__ 1
    #define __LDBL_HAS_QUIET_NAN__ 1
    #define __LDBL_MANT_DIG__ 64
    #define __LDBL_MAX_10_EXP__ 4932
    #define __LDBL_MAX_EXP__ 16384
    #define __LDBL_MAX__ 1.18973149535723176502e+4932L
    #define __LDBL_MIN_10_EXP__ (-4931)
    #define __LDBL_MIN_EXP__ (-16381)
    #define __LDBL_MIN__ 3.36210314311209350626e-4932L
    #define __LITTLE_ENDIAN__ 1
    #define __LONG_LONG_MAX__ 9223372036854775807LL
    #define __LONG_MAX__ 9223372036854775807L
    #define __LP64__ 1
    #define __MACH__ 1
    #define __MMX__ 1
    #define __NO_INLINE__ 1
    #define __NO_MATH_INLINES 1
    #define __ORDER_BIG_ENDIAN__ 4321
    #define __ORDER_LITTLE_ENDIAN__ 1234
    #define __ORDER_PDP_ENDIAN__ 3412
    #define __PIC__ 2
    #define __POINTER_WIDTH__ 64
    #define __PRAGMA_REDEFINE_EXTNAME 1
    #define __PTRDIFF_TYPE__ long int
    #define __PTRDIFF_WIDTH__ 64
    #define __REGISTER_PREFIX__ 
    #define __SCHAR_MAX__ 127
    #define __SHRT_MAX__ 32767
    #define __SIG_ATOMIC_WIDTH__ 32
    #define __SIZEOF_DOUBLE__ 8
    #define __SIZEOF_FLOAT__ 4
    #define __SIZEOF_INT128__ 16
    #define __SIZEOF_INT__ 4
    #define __SIZEOF_LONG_DOUBLE__ 16
    #define __SIZEOF_LONG_LONG__ 8
    #define __SIZEOF_LONG__ 8
    #define __SIZEOF_POINTER__ 8
    #define __SIZEOF_PTRDIFF_T__ 8
    #define __SIZEOF_SHORT__ 2
    #define __SIZEOF_SIZE_T__ 8
    #define __SIZEOF_WCHAR_T__ 4
    #define __SIZEOF_WINT_T__ 4
    #define __SIZE_MAX__ 18446744073709551615UL
    #define __SIZE_TYPE__ long unsigned int
    #define __SIZE_WIDTH__ 64
    #define __SSE2_MATH__ 1
    #define __SSE2__ 1
    #define __SSE3__ 1
    #define __SSE_MATH__ 1
    #define __SSE__ 1
    #define __SSP__ 1
    #define __SSSE3__ 1
    #define __STDC_HOSTED__ 1
    #define __STDC_UTF_16__ 1
    #define __STDC_UTF_32__ 1
    #define __STDC_VERSION__ 199901L
    #define __STDC__ 1
    #define __UINTMAX_TYPE__ long unsigned int
    #define __USER_LABEL_PREFIX__ _
    #define __VERSION__ "4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.38)"
    #define __WCHAR_MAX__ 2147483647
    #define __WCHAR_TYPE__ int
    #define __WCHAR_WIDTH__ 32
    #define __WINT_TYPE__ int
    #define __WINT_WIDTH__ 32
    #define __amd64 1
    #define __amd64__ 1
    #define __apple_build_version__ 5030038
    #define __block __attribute__((__blocks__(byref)))
    #define __clang__ 1
    #define __clang_major__ 5
    #define __clang_minor__ 1
    #define __clang_patchlevel__ 0
    #define __clang_version__ "5.1 (clang-503.0.38)"
    #define __core2 1
    #define __core2__ 1
    #define __llvm__ 1
    #define __pic__ 2
    #define __strong 
    #define __tune_core2__ 1
    #define __unsafe_unretained 
    #define __weak __attribute__((objc_gc(weak)))
    #define __x86_64 1
    #define __x86_64__ 1

    find program=['llvm-ar', 'ar'] paths=['/Users/vagrant/miniconda3/envs/swig/bin', '/usr/local/ccache/bin', '/usr/bin', '/bin', '/usr/sbin', '/sbin', '/usr/local/bin'] var='AR' -> ['/usr/bin/ar']
    find program=['ar'] paths=['/Users/vagrant/miniconda3/envs/swig/bin', '/usr/local/ccache/bin', '/usr/bin', '/bin', '/usr/sbin', '/sbin', '/usr/local/bin'] var='AR' -> ['/usr/bin/ar']
    /usr/local/ccache/bin/clang
    ----------------------------------------
    Checking for program 'python'
    /Users/vagrant/miniconda3/envs/swig/bin/python
    find program=['python'] paths=['/Users/vagrant/miniconda3/envs/swig/bin', '/usr/local/ccache/bin', '/usr/bin', '/bin', '/usr/sbin', '/sbin', '/usr/local/bin'] var='PYTHON' -> ['/Users/vagrant/miniconda3/envs/swig/bin/python']
    ['/Users/vagrant/miniconda3/envs/swig/bin/python', '-c', 'import imp;print(imp.get_tag())']
    err: Traceback (most recent call last):
      File "<string>", line 1, in <module>
    AttributeError: 'module' object has no attribute 'get_tag'

    ['/Users/vagrant/miniconda3/envs/swig/bin/python', '-c', 'import sys\nfor x in sys.version_info: print(str(x))']
    out: 2
    7
    10
    final
    0

    ['/Users/vagrant/miniconda3/envs/swig/bin/python', '-c', "from distutils.sysconfig import get_config_var, get_python_lib\n\nprint(repr(get_python_lib(standard_lib=0, prefix='/usr/local') or ''))"]
    out: '/usr/local/lib/python2.7/site-packages'

    '/usr/local/lib/python2.7/site-packages'

    ['/Users/vagrant/miniconda3/envs/swig/bin/python', '-c', "from distutils.sysconfig import get_config_var, get_python_lib\n\nprint(repr(get_python_lib(plat_specific=1, standard_lib=0, prefix='/usr/local') or ''))"]
    out: '/usr/local/lib/python2.7/site-packages'

    '/usr/local/lib/python2.7/site-packages'

    ----------------------------------------
    Checking for python version
    (2, 7, 10, 'final', 0)
    ['/Users/vagrant/miniconda3/envs/swig/bin/python', '-c', "from distutils.sysconfig import get_config_var, get_python_lib\n\nprint(repr(get_config_var('prefix') or ''))\nprint(repr(get_config_var('SO') or ''))\nprint(repr(get_config_var('LDFLAGS') or ''))\nprint(repr(get_config_var('LIBDIR') or ''))\nprint(repr(get_config_var('LIBPL') or ''))\nprint(repr(get_config_var('INCLUDEPY') or ''))\nprint(repr(get_config_var('Py_ENABLE_SHARED') or ''))\nprint(repr(get_config_var('MACOSX_DEPLOYMENT_TARGET') or ''))\nprint(repr(get_config_var('LDSHARED') or ''))\nprint(repr(get_config_var('CFLAGS') or ''))\nprint(repr(get_config_var('LDVERSION') or ''))"]
    out: '/Users/vagrant/miniconda3/envs/swig'
    '.so'
    '-L/Users/vagrant/miniconda3/envs/swig/lib -arch x86_64  '
    '/Users/vagrant/miniconda3/envs/swig/lib'
    '/Users/vagrant/miniconda3/envs/swig/lib/python2.7/config'
    '/Users/vagrant/miniconda3/envs/swig/include/python2.7'
    1
    '10.5'
    'gcc -bundle -undefined dynamic_lookup -L/Users/vagrant/miniconda3/envs/swig/lib -arch x86_64  '
    '-fno-strict-aliasing -I/Users/vagrant/miniconda3/envs/swig/include -arch x86_64 -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes'
    ''

    '/Users/vagrant/miniconda3/envs/swig'
    '.so'
    '-L/Users/vagrant/miniconda3/envs/swig/lib -arch x86_64  '
    '/Users/vagrant/miniconda3/envs/swig/lib'
    '/Users/vagrant/miniconda3/envs/swig/lib/python2.7/config'
    '/Users/vagrant/miniconda3/envs/swig/include/python2.7'
    1
    '10.5'
    'gcc -bundle -undefined dynamic_lookup -L/Users/vagrant/miniconda3/envs/swig/lib -arch x86_64  '
    '-fno-strict-aliasing -I/Users/vagrant/miniconda3/envs/swig/include -arch x86_64 -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes'
    ''

    Configuration returned from ['/Users/vagrant/miniconda3/envs/swig/bin/python']:
    prefix = '/Users/vagrant/miniconda3/envs/swig'
    SO = '.so'
    LDFLAGS = '-L/Users/vagrant/miniconda3/envs/swig/lib -arch x86_64  '
    LIBDIR = '/Users/vagrant/miniconda3/envs/swig/lib'
    LIBPL = '/Users/vagrant/miniconda3/envs/swig/lib/python2.7/config'
    INCLUDEPY = '/Users/vagrant/miniconda3/envs/swig/include/python2.7'
    Py_ENABLE_SHARED = 1
    MACOSX_DEPLOYMENT_TARGET = '10.5'
    LDSHARED = 'gcc -bundle -undefined dynamic_lookup -L/Users/vagrant/miniconda3/envs/swig/lib -arch x86_64  '
    CFLAGS = '-fno-strict-aliasing -I/Users/vagrant/miniconda3/envs/swig/include -arch x86_64 -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes'
    LDVERSION = ''

    ----------------------------------------
    python-config
    /Users/vagrant/miniconda3/envs/swig/bin/python-config
    find program=['/Users/vagrant/miniconda3/envs/swig/bin/python-config', 'python2.7-config', 'python-config-2.7', 'python2.7m-config'] paths=['/Users/vagrant/miniconda3/envs/swig/bin', '/usr/local/ccache/bin', '/usr/bin', '/bin', '/usr/sbin', '/sbin', '/usr/local/bin'] var='PYTHON_CONFIG' -> ['/Users/vagrant/miniconda3/envs/swig/bin/python-config']
    ------------------------------------------------------------------
    Asking python-config for pyembed '--cflags --libs --ldflags' flags
    ['/Users/vagrant/miniconda3/envs/swig/bin/python-config', '--cflags', '--libs', '--ldflags']
    out: -I/Users/vagrant/miniconda3/envs/swig/include/python2.7 -I/Users/vagrant/miniconda3/envs/swig/include/python2.7 -fno-strict-aliasing -I/Users/vagrant/miniconda3/envs/swig/include -arch x86_64 -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
    -lpython2.7 -ldl -framework CoreFoundation
    -lpython2.7 -ldl -framework CoreFoundation -u _PyMac_Error

    yes
    ------------------------------------------------------------------
    Testing pyembed configuration
    ==>

    #include <Python.h>
    #ifdef __cplusplus
    extern "C" {
    #endif
        void Py_Initialize(void);
        void Py_Finalize(void);
    #ifdef __cplusplus
    }
    #endif
    int main(int argc, char **argv)
    { 
       (void)argc; (void)argv;
       Py_Initialize();
       Py_Finalize();
       return 0;
    }

    <==
    [1/2] Compiling ^[[32mbuild/.conf_check_6b3cea92273b8a0091966440184db6d4/test.c^[[0m

    ['/usr/local/ccache/bin/clang', '-isysroot', '/Developer/SDKs/MacOSX10.5.sdk', '-fno-strict-aliasing', '-arch', 'x86_64', '-fwrapv', '-I/Users/vagrant/miniconda3/envs/swig/include/python2.7', '-I/Users/vagrant/miniconda3/envs/swig/include', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DHAVE_PYEMBED=1', '-DNDEBUG', '../test.c', '-c', '-o', '/Users/vagrant/repo/dfroger/quickstart/bug/build/.conf_check_6b3cea92273b8a0091966440184db6d4/testbuild/test.c.1.o']
    err: clang: warning: no such sysroot directory: '/Developer/SDKs/MacOSX10.5.sdk'
    In file included from ../test.c:2:
    /Users/vagrant/miniconda3/envs/swig/include/python2.7/Python.h:33:10: fatal error: 'stdio.h' file not found
    #include <stdio.h>
             ^
    1 error generated.

    from /Users/vagrant/repo/dfroger/quickstart/bug: Test does not build: Traceback (most recent call last):
      File "/Users/vagrant/miniconda3/envs/swig/bin/.waf-1.8.16-70467110a783bdfc89e611833bbfa1ce/waflib/Configure.py", line 334, in run_build
        bld.compile()
      File "/Users/vagrant/miniconda3/envs/swig/bin/.waf-1.8.16-70467110a783bdfc89e611833bbfa1ce/waflib/Build.py", line 185, in compile
        raise Errors.BuildError(self.producer.error)
    BuildError: Build failed
     -> task in 'testprog' failed (exit status 1):
        {task 4317263504: c test.c -> test.c.1.o}
    ['/usr/local/ccache/bin/clang', '-isysroot', '/Developer/SDKs/MacOSX10.5.sdk', '-fno-strict-aliasing', '-arch', 'x86_64', '-fwrapv', '-I/Users/vagrant/miniconda3/envs/swig/include/python2.7', '-I/Users/vagrant/miniconda3/envs/swig/include', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DHAVE_PYEMBED=1', '-DNDEBUG', '../test.c', '-c', '-o', '/Users/vagrant/repo/dfroger/quickstart/bug/build/.conf_check_6b3cea92273b8a0091966440184db6d4/testbuild/test.c.1.o']

    Could not build a python embedded interpreter
    from /Users/vagrant/repo/dfroger/quickstart/bug: The configuration failed
    ------------------------------------------------------------------
    Testing pyembed configuration
    ==>

    #include <Python.h>
    #ifdef __cplusplus
    extern "C" {
    #endif
        void Py_Initialize(void);
        void Py_Finalize(void);
    #ifdef __cplusplus
    }
    #endif
    int main(int argc, char **argv)
    { 
       (void)argc; (void)argv;
       Py_Initialize();
       Py_Finalize();
       return 0;
    }

    <==
    [1/2] Compiling ^[[32mbuild/.conf_check_6b3cea92273b8a0091966440184db6d4/test.c^[[0m

    ['/usr/local/ccache/bin/clang', '-isysroot', '/Developer/SDKs/MacOSX10.5.sdk', '-fno-strict-aliasing', '-arch', 'x86_64', '-fwrapv', '-I/Users/vagrant/miniconda3/envs/swig/include/python2.7', '-I/Users/vagrant/miniconda3/envs/swig/include', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DHAVE_PYEMBED=1', '-DNDEBUG', '../test.c', '-c', '-o', '/Users/vagrant/repo/dfroger/quickstart/bug/build/.conf_check_6b3cea92273b8a0091966440184db6d4/testbuild/test.c.1.o']
    err: clang: warning: no such sysroot directory: '/Developer/SDKs/MacOSX10.5.sdk'
    In file included from ../test.c:2:
    /Users/vagrant/miniconda3/envs/swig/include/python2.7/Python.h:33:10: fatal error: 'stdio.h' file not found
    #include <stdio.h>
             ^
    1 error generated.

    from /Users/vagrant/repo/dfroger/quickstart/bug: Test does not build: Traceback (most recent call last):
      File "/Users/vagrant/miniconda3/envs/swig/bin/.waf-1.8.16-70467110a783bdfc89e611833bbfa1ce/waflib/Configure.py", line 334, in run_build
        bld.compile()
      File "/Users/vagrant/miniconda3/envs/swig/bin/.waf-1.8.16-70467110a783bdfc89e611833bbfa1ce/waflib/Build.py", line 185, in compile
        raise Errors.BuildError(self.producer.error)
    BuildError: Build failed
     -> task in 'testprog' failed (exit status 1):
        {task 4317264976: c test.c -> test.c.1.o}
    ['/usr/local/ccache/bin/clang', '-isysroot', '/Developer/SDKs/MacOSX10.5.sdk', '-fno-strict-aliasing', '-arch', 'x86_64', '-fwrapv', '-I/Users/vagrant/miniconda3/envs/swig/include/python2.7', '-I/Users/vagrant/miniconda3/envs/swig/include', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DHAVE_PYEMBED=1', '-DNDEBUG', '../test.c', '-c', '-o', '/Users/vagrant/repo/dfroger/quickstart/bug/build/.conf_check_6b3cea92273b8a0091966440184db6d4/testbuild/test.c.1.o']

    Could not build a python embedded interpreter
    from /Users/vagrant/repo/dfroger/quickstart/bug: The configuration failed

**Comment by dfroger** [comment]
Oh, that strange:

    python-config --cflags
    -I/Users/vagrant/miniconda3/envs/swig/include/python2.7 -I/Users/vagrant/miniconda3/envs/swig/include/python2.7 -fno-strict-aliasing -I/Users/vagrant/miniconda3/envs/swig/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes

but:

    CFLAGS='' python-config --cflags
    -I/Users/vagrant/miniconda3/envs/swig/include/python2.7 -I/Users/vagrant/miniconda3/envs/swig/include/python2.7 -fno-strict-aliasing -I/Users/vagrant/miniconda3/envs/swig/include -arch x86_64 -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes

**Comment by dfroger** [comment]
Seem that is comes from here:
    https://github.com/python/cpython/blob/1fe0fd9feb6a4472a9a1b186502eb9c0b2366326/Lib/_osx_support.py#L296

I will not set CFLAGS, and instead add option in my wscript to pass it.

Don't know if I can close the issue, or if Python waf tool may issue a warning about this.

**Comment by ita1024** [comment]
It seems to work exactly as designed.

**Comment by ita1024** [comment]
(if a warning were added, then it would always appear when running under Xcode or other IDEs)
