### ISSUE TITLE
qt4 unchanged qrc files keep getting rebuilt

### ISSUE THREAD

**Issue by BuildMonkey** [waf-project/waf#1664]
I have an icon.qrc file that generates an icon_rc.cpp file. Even though I do not make changes to the icon.qrc file, I see that waf is still rebuilding the icon_rc.cpp file. Is there a way to stop this?

Thanks

**Comment by ita1024** [comment]
Remove the generated files from the source directory and run `waf distclean` once.

**Comment by BuildMonkey** [comment]
The icon_rc.cpp file is actually in the build directory that is deleted when you run 'waf distclean'. Your suggestion doesn't change the behavour.

**Comment by ita1024** [comment]
Then investigate why this is happening: `waf -v` and the `why.py` tool may help. The behaviour that you describe is not happening in `demos/qt4`.

**Comment by ita1024** [comment]
Closed for inactivity and no reproduceability (no testcase or anything to help).
