### ISSUE TITLE
"Attribute not found" - Exception in Node.path_from

### ISSUE THREAD

**Issue by Niko3** [waf-project/waf#1665]
On Waf 1.8.xx:
I'm getting an error on Node.path_from Method while checking the path from one node to another.
In my case the two nodes rely on the exactly same path but have different ids, however ... 
a check for the parent attribute would fix the problem and avoid throwing a exception, that might be thrown.

		if getattr(c1, "parent", None):
			for i in range(up):
				lst.append('..')
		else:
			if lst and not Utils.is_win32:
				lst.append('')

**Comment by ita1024** [comment]
It seems that you are mixing nodes from two different contexts. This is not allowed, only one node type can be used within a context.

**Comment by Niko3** [comment]
Thank you ita1024 the nodes where really saved in the base class .... my fault. So they really came from another context, my fault
