### ISSUE TITLE
Executables are sometimes needlessly re-linked

### ISSUE THREAD

**Issue by rr-** [waf-project/waf#1667]
My use case:

1. The project is written in C++ and consists of two executables
2. One of them takes long time to link
3. I want to change a dependency of the other executable and have waf compile that executable only.

The issue itself is that whenever I run `./waf`, it relinks both executables, even though *nothing is changed at all*. Furthermore, this behavior is random - sometimes waf figures out there's no need to link anything, and all targets are considered to be up to date. Statistically speaking, this correct behavior happens about once every 5-10 builds.

To prove that there's nothing different about the builds: I ran `waf -dvvv` multiple times without doing anything to the code, and here are parts of the log I believe to be the most important:

1. The case when waf **does not** relink the executables

        19:06:09 envhash 953955903c0566c01873ad683412f2dd [[], [], [], '-I%s', ['/usr/bin/g++'], [], ['-Wall', '-Wextra', '-pedantic', '-Wwrite-strings', '-Wno-unused-variable', '-Wno-unused-parameter', '-Wold-style-cast', '-ffloat-store', '-std=c++14', '-ggdb', '-iquote', '/home/rr-/src/arc_unpacker/src'], [], ['-c', '-o'], ['HAVE_ZLIB_H=1', 'HAVE_OPENSSL_RSA_H=1', 'HAVE_BOOST_FILESYSTEM_HPP=1', 'HAVE_BOOST_LOCALE_HPP=1'], '-D%s', [], [], ['/home/rr-/src/arc_unpacker/build/src', '/home/rr-/src/arc_unpacker/src']]
        19:06:09 envhash 3fa68bce3f7bd56815282b23f875f386 [[], [], [], '-I%s', ['/usr/bin/g++'], [], ['-Wall', '-Wextra', '-pedantic', '-Wwrite-strings', '-Wno-unused-variable', '-Wno-unused-parameter', '-Wold-style-cast', '-ffloat-store', '-std=c++14', '-ggdb', '-iquote', '/home/rr-/src/arc_unpacker/src'], [], ['-c', '-o'], ['HAVE_ZLIB_H=1', 'HAVE_OPENSSL_RSA_H=1', 'HAVE_BOOST_FILESYSTEM_HPP=1', 'HAVE_BOOST_LOCALE_HPP=1', 'AU_VERSION="0.8-218-g51d4c41-dirty"'], '-D%s', [], [], ['/home/rr-/src/arc_unpacker/build/src', '/home/rr-/src/arc_unpacker/src']]
        19:06:09 envhash 7135b5a1bc5268502f3ba7e66471846e [[], [], [], ['-o'], [], [], [], [], [], ['png', 'jpeg', 'z', 'boost_filesystem', 'boost_system', 'boost_locale', 'crypto'], [], '-L%s', '-l%s', [], [], ['/usr/bin/g++'], [], '-Wl,-rpath,%s', '-Wl,-Bdynamic', [], [], '-L%s', '-Wl,-Bstatic', '-l%s']
        19:06:09 envhash bba70267657a89097824ee6a1e5bd0c3 [[], [], [], '-I%s', ['/usr/bin/g++'], [], ['-Wall', '-Wextra', '-pedantic', '-Wwrite-strings', '-Wno-unused-variable', '-Wno-unused-parameter', '-Wold-style-cast', '-ffloat-store', '-std=c++14', '-ggdb', '-iquote', '/home/rr-/src/arc_unpacker/src', '-iquote', '/home/rr-/src/arc_unpacker/tests'], [], ['-c', '-o'], ['HAVE_ZLIB_H=1', 'HAVE_OPENSSL_RSA_H=1', 'HAVE_BOOST_FILESYSTEM_HPP=1', 'HAVE_BOOST_LOCALE_HPP=1'], '-D%s', [], [], ['/home/rr-/src/arc_unpacker/build/src', '/home/rr-/src/arc_unpacker/src', '/home/rr-/src/arc_unpacker/build/tests', '/home/rr-/src/arc_unpacker/tests']]
        19:06:09 envhash 7135b5a1bc5268502f3ba7e66471846e [[], [], [], ['-o'], [], [], [], [], [], ['png', 'jpeg', 'z', 'boost_filesystem', 'boost_system', 'boost_locale', 'crypto'], [], '-L%s', '-l%s', [], [], ['/usr/bin/g++'], [], '-Wl,-rpath,%s', '-Wl,-Bdynamic', [], [], '-L%s', '-Wl,-Bstatic', '-l%s']
        Waf: Leaving directory `/home/rr-/src/arc_unpacker/build'

2. The case when waf **does** relink the executables

        19:05:54 envhash 953955903c0566c01873ad683412f2dd [[], [], [], '-I%s', ['/usr/bin/g++'], [], ['-Wall', '-Wextra', '-pedantic', '-Wwrite-strings', '-Wno-unused-variable', '-Wno-unused-parameter', '-Wold-style-cast', '-ffloat-store', '-std=c++14', '-ggdb', '-iquote', '/home/rr-/src/arc_unpacker/src'], [], ['-c', '-o'], ['HAVE_ZLIB_H=1', 'HAVE_OPENSSL_RSA_H=1', 'HAVE_BOOST_FILESYSTEM_HPP=1', 'HAVE_BOOST_LOCALE_HPP=1'], '-D%s', [], [], ['/home/rr-/src/arc_unpacker/build/src', '/home/rr-/src/arc_unpacker/src']]
        19:05:54 envhash 3fa68bce3f7bd56815282b23f875f386 [[], [], [], '-I%s', ['/usr/bin/g++'], [], ['-Wall', '-Wextra', '-pedantic', '-Wwrite-strings', '-Wno-unused-variable', '-Wno-unused-parameter', '-Wold-style-cast', '-ffloat-store', '-std=c++14', '-ggdb', '-iquote', '/home/rr-/src/arc_unpacker/src'], [], ['-c', '-o'], ['HAVE_ZLIB_H=1', 'HAVE_OPENSSL_RSA_H=1', 'HAVE_BOOST_FILESYSTEM_HPP=1', 'HAVE_BOOST_LOCALE_HPP=1', 'AU_VERSION="0.8-218-g51d4c41-dirty"'], '-D%s', [], [], ['/home/rr-/src/arc_unpacker/build/src', '/home/rr-/src/arc_unpacker/src']]
        19:05:54 envhash 7135b5a1bc5268502f3ba7e66471846e [[], [], [], ['-o'], [], [], [], [], [], ['png', 'jpeg', 'z', 'boost_filesystem', 'boost_system', 'boost_locale', 'crypto'], [], '-L%s', '-l%s', [], [], ['/usr/bin/g++'], [], '-Wl,-rpath,%s', '-Wl,-Bdynamic', [], [], '-L%s', '-Wl,-Bstatic', '-l%s']
        [275/479] Linking build/arc_unpacker
        19:05:54 runner ['/usr/bin/g++', ...many object files..., '-o', '/home/rr-/src/arc_unpacker/build/arc_unpacker', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-lpng', '-ljpeg', '-lz', '-lboost_filesystem', '-lboost_system', '-lboost_locale', '-lcrypto']
        19:05:54 envhash bba70267657a89097824ee6a1e5bd0c3 [[], [], [], '-I%s', ['/usr/bin/g++'], [], ['-Wall', '-Wextra', '-pedantic', '-Wwrite-strings', '-Wno-unused-variable', '-Wno-unused-parameter', '-Wold-style-cast', '-ffloat-store', '-std=c++14', '-ggdb', '-iquote', '/home/rr-/src/arc_unpacker/src', '-iquote', '/home/rr-/src/arc_unpacker/tests'], [], ['-c', '-o'], ['HAVE_ZLIB_H=1', 'HAVE_OPENSSL_RSA_H=1', 'HAVE_BOOST_FILESYSTEM_HPP=1', 'HAVE_BOOST_LOCALE_HPP=1'], '-D%s', [], [], ['/home/rr-/src/arc_unpacker/build/src', '/home/rr-/src/arc_unpacker/src', '/home/rr-/src/arc_unpacker/build/tests', '/home/rr-/src/arc_unpacker/tests']]
        19:05:54 runner_env kw={'shell': False, 'env': None, 'cwd': '/home/rr-/src/arc_unpacker/build'}
        19:05:54 envhash 7135b5a1bc5268502f3ba7e66471846e [[], [], [], ['-o'], [], [], [], [], [], ['png', 'jpeg', 'z', 'boost_filesystem', 'boost_system', 'boost_locale', 'crypto'], [], '-L%s', '-l%s', [], [], ['/usr/bin/g++'], [], '-Wl,-rpath,%s', '-Wl,-Bdynamic', [], [], '-L%s', '-Wl,-Bstatic', '-l%s']
        [479/479] Linking build/run_tests
        19:05:54 runner ['/usr/bin/g++', ...many object files..., '-o', '/home/rr-/src/arc_unpacker/build/run_tests', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-lpng', '-ljpeg', '-lz', '-lboost_filesystem', '-lboost_system', '-lboost_locale', '-lcrypto']
        19:05:54 runner_env kw={'shell': False, 'env': None, 'cwd': '/home/rr-/src/arc_unpacker/build'}
        Waf: Leaving directory `/home/rr-/src/arc_unpacker/build'

Points of interest:

1. There are no `.cc` files recompiled, only the executables get relinked.
2. The environment hashes do not change.
3. The wscript doesn't rely on random data other than version that is taken from `git describe` during script startup (which of course does not change between rebuilds).
4. Tested on waf 1.8.17.

The wscript itself is available at [this link](https://github.com/vn-tools/arc_unpacker/blob/master/wscript).

If this is a problem with my wscript, how can I debug and fix the issue? Thanks!

**Comment by rr-** [comment]
Alright, I figured it out.

The source paths passed `bld.program` and `bld.objects` were ordered in random order. Sorting them by file name has solved the issue.

**Comment by ita1024** [comment]
`bld.path.ant_glob` results are sorted by default.
