### ISSUE TITLE
Provide a way to know the variant build node at configuration time

### ISSUE THREAD

**Issue by guludo** [waf-project/waf#1668]
Sometimes it's necessary to know where will be the build node for the current env during configuration time. I'm talking about a scenario when we have variant builds and different envs for each (through the function `setenv()`).

One example is my case: I'm building an external tool with an external build system, and I need to tell the external build system configuration where it should build its stuff. :-)

**Comment by ita1024** [comment]
The folder can be obtained easily by looking up the output directory and the name of the variant folder. No change is deemed necessary.
