### ISSUE TITLE
File "waf" from waf.io unpacks wrong version of waflib

### ISSUE THREAD

**Issue by starius** [waf-project/waf#1677]
```
curl https://waf.io/waf-1.8.17 > waf
chmod +x waf
./waf --help
curl https://waf.io/waf-1.8.17.tar.bz2 | tar -xjf-

# file waf is equal to the same file from archive
cmp waf waf-1.8.17/waf

# but it unpacks different version of waflib
cmp waf-1.8.17/waflib/Build.py .waf-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Build.py

waf-1.8.17/waflib/Build.py .waf-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Build.py differ: byte 3, line 1
```

**Comment by ita1024** [comment]
The waf file does unpack a content that is dependent on the python version in order to support Python 2.5. 

If your intention is to ship unpacked `waf` files - I guess that this is what you are trying to do? - then use the files from the archive directly. Compatibility with Python 2.5 and 2.6 will be lost.

**Comment by starius** [comment]
I see. waf file is the most portable way of using waf, isn't it?

Does Python 2.6 support files from archive directly?

The Waf book [says](https://waf.io/book/#_obtaining_the_waf_file):

> Building Waf requires a Python interpreter having a version number in the range 2.6-3.4. The source code is then processed to support Python 2.5.

Is Python 3.5 supported?

**Comment by ita1024** [comment]
Yes, running the Waf file directly is best as the code will run directly over a wide range of python interpreters and versions.

The code unpacked with Python 3 can run on Python 2.6 and 2.7. Yet, if your intention is to ship such files, then you should really use the files from the `tar` archive.

Python 3.5 is indeed supported, we only had 3.4 at the time of writing that paragraph.

**Comment by starius** [comment]
Thank you!
