### ISSUE TITLE
tests: provide a way to always run failed tests

### ISSUE THREAD

**Issue by guludo** [waf-project/waf#1678]
Currently, by default, waf_unit_test tool doesn't run tests that have been run before. I think that is good for tests that have succeed. However, that might not be so good for tests that fail.

Consider the following example. Let's say we have N failing tests and we're working on fixing them. Then we fix almost all of them. By just running the tests with the default behavior, if they have been run before, one or more tests might not be run, and we might think our work is done.

I know that situation can be avoided by using `--alltests` option, but that would make waf run unrelated tests unnecessarily.

Thus, I propose the addition of a way of always run the failed tests in subsequent calls to build. I'd love it to be the default behavior, but I doubt that will be possible. If really not, a command line option could enable that.

**Comment by ita1024** [comment]
Such a thing can be made permanent in your project. Update your copy: cb4fe1b905516d6adfbeb0cfd7334f271ff6a4e1

**Comment by guludo** [comment]
Thank you :-)

**Comment by guludo** [comment]
I'm closing this now.
