### ISSUE TITLE
Ifort linking flags on Windows (ifort_modifier_win32)

### ISSUE THREAD

**Issue by haraldkl** [waf-project/waf#1681]
Yet another question regarding Fortran on Windows.

Ifort defines the win32 modifier to be the one from fc_config, which sets Linking flags with --Wl, however on Windows the ifort compiler does not take these options, instead it should be /Qoption,link. Thus, I think, the modifier should be different. However, I don't even know whether the options provided are available with the ifort linker. Thus, I cancelled them out completely. The diff looks like this:

     diff -r 50c9a495a5b3 waflib/Tools/ifort.py
     --- a/waflib/Tools/ifort.py	Wed Jan 06 14:53:18 2016 +0100
     +++ b/waflib/Tools/ifort.py	Wed Jan 06 15:25:04 2016 +0100
    @@ -20,7 +20,17 @@
 
     @conf
     def ifort_modifier_win32(conf):
    -	fc_config.fortran_modifier_win32(conf)
    +	"""Define ifort flags for the windows platforms"""
    +	v = conf.env
    +	v['fcprogram_PATTERN'] = v['fcprogram_test_PATTERN']  = '%s.exe'
    +
    +	v['fcshlib_PATTERN']   = '%s.dll'
    +	v['implib_PATTERN']    = 'lib%s.dll.a'
    +
    +	v['FCFLAGS_fcshlib']   = []
    +
    +	v.append_value('FCFLAGS_fcshlib', ['-DDLL_EXPORT']) # TODO adding nonstandard defines like this DLL_EXPORT is not a good idea
    +
 
     @conf
     def ifort_modifier_darwin(conf):

**Comment by ita1024** [comment]
What is the question exactly?

**Comment by haraldkl** [comment]
Should I create a pull request out of that, or is there an obvious better option to ensure proper linking options for ifort on windows?

**Comment by ita1024** [comment]
Is there an obvious better option? If the ifort compiler requires particular flags on windows, then there is no way around it, is there?

Now, why have you copy-pasted the part that reads `-DLL_EXPORT`? And where is the '/Q,link' supposed to appear?

**Comment by haraldkl** [comment]
> If the ifort compiler requires particular flags on windows, then there is no way around it, is there?

Of course, but maybe the organisation of when to set it where in waf might be done differently, possibly with less code duplication.

> Now, why have you copy-pasted the part that reads -DLL_EXPORT?

I am not sure about it. Probably it should be /DDLL_EXPORT, but it might as well be removed.

> And where is the '/Q,link' supposed to appear?

    v.append_value('LINKFLAGS', ['-Wl,--enable-auto-import'])

all -Wl options should be changed to /Q,link. However, this enable-auto-import option does not appear to be necessary and I am not sure, whether it is available on Windows, as I am not having an ifort windows installation myself. Thus, I dropped it altogether. I'll put this into a pull request, once I figured out what would be the appropriate flags to use.

**Comment by ita1024** [comment]
I do not understand, why are you making changes if you do not have an ifort installation on windows? Are you actually testing the changes that you are trying to make?

**Comment by haraldkl** [comment]
There is a user of my library, trying to compile it on windows and running into those issues: https://bitbucket.org/haraldkl/aotus/issues/4/waf-cannot-find-ifort-when-building-under

**Comment by ita1024** [comment]
It makes sense now, a few changes in `ifort.py` will be unavoidable.

The compiler seems to be inspired from Visual Studio, so the detection will most likely require running `.bat` files, reading registry keys and processing commands in the same way as `msvc.py`. The best thing would be to ensure that `demos/fortran` builds properly. I think you need to obtain a version of the compiler first.

**Comment by haraldkl** [comment]
OK, thanks. I'll see what I can do...

**Comment by haraldkl** [comment]
I got hands on an installation with msvc and ifort on windows and started looking into the needs for Ifort on windows. I got it working, though only in a preliminary way. Indeed we need to run a compilervars.bat beforehand to set the paths correctly.

However, there are two obstacles I ran into, which are maybe a little more general. The one is that the ifort compiler on windows wants to have the output option /o and the output name separated. In the the run_str for fc they are directly concateneted:

    ${FC_TGT_F}${TGT[0].abspath()}

However, I am not sure why this is done, as on other systems a separation here also works. Adding the separation for the general case would be a minimal changeset to get this working also on windows, I think. The other point relates to #1680 and #1679. Ifort is looking for the archiver and might set the AR variable differently from the C-Compiler. This should not be done, as later on the wrong archiver might be utilized. Thus, I was wondering whether fc_config should rather set AR_fcstlib? I think this is only of an issue with mixed languages, but I don't think it is an uncommon need. What do you think about these two points?

**Comment by ita1024** [comment]
For the flag separation on waf 1.8: the flags are already apart, as the commands are executed without a shell (see 331dd9f96c58b0243aae87a51d8745c4e4cceb72). Do you mean to have `/o` concatenated with what comes after? And is there no `/out` option?

If additional flag merging is necessary, the visual studio flag merging routines should be used for fortran classes too.

For AR variables, msvc adds its own archiver variables (AR, ARFLAGS, ...) without any problem, so I do not believe that something new is actually necessary.

**Comment by haraldkl** [comment]
> Do you mean to have /o concatenated with what comes after?

Yes. The current run_str for the fc stuff has `${FC_TGT_F}${TGT[0].abspath()}` in it with no blank between `FC_TGT_F`and `TGT[0]`, I didn't follow through the code that compiles it into the actual command being called, but ifort on windows complains about `/o` and the name need to be separated. Placing a blank in between in the `run_str` resolves this. Thus, I believe, that the whole expression above without the blank is passed as a single argument to the subprocess.

> And is there no /out option?

Ah, well. No /out, but actually you are right, there is an [/exe: option](https://software.intel.com/de-de/node/525073) and an [/object: option](https://software.intel.com/de-de/node/525092). I am sorry, should have looked that up before. Those would also resolve the issue.

> For AR variables, msvc adds its own archiver variables (AR, ARFLAGS, ...) without any problem, so I do not believe that something new is actually necessary.

As you wrote in the other threads, there should only be one AR and ARFLAGS, there can't be multiple because of the name clashes? Probably I am not getting this correctly, a lot of the stuff that is going on appears like black magic to me. I thought, msvc.py sets the AR and ARFLAGS in the env which holds for all classes, but if a variable is postfixed by a specific feature name, that feature would use that one instead. What I am struggling with is the case where there are two tools each defining AR and ARFLAGS differently. The one that is called later will overwrite the previous one, right?

In a pure Fortran project this is not an issue, as we can invoke the loading of the fc configuration after the c compiler configuration and ensure to get the Fortran linker and archiver. But how about a project, where a C-library is built and then used by a Fortran application? Now I need the archiver for the C compiler to construct the library first, but it might have been overwritten by the Fortran configuration. I now thought that ifort.py could for example store its archiver in `AR_fcstlib` and that would be used by the `fcstlib` feature instead of the global AR variable and thereby resolving the issue as the user can opt to construct his library with either cstlib or fcstlib as needed.

**Comment by ita1024** [comment]
Placing a blank in the run_str line cannot solve anything in waf 1.8 because Fortran commands are already executed as lists without a shell/interpreter, and the current implementation keep distinct elements in lists. Paste the error message somewhere.

In any case, no space will be added anywhere in waf 1.8 as this might break existing code. As I mentioned, the command execution - if necessary - must use the same pattern as msvc command execution and not change anything in current fortran tools.

Concerning your fortran projects, the production of applications mixing several programming languages *requires* setting environments properly as the variable names can overlap. Using visual studio and gcc in the same project is not uncommon, and setting up environments properly is almost trivial as illustrated below:

```python
def options(opt):
        opt.load('compiler_cxx compiler_c')

def configure(conf):
        conf.setenv('default')
        conf.setenv('cplusplus')
        conf.load('compiler_cxx')

        conf.setenv('default')
        conf.setenv('barec')
        conf.load('compiler_c')

def build(bld):
        bld.env = bld.all_envs['cplusplus']
        bld.objects(source='main.c')

        bld.env = bld.all_envs['barec']
        bld.objects(source='main.c')
```

**Comment by haraldkl** [comment]
OK, thanks for bearing with me. I didn't get the hint regarding the environments the first time you mentioned it as I only used that up to now for different variants.

I think, adapting the win32 modifier for ifort would be sufficient to get the compiler working if the user runs the compilervars.bat beforehand. I'll do a pull request for that, once I did some more testing for it. Finding and running the compilervars.bat automagically will require some more work though.

**Comment by ita1024** [comment]
No worries, I understand the complexity and the difficulties of setting up a testing environment. Just ask if there is any doubt/problem.

**Comment by haraldkl** [comment]
Currently my ifort modifier looks like this:

    def ifort_modifier_win32(conf):
    	v=conf.env
    	v['fcprogram_PATTERN']=v['fcprogram_test_PATTERN']='%s.exe'
    	v['FCSTLIB_MARKER']='/link'
    	v['FCSHLIB_MARKER']=''
    	v['FCLIB_ST']='%s.lib'
    	v['FCLIBPATH_ST']='/LIBPATH:%s'
    	v['FCSTLIB_ST']='%s.lib'
    	v['FCSTLIBPATH_ST']='/LIBPATH:%s'
    	v['FCINCPATH_ST']='/I%s'
    	v['FCDEFINES_ST']='/D%s'
    	v['fcshlib_PATTERN']='%s.dll'
    	v['implib_PATTERN']='lib%s.dll'
    	v['FCLNK_TGT_F']=['/o']
    	v['FC_TGT_F']=['/c','/o']
    	v['FCFLAGS_fcshlib']=[]
    	v['AR_TGT_F']='/out:'
    	msvc.wrap_class('fcstlib')

The /object: and /exe: options require the merging, which I am currently struggling with. The linker of Fortran provides some processing of IPO files and then hands the objects off to the MS Linker, and it basically behaves like the MS Linker:

> The linking tool invokes the Intel compiler to perform multi-file IPO if objects containing IR (intermediate representation) is found. These are mock objects. It invokes Microsoft* link.exe to link the application.
The command-line syntax for the Intel® linker is the same as that of the Microsoft linker
> xilink.exe accepts all the options of link.exe and will pass them on to link.exe at the final linking stage

That's why I make use of the msvc.wrap_class here. However, it doesn't seem to work, and I am not sure why. When following the call path it looks like the modified exec_command is used, but somehow the /out: option with the ':' does not get merged with the following option and I end up with /out: being a separate argument.

Also seperated environments complicate the situation here, as the exec_msvc checks on the CC_NAME, so I need this information in the Fortran environment as well. For this I do the following in my wscript:

    conf.setenv('default')
    conf.load('waf_unit_test')
    conf.add_os_flags('DEFINES', dup=False)

    conf.setenv('cenv',conf.env)
    conf.load('compiler_c')

    conf.setenv('default')
    conf.env.CC_NAME = conf.all_envs['cenv'].CC_NAME
    conf.env.DEST_OS = conf.all_envs['cenv'].DEST_OS

    conf.setenv('fortenv',conf.env)
    conf.load('compiler_fc')

I also tried to use the C static lib feature for all libraries, but this somehow garbles up the Fortran dependencies and module files are not available anymore when required.
The build command looks like this then:

    # C parts
    bld.env = bld.all_envs[cenv]

    bld(
        features = 'c',
        source = core_sources + lib_sources,
        use = ['LUA_POSIX'],
        target = 'luaobjs')

    bld(
        features = 'c cstlib',
        use = 'luaobjs',
        target = 'lualib')

    bld(
        features = 'c',
        source = wrap_sources,
        use = 'luaobjs',
        includes = 'external/lua-5.3.2/src',
        target = 'wrapobjs')
    bld(
        features = 'cstlib',
        use = ['luaobjs', 'fluobjs', 'wrapobjs'],
        target = 'flu')
		
    bld(
        features = 'cstlib',
        use = ['aotobjs', 'luaobjs', 'fluobjs', 'wrapobjs'],
        target = 'aotus')

    # Fortran parts
    bld.env = bld.all_envs[fortenv]

    bld(
        features = 'fc',
        source = flu_sources,
        target = 'fluobjs')

    bld(
        features = 'fc',
        source = aotus_sources,
        target = 'aotobj')

    bld(
        features = 'fc fcprogram',
        source = ['sample/aotus_sample.f90'],
        use = 'aotus',
        target = 'aotus_sample')

In demos/fortran I am facing similar issues. It does not make use of separate environments for C and Fortran. Should I first change that?

**Comment by ita1024** [comment]
Setting CC_NAME in the wscript file defeats the point of having a Waf tool at all, does it not?

Please post the testcase with your new ifort tool somewhere.

**Comment by haraldkl** [comment]
conf.load('compiler_c') sets CC_NAME, I merely copy it from the one environment to another.

I created a [new branch](https://github.com/haraldkl/waf/tree/ifort_on_win) and will try to get it working for demos/fortran. That project looks for verbose flags and already fails at that point. These are then used for a LINKFLAGS_CLIB configuration, I never had a need for that and am not sure whether I get this machinery working on windows.

**Comment by ita1024** [comment]
`msvc.wrap_class('fcstlib')` must be performed during the build, not just in the configuration phase.

**Comment by ita1024** [comment]
[Update your copy](https://github.com/waf-project/waf/blob/master/waflib/Tools/ifort.py#L108).

The latest version can compile a simple Fortran executable and produce the manifest files. It will fail on the link verbose flag detection at this time

**Comment by haraldkl** [comment]
Oh man. That's wonderful. Thanks a million, I went skiing over the weekend and you did all the work? Now I feel a little guilty...
I'll look into it later today.

**Comment by haraldkl** [comment]
The building of shlib1-2.dll in demos/fortran fails for me, with missing external symbol MAIN__ referenced in libcoremt.lib(for_main.obj). It might be due my commenting out of the verbose_linking stuff including the fortran_clib. Configuration works fine in the demos project. In my own configuration with separated environments for C and Fortran I get some message about a missing Resource compiler, though that does not look harmful, the FC_NAME seems to be an empty list afterwards.

**Comment by haraldkl** [comment]
If I set FC_NAME in find_ifort_win32, my project (https://bitbucket.org/apesteam/aotus/branch/sepenv), which does not use shared libraries, but a separated environment for C and Fortran works fine with the new ifort identification system.

**Comment by ita1024** [comment]
It would be good to have the verbose link building too.

**Comment by haraldkl** [comment]
The only option I found, that could provide something similar would be /watch:cmd. However, it does not provide any additional library information for a simple Fortran file. The link command that is being executed it says:

    link  \
        -out:test.exe \
        -subsystem:console \
        test.obj

Do satisfy the verbose link search, I'd add the /watch:cmd to the list of options to test and change the regex to also match 'link'. I am not so sure about the parsing, though.

**Comment by ita1024** [comment]
Would the fortran demo build with the Intel compiler if the test passed?

**Comment by haraldkl** [comment]
I'll give it a try, but I don't think it resolves the shared library issue, that rather seems to be another thing.

**Comment by haraldkl** [comment]
I am already confused again. check_fortran uses fc and fcprogram. fcprogram seems to uses xilink for the linking step, after the wrapping of the class by the msvc stuff. This succeeds.

The check_fortran_verbose_flag uses fc and fcprogram_test, which invokes ifort for the linking step and this fails for me now, because it does not find the link command at this point. fcprogram should also be wrapped. However, if I do that it would use xilink and the /watch:cmd is not an option for that. We would not get revealed which libraries the Fortran compiler is attempting to automatically link against. Changing the linker to ifort in ifort.py fails for me, with a complaint about ifconsol.lib not being found when trying to build the simple fortran app.

**Comment by ita1024** [comment]
Wrap fcprogram_test too?

**Comment by haraldkl** [comment]
If I include fcprogram_test in the list of classes to wrap with the msvc execution in ifort.py:

    for k in 'fc fcprogram fcprogram_test fcshlib fcstlib'.split():
	wrap_class(k)

and

    @feature('fcprogram', 'fcprogram_test', 'fcshlib')
    @after_method('apply_link')
    def apply_manifest_ifort(self):
    	if self.env.IFORT_WIN32 and getattr(self, 'link_task', None):
    		# it seems ifort.exe cannot be called for linking
    		self.link_task.env.FC = self.env.LINK_FC

    	if self.env.IFORT_WIN32 and self.env.IFORT_MANIFEST and getattr(self, 'link_task', None):
    		out_node = self.link_task.outputs[0]
    		man_node = out_node.parent.find_or_declare(out_node.name + '.manifest')
    		self.link_task.outputs.append(man_node)
    		self.link_task.do_manifest = True

Then the build tries to create a manifest and fails at that like this:

    ['C:\\Program Files (x86)\\Windows Kits\\8.1\\bin\\x64\\MT.exe', '/NOLOGO', '-manifest', 'C:\\Users\\me\\Documents\\waf_hg\\demos\\fortran\\build\\conf_check_4ceed40a717d0f8347e9de4aa43835bd\\testbuild\\testprog.exe.manifest', '-outputresource:C:\\Users\\me\\Documents\\waf_hg\\demos\\fortran\\build\\conf_check_4ceed40a717d0f8347e9de4aa43835bd\\testbuild\\testprog.exe;']
    out: MT.exe : command line error c1010011: -inputresource or -outputresource or -updateresource specified with nothing after the semicolon.

It does not try to construct the manifest while building the simple fortran app right before this. This difference has to be due to different return values from the exec_commands as far as I can see.

**Comment by ita1024** [comment]
A few more lines are necessary: 823ed6d199536fcb9c593625c89346cabfc3ed67
Is there anything like a verbose flag? As I understand it, that test is required for obtaining the libraries/paths to link fortran apps with c/c++ objects.

**Comment by haraldkl** [comment]
[According to Intel](https://software.intel.com/de-de/node/525234) the closest alternative to the verbose flag on windows seems to be the /watch:cmd option. But as I said, it doesn't look like it provides the necessary library information and does not work for xilink at all.

The only point where the library information is needed is when you need to invoke the C-Linker for a project with Fortran code. I believe this is mainly needed for Projects with C++ parts, for pure C it is usually possible to use the Fortran linking step. I don't know if there is any difference on Windows as xilink is used for the linking and not ifort.

**Comment by ita1024** [comment]
The verbose flag detection seems to be is required for `demos/fortran/typemap`. Is there any way to make that build with ifort?

**Comment by haraldkl** [comment]
Actually giving /verbose to xilink results in tons of output on the command line, which seems to contain all library dependency information we could ask for, though I am not sure if this is really helpful or required at all. If I comment out the check_fortran_verbose_flag and the check_fortran_clib in both wscripts, the build runs through up to the last linking of the shared library, which fails because of a missing foo.lib. But this seems to be rather due to some /IMPLIB flag that got into there rather to anything related to the fortran_clib stuff.

I do not see any need for the fortran_clib config stuff in the typemap wscript. It would be relevant when using a cprogram or clib feature depending on Fortran object files, but this does not seem to be the case in the demos project. If I comment the two fortran_clib related configurators, the example still builds without issues on my MacBook with gfortran and clang. If it weren't for the IMPLIB option, I believe, the same would be true on Windows with ifort and msvc.

**Comment by ita1024** [comment]
For missing .lib files update your copy first.

**Comment by haraldkl** [comment]
I am on c421fe5 the missing lib is in the typemap subdirectory, not the one above:

    [22/22] Linking build\typemap\foo.dll
    runner ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.1.146\\windows\\bin\\intel64\\XILINK.exe', '/NOLOGO', '/MANIFEST', '/subsystem:console', '/MANIFEST', '/IMPLIB:typemap\\foo.lib', '/DLL', 'typemap\\fsrc.f90.1.o', 'typemap\\basetypes.f90.1.o', 'typemap\\fwrap_ktp.f90.1.o', '/out:C:\\Users\\me\\Documents\\waf\\demos\\fortran\\build\\typemap\\foo.dll', '/LIBPATH:C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.1.146\\windows\\compiler\\lib', '/LIBPATH:C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.1.146\\windows\\compiler\\lib\\intel64', '/LIBPATH:C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.1.146\\windows\\compiler\\lib\\intel64_win', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\LIB\\amd64', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\ATLMFC\\LIB\\amd64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.10240.0\\ucrt\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\lib\\um\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\8.1\\lib\\winv6.3\\um\\x64', '/LIBPATH:C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.1.146\\windows\\mpi\\intel64\\bin\\..\\..\\intel64\\lib', '/LIBPATH:C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.1.146\\windows\\ipp\\lib\\intel64', '/LIBPATH:C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.1.146\\windows\\mkl\\lib\\intel64', '/LIBPATH:C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.1.146\\windows\\compiler\\lib\\intel64', '/LIBPATH:C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.1.146\\windows\\tbb\\bin\\..\\lib\\intel64\\vc_mt', '/LIBPATH:C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.1.146\\windows\\daal\\lib\\intel64_win', '/LIBPATH:C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.1.146\\windows\\compiler\\lib\\intel64_win', '/LIBPATH:C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.1.146\\windows\\tbb\\lib\\intel64_win\\vc_mt', '/LIBPATH:C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\LIB\\amd64', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\ATLMFC\\LIB\\amd64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\8.1\\References\\CommonConfiguration\\Neutral', '/LIBPATH:\\Microsoft.VCLibs\\14.0\\References\\CommonConfiguration\\neutral']

    runner ['C:\\Program Files (x86)\\Windows Kits\\8.1\\bin\\x64\\MT.exe', '/NOLOGO', '-manifest', 'C:\\Users\\me\\Documents\\waf\\demos\\fortran\\build\\typemap\\foo.dll.manifest', '-outputresource:C:\\Users\\petervitt\\Documents\\waf\\demos\\fortran\\build\\typemap\\foo.dll;2']

    Build failed
    -> missing file: 'C:\\Users\\me\\Documents\\waf\\demos\\fortran\\build\\typemap\\foo.lib

**Comment by ita1024** [comment]
That's most likely because a `.def` file is missing. Try adding the `foo.def` file from the upper directory?

**Comment by haraldkl** [comment]
No, that does not change the error. However, the foo.dll is actually built and the error just comes from check_compile which looks for the .lib, while only the .dll is created.

**Comment by ita1024** [comment]
Are you sure it is the right symbol in the .def file?

**Comment by haraldkl** [comment]
No, I am not sure. I actually just copied it from the parent.

**Comment by haraldkl** [comment]
I need to get some sleep first, but I am pretty convinced the linking works fine and it is only some checking in waf afterward.

**Comment by haraldkl** [comment]
OK, so the task looks like this:

    fcshlib fsrc.f90.1.o,basetypes.f90.1.o,fwrap_ktp.f90.1.o -> foo.dll,foo.lib,foo.dll.manifest

But I could not figure out yet, where this foo.lib in the list of outputs is coming from.

**Comment by haraldkl** [comment]
Changing the implib_PATTERN in ifort.py to use the .dll extension instead of the lib fixes this, but somehow results in the linking of the shared library for foo.ex (shlib1) not looking for the version number anymore (shlib1-2.dll not found).

**Comment by haraldkl** [comment]
OK, I figured it (I think). The def needs to be

    EXPORTS
    	EXAMPLE_MOD_mp_SUB1

Which is of course compiler specific, as the module name mangling is coming from the compiler. Probably this def should be created, but that would involve parsing the Fortran code and extracting rather involved information from it.

With such a def in place, the build succeeds if the fortran_verbose_link_flag and fortran_clib stuff is commented out.

**Comment by haraldkl** [comment]
Put the def stuff for the typemap subdirectory in the pull request #1688.

**Comment by ita1024** [comment]
So the example should be modified as 3f2e58b1a349167b3759f80d34f73e45f067dcb1. It seems that mangling, verbose flag and clib detection are inapplicable here, or am I misinterpreting?

**Comment by haraldkl** [comment]
Well, the example does not require those configurations, no matter which system, as it does not use the C-Linker for Fortran objects. Finding the required libraries for Fortran objects does not seem to be necessary, as anyway xilink is used for linking on windows and not ifort.

The identification of name mangling is a feature that is required by mixed Fortran/C Projects, which do not make use of the ISO_C_Binding from Fortran 2003. The example in demos/Fortran, however, does use the ISO_C_Binding. In any case it does not hurt to execute this configuration in the wscript, but it does not help anything either. It could be useful for the def files, but to create those automatically we would need to identify all the symbols that should be exported.

Thus, yes, I think, it would be appropriate to just deactivate those configurators on Windows, but as far as I can see it, they are also not used on other platforms. It might be less confusing to not use them altogether in this example, and rather add other subdirectories, which actually show where those features might be useful.

**Comment by ita1024** [comment]
Good! The examples in master will remain with the if blocks, and some cleanup was been added to the branch waf-1.9 a255ba93c6cb5e4cfd1db7fba84bf85f7ef70c62.

There is a lot of copy-pasted code so whole ifort tool should be rewritten in waf 1.9, but I think we can close this for waf 1.8.
