### ISSUE TITLE
How to avoid shlink marker when there are no dynamic libraries to link against?

### ISSUE THREAD

**Issue by haraldkl** [waf-project/waf#1685]
An issue I am seeing with some compilers on some systems is that the shlink marker causes trouble when there is no dynamic library following it. For example on the Cray systems dynamic linking is avoided for the compute node linux and a static libc is used, resulting in the following error with the intel compiler:

    ['ftn', 'test.f.1.o', '-o/zhome/academic/HLRS/grsa/igrklima/aotus/build/.conf_check_a9fc719e3f87866876151aff0893f834/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic']
    err: ld: dynamic STT_GNU_IFUNC symbol `strcmp' with pointer equality in `/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../lib64/libc.a(strcmp.o)' can not be used when making an executable; recompile with -fPIE and relink with -pie

Now, I anyway do not have any dynamic libraries to link to, and simply deactivate the shlib marker in my wscript like this:

    # Deactivate dynamic linking flags for Cray
    if conf.env.FC[0] == 'ftn':
      conf.env['FCSHLIB_MARKER'] = ''

However, I wonder whether there is a more general solution, and we could leave out the SHLIB_MARKER when there are no specific shlibs to link against? This should also be done for the STLIB_MARKER, I think. If there are no specific stlibs to link against, we do not need the STLIB_MARKER.

**Comment by ita1024** [comment]
Yes:

```python
from waflib import TaskGen
@TaskGen.feature('fcprogram', 'fcshlib')
@TaskGen.before_method('process_use')
@TaskGen.after_method('apply_link')
def kill_marker_flags(self):
        if self.env.FC_NAME = 'yourfancyfortrancompilername':
                if not self.env.LIB and not self.env.LIBPATH:
                        self.env.SHLIB_MARKER = []
                if not self.env.STLIB and not self.env.STLIBPATH:
                        self.env.STLIB_MARKER = []
```

**Comment by haraldkl** [comment]
Thanks a lot.
