### ISSUE TITLE
Solaris Studio compiler version check

### ISSUE THREAD

**Issue by asylvest** [waf-project/waf#1686]
Older versions of the Solaris Studio compiler, such as 12.3, reported their version in this format:

```
$ /opt/solarisstudio12.3/bin/cc -V
cc: Sun C 5.12 SunOS_sparc 2011/11/16

$ /opt/solarisstudio12.3/bin/CC -V
CC: Sun C++ 5.12 SunOS_sparc 2011/11/16
```

This is the format c_config.py expects (line 1150).  However, newer versions such as 12.5 beta report their version in a bit of a different format:

```
$ /opt/solarisstudio12.5/bin/cc -V
cc: Studio 12.5 Sun C 5.14 SunOS_sparc Beta 2015/11/17

$ /opt/solarisstudio12.5/bin/CC -V
CC: Studio 12.5 Sun C++ 5.14 SunOS_sparc Beta 2015/11/17
```

The regex just needs to be updated to skip an optional "Studio" up front.

**Comment by asylvest** [comment]
Depends how precise you want to be, but this would handle either case (just skip everything between `cc` and `sun` rather than expecting just spaces):

```
version_re=re.compile(r'cc:.*sun\s+(c\+\+|c)\s+(?P<major>\d*)\.(?P<minor>\d*)',re.I).search
```

**Comment by ita1024** [comment]
Does the output change according to the locale?

**Comment by ita1024** [comment]
Try 101dc83283c478e0cd6235c26c0c1b052bd9a0e0

**Comment by asylvest** [comment]
Not sure offhand if the output changes based on locale, but I've confirmed 101dc83 works for both 12.3 and 12.5 beta.  Thanks for the quick update!

**Comment by ita1024** [comment]
The man page does not seem to list environment variables that influence the outputs. I have no way to test recent versions, so get back to me if you see notice a problem.
