### ISSUE TITLE
Add compiler independent system header (-isystem) support

### ISSUE THREAD

**Issue by ivankoster** [waf-project/waf#1693]
The GCC and Clang compilers have an alternative for the -I compiler option to add include paths.
The -isystem option adds the include path, but also marks the path as a system header.
As an added benefit is that warnings in these header files are suppressed.
This is very welcome if you compile with a lot of warning diagnostics enabled and when warnings are errors.

Currently I use this by adding the ["-isystem", "..path.."] to the CFLAGS environment variable.
This is not compiler independent, since for example the microsoft compiler does not support -isystem.

What would be the best way to add this to waf?
Add a something like SYSINCLUDES to the environment, like INCLUDES, so that it can be added to the run_str for c and c++ tasks?

**Comment by ita1024** [comment]
No support will be added for the following reasons:
* the `-isystem` usage is very compiler specific
* flags can be added to the beginning or to the end of commands through CFLAGS/CPPFLAGS
* in each CFLAGS/CPPFLAGS the flags can be further reordered at the start or at the end
* if something were needed you would have already added a task generator method in your script files
