### ISSUE TITLE
update_outputs doesn't work on library targets when using "install"

### ISSUE THREAD

**Issue by GeekOffTheStreet** [waf-project/waf#1694]
I've noticed that when a shared library is created in the source directory, update_outputs doesn't prevent rebuilds if "waf install" is used.  Here is minimal example that modifies the wscript under playground/c-objects-stlib-shlib (waf 1.8.9):

```
def options(opt):
	opt.load('gcc gnu_dirs')

def configure(conf):
	conf.load('gcc gnu_dirs')

def build(bld):
	
	bld(
	 features='c',
	 source='test_shlib.c',
	 use='cshlib',
	 target='objects-for-shlib',
	)

	bld(
	 features='c cshlib',
	 target=bld.srcnode.make_node('libsomething-shared.so'),
	 use='objects-for-shlib',
     update_outputs=True
	)
```

Here's an example where I run a build a couple times in a row after a successful build and then run install.  The following build (or install) will cause a re-linking of the library:

```
/ssd/c-objects-stlib-shlib > ./waf build -v
Waf: Entering directory `/ssd/c-objects-stlib-shlib/build'
Waf: Leaving directory `/ssd/c-objects-stlib-shlib/build'
'build' finished successfully (0.008s)
/ssd/c-objects-stlib-shlib > ./waf build -v
Waf: Entering directory `/ssd/c-objects-stlib-shlib/build'
Waf: Leaving directory `/ssd/c-objects-stlib-shlib/build'
'build' finished successfully (0.008s)
/ssd/c-objects-stlib-shlib > ./waf install
Waf: Entering directory `/ssd/c-objects-stlib-shlib/build'
+ install /ssd/dist/lib64/libsomething-shared.so (from libsomething-shared.so)
Waf: Leaving directory `/ssd/c-objects-stlib-shlib/build'
'install' finished successfully (0.021s)
/ssd/c-objects-stlib-shlib > ./waf build -v
Waf: Entering directory `/ssd/c-objects-stlib-shlib/build'
[2/2] Linking libsomething-shared.so
17:05:12 runner ['/usr/bin/gcc', '-shared', '-shared', 'test_shlib.c.1.o', '-o', '/ssd/c-objects-stlib-shlib/libsomething-shared.so', '-Wl,-Bstatic', '-Wl,-Bdynamic']
Waf: Leaving directory `/ssd/c-objects-stlib-shlib/build'
'build' finished successfully (0.042s)
```

**Comment by ita1024** [comment]
The keyword `update_outputs` only affects `rule=` task generators. Since update_outputs will be the default in waf 1.9, you should switch to that branch right now, use the following revision 5b82ce528ce1a2c492aa8474500965e26d49339c in case following the latest is excluded.

The lack of "update_outputs" causes the .so file to inherit the task signature from the link task, and its own hash from the installation task (files in the source directory are hashed). The mismatch is what is causing the rebuilds.
