### ISSUE TITLE
Command line define dependencies not created when using compiler's implicit default value

### ISSUE THREAD

**Issue by mjessome** [waf-project/waf#1704]
Issue seems to be caused by:
https://github.com/waf-project/waf/blob/master/waflib/Tools/c_preproc.py#L940

GCC and clang (and probably most compilers) give command-line defines of the form `-DNO_EXPLICIT_VALUE` give `NO_EXPLICIT_VALUE` a default value of `1`, however waf doesn't use this implicit default value.

Take the following example:

```
// test.c
#if INCLUDE_OPTIONAL
#include "optional_header.h"
#endif
```

When built with `INCLUDE_OPTIONAL` added to `env['DEFINES']`, test.c is not rebuilt when `optional_header.h` is modified.

When built with `INCLUDE_OPTIONAL=1` added to `env['DEFINES']`, test.c _is_ rebuilt when `optional_header.h` is modified.

**Comment by ita1024** [comment]
Update your copy to 7e26f1fdf4ab5fab7254767f5889f4cbd5f550cd

**Comment by ita1024** [comment]
The only arguments currently supported on the command-lines are ones in the form `-DNAME=VALUE`, so this is a feature request.

Use the following on the branch waf-1.9 2d899372058b27f8dd62344b34e1d1d288220b85

**Comment by ita1024** [comment]
Use waf 1.9.0.
