### ISSUE TITLE
Question: Task, dep_nodes vs node_deps

### ISSUE THREAD

**Issue by ColdenCullen** [waf-project/waf#1707]
I'm trying to add nodes as dependencies of a task, but I noticed that the `Task` class has 2 seemingly useful attributes: `dep_nodes`, and `node_deps`. Which one should I use? What are both for? Can we add better documentation to avoid this confusion in the future?

Thanks for your help!

**Comment by ita1024** [comment]
The attribute `node_deps` does not belong to Task and its usage is provided by the API documentation. If you do not know what it can be useful for you should not use it.

To add task dependencies, add nodes to the list `inputs` and if you need something more complex use a dependency scanner as described in the documentation. Using `dep_nodes` is not recommended.

**Comment by ColdenCullen** [comment]
Ah, you are correct, I totally missed the `bld.` in front of `node_deps`. I'll give the scanner method a shot.

**Comment by ColdenCullen** [comment]
That worked, thanks!
