### ISSUE TITLE
Context.top_dir should be os.getcwd() by default

### ISSUE THREAD

**Issue by johannesmeng** [waf-project/waf#1712]
In 1.8.19, Context.py top_dir is set to empty, which leads waf_entry_point to search above the current directory by default.

If permissions do not allow listing directories above cwd, there will be an exception thrown,
which is not a helpful error message.

Yes, waf --top=... fixes  that, but the default should be so that waf never touches anything
above cwd.

**Comment by ita1024** [comment]
No need for `waf --top`, just run `waf configure` once in the required directory and the other commands will then use the base directory.

Calling Waf from a subfolder will perform a partial build of the targets below that folder. The behaviour that you are suggesting would break that.

**Comment by johannesmeng** [comment]
I see, but would it be reasonable to add a try/except around the os.listdir, then?

**Comment by ita1024** [comment]
Maybe. What is the usecase for that?

**Comment by johannesmeng** [comment]
Basically if you have a directory "parent", and nested inside "child", but do not have permissions
to run os.listdir() in "parent". This could be /home and /home/userdir, and for some reason your
admin decided that you cannot list /home.

Now you run waf in "child", forgetting to add the configure. This will throw an exception
about permissions and terminate waf. By the way, this exact thing triggered this bug report. 
I didn't really think about trying waf configure simply because waf terminated so violently.

On a somewhat related note, one might also think about printing the directories that waf searches
to make the process a bit more obvious to the user.

**Comment by ita1024** [comment]
Like 028ecf43df0209a050e1a601b235255eb4c7c1a6 ?

**Comment by johannesmeng** [comment]
Yes :)

**Comment by ita1024** [comment]
That will be in the next release; update your copy from Git in the meantime.

**Comment by johannesmeng** [comment]
Thanks a lot!
