### ISSUE TITLE
clang, CXXFLAGS & pkgconfig

### ISSUE THREAD

**Issue by x42** [waf-project/waf#1714]
`pkgconfig --cflags` for some C++ libs (e.g glibmm) includes `-std=c++11`.

For mixed C,C++ projects waf does not currently provide for separate CFLAGS/CXXFLAGS  with `uselib`. When compiling a C file this results in
`clang error: invalid argument '-std=c++11' not allowed with 'C/ObjC'`

I don't know what the best solution in this case would be, a separate `uselib` per language would be an option;  ie. means to explicitly only set CFLAGS or CXXFLAGS for a given library.

Meanwhile I've worked around this:
```diff
diff --git a/waflib/Tools/c_config.py b/waflib/Tools/c_config.py
index 6809441..5dd219b 100644
--- a/waflib/Tools/c_config.py
+++ b/waflib/Tools/c_config.py
@@ -168,6 +168,8 @@ def parse_flags(self, line, uselib_store, env=None, force_static=False, posix=No
    elif x.startswith('/LIBPATH:'):
      prefix = (force_static or static) and 'STLIBPATH_' or 'LIBPATH_'
      appu(prefix + uselib, [x.replace('/LIBPATH:', '')])
+   elif x.startswith('-std=c++'):
+     app('CXXFLAGS_' + uselib, [x])
    elif x == '-pthread' or x.startswith('+') or x.startswith('-std'):
      app('CFLAGS_' + uselib, [x])
      app('CXXFLAGS_' + uselib, [x])
```

**Comment by ita1024** [comment]
Distinct environments should be setup for C and for C++ before calling pkg-config.

The change suggested above will not catch the case of passing -std=c89 to c++ compilers. Try 24d70a0bc0664c1460c4f83b67e0655d6aa18958

**Comment by x42** [comment]
thanks,  waf-1.8.19-32-g24d70a0 works just fine here.
