### ISSUE TITLE
qt5: QT_INSTALL_BINS should be QT_HOST_BINS

### ISSUE THREAD

**Issue by mrzechonek** [waf-project/waf#1726]
https://github.com/waf-project/waf/blob/master/waflib/Tools/qt5.py#L546

I think that we should run `qmake -query QT_HOST_BINS` instead of `QT_INSTALL_BINS` to support cross-compilation environments.

Take a look at buildroot's qt. "sysroot" contains binaries for the target (compiled for a different architecture, therefore unrunnable or maybe even missing if target doesn't need them):

```
$ $BUILDROOT/output/host/usr/bin/qmake -query QT_INSTALL_BINS
.../output/host/usr/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/bin

$ $BUILDROOT/buildroot/output/host/usr/bin/qmake -query QT_HOST_BINS   
.../output/host/usr/bin
```

Regular Qt5 have these pointing to the same directory:

```
$ qmake -query QT_HOST_BINS 
/usr/lib64/qt5/bin

$ qmake -query QT_INSTALL_BINS
/usr/lib64/qt5/bin
```

**Comment by ita1024** [comment]
This seems to be new in qt5 - 6b2e837bc20f9be6a434fc40ec5b9f6d24823219 in the branch waf-1.9

**Comment by mrzechonek** [comment]
Cool, thank you!
