### ISSUE TITLE
Support for clang with Visual Studio 2015

### ISSUE THREAD

**Issue by shoover** [waf-project/waf#1727]
Visual Studio 2015 Update 1 includes Clang 3.7. Compilation works with waf configure --check-c-compiler=clang. Linking is complicated by the fact that Microsoft's clang.exe shells out to link.exe but does not translate some critical link flags from the gcc syntax. It seems waf would require modifications or a new tool that understands the hybrid options required for compiling with clang and passing through the right linkflags.

I will show what I had to do, but it may not be worth messing with until things stabilize on the Microsoft side. Perhaps they will finish translating the linkflags in a future release.

First the environment must be manually configured:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat
set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Clang 3.7\bin\x86
```

env overrides are required to hybridize the clang tool for msvc's linker. This allows building most C targets in demos/.

```
def configure(conf):
    conf.load('compiler_c')

    # Disable -Bdynamic and -Bstatic markers as for link.exe
    conf.env['SHLIB_MARKER']        = ''
    conf.env['STLIB_MARKER']        = ''

    # link.exe-style lib patterns
    conf.env['implib_PATTERN']      = '%s.lib'
    conf.env['cstlib_PATTERN']      = '%s.lib'

    # Pass through link.exe-style linkflags
    conf.env['IMPLIB_ST']         = '-Wl,/IMPLIB:%s'
    conf.env['LIB_ST']            = '-Wl,%s.lib'
    conf.env['LIBPATH_ST']        = '-Wl,/LIBPATH:%s'
    conf.env['STLIB_ST']          = '-Wl,%s.lib'
    conf.env['STLIBPATH_ST']      = '-Wl,/LIBPATH:%s'
```

With all of the above, waf configure --check-c-compiler=clang works.

While building, I got stuck on a static link error: 

```
..\shlib\foo.def : fatal error LNK1107: invalid or corrupt file: cannot read at 0xD

[13/14] Linking build\stlib\test_static_link.exe
clang.exe: error: linker command failed with exit code 1107 (use -v to see invocation)
```

I believe changes are needed in ccroot.py apply_implib regarding defs and the pe format. Again, maybe a Microsoft update will translate the flag appropriately.

**Comment by ita1024** [comment]
I am not sure anything else will happen here so this will be closed now.
