### ISSUE TITLE
msvc link warning

### ISSUE THREAD

**Issue by shoover** [waf-project/waf#1731]
I get this warning with a moderate sized project building several targets to the same directory. I am using /FS to force compiler PDB writes through the mspdb server to work around problems with multiprocessor compilation.

```
test.c.2.o : warning LNK4099: PDB 'vc140.pdb' was not found with 'test.c.2.o' or at 'C:\Users\Shawn\dev\test\build-win32\debug\vc140.pdb'; linking object as if no debug info
```

I believe waf is doing its normal job of perfectly orchestrating parallel builds, which leads to a situation where some files are still compiling (test programs) while a different target is being linked (shared library). The linker tries to open the object pdb file, which by default is common amongst all targets in the directory, to copy information to the target pdb file and fails because the mspdb server has it locked for writing compilation debug info.

I have worked around it by arranging link dependencies with the taskgen method below. Would some version of this be useful in waf?

Other options on a case by case basis would be using different build directories per target or otherwise defining dependencies between the tasks, but I think getting to the root of the implicit dependency is somewhat useful for the general case.

```
@TaskGen.feature('cshlib', 'cstlib', 'cprogram')
@TaskGen.after_method('apply_link')
def apply_debug_symbols(self):
    """For msvc, generate a PDB file name and make the link task depend
    on it. The PDB name is added to CFLAGS using /Fdfile and the PDB
    file is added as an implicit output for the compiler task and a
    dependency for the link task. You can override the flag by setting
    ``bld.env['DBGPATH_ST']``.

    Tracking is needed to prevent conflicts if there are multiple
    targets building in one directory and some compiler instances are
    still writing debug info while a linker for
    another target is trying to read the same file.

    The taskgen attribute ``pdb`` optionally names the file (basename
    only), in case you want to make the name unique. If not provided,
    the default is ``vcVER``, where VER is the MSVC_VERSION, e.g.
    vc140. It is unclear if there is any speed gain by using a unique
    name per target in the same directory with multiprocessing and the
    /FS flag. MSDN recommends using separate directories per target.

        bld(features='cprogram', source='main.c', pdb='main-sym')

    """
    if self.env.CC_NAME != 'msvc' or not getattr(self, 'link_task', None):
	return

    if not getattr(self.env, 'DBGPATH_ST', None):
        self.env['DBGPATH_ST'] = '/Fd%s'

    # PDB basename for the flag
    if getattr(self, 'pdb', None):
        pdb = self.pdb
    else:
        msvc_ver = str(self.env['MSVC_VERSION']).replace('.', '')
        pdb = 'vc%s' % msvc_ver

    # Add the extension for the node
    node = self.path.find_or_declare(pdb + '.pdb')
    self.link_task.dep_nodes.append(node)

    for t in getattr(self, 'compiled_tasks', []):
        t.outputs.append(node)
        t.env.append_unique('CFLAGS', self.env['DBGPATH_ST'] % node.bldpath())
```

**Comment by shoover** [comment]
To do it robustly would require checking the CFLAGS to see if the user has actually set /Zi or /ZI to generate debug info, and determining how to resolve conflicts if they set /Fdfile already.

**Comment by ita1024** [comment]
Before making any change, I will need a small Waf project that shows the problem and how it is solved. There is some pdb file processing in this part, and I will need to understand how those parts fit together:
https://github.com/waf-project/waf/blob/waf-1.9/waflib/Tools/msvc.py#L980

In particular:
* Which task creates the .pdb file? Is it actually the whole list of .c/.cxx files? Is one pdb file per c/cxx task not possible?
* Should the default name not be unique or match the link task name?
* Is the pdb file not meant to be installed?

**Comment by shoover** [comment]
On Fri, Apr 15, 2016 at 5:28 PM, ita1024 <notifications@github.com> wrote:

> Before making any change, I will need a small Waf project that shows the
> problem and how it is solved.
>
So far I have not been able to construct a minimal test case, but I will
think about it more.

> There is some pdb file processing in this part, and I will need to
> understand how those parts fit together:
> https://github.com/waf-project/waf/blob/waf-1.9/waflib/Tools/msvc.py#L980
>
The referenced msvc code sets a link flag for the linker debug symbols. The
new proposal affects only the compiler debug symbols (which the linker
reads and merges).

> In particular:
>
>    - Which task creates the .pdb file? Is it actually the whole list of
>    .c/.cxx files? Is one pdb file per c/cxx task not possible?
>
> Every .c/.cxx compile task can create a .pdb file, either common or
unique. Handling this at the library or program task generator level was a
mistake in the first posted method. The method should apply to the 'c'
feature to apply to 'objects' and others as well.

Unfortunately when implemented as a 'c' feature, each compile task's .pdb
node must be searched to avoid adding duplicates to the link_task deps. In
the case of one shared file per task generator, this would be fast. The
diabolical case is many source files and all with a unique .pdb.

>
>    - Should the default name not be unique or match the link task name?
>
> The linker .pdb will match the link task name, so that would conflict if
reused for the compile tasks. The vcXXX.pdb default comes from the
compiler. However, if a pdb taskgen attribute is not added, then we would
not have to change CFLAGS and just have to know the compiler's convention
to add the dep to the link task.

>
>    - Is the pdb file not meant to be installed?
>
> Since typical use is as a sort of work file alongside the object file to
hold information for the linker, that will depend on whether object files
are installed. I think installation is not needed by default but perhaps
there are cases that need it?

**Comment by shoover** [comment]
I have found a test case. If many threads are used to build many C programs, debug info is generated with the default pdb file (/Zi and no /Fd), and the /FS compile flag is used, the warning occurs at some number of jobs and targets.

I am not entirely certain of the mechanism of the warning, but either constraining the build order or injecting a sleep before the link tasks can start works around the issue. Constraining the order makes it seem deterministic, while the sleep workaround is not.

Of course setting a unique pdb file per target also works (despite cluttering the build directory), as would configuring a subdirectory per target.

See https://github.com/shoover/waf/commit/811f7c032a1a2f822f42aebb9a136ddc9b11d5a6 for the test project.

**Comment by ita1024** [comment]
> I have worked around it by arranging link dependencies with the taskgen method below. Would some version of this be useful in waf?

I believe that such a setup is rather uncommon, and as such it is best presented as a showcase rather than something taking roots in the Waf libraries.

I had a quick look at the test project, and here are a few comments:
* There is no 'apply_link' method when linking is not requested, therefore `@TaskGen.after_method('apply_link')` is incomplete and should read `@TaskGen.after_method('apply_link', 'process_source')` at least.
* The indentation mixes tabs and spaces, and the print lines will be rejected by Python3
* I do not understand the concurrency problem, and it may just be that I need to get more familiar with that system:
   - Sharing a common pdb output file looks like a very bad idea. If the pdb file is removed manually, then which task will be reponsible for building it again?
   - Pdb naming should leverage existing object file names which are likely to be unique when source files are used by several task generators (use Node.change_ext)
   - I do not understand why sleeping is necessary. Is there anything besides running the build in -j1 mode?

**Comment by shoover** [comment]
Thank you for your feedback. I will clean it up. I use a "capable editor" but for the life of me I struggle to configure it for Python projects that use tabs.

- Sharing the common pdb is simply the compiler default [1], so I started with that. Due to the default folder hierarchy in Visual Studio projects there is typically no concurrency issue across projects, and MSDN recommends such a structure for command line use [2]. As for consistency of the pdb within the project, msbuild actually checks for the pdb and rebuilds all sources in the project if the pdb is missing. Further, the linker knows from the object file where the debug info should be and warns if information is missing. I don't know why they prefer to use one pdb (going so far as providing a pdb server to serialize writes when compiling multiple files at once), rather than use separate pdbs.
- I will try the per object file naming.
- The sleeping was just an attempt to isolate the problem in a different way to see if there was a problem with concurrent link tasks or an issue only compiling and linking. There are no issues with concurrent linking, so the sleeping should be removed.

[1] - https://msdn.microsoft.com/en-us/library/958x11bc.aspx

[2] - https://msdn.microsoft.com/en-us/library/dn502518.aspx

**Comment by shoover** [comment]
The latest findings and demo revision are here: https://github.com/shoover/waf/blob/f07b8a1f733ed1fe5857780fc6a54134d7a4ce1f/tests/pdbs/wscript.

This includes all the cleanup and the ability to generate a unique compile pdb per object or parse /Fd variations from CFLAGS.

My conclusion is that the a solution is needed in certain cases, e.g. multiple small test programs in one folder seems common, multiple libraries in one folder maybe less so. In practice it is sufficient to generate a unique compile pdb per target. It does not seem worth the hassle of dealing with waf nodes and generating one pdb per object. As you can see the per-object method is quite complicated and perhaps not worth including if there is interest in this as showcase/demo.

For my own project, I will drop the per-target method in the wscript and be done with it.
