### ISSUE TITLE
WAF is crashing on uname

### ISSUE THREAD

**Issue by sebekk23** [waf-project/waf#1733]
Hi

I have problems with waf based application on my gentoo box with 4.4.6 kernel (BananaPi machine with ARMv7 CPU)

More details are here: https://forums.gentoo.org/viewtopic-p-7909912.html

**Comment by ita1024** [comment]
That's in Samba, not in Waf.

Samba is also known to use a very old and unsupported Waf version.

**Comment by ita1024** [comment]
If you think that the problem is not samba-specific, provide an example of another project using Waf and attach the config.log file.

**Comment by Tickeldi** [comment]
tevent 0.9.28

[config.log.zip](https://github.com/waf-project/waf/files/263520/config.log.zip)

**Comment by ita1024** [comment]
As mentioned above: the problem is in the samba scripts.

If you read the config.log, you will also see that there are newlines in the `uname` output, so your system name is invalid. Good luck!

**Comment by dragon101788** [comment]
有解决方案么?

**Comment by ita1024** [comment]
@dragon101788 Ask the samba-project people! They are using an extremely outdated version of Waf that is unsupported.
