### ISSUE TITLE
Create shared library from objects without source files does not error nor create shared lib

### ISSUE THREAD

**Issue by drahnr** [waf-project/waf#1734]
```python
	objects = bld.objects(
		features = ['c', 'glib2'],
		target = 'objects',
		source = bld.path.ant_glob(['src/*.c']),
		includes = ['src/'],
		export_includes = ['src/'],
		uselib = 'M GOBJECT GLIB GTK3'
	)


	shlib = bld.shlib(
		features = ['c', 'glib2'],
		target = LIBNAME,
		source = [], use = 'objects',
		includes = ['src/'], 
		export_includes = ['src/'],
		uselib = 'M GOBJECT GLIB GTK3',
		install_path = "${LIBDIR}"
	)

      ..... a lot of tests using objects
```

this does not produce the shared lib as I'd expect

```sh
waf 1.8.20 (14c787c991e1d9badd9d302bc9eaa060e9d4b03c)
```

**Comment by ita1024** [comment]
The system cannot guess whether you want a library in c, c++ or fortran mode, so the feature must be declared properly: `bld.shlib(features='c cshlib glib2', ...)`.

You will also need to add the shared library flags such as `-fPIC` with `bld.objects(use='cshlib', ...)` else the resulting application will crash.

**Comment by drahnr** [comment]
Is there a usecase where `bld.shlib(features='c', ...` would not create a cshlib?

**Comment by ita1024** [comment]
When no source file is given, the system cannot guess the user intention, and an error is raised "Cannot Link from ...".

Your example is circumvents this but fails at passing a meaningful set of features.

**Comment by ita1024** [comment]
Closing this now.
