### ISSUE TITLE
persistence of options

### ISSUE THREAD

**Issue by drahnr** [waf-project/waf#1736]
Is there a reason that 

```
add_option(...)
```

does not inject the same options to `build` and `install` despite given to the `configure` stage?

**Comment by ita1024** [comment]
I am not sure I follow. Is this about the help message on `waf --help`?

**Comment by drahnr** [comment]
```
./waf configure --yada-yada
./waf build install
```

the later is not aware of `--yada-yada` being set at configure stage anymore.

1.8.20

```
def options(opt):
	opt.load('gnu_dirs')
	opt.add_option('--yada-yada', action='store_true', dest='yada_yada', default=False, help='yada 2x!')

#...

def build(bld):
    if bld.options.yada_yada:
        print ("yada is set")
```

I am not really familiar with the caching mechanisms of waf so apologize if I did something wrong.

**Comment by ita1024** [comment]
Command-line options are not persistent by default. There can be a variety of commands deriving from configure/build and tracking which ones need persistence is intractable.

**Comment by drahnr** [comment]
Would it be not the best approach to persist _all_ of them by default?

**Comment by ita1024** [comment]
I do not think so:
1. quite a lot of options are certainly not meant to be persistent by default: --progress, --destdir, --zones, ...
2. once an option is persisted, it is actually quite difficult to undo it, and this would mean to add --no-options for everything
3. finding out which commands must reset options and which ones must set them is tricky (configure/build/etc)

We tried this a long time ago and it was not pretty, so the only area this is applied is for `Configure.autoconfig=='clobber'`. Things that need persistence must be stored in `conf.env`.

**Comment by drahnr** [comment]
Would you be interested in a patch which would allow simple persisting via an additional flag on add_option (default False)?

**Comment by drahnr** [comment]
Makes sense.
