### ISSUE TITLE
concurrent build of cshlib before cstlib fails on linux

### ISSUE THREAD

**Issue by piem** [waf-project/waf#1737]
hi,

I recently changed aubio/aubio@7e9c67d to make sure programs were linked to the shared lib, not the static one. This [fails the build](https://travis-ci.org/aubio/aubio/builds/127218111) on linux with `src/libaubio.so: file not recognized: File truncated`.

The build passes with `-j1`, or when running `./waf build` once more, but fails otherwise (reproduced with waf 1.8.20 and 1.9.0pre2).

Switching the order of the targets to make sure `cshlib` is build before `cstlib` appears to [fix the build](https://travis-ci.org/aubio/aubio/builds/127227446): aubio/aubio@3bf80b9.

best, Paul

**Comment by ita1024** [comment]
Libraries should be brought in with the use= system to set the dependencies, the build order and the library paths!

**Comment by ita1024** [comment]
Besides that, the compiler name can be determined using `ctx.env.CC_NAME == 'msvc'`, probing for `CL.exe` in the CC variable is rather awkward.

**Comment by ita1024** [comment]
Example here: https://github.com/waf-project/waf/blob/waf-1.9/demos/c/shlib/wscript_build#L15

**Comment by piem** [comment]
Hi,

Ok, thanks for the compiler check, i will fix it asap.

Great, i didn't know that libraries could be mixed in `use`. This works:
```python
ctx.check_cfg(package = 'libavcodec', atleast_version = '54.35.0',
                args = '--cflags --libs', uselib_store = 'AVCODEC')
# ...
bld.program(source = # ...
        use = ['aubio', 'AVCODEC'], lib = ['m'],
```

but this doesn't:

```python
    use = ['aubio', 'AVCODEC', 'm'],
```

what would be the correct way of adding `-lm`?

**Comment by piem** [comment]
well,

```python
    ctx.check_cc(lib='m', uselib_store='M', mandatory=False)
```

seems to be enough, so I guess this can be closed.

Is `uselib` just the old name for `use`?

**Comment by ita1024** [comment]
Yes.
