### ISSUE TITLE
Dynamically named install task generator can't be found

### ISSUE THREAD

**Issue by antoche** [waf-project/waf#1740]
Hi,

Following from #1739. Using the same wscript:

```
from waflib import TaskGen
from waflib import Logs
from waflib.Build import inst

def options(opt):
    opt.load( 'compiler_cxx' )

def configure(opt):
    opt.load( 'compiler_cxx' )

@TaskGen.feature( '*' )
@TaskGen.after( 'process_subst', 'process_rule' )
def processInstall( taskGen ):

    installTask = getattr( taskGen, 'install_task', None )
    if installTask:
        installTask.name = '%s.install'%taskGen.name
        Logs.info( 'processInstall: Created %s'%installTask.name )
    elif getattr( taskGen, 'install_path', None ):
        Logs.info( 'processInstall: %s has no install task, install_path=%s'%( taskGen, taskGen.install_path ) )



@TaskGen.feature( '*' )
@TaskGen.after( 'process_rule', 'process_source' )
def postDependencies( self ):
    """
    Apply dependencies even for rule-based task generators

    Provides the same functionality as cxx's uselib, but for any generic task.
    """
    deps = getattr( self, 'dependsOn', [] )
    for name in self.to_list( deps ):

        other = self.bld.get_tgen_by_name( name )
        # Force other task generator to create its tasks
        other.post()

        if not self.tasks:
            Logs.warn( '%s has no tasks to constrain dependencies on!'%self.name )

        if isinstance( other, inst ):
            tasks = [ other ]
        else:
            tasks = other.tasks

        for t in self.tasks:
            for d in tasks:
                t.set_run_after( d )

def build(bld):

    bld.stlib( 
        target  = 'myLib', 
        source  = ['src/myLib.cc'],
        install_path = '${PREFIX}/lib' )

    bld( name = 'foo',
         rule = 'stat ${PREFIX}/lib/libmyLib.a',
         dependsOn = 'myLib.install' )
```

Running `waf install` in waf-1.8 and 1.9pre2 results in foo being run after myLib's installation, as expected:

```
Waf: Entering directory `/tmp/build'
processInstall: Created myLib.install
processInstall: Created myLib.install.install
[1/4] Compiling src/myLib.cc
[2/4] Linking build/libmyLib.a
+ install /tmp/lib/libmyLib.a (from build/libmyLib.a)
[4/4] Running foo
  File: `/tmp/lib/libmyLib.a'
  Size: 3480            Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d      Inode: 1463132     Links: 1
Access: 2016-05-11 14:40:30.236253000 +1200
Modify: 2016-05-11 14:40:30.236253000 +1200
Change: 2016-05-11 14:40:30.236253723 +1200
 Birth: -

Waf: Leaving directory `/tmp/build'
'install' finished successfully (0.153s)
```

But running it against 145dba3, the named install task generators can't be found:

```
Waf: Entering directory `/tmp/build'
processInstall: Created myLib.install
Waf: Leaving directory `/tmp/build'
Could not find a task generator for the name 'myLib.install'
```

**Comment by ita1024** [comment]
There is no "myLib.install", it is just "myLib".

See: https://github.com/waf-project/waf/blob/waf-1.9/tests/install/wscript#L33

**Comment by antoche** [comment]
Look at the processInstall method. It adds a name to the install task of myLib, as recommended at https://groups.google.com/d/msg/waf-users/gJo_D7kN39c/SDpazpomAQAJ. 

Are you saying I should now use a different solution to specify a dependency between the installation of myLib and another target?

**Comment by ita1024** [comment]
Yes: nesting task generators will not work for partial builds. And you can remove the code that you pasted, it is unnecessary for setting a build order/dependency.

Do you have a problem with [https://github.com/waf-project/waf/blob/waf-1.9/tests/install/wscript#L33](the testcase) ?

**Comment by antoche** [comment]
That example only shows how to set a dependency between install_files() and another task. How do I specify a dependency between myLib's installation and another task? Are you saying the installation task is also called "myLib"?

**Comment by ita1024** [comment]
The type of the objects returned by `bld.stlib()` and by `bld.install_files()` is the same. What works for the latter should work for the former.

Tasks have no name, and the installation task happens to be an object bound to the task generator object on the `.install_task` attribute.

**Comment by antoche** [comment]
I see. So in a `build` command, `myLib` refers to a task generator that will yield the build tasks. In an `install` command, `myLib` refers to a task generator that will yield build and install tasks.

**Comment by ita1024** [comment]
Yes, it does.
