### ISSUE TITLE
Reversed shared library symlinks

### ISSUE THREAD

**Issue by jeberger** [waf-project/waf#1742]
When building a shared library with the vnum option:

```python
bld.shlib (target = "mylib",
           vnum = "0.0.1",
           source = bld.path.ant_glob ([ "src/*.c" ]))
```

waf creates the following files:

- `libmylib.so` actual ELF file for the library,
- `libmylib.so.0` symlink to `libmylib.so`
- `libmylib.so.0.0.1` symlink to `libmylib.so`.

However standard practice would be:

- `libmylib.so.0.0.1` actual ELF file for the library,
- `libmylib.so.0` symlink to `libmylib.so.0.0.1`
- `libmylib.so` symlink to `libmylib.so.0.0.1`.

**Comment by ita1024** [comment]
Those files/symlinks are not installed.
