### ISSUE TITLE
Add --dry-run option to install

### ISSUE THREAD

**Issue by gregn-adroll** [waf-project/waf#1744]
`./waf install` produces a summary of the files it has installed in the destination folder. Does `waf` already have a feature for listing the installation (or uninstallation) actions that it plans to take without actually performing them?

**Comment by ita1024** [comment]
No, and we have no plans to add such a thing.

**Comment by ita1024** [comment]
Why do you need such a thing? Information missing.

**Comment by gregn-adroll** [comment]
I was just curious. I'm working on a project that uses waf and I accidentally overwrote a shared library without intending to. Then I started digging around the documentation to see if waf could be configured to either list what files it plans to install or actions it plans to take.

**Comment by ita1024** [comment]
Not an immediate need then :-)
