### ISSUE TITLE
pyext and pyembed fails on OSX with Conda Python 3.5

### ISSUE THREAD

**Issue by dfroger** [waf-project/waf#1745]
Tested on OSX ``10.9`` and ``10.10``, using Python 3.5 from ``conda``:

    conda install -n demo_bug python=3.5
    source activate demo_bug

I can't make the ``pyembed`` and ``pyext`` work:

    cd waf/demos/python
    waf configure

    Setting top to                           : /Users/froger/repo/waf/demos/python 
    Setting out to                           : /Users/froger/repo/waf/demos/python/build 
    Checking for 'clang' (C compiler)        : /usr/bin/clang 
    Checking for program 'python'            : /Users/froger/miniconda/envs/freshkiss3d/bin/python 
    Checking for python version              : (3, 5, 1, 'final', 0) 
    python-config                            : /Users/froger/miniconda/envs/freshkiss3d/bin/python3.5-config 
    Asking python-config for pyembed '--cflags --libs --ldflags' flags : yes 
    Testing pyembed configuration                                      : Could not build a python embedded   interpreter 
    Testing pyembed configuration                                      : yes 
    Asking python-config for pyext '--cflags --libs --ldflags' flags   : yes 
    Testing pyext configuration                                        : Could not build python extensions 
    Testing pyext configuration                                        : Could not build python extensions
    The configuration failed
    (complete log in /Users/froger/repo/waf/demos/python/build/config.log)

``config.log`` file is attached.

I'm using the lasted version of ``waf``.

[config.log.txt](https://github.com/waf-project/waf/files/272476/config.log.txt)

**Comment by ita1024** [comment]
`python-config` fails to provide the library paths to link targets (-L flags). Try to set the path to point to the correct version of python-config, or set the LDFLAGS environment variable flags prior to running the configuration.

**Comment by dfroger** [comment]
Note that with ``distutils``, building extension works. 

With this ``setup.py`:

    #!/usr/bin/env python
    from distutils.core import setup, Extension

    spam = Extension('spam', sources = ['spammodule.c'])

    setup(name='spam', ext_modules=[spam])

this works:

    cd waf/demos/python
    python setup.py build_ext --inplace

**Comment by dfroger** [comment]
With this command:

    LDFLAGS=$CONDA_ENV_PATH/lib ../../waf configure

I still have errors (see attached). I'll investigate in more depth tomorrow and try different settings of ``LDFLAGS``, ``CFLAGS`` or other settings of the ``python`` waf tool.

[config.log.txt](https://github.com/waf-project/waf/files/273288/config.log.txt)

**Comment by ita1024** [comment]
There is a missing "-L":
```
LDFLAGS=-L$CONDA_ENV_PATH/lib ../../waf configure
```

As for distutils, the module is known to be broken in a variety of ways in a variety of cPython versions.

**Comment by dfroger** [comment]
Sorry for the missing `-L`, I was tired...

With:

    LDFLAGS=-L$CONDA_ENV_PATH/lib ../../waf configure

I now have the error:

    err: ld: -stack_size option can only be used when linking a main executable

I'll try to remove the `-stack_size`.

[config.log.txt](https://github.com/waf-project/waf/files/274026/config.log.txt)

**Comment by dfroger** [comment]
`python3.5-config` (from `conda`) give the `-Wl,-stack_size,1000000` flag:

    $ python3.5-config --ldflags
    -lpython3.5m -ldl -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation

`python3.5-config` is invoked in [check_python_headers](https://github.com/waf-project/waf/blob/waf-1.8.20/waflib/Tools/python.py#L349), which set `PYTHON_PYEXT_LDFLAGS` (or `LDFLAGS` in `PYEXT` uselib?).

Just [bellow](https://github.com/waf-project/waf/blob/waf-1.8.20/waflib/Tools/python.py#L352), [test_pyext](https://github.com/waf-project/waf/blob/waf-1.8.20/waflib/Tools/python.py#L232) is called, which fails because of `-stack_size`.

Is their any way/hook to fix `PYTHON_PYEXT_LDFLAGS` (remove `-stack_size`), just after `python3.5-config` is invoked?

**Comment by ita1024** [comment]
Your python installation is broken, I have both 3.5 and 2.7 on OSX and I have no such problem configuring and building the projects.

**Comment by ita1024** [comment]
You can try something like this, but I would rather get a working python installation:
```python
from waflib import TaskGen
@TaskGen.feature('pyext')
@TaskGen.after('apply_link', 'propagate_uselib_vars')
def remove_flag_stack(self):
        flags = self.env.LINKFLAGS
        self.env.LINKFLAGS = [x for x in flags if not x.startswith('-Wl,-stack_size,')]
```

**Comment by dfroger** [comment]
Ok, I will notify conda packagers about the problem.

Thanks for the fix, will try it.
