### ISSUE TITLE
Error in waf/waflib/Tools/python.py

### ISSUE THREAD

**Issue by kartikgupta0909** [waf-project/waf#1750]
I got a Attribute Error while I was using waf. I think the problem is in line 581 in the file waf/waflib/Tools/python.py. Because the variable Options.options.python is not being set as None if not provided by the user and hence would give an attribute error when asked for a value.

**Comment by ita1024** [comment]
Any way to reproduce the problem? Have you used the example or tried to roll your own?
https://github.com/waf-project/waf/blob/master/demos/python/wscript#L14

**Comment by ita1024** [comment]
No action possible, closing now.
