### ISSUE TITLE
waf_unit_test: give possibility to pass parameters to executable

### ISSUE THREAD

**Issue by fedepell** [waf-project/waf#1753]
I found the necessity to pass parameters to the unit test executable. This can be very useful for example when using googletest as a test library, since via command line parameters some behaviour can be modified easily (for example my current concrete need was to pass the option to generate XML files that I need then for the CI server for a more complete output, but it may be also some other features).

From the documentation this is not possible ("_When the build is executed, the program ‘test’ will be built and executed without arguments._") but indeed I found a way to do it, by using something like:

`                ut_cmd   = '%s --gtest_output=xml:out.xml',
`

And it works fine, but I think it's much more a hack than the intended feature and may clash with the option for which this ut_cmd is used (testcmd command line option) . 

I think it would be interesting to add the possibility to officially pass parameters to the test execution with something like:

`               ut_params = '--gtest_output=xml:out.xml'
`

or:

`               ut_params = [ '--gtest_output=xml:out.xml' , '--gtest_print_time=0' ]
`

(or support both)

I can contribute this (as I implemented it almost fully before noticing the hack) if it sounds useful.

Thanks!
F.

**Comment by ita1024** [comment]
Works already:
https://github.com/waf-project/waf/blob/master/demos/unit_test/tests/test1/wscript_build#L15

Appending parameters is not necessarily the only case: some script could be used to spawn the executable to limit for example memory usage or to run additional tests. We could make `ut_fun` a string expression featuring `${}` substitutions though.

**Comment by fedepell** [comment]
Thanks for the link, sorry missed that example! Agree totally with _ut_fun_ can be done (and much more can be done indeed as you explain). But for something so "simple" as passing the arguments isn't this way maybe a bit too complex? (I'm just thinking on maintainability in the long term with some rather big wscript files with this potential functions floating around)

Still using _ut_fun_ to append an argument as in the example works, but breaks the _ut_cmd_ feature, as the code is:

```
		if testcmd:
                       self.ut_exec = (testcmd % self.ut_exec[0]).split(' ')
```

Gets _ut_exec[0]_ therefore losing the just added parametrs (which are un _ut_exec_[1] ... ). So if you use both _uf_fun_ to append and the _testcmd_ Option, then the argument is lost. 
I can in case check/fix this.



I didn't understand your last comment about making _ut_fun_ a string (given now it's a function getting called as is later in _run_ ).

Thanks!

**Comment by ita1024** [comment]
Do you mean that hear what I meant or that you still do not understand the change that can be made to ut_fun?

**Comment by fedepell** [comment]
I did not understand clearly just the last phrase: 

We could make ut_fun a string expression featuring ${} substitutions though.

**Comment by ita1024** [comment]
So you still do not understand the point, so an example is necessary. Let us pretend for one second that a script provides something like this:
```python
    bld(..., features='cxx cxxprogram test', ut_fun='valgrind ${TGT} --option=foo')
```
Would you consider this sufficient or are you looking for something more complicated?

**Comment by ita1024** [comment]
Sure, there is no need to use the same attribute.

**Comment by fedepell** [comment]
I was trying to implement the feature and was hoping to use something like Utils.subst_vars but that doesn't include TGT/SRC but just the environment (which are correctly substituted). Is there a similar trick maybe also for that vars?

**Comment by fedepell** [comment]
I gave it a try: I got the standard environment and added just TGT by hand. Not sure this is the best. But it works fine and is very interesting since also generic environment variables can be very useful for test execution (see example in the commit message).

I put it here:

https://github.com/fedepell/waf/tree/unit-test-parameters

**Comment by ita1024** [comment]
That's too limited. If the task class implemented exec_command, then it would be easy to re-use `waflib.Task.Task.compile_fun`.

**Comment by fedepell** [comment]
I understand! Indeed I was looking exactly at that code, but it was looking much more complex with my limited knowledge to implement it that way.

**Comment by ita1024** [comment]
See: https://github.com/waf-project/waf/commit/16aeb5756a075d1a99fb8cb93b0d86f7c90ed533

**Comment by ita1024** [comment]
Use waf 1.9
