### ISSUE TITLE
Cannot create static library due to "WafError: Execution failure: [Errno 7] Argument list too long"

### ISSUE THREAD

**Issue by sebhub** [waf-project/waf#1756]
Typical values for the command argument list maximum are (getconf ARG_MAX) 2097152 on Linux and 32000 on msys2. The following project fails to build on Linux:

#!/bin/sh -x

n=10000
f="source-file-abcdefghijklmnopqrstuvwxyz-abcdefghijklmnopqrstuvwxyz-abcdefghijklmnopqrstuvwxyz-abcdefghijklmnopqrstuvwxyz-abcdefghijklmnopqrstuvwxyz-abcdefghijklmnopqrstuvwxyz-abcdefghijklmnopqrstuvwxyz-abcdefghijklmnopqrstuvwxyz-"

for i in `seq $n` ; do echo "int f$i(void) { return $i; }" > $f-$i.c ; done

cat >wscript <<eof
top = '.'
out = 'build'

def options(conf):
        conf.load('compiler_c')

def configure(conf):
        conf.load('compiler_c')

def build(bld):
        bld.stlib(target = 'large', source = [
eof

for i in `seq $n` ; do echo "           '$f-$i.c'," >> wscript ; done

cat >>wscript <<eof
        ])
eof

Output:

Waf: Entering directory `/home/EB/sebastian_h/apps/bug-waf-large-lib/build'
[10001/10001] Linking build/liblarge.a
Waf: Leaving directory `/home/EB/sebastian_h/apps/bug-waf-large-lib/build'
Build failed
Traceback (most recent call last):
  File "/home/EB/sebastian_h/bin/.waf-1.8.21-f82045c32bfe2733639c9d1b6e51d409/waflib/Task.py", line 110, in process
    ret=self.run()
  File "/home/EB/sebastian_h/bin/.waf-1.8.21-f82045c32bfe2733639c9d1b6e51d409/waflib/Tools/ccroot.py", line 95, in wrap
    return old(self)
  File "<string>", line 19, in f
  File "/home/EB/sebastian_h/bin/.waf-1.8.21-f82045c32bfe2733639c9d1b6e51d409/waflib/Task.py", line 95, in exec_command
    return bld.exec_command(cmd,**kw)
  File "/home/EB/sebastian_h/bin/.waf-1.8.21-f82045c32bfe2733639c9d1b6e51d409/waflib/Context.py", line 177, in exec_command
    raise Errors.WafError('Execution failure: %s'%str(e),ex=e)
WafError: Execution failure: [Errno 7] Argument list too long

waf should be able to detect that the argument list is too large and choose tool specific means to avoid the problem, e.g. use @file in case of GNU ar.

**Comment by ita1024** [comment]
Use the extension referenced above.

**Comment by sebhub** [comment]
Thanks, works like a charm on Linux and msys2.

**Comment by ita1024** [comment]
Waf 1.9 has this by default, no extension needed.
