### ISSUE TITLE
make waf logging more compatible with Python logging

### ISSUE THREAD

**Issue by jason-s** [waf-project/waf#1763]
I suspect this will be summarily closed, but....

The waf internal logging methods are really incompatible with the standard Python logging methodology, which essentially amounts to a publish/subscribe system. (Objects publish log records, logging handlers subscribe to those records) A normal Python module would do something like

```
import logging
logger = logging.getLogger(__name__)
```

and then call logger.whatever() in those module's functions. Then elsewhere the calling application decides which loggers to set at what levels and direct to which output files / streams / etc.

What is really difficult about waf is that it just uses one big logger ("waflib"), stuffs it in a global singleton variable `Logs.log`, *and* it uses this to produce the standard output of waf, adding concepts like zones and whatnot to customize what appears on waf's stdout. 

I don't want to mess with waf's stdout, I want to access some of waf's log records and send to a file. In my case, I wanted to preserve the standard waf output, but capture the task execution commands (e.g. as in `waf -v`) to a log file, so that there is more information in the log file and stdout doesn't get cluttered via extra information.

I've tried several ways (the build_logs tool just tries to copy stdout, which is NOT what I want), it looks like I can do what I want but only by monkeypatching the `Context.exec_command()` method. If I assign a logger to `bld.logger` that overrides the `Logs.log` logger, it has side effects:
- it removes it from printing to stdout
- it also enables verbosity in Context.exec_command

so that doesn't work.

It would be much easier if waf had a clean logging architecture that was compatible with the standard Python logging system.

**Comment by jason-s** [comment]
I finally settled on this (called in `init()`) for my purposes.

```
def monkeypatch_context_logging(path):
    import waflib
    # from waflib.Logs.make_logger
    ####
    wlogger=logging.getLogger('waflib')
    hdlr=logging.FileHandler(path,'w')
    formatter=logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    hdlr.setFormatter(formatter)
    wlogger.addHandler(hdlr)
    wlogger.setLevel(logging.DEBUG)
    ####
    logger = logging.getLogger('build')
    logger.addHandler(hdlr)
    logger.setLevel(logging.INFO)
    ####

    ec0 = waflib.Context.Context.exec_command
    def ec1(self,cmd,**kw):
        logger.info("exec_command %s", cmd)
        return ec0(self,cmd,**kw)
    waflib.Context.Context.exec_command = ec1
```

**Comment by ita1024** [comment]
This will be closed because:

1. This is not actionable
2. This is a rant

You could achieve what you want if you knew the Python logging framework better. Blaming the waflib.Log.log object is irrelevant, as the situation would not be any better if we had one log singleton by Waf module (which would create performance issues).

@zougloub in case you want to comment

**Comment by ita1024** [comment]
No further comment, closing now.
