### ISSUE TITLE
Python support into waf_unit_test

### ISSUE THREAD

**Issue by fedepell** [waf-project/waf#1765]
As Python is one of the supported languages I think it would be nice if we could integrate running Python unit tests in the waf_unit_test module (which is historically for C/C++/D). 

I tried to study the code myself and my conclusion is that it is not natural to do so as the waf_unit_test assumes a language with a linking stage and a clear target, something that the Python language support doesn't have, making a proper integration difficult.

I played a bit around and found a **hack** that makes things work, but as I totally realize this is a hack I'm not putting a pull request :) But I'm posting this to raise the question if something could be done in this direction, which I think would be something valuable for waf.

Here is my hackommit: 
https://github.com/fedepell/waf/commit/c893b1fe6e4cf09f20cd952450df9e2cac6de3b0

Actually with this hack I can run tests normally for target with a single file like:

`bld(features='py test', source=('src/pytest.py'))`

Which will execute src/pytest.py and simply check the exit code. 

Or with a test runner such as nose using the recent ut_str feature:

`bld(features='py test', source=('src/pytest.py'), ut_str  = 'nosetests ${SRC}')`

Things get more complicated when the source is more than a file, since in that case the immediate execution is not possible (as _"There can be only one unit test task by task generator"_) but still can be used via a test runner (which is anyway what I need) like for example:

`bld(features='py test', source=bld.path.ant_glob('src/*.py'), ut_str   = 'nosetests --with-doctest ${SRC}')`

This will correctly run all the src/*.py tests through nose (in the example including also doctests) and report accordingly.

If ut_str is not used in this second example then the first Python file will be executed passing as argument the others, not really something we desired.

Any ideas and possibilities to have something in this direction in the future maybe?

Thanks!
F.

**Comment by xbreak** [comment]
I agree. Support for a more generalized unit test runner would be great!

**Comment by ita1024** [comment]
@fedepell: I believe that you are making it more complicated than necessary: there is no need to change the waf_unit_test.py file whatsoever.
@xbreak: works already

```python
import os
from waflib import Task, TaskGen
@TaskGen.feature('pytest')
def do_pytest(self):
        nodes = self.to_nodes(self.pytest_files)
        tsk = self.create_task('utest', nodes)
        self.ut_run, lst = Task.compile_fun(self.ut_str, shell=getattr(self, 'ut_shell', False))
        tsk.vars = lst + tsk.vars
        self.ut_cwd = self.path
        self.ut_env = dict(os.environ)

def build(bld):
        bld(features='pytest', pytest_files='wscript', ut_str='ls ${SRC}')

def configure(conf):
        conf.load('waf_unit_test')
```

**Comment by ita1024** [comment]
I have little time to learn yet another testing framework right now. If you want to add something for python nosetests, make a pull request and add a demo/showcase. The python-specific waf_unit_test code should go in a separate file for a start.

**Comment by fedepell** [comment]
Hi!
Thanks for the comments and the clarification on how to do it in a better way! I'll try to clear up my ideas a bit and as you suggest I'll try in case to do a pull request! Let me see a bit better now, after your example, how I could structure the thing. I have to test something similar also with Java (with a test runner) so let me see if I could derive something more generic.

Thanks a lot again!
F.
