### ISSUE TITLE
Issue with `A compiler producing source files with names unknown in advance` example in the waf book?

### ISSUE THREAD

**Issue by bradtgmurray** [waf-project/waf#1766]
We recently integrated protobuf compilation into our waf build which follows the pattern of a build task that doesn't know the name of it's outputs in advance. We found section "11.4.2. A compiler producing source files with names unknown in advance" in the waf book and pretty much used that sample code verbatim. However, rarely we'll end up with a failed build that looks something like the following.

```
Traceback (most recent call last):
  File "/root/bamboo-agent-home/xml-data/build-dir/TT-MC10-BSPBQ/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Task.py", line 110, in process
    ret=self.run()
  File "/root/bamboo-agent-home/xml-data/build-dir/TT-MC10-BSPBQ/waftools/protoc.py", line 55, in run
    tsk.add_c_tasks(tsk.outputs)
  File "/root/bamboo-agent-home/xml-data/build-dir/TT-MC10-BSPBQ/waftools/protoc.py", line 70, in add_c_tasks
    tsk.generator.link_task.inputs.sort(key=lambda x: x.abspath())
ValueError: list modified during sort
```

Relevant line in the waf book is here: https://github.com/waf-project/waf/blob/b78ba7d72cede612eff939db065a6ba68b067975/docs/book/scenarios.txt#L645

Is it possible for two threads to call `run` and `runnable_status` on tasks that have the same `.link_task` concurrently? If so, should this example be updated to account for that?

**Comment by ita1024** [comment]
It seems that we have removed too much code lately, so the link task is being processed at the same time. Consider 9ede16b70ab65ecb39ce638fa308c20beea8a534

**Comment by bradtgmurray** [comment]
Thanks for a quick reply. I'll apply this change and see if it crops up again in our CI. Unfortunately we've only been able to trigger it once a day or so, I won't have a sure answer for you if this fixes it for a few days. I'll reopen if we see it again.

**Comment by ita1024** [comment]
If a program is build make sure the label reads "cprogram" or "cxxprogram".

**Comment by bradtgmurray** [comment]
We're currently building these files into a static library using `bld.stlib()` and then including them in our final program using `use`. Is that an issue?

**Comment by ita1024** [comment]
Yes! Make sure the name is correct by running "waf -v" and verifying that there is no warning.

In this case the name should be `cstlib` or `cxxstlib` depending on the programming language; it is **not** "cstaticlib", see 1201a7776fae3698712f5e4276915e60c2dd776a
