### ISSUE TITLE
Allow disabling define_name functionality

### ISSUE THREAD

**Issue by holtrop** [waf-project/waf#1767]
In some cases the user may not want any define added. This code in the configuration step:

```python
conf.check(header_name = "getopt.h", define_name = None)
```

will raise an AssertionError that define_name is not a str. It would be nice to be able to disable adding a define for particular configuration steps (anything that accepts define_name).

**Comment by ita1024** [comment]
How about passing `global_define=False`? This should have similar effects.

**Comment by ita1024** [comment]
None is useful to catch invalid parameters so it will stay as-is. Passing an empty string will be less problematic. Use the following with the git version or wait for waf 1.9.2
cdb46e29f908a9173a3d35f0db0f7912d37473ae

**Comment by holtrop** [comment]
Using an empty string sounds good. I also was unaware of the global_define option, which seems to do what I want as well. Perhaps another issue would be to document global_define in the Waf Book :). I'll close this now though.
