### ISSUE TITLE
Default build method

### ISSUE THREAD

**Issue by haizaar** [waf-project/waf#1768]
Hello,

I'm using waf for building docker images. I have multiple directories in my project, each one having  exactly the same `build` method in them:

```
def build(ctx):
    ctx(source="Dockerfile")
```

(I have defined implicit rule in the top `wscript` file).

Is there a way to eliminate such code duplication?

Thank you!

**Comment by ita1024** [comment]
There are a few possibilities, such as using `wscript_build` files instead of `wscript` files. In this case, I imagine that you are calling `bld.recurse()` for all folders; if that is the case, try passing the `path` to the base directory:
```python
def build(bld):
    for x in 'folder1 folder2 folder3'.split():
        bld(source='Dockerfile', path=bld.path.find_node(x))
```

**Comment by haizaar** [comment]
Worked great! Thanks for the prompt response (and sorry for the  late ack :)
