### ISSUE TITLE
waf dist with Python 3.5 throws encoding error

### ISSUE THREAD

**Issue by moltob** [waf-project/waf#1769]
Using Python 3.5 64 Bit on Windows I get an encoding error:

    W:\Temp\waf\hw>waf dist
      ...
        self.archive()
      File "W:\Temp\waf\hw\waf3-1.9.1-584ef1b5b82e22046b7c9d5797d92393\waflib\Scripting.py", line 272, in archive
        digest=' (sha=%r)'%sha1(node.read()).hexdigest()
    TypeError: Unicode-objects must be encoded before hashing

The same does work just fine with Python 2.7. The issue is probably this:

* node.read() returns the content of the file as string
* constructors of hash functions in Python 3 take byte-like objects

Can be fixed (for both Python 2 and 3) by changing the code in Scripting.py:272, from

    digest=' (sha=%r)'%sha1(node.read()).hexdigest()

to

    digest=' (sha=%r)'%sha1(node.read().encode(encoding='ISO8859-1')).hexdigest()

This change should not be too much of an issue, as the digest is only used as user console information.

**Comment by moltob** [comment]
Let me know if you like a PR.

**Comment by ita1024** [comment]
The fix will appear in waf 1.9.2
