### ISSUE TITLE
Enabling support for list of targets for uselib_store for conf.check_c[xx] functions

### ISSUE THREAD

**Issue by cyrilbouvier** [waf-project/waf#1771]
Hi,

I was wondering if it would be possible to enable support of multiple uselib_store for checking functions during configure. I would like to be able to write something like:

`conf.check_cxx (header_name = "time.h", uselib_store = [ "SET1", "SET2" ])`

If I understand the code correctly, it would mean patching the function post_check in Tools/c_config.py.

Here is a proposed patch:

current version:
```
if is_success and'uselib_store'in kw:
		from waflib.Tools import ccroot
		_vars=set([])
		for x in kw['features']:
			if x in ccroot.USELIB_VARS:
				_vars|=ccroot.USELIB_VARS[x]
		for k in _vars:
			x=k.lower()
			if x in kw:
				self.env.append_value(k+'_'+kw['uselib_store'],kw[x])
```

Proposed changes:
```
if is_success and'uselib_store'in kw:
            from waflib.Tools import ccroot
            _vars=set([])
            if not isinstance (kw['uselib_store'], list)
                kw['uselib_store'] = [kw['uselib_store']]
            for x in kw['features']:
                if x in ccroot.USELIB_VARS:
                     _vars|=ccroot.USELIB_VARS[x]
            for k in _vars:
                for store in kw['uselib_store']:
                     x=k.lower()
                     if x in kw:
                         self.env.append_unique(k+'_'+store,kw[x])
```

[ I also changed the append_value to append_unique to avoid duplicates ]

Cyril

**Comment by ita1024** [comment]
This would make the code much more complex. Why are you doing that?

**Comment by cyrilbouvier** [comment]
> Why are you doing that?

Because I want to test the existence of a library and use this library with two different "settings".

> This would make the code much more complex.

It only need 3 more lines of code ! (and I am not sure but two of them could be combine with the to_list method of utils)

**Comment by ita1024** [comment]
The variable `uselib_store` is used in more than 3 lines, see for example:
https://github.com/waf-project/waf/blob/master/waflib/Tools/c_config.py#L321

The tests may be wrapped or repeated, so this can be considered an optimization. Given the complexity and the meager benefits we will not make any change.

**Comment by cyrilbouvier** [comment]
There is no need to change the rest of the code. With the changes that I proposed you could still use both syntax: `uselib_store = "SET1" ` and `uselib_store = [ "SET1", "SET2" ]`.
