### ISSUE TITLE
Adding a LICENSE file

### ISSUE THREAD

**Issue by mortenvp** [waf-project/waf#1773]
We would like to distribute some of our `waf` tools under the same license as `waf` itself. However, it is no currently so easy to figure out exactly what license `waf` is under. 

Would it be possible to add a `LICENSE` text file or similar in the source folder?

All the best,
Morten

**Comment by ita1024** [comment]
The license is at the very beginning of the Waf file, so we will not add yet another boilerplate file:
https://github.com/waf-project/waf/blob/master/waf-light#L6

**Comment by mortenvp** [comment]
Hi @ita1024 sounds good. Just couldn't find it, you could consider writing / linking to that in the README.md
