### ISSUE TITLE
MSVC doesn't print errors

### ISSUE THREAD

**Issue by artiomn** [waf-project/waf#1776]
MSVC compiler out errors into stdout. Runner doesn't print this errors. It's very inconvenient, because after build failure, I need to repeat build command by hands.

P.S.:
[Interesting MSVC helper from Crytek (with PCH)](https://github.com/CRYTEK-CRYENGINE/CRYENGINE/blob/release/Code/Tools/waf-1.7.13/crywaflib/mscv_helper.py)

**Comment by ita1024** [comment]
The errors are displayed properly with waf running under cmd.exe with visual studio. Please make a testcase.

**Comment by artiomn** [comment]
Yes, all is ok. It's my failure. Sorry.

**Comment by artiomn** [comment]
Problem appeared, because I have my own logger.
I think, it's not a bug, but merely unclear behaviour.

Context.exec_command():354:
```python
if out:
	if not isinstance(out, str):
		out = out.decode(sys.stdout.encoding or 'iso8859-1')
	if self.logger:
		self.logger.debug('out: %s', out)
	else:
		Logs.info(out, extra={'stream':sys.stdout, 'c1': ''})
```

In this code fragment, command output passed to debug function, :
```python
	if self.logger:
		self.logger.debug('out: %s', out)
```

Debug will be print output only if `verbose` flag set:
```python
def debug(*k, **kw):
	"""
	Wraps logging.debug and discards messages if the verbosity level :py:attr:`waflib.Logs.verbose` ≤ 0
	"""
	global verbose
	if verbose:
		k = list(k)
		k[0] = k[0].replace('\n', ' ')
		global log
		log.debug(*k, **kw)
```

But MSVC prints errors to the stdout, not stderr and without `verbose` it may not be printed.

**Comment by ita1024** [comment]
Is there anything to do here?

**Comment by artiomn** [comment]
Maybe replace logger.debug() on something else or provide user flag to control output (yes, of course I can create my own wrapper on the `logger`, but it looks like a crunch)?

**Comment by artiomn** [comment]
Or make a little patch, like this:

```python
			if self.logger:
				if 'error' in out:
					self.logger.error(out)
				else:
					self.logger.debug('out: %s', out)
```

**Comment by ita1024** [comment]
I do not think so:
* Your logger can easily find which lines start by `out:` and which lines start by `err:`
* Your context classes can override `exec_command`
* This would break existing for rather obscure reasons
