### ISSUE TITLE
waflib in the waf directory

### ISSUE THREAD

**Issue by artiomn** [waf-project/waf#1778]
Waf fails if WAFDIR environment variable doesn't set and directory with wscript doesn't contain library. 
It doesn't find waf library in directory with waf. Sometimes it's useful.

Fix:

```diff
--- a/waf-light
+++ a/waf-light
@@ -154,6 +154,11 @@ def find_lib():
        w = test(dir)
        if w: return w

+   #waflib in the 'waf' directory
+       dir = os.path.dirname(__file__)
+       w = test(dir)
+       if w: return w
+
        #unpack
        unpack_wafdir(dir, src)
        return dir
```

**Comment by ita1024** [comment]
In this case, why not use the file `waf-light` directly?

**Comment by artiomn** [comment]
How?
In my case, I want to have build system as a git submodule (or, maybe, even installed on the developer machine).
The developer, who uses system, don't need to know about the environment variables, he wants to run waf_build/waf build from his project directory to build project.

**Comment by artiomn** [comment]
OMG, I understood, what you meant:
```python
	#waf-light
	if name.endswith('waf-light'):
		w = test(base)
		if w: return w
		err('waf-light requires waflib -> export WAFDIR=/folder')
```

I want to run `waf` command, simply, not a `waf-light`. :-)

**Comment by ita1024** [comment]
Well, no, the file `ẁaf` is meant to contain its library and this is meant to protect against silly mistake. No change will be made.
