### ISSUE TITLE
msvcdeps doesn't work

### ISSUE THREAD

**Issue by artiomn** [waf-project/waf#1780]
I think, `exec_response_command`, which redefines in `msvcdeps` was removed in the `msvc` module.
Now, `msvcdeps_paths` attribute is not set.

```
build: logging stopped.
Build failed
Traceback (most recent call last):
  File "d:\repos\my_build_system\src\waflib\extras\parallel_debug.py", line 234,
 in process
    self.post_run()
  File "d:\repos\my_build_system\src\waflib\extras\gccdeps.py", line 80, in post
_run
    return self.no_gccdeps_post_run()
  File "d:\repos\my_build_system\src\waflib\extras\msvcdeps.py", line 101, in po
st_run
    for path in self.msvcdeps_paths:
AttributeError: 'c' object has no attribute 'msvcdeps_paths'
```

P.S.:
[Improved msvcdeps from Crytek (with pretty-printed custom error message)](https://github.com/CRYTEK-CRYENGINE/CRYENGINE/blob/release/Code/Tools/waf-1.7.13/crywaflib/msvcdeps.py)

**Comment by ita1024** [comment]
`msvcdeps.py` works, but it cannot be loaded at the same time as `gccdeps.py`. Feel free to submit a pull request.

**Comment by ita1024** [comment]
`gccdeps.py` and `msvcdeps.py` can be loaded together:

```python
def configure(conf):
    ...
    conf.load('gccdeps msvcdeps')
```

**Comment by artiomn** [comment]
Look at the error message, please:
```
Waf: Leaving directory `d:\repos\third-party\openssl\build'
build: logging stopped.
Build failed
Traceback (most recent call last):
  File "d:\repos\my_build_system\src\waflib\extras\parallel_debug.py", line 234,
 in process
    self.post_run()
  File "d:\repos\my_build_system\src\waflib\extras\msvcdeps.py", line 101, in po
st_run
    for path in self.msvcdeps_paths:
AttributeError: 'c' object has no attribute 'msvcdeps_paths'
```

It is without gccdeps loaded (previously, it was loaded in the "separated environment" and didn't affect on msvcdeps).

**AttributeError: 'c' object has no attribute 'msvcdeps_paths'**

**Comment by artiomn** [comment]
Compartibility patch:
```diff
--- waflib\extras\gccdeps.py.orig	Fri Jul 22 12:10:57 2016 UTC
+++ waflib\extras\gccdeps.py	Fri Jul 22 12:54:52 2016 UTC
@@ -26,6 +26,10 @@
 supported_compilers = ['gcc', 'icc', 'clang']
 
 def scan(self):
+	# I can use several compilers simultaneously.
+	if self.env.CC_NAME not in supported_compilers:
+		return self.no_gccdeps_scan()
+
 	if not self.__class__.__name__ in self.env.ENABLE_GCCDEPS:
 		if not self.env.GCCDEPS:
 			self.generator.bld.fatal('Load gccdeps in configure!')
@@ -63,7 +67,7 @@
 		lock.acquire()
 		node = cached_nodes[node_lookup_key]
 	except KeyError:
-		node = base_node.find_resource(path)
+		node = base_node.find_node(path)
 		cached_nodes[node_lookup_key] = node
 	finally:
 		lock.release()
@@ -98,7 +102,8 @@
 	# So the first step is to sanitize the input by stripping out the left-
 	# hand side of all these lines. After that, whatever remains are the
 	# implicit dependencies of task.outputs[0]
-	txt = '\n'.join([remove_makefile_rule_lhs(line) for line in txt.splitlines()])
+	txt = '\n'.join([remove_makefile_rule_lhs(line) for line in txt.splitlines()
+                     if not line.endswith(':')])
 
 	# Now join all the lines together
 	txt = txt.replace('\\\n', '')
```

**Comment by ita1024** [comment]
I believe that you are using outdated versions of both files, else you would have noticed the extra "post_run" lines in the outputs.

Regarding the diff that you pasted:
* `find_node` can return Node` objects that represent folder, so `find_resource` is really necessary there because it will filter those that are files. If you think otherwise, please provide a testcase
* I do not understand the purpose of `if not line.endswith(':')`, and for this too some testcase is necessary. Is the current implementation failing to find dependencies for something?
* `if self.env.CC_NAME not in supported_compilers:` seems incorrect because the configuration tests for `-MMD` flag support. There is no `no_gccdeps_scan` function defined in the `gccdeps.py` file.

I am sadly unable to reproduce the problem, so please provide a working testcase!

**Comment by artiomn** [comment]
> I believe that you are using outdated versions of both files,
> else you would have noticed the extra "post_run" lines in the outputs.
Patch was created before you commit with msvcdeps/gccdeps compartibility fix.
Msvcdeps was old, really. Now it's working. 
Thank you.

- I don't remember why, but it didn't work. Testing node on None, perhaps, would be a better solution.
- It was not fully correct case. Clang with -MP flag (below I posted traceback and comments).
- Ok, may be it's not fully correct (simply, I use fixed set of compilers, which support -MMD). `no_gccdeps_scan`, of course doesn't exist in gccdeps.py, because you have removed it by a commit 7aaa7c1, but patch was for the previous version of the file.

```
Build failed
Traceback (most recent call last):
  File "d:\repos\my_build_system\src\waflib\extras\parallel_debug.py", line 234,
 in process
    self.post_run()
  File "d:\repos\my_build_system\src\waflib\extras\gccdeps.py", line 145, in pos
t_run
    raise ValueError('could not find %r for %r' % (x, self))
ValueError: could not find ['src', 'crypto', 'cryptlib.h:'] for
        {task 53322896: c dso_beos.c -> dso_beos.c.2.o}
```

text fragment without `endswith` (last lines are incorrect):

```
  ..\src\crypto\dso\dso_beos.c ..\src\crypto/cryptlib.h ..\src/e_os.h \
  ..\src\include/openssl/opensslconf.h \
  ..\src\include/openssl/../../crypto/opensslconf.h \
  ..\src\include/openssl/e_os2.h ..\src\include/openssl/../../e_os2.h \
...
  ..\src\include/openssl/dso.h \
  ..\src\include/openssl/../../crypto/dso/dso.h
...
..\src\include/openssl/../../crypto/err/err.h:

..\src\include/openssl/lhash.h:

..\src\include/openssl/../../crypto/lhash/lhash.h:

..\src\include/openssl/dso.h:
```

text fragment filtered with `endswith`:

```
  ..\src\engines\ccgost\gost_ctl.c ..\src\include/openssl/crypto.h \
  ..\src\include/openssl/../../crypto/crypto.h \
  ..\src\include/openssl/e_os2.h ..\src\include/openssl/../../e_os2.h \
...
  ..\src\engines\ccgost/gost89.h ..\src\engines\ccgost/gosthash.h
```
