### ISSUE TITLE
Flex taskgens do not support flexflags

### ISSUE THREAD

**Issue by Whyki** [waf-project/waf#1781]
Need support for flexflags to provide source specific parameters ie. -P[prefix]

**Comment by ita1024** [comment]
Why not do this in the configuration? `conf.env.append_value('FLEXFLAGS', '-P/opt')` ?

**Comment by Whyki** [comment]
Well the option -P works different it is prefix added to flex generated C variables, so obviously if you have multiple parsers/libraries you don't want the same options. In our build system we have few parsers which will compile only with specific flex options so we cannot use common one in configuration. 

I'll elaborate on flex tool re-implement which would support flexflags correctly: force rebuild on change.

**Comment by ita1024** [comment]
Each task generator can provide its own settings and there will be a rebuild if the flags change:

```python
tg=bld.program(..., source='foo.flex')
tg.env.append_value('FLEXFLAGS', ...)
```

If you are after something more convenient, try example:

```python
bld(features='c cprogram', sources='foo.flex main.c', flexpath='/opt')

from waflib import TaskGen
@TaskGen.feature('c')
@TaskGen.before_method('process_source')
def add_P_for_flex(self):
    if getattr(self, 'flexpath'):
        self.env.append_value('FLEXFLAGS', '-P' + self.flexpath)
```

The drawback is that this requires a feature to be set (c, cxx, ...) and this increases the amount of methods to execute by default. If we added a `flex` feature we could do this, but then the task the declaration would require it.

**Comment by ita1024** [comment]
Try 954594bf0794094b90093154a96f4bfe867a8f62

**Comment by Whyki** [comment]
Works great, thanks!
