### ISSUE TITLE
gccdeps prints error

### ISSUE THREAD

**Issue by artiomn** [waf-project/waf#1784]
`from d:\repos\third-party\openssl: Load gccdeps in configure!`

```python
def scan(self):
	if not self.__class__.__name__ in self.env.ENABLE_GCCDEPS:
		if not self.env.GCCDEPS:
			self.generator.bld.fatal('Load gccdeps in configure!')
		return super(self.derived_gccdeps, self).scan()
```

I build by msvc, but load gccdeps in a separate environment (via ctx.setenv and my environment loader), where variable GCCDEPS isn't set.
Could you remove this check (moreover, msvcdeps hasn't similar check)?

**Comment by ita1024** [comment]
Sure, this verification is unnecessary now.
