### ISSUE TITLE
[Question] How to post into waf-users mail list

### ISSUE THREAD

**Issue by paulobrizolara** [waf-project/waf#1787]
First, i am sorry for posting this here, but since i could not post to the mail list (and that is the problem),
i did not know where else i could make this question.

I would like to know what is needed to post a message to the waf-users mail list.
I have been watching the list for a while, and i believe that i already joined the group,
since i receive the emails and no 'join group' button appears on google groups interface.
However, when i tried to send a message to the list (about a little tool i am doing related to waf),
i received an error response from 'mailer-daemon@google.com' saying:

           We're writing to let you know that the group you tried to contact (waf-users) may not exist, or you may not have permission to post messages to the group.
           ...

So, there is something else i should do? (i saw the list is moderated and thought this may be related to that)

Sorry if i missed something and thanks for your help

**Comment by ita1024** [comment]
Advertisement messages can get flagged as spam. Do not advertise or post links that advertise products or external projects, thanks.

**Comment by paulobrizolara** [comment]
I understand your point. 
But, please, notify (and dialogue) before flagging a message as spam or blocking anyone. 
Because, like me, others would not even know that they were blocked.

In my case, i was not trying to advertise anything, but just share something that i thought other waf users could consider useful.
And know looks like i cannot post anything on the list.
And i did not even had the chance to explain myself.
