### ISSUE TITLE
[Not a bug] Spam to console with logger redefined

### ISSUE THREAD

**Issue by artiomn** [waf-project/waf#1788]
You've uncommented lines 323-324 in the Context.py:

```python
		if self.logger:
			self.logger.info(cmd)
```

And now, with standard python logger, all commands are printed to console.
It's annoying and make the build slower.
Could you change it to the logger.debug, for example?

**Comment by ita1024** [comment]
I do not believe that I have uncommented anything recently, yet, we need these commands in the configuration logs (`config.log`). Are you sure that a logger is what you need? The extension [build_logs](https://github.com/waf-project/waf/blob/master/waflib/extras/build_logs.py) is sometimes enough.

**Comment by artiomn** [comment]
I know about build_logs.
But I need define my own logger, because I want to write logs in separate files with names, based on command, date and time.
If it's not correct use case, for which purposes needs logger?

**Comment by ita1024** [comment]
The logger is commonly use to keep track of the build in the `config.log` file. The command-lines are definitely worth logging, so it may be that your logger should avoid logging on the info level.
