### ISSUE TITLE
check_python_module ignores PYTHONPATH

### ISSUE THREAD

**Issue by vedranmiletic** [waf-project/waf#1791]
Observed in ns-3 regarding locating pybindgen. I can provide patches for ns-3-dev to be testable with both Waf 1.8 and 1.9 if needed.

This is a regression, bisected down to:

> commit 8207a878a96b19a9d5592e18af4844bdc499427f
> Author: Thomas Nagy
> Date:   Thu Feb 25 20:03:07 2016 +0100
> 
>     Enable multiprocessing for faster subprocess execution

I was weirded out too, so I double checked. It is that commit.

**Comment by ita1024** [comment]
The `pybindgen` detection is in `ns-3`, not in waf, so there is not much we can do here.

**Comment by ita1024** [comment]
In `demos/python`, try changing the detection of `pygccxml` to `spam`, build the project once so that the `spam.so` file is created, then compare the outputs of these commands:

```sh
$ waf configure
$ PYTHONPATH=$PWD/build waf configure
```

You will see that `PYTHONPATH` *is* definitely used.

**Comment by vedranmiletic** [comment]
Would you mind trying the following:

 $ hg clone http://code.nsnam.org/ns-3-allinone
 $ cd ns-3-allinone
 $ ./download.py
 $ cd ns-3-dev
 $ wget https://waf.io/waf-1.9.1
 $ chmod +x waf-1.9.1

Apply the following patch to ns-3-dev: https://gist.github.com/vedranmiletic/269f3c86fc42d3e7df0daf6958ff50d1

Then compare:

 $ ./waf configure
 $ ./waf-1.9.1 configure

It will exit at "Checking for python module 'pybindgen'".

**Comment by ita1024** [comment]
Sorry, but that's way too complicated (and mercurial is currently broken on my system). Please provide a simple testcase.

As mentioned above, PYTHONPATH is not ignored.

**Comment by vedranmiletic** [comment]
I am still figuring how to minimize this. In the meantime I modified PYTHON_MODULE_TEMPLATE to add:

```
from os import getenv
print(getenv('PYTHONPATH'))

```

and found out that conf.check_python_module() call in 1.8 gives correct path, while with 1.9 it is empty. We add the path for pybindgen by modifying os.environ['PYTHONPATH'], is that correct?

**Comment by vedranmiletic** [comment]
Nailed it. Please try `./waf configure` in `demos/python ` in 1.8 and 1.9 with the following patch:

```
diff --git a/demos/python/wscript b/demos/python/wscript
index 2a19877..1a3984b 100644
--- a/demos/python/wscript
+++ b/demos/python/wscript
@@ -3,6 +3,8 @@
 # Gustavo Carneiro, 2007
 
 import sys
+import os
+from waflib import Logs
 
 VERSION='0.0.1'
 APPNAME='python_test'
@@ -15,10 +17,12 @@ def options(opt):
        opt.load('compiler_c')
 
 def configure(conf):
+       conf.logger = Logs.make_logger("config.log", 'cfg')
        conf.load('compiler_c')
        conf.load('python')
        conf.check_python_version((2,4,2))
        conf.check_python_headers()
+       os.environ['PYTHONPATH'] = 'whatever/is/here/and/should/appear/in/output'
 
        conf.check_python_module('os')
        conf.check_python_module('re', condition="ver > num(2,0,4) and ver <= num(2,3,0)")
diff --git a/waflib/Tools/python.py b/waflib/Tools/python.py
index c9d0afc..bdea3fa 100644
--- a/waflib/Tools/python.py
+++ b/waflib/Tools/python.py
@@ -521,6 +521,10 @@ def check_python_version(conf, minver=None):
                conf.fatal('The python version is too old, expecting %r' % (minver,))
 
 PYTHON_MODULE_TEMPLATE = '''
+from os import getenv
+print("PATH WILL BE HERE")
+print(getenv('PYTHONPATH'))
+print("PATH WILL END HERE")
 import %s as current_module
 version = getattr(current_module, '__version__', None)
 if version is not None:
```

**Comment by ita1024** [comment]
Setting `os.environ` in this manner does not affect already-started programs.

Try the following:
```python
from waflib import Utils
# after modifying values in os.environ:
Utils.process_pool.clear()
# or to disable pre-forked process execution (slower builds):
Utils.run_process = Utils.run_regular_process
```

**Comment by vedranmiletic** [comment]
Verified as working. Thank you!

**Comment by ita1024** [comment]
This will be in version 1.9.2
