### ISSUE TITLE
cross compile, could not determine the compiler type

### ISSUE THREAD

**Issue by lianghuaxu** [waf-project/waf#1792]
hi all 
i use waf 1.6.11 (a7e69d6b81b04729804754c4d5214da063779a65).

ecently, i used the glmark2 (ver: glmark2-2014-03) source code to cross compile for my TI platform system on GPU evaluation, i followed the steps on doc INSTALL under top directory /glmark2, i have added my CROSS-COMPILER path to the environment variable $PATH, the prompts on my host terminal here :
<<
ubuntu@desktop:~/ti/glmark2/glmark2$ ./waf configure --with-flavors=drm-glesv2 --data-path=/home/ubuntu/ti/glmark2/glmark2/data
 Setting top to : /home/ubuntu/ti/glmark2/glmark2
Setting out to : /home/ubuntu/ti/glmark2/glmark2/build
Checking for 'gcc' (c compiler) : not found
Checking for 'icc' (c compiler) : not found
could not configure a c compiler!
(complete log in /home/ubuntu/ti/glmark2/glmark2/build/config.log)
>>
error message gcc compiler can't be found, while i opened the /glmark2/build/config.log:
------------------------------
....
Checking for 'gcc' (c compiler)
find program=['gcc', 'cc'] paths=['/home/ubuntu/ti/ti-glsdk_dra7xx-evm_7_04_00_03/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/arm-linux-gnueabihf/bin', '/usr/lib/lightdm/lightdm', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/games'] var='CC' -> '/home/ubuntu/ti/ti-glsdk_dra7xx-evm_7_04_00_03/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/arm-linux-gnueabihf/bin/gcc'
from /home/ubuntu/ti/glmark2/glmark2: Could not determine the compiler type
not found
.....
-------------------------------
it seems the waf tool can recognize the CROSS-COMPILER for my ti platform, it is tool chains gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux;
anybody meet this, plz give me some hint, very appreciate the help.

BR
lianghua

**Comment by ita1024** [comment]
That compiler is not gcc and it does not behave like gcc; it most likely fails to set the `__GNUC__` macro.

The version 1.6 is a rather old Waf version, but a few approaches are worth trying. Try for example to find the file `waflib/Tools/c_config.py` under the hidden `.waf-...` directory and comment the relevant 2 lines of code in the function `def get_cc_version`. Can you do that?

**Comment by lianghuaxu** [comment]
hi ita1024
     very appreciate your reply.
there are some informations let me explain, my target system is a TI chipset which arm Cortex-A15, OS linux3.14, I want use project "glmark2" to evaluate the GPU. so i download this source code from open source web https://github.com/glmark2/glmark2; the project based on waf version 1.6.11.
#Q1:find the file waflib/Tools/c_config.py under the hidden .waf-... directory and comment the relevant 2 lines of code in the function def get_cc_version. Can you do that?_
### # I can find this file c_config.py:
<<<
def get_cc_version(conf,cc,gcc=False,icc=False):
	cmd=cc+['-dM','-E','-']
	env=conf.env.env or None
	try:
		p=Utils.subprocess.Popen(cmd,stdin=Utils.subprocess.PIPE,stdout=Utils.subprocess.PIPE,stderr=Utils.subprocess.PIPE,env=env)
		p.stdin.write('\n')
		out=p.communicate()[0]
	except:
		conf.fatal('Could not determine the compiler version %r'%cmd)
	if not isinstance(out,str):
		out=out.decode(sys.stdout.encoding)
	if gcc:
		if out.find('__INTEL_COMPILER')>=0:
			conf.fatal('The intel compiler pretends to be gcc')
		if out.find('__GNUC__')<0:
			conf.fatal('Could not determine the compiler type')
	if icc and out.find('__INTEL_COMPILER')<0:
		conf.fatal('Not icc/icpc')
	k={}
	if icc or gcc:
		out=out.split('\n')
		for line in out:
			lst=shlex.split(line)
			if len(lst)>2:
				key=lst[1]
				val=lst[2]
				k[key]=val
		def isD(var):
			return var in k
		def isT(var):
			return var in k and k[var]!='0'
		if not conf.env.DEST_OS:
			conf.env.DEST_OS=''
		for i in MACRO_TO_DESTOS:
			if isD(i):
				conf.env.DEST_OS=MACRO_TO_DESTOS[i]
				break
		else:
			if isD('__APPLE__')and isD('__MACH__'):
				conf.env.DEST_OS='darwin'
			elif isD('__unix__'):
				conf.env.DEST_OS='generic'
		if isD('__ELF__'):
			conf.env.DEST_BINFMT='elf'
		elif isD('__WINNT__')or isD('__CYGWIN__'):
			conf.env.DEST_BINFMT='pe'
			conf.env.LIBDIR=conf.env['PREFIX']+'/bin'
		elif isD('__APPLE__'):
			conf.env.DEST_BINFMT='mac-o'
		if not conf.env.DEST_BINFMT:
			conf.env.DEST_BINFMT=Utils.destos_to_binfmt(conf.env.DEST_OS)
		for i in MACRO_TO_DEST_CPU:
			if isD(i):
				conf.env.DEST_CPU=MACRO_TO_DEST_CPU[i]
				break
		Logs.debug('ccroot: dest platform: '+' '.join([conf.env[x]or'?'for x in('DEST_OS','DEST_BINFMT','DEST_CPU')]))
		if icc:
			ver=k['__INTEL_COMPILER']
			conf.env['CC_VERSION']=(ver[:-2],ver[-2],ver[-1])
		else:
			conf.env['CC_VERSION']=(k['__GNUC__'],k['__GNUC_MINOR__'],k['__GNUC_PATCHLEVEL__'])
	return k
>>> 
### i am not familiar with Python's syntax, so i don't know from where to comment the relevant 2lines to get rid get_cc_version check. and i am still afraid  some env information like conf.env.DEST_OS, will lost.
## #Q2: yesterday, I reconfigure this "glmak2" like this on my host PC:
ubuntu@desktop:~/ti/glmark2/glmark2$ export PATH=/home/ubuntu/ti/ti-glsdk_dra7xx-evm_7_04_00_03/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin:$PATH
ubuntu@desktop:~/ti/glmark2/glmark2$ ./waf configure --with-flavors=drm-gl ## --check-c-compiler=arm-linux-gnueabihf-gcc --check-cxx-compiler=arm-linux-guneabihf-g++ 
Setting top to                           : /home/ubuntu/ti/glmark2/glmark2 
Setting out to                           : /home/ubuntu/ti/glmark2/glmark2/build 
Checking for 'arm-linux-gnueabihf-gcc' (c compiler) : not found 
could not configure a c compiler!
(complete log in /home/ubuntu/ti/glmark2/glmark2/build/config.log)
.....

## **and the config.log :**
----------------------------------------------------------------------------------------------
Setting out to 
home/ubuntu/ti/glmark2/glmark2/build
---------------------------------------------------
Checking for 'arm-linux-gnueabihf-gcc' (c compiler)
from /home/ubuntu/ti/glmark2/glmark2: Could not load the Waf tool 'arm-linux-gnueabihf-gcc' from '/home/ubuntu/ti/glmark2/glmark2', '/home/ubuntu/ti/glmark2/glmark2', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PIL', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/ubuntuone-client', '/usr/lib/python2.7/dist-packages/ubuntuone-control-panel', '/usr/lib/python2.7/dist-packages/ubuntuone-couch', '/usr/lib/python2.7/dist-packages/ubuntuone-installer', '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol' (try the --download option?):
No module named arm-linux-gnueabihf-gcc
not found
from /home/ubuntu/ti/glmark2/glmark2: could not configure a c compiler!
-----------------------------------------------------------------------------------------------------
i can't understand why waf don't search the compiler "arm-linux-gnueabihf-gcc" &"arm-linux-gnueabihf-g++" under directory /home/ubuntu/ti/ti-glsdk_dra7xx-evm_7_04_00_03/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin, that I have added to environment variable $PATH. it seems the waf have it's own path to check the compiler. while my cross compiler for c, c++ are under the directory /home/ubuntu/ti/ti-glsdk_dra7xx-evm_7_04_00_03/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin, named  "arm-linux-gnueabihf-gcc" &"arm-linux-gnueabihf-g++"; 
**could you plz tell how the waf check the compiler's information when cross compiler don't name "gcc", and "g++";**
thank you.

**Comment by lianghuaxu** [comment]
hi ita1024
very appreciate your reply.
there are some informations let me explain, my target system is a TI chipset which arm Cortex-A15, OS linux3.14, I want use project "glmark2" to evaluate the GPU. so i download this source code from open source web https://github.com/glmark2/glmark2; the project based on waf version 1.6.11.
#Q1:find the file waflib/Tools/c_config.py under the hidden .waf-... directory and comment the relevant 2 lines of code in the function def get_cc_version. Can you do that?_
# I can find this file c_config.py:

<<<
def get_cc_version(conf,cc,gcc=False,icc=False):
cmd=cc+['-dM','-E','-']
env=conf.env.env or None
try:
p=Utils.subprocess.Popen(cmd,stdin=Utils.subprocess.PIPE,stdout=Utils.subprocess.PIPE,stderr=Utils.subprocess.PIPE,env=env)
p.stdin.write('\n')
out=p.communicate()[0]
except:
conf.fatal('Could not determine the compiler version %r'%cmd)
if not isinstance(out,str):
out=out.decode(sys.stdout.encoding)
if gcc:
if out.find('INTEL_COMPILER')>=0:
conf.fatal('The intel compiler pretends to be gcc')
if out.find('__GNUC')<0:
conf.fatal('Could not determine the compiler type')
if icc and out.find('__INTEL_COMPILER')<0:
conf.fatal('Not icc/icpc')
k={}
if icc or gcc:
out=out.split('\n')
for line in out:
lst=shlex.split(line)
if len(lst)>2:
key=lst[1]
val=lst[2]
k[key]=val
def isD(var):
return var in k
def isT(var):
return var in k and k[var]!='0'
if not conf.env.DEST_OS:
conf.env.DEST_OS=''
for i in MACRO_TO_DESTOS:
if isD(i):
conf.env.DEST_OS=MACRO_TO_DESTOS[i]
break
else:
if isD('APPLE')and isD('MACH'):
conf.env.DEST_OS='darwin'
elif isD('unix'):
conf.env.DEST_OS='generic'
if isD('ELF'):
conf.env.DEST_BINFMT='elf'
elif isD('WINNT')or isD('CYGWIN'):
conf.env.DEST_BINFMT='pe'
conf.env.LIBDIR=conf.env['PREFIX']+'/bin'
elif isD('APPLE'):
conf.env.DEST_BINFMT='mac-o'
if not conf.env.DEST_BINFMT:
conf.env.DEST_BINFMT=Utils.destos_to_binfmt(conf.env.DEST_OS)
for i in MACRO_TO_DEST_CPU:
if isD(i):
conf.env.DEST_CPU=MACRO_TO_DEST_CPU[i]
break
Logs.debug('ccroot: dest platform: '+' '.join([conf.env[x]or'?'for x in('DEST_OS','DEST_BINFMT','DEST_CPU')]))
if icc:
ver=k['INTEL_COMPILER']
conf.env['CC_VERSION']=(ver[:-2],ver[-2],ver[-1])
else:
conf.env['CC_VERSION']=(k['__GNUC'],k['GNUC_MINOR'],k['GNUC_PATCHLEVEL'])
return k  
          **i am not familiar with Python's syntax, so i don't know from where to comment the relevant 2lines to get rid get_cc_version check. and i am still afraid some env information like conf.env.DEST_OS, will lost.**

            #Q2: yesterday, I reconfigure this "glmak2" like this on my host PC:
`            ubuntu@desktop:~/ti/glmark2/glmark2$ export PATH=/home/ubuntu/ti/ti-glsdk_dra7xx-evm_7_04_00_03/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin:$PATH
            **ubuntu@desktop:~/ti/glmark2/glmark2$ ./waf configure --with-flavors=drm-gl --check-c-compiler=arm-linux-gnueabihf-gcc --check-cxx-compiler=arm-linux-guneabihf-g++**
            Setting top to : /home/ubuntu/ti/glmark2/glmark2
            Setting out to : /home/ubuntu/ti/glmark2/glmark2/build
            Checking for 'arm-linux-gnueabihf-gcc' (c compiler) : not found
            could not configure a c compiler!
            (complete log in /home/ubuntu/ti/glmark2/glmark2/build/config.log)
            .....
  `

and the config.log :

Setting out to
home/ubuntu/ti/glmark2/glmark2/build

Checking for 'arm-linux-gnueabihf-gcc' (c compiler)
from /home/ubuntu/ti/glmark2/glmark2: Could not load the Waf tool 'arm-linux-gnueabihf-gcc' from '/home/ubuntu/ti/glmark2/glmark2', '/home/ubuntu/ti/glmark2/glmark2', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PIL', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/ubuntuone-client', '/usr/lib/python2.7/dist-packages/ubuntuone-control-panel', '/usr/lib/python2.7/dist-packages/ubuntuone-couch', '/usr/lib/python2.7/dist-packages/ubuntuone-installer', '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol' (try the --download option?):
No module named arm-linux-gnueabihf-gcc
not found
from /home/ubuntu/ti/glmark2/glmark2: could not configure a c compiler!

i can't understand why waf don't search the compiler "arm-linux-gnueabihf-gcc" &"arm-linux-gnueabihf-g++" under directory /home/ubuntu/ti/ti-glsdk_dra7xx-evm_7_04_00_03/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin, that I have added to environment variable $PATH. it seems the waf have it's own path to check the compiler. while my cross compiler for c, c++ are under the directory /home/ubuntu/ti/ti-glsdk_dra7xx-evm_7_04_00_03/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin, named "arm-linux-gnueabihf-gcc" &"arm-linux-gnueabihf-g++";
**could you plz tell how the waf check the compiler's information when cross compiler don't name** "gcc", and "g++";
thank you.

**Comment by ita1024** [comment]
The option `--check-cxx-compiler=` can be used when there is a corresponding waf extension to detect a particular compiler. Since you do not have such extensions, you cannot use them.

Setting the variables CC and CXX and removing the two lines suggested would work, but that is not something you can do at this time.

Since this is not a Waf matter and cannot use the information above, you should ask support to the author of the project in question.
