### ISSUE TITLE
Parallel configure?

### ISSUE THREAD

**Issue by haasn** [waf-project/waf#1793]
```./waf configure``` doesn't seem to be affected by `--jobs`, even though it could be easily parallelized (in principle) by running all of the checks in parallel.

As it stands, configuring a project can take considerably longer than building the project itself. Would it be possible to add support for parallel configuration to waf?

**Comment by ita1024** [comment]
We have had that for a while, see for example
https://github.com/waf-project/waf/blob/master/demos/c/wscript#L38

Yet, this did not catch up as parallel configurations seems to make the code more complicated to reason about :-/

**Comment by haasn** [comment]
Hmm. I think the parallelism I am looking for here is on a level higher than that. To use a specific example of a wscript that is sluggish to configure:

https://github.com/mpv-player/mpv/blob/master/wscript

Every single feature pretty much just has 1 check associated with it, so the multicheck doesn't seem to be applicable (as it would only allow parallelizing multiple checks at the same time for the same feature, as I understand it)

The parallelism here would need to come from `ctx.parse_dependencies()`, which is iterating through the dependencies in a simple loop:

```
    [__check_dependency__(ctx, dependency) for dependency in dependencies]
```

Parallelizing this loop would achieve the desired speedup for this wscript.

**Comment by ita1024** [comment]
The code from multicheck can be re-used quite easily though. The current implementation uses an instance of [cfgtask](https://github.com/waf-project/waf/blob/master/waflib/Tools/c_config.py#L1245), and though overriding/replacing the task might be necessary at this time, it should be sufficient to specify the configuration method to use, for example [conf.test](https://github.com/waf-project/waf/blob/master/waflib/Configure.py#L607) or a method based on [conf.run_build](https://github.com/waf-project/waf/blob/master/waflib/Configure.py#L508) depending on the level of abstraction desired.

There is not much time for diving into the details of the mpv scripts, but you are stuck, prepare a small example in a similar form as the [example above](https://github.com/waf-project/waf/blob/master/demos/c/wscript#L38).

**Comment by ita1024** [comment]
I guess it is not urgent after all. Support for arbitrary build/configuration tests was prepared, update your copy to 7d3ddac8609597957c943d30e946c7b8d9ecdc5c

https://github.com/waf-project/waf/blob/master/demos/c/wscript#L38

**Comment by haasn** [comment]
I'm giving it a try, but `ctx.multicheck` doesn't seem to do the job properly for me. My steps are as follows.

First, I just ported over the working logic of the `parse_dependencies` function so I could try parallelizing it:
```
def configure(ctx):
    ...
    def __check_dep__(dep):
        return Dependency(ctx, ctx.known_deps, ctx.satisfied_deps, dep).check

    [__check_dep__(d)() for d in build_options]
```

This works fine. Now, I tried using `ctx.multicheck` to run it in parallel:

```
    #[__check_dep__(d)() for d in build_options]
    ctx.multicheck(*[{'func': __check_dep__(d)} for d in build_options])
```

This does not work: I just see
```
Executing 17 configuration tests                                  : no 
One of the tests has failed, read config.log for more information
(complete log in /home/nand/dev/mpvhq/build/config.log)
```

Looking at the way build_options works, it seems to treat a “disabled” option as a “failed” check, which somehow trips ctx.multicheck into thinking that the entire group (and therefore, the build) has failed as a result.

How would you rewrite this to make it work the way I expected it to? For reference, I was planning on extending it like this to check all features of all groups in parallel:

```
    def multi_dependencies(*groups):
        def __check_dep__(dep):
            return Dependency(ctx, ctx.known_deps, ctx.satisfied_deps, dep).check

        checks = []
        for group in groups:
            checks += [__check_dep__(dependency) for dependency in group]

        ctx.multicheck(*[{'func': c} for c in checks])

    multi_dependencies(build_options,
                       main_dependencies,
                       audio_output_features,
                       video_output_features,
                       libav_dependencies,
                       hwaccel_features,
                       radio_and_tv_features)
```

**Comment by haasn** [comment]
fwiw, I also tried something like this:

```
    def multi_dependencies(*groups):
        def __check_dep__(dep):
            Dependency(ctx, ctx.known_deps, ctx.satisfied_deps, dep).check()

        threads = []
        for group in groups:
            threads += [Thread(target=__check_dep__, args=(dependency,))
                        for dependency in group]

        [t.start() for t in threads]
        [t.join()  for t in threads]
```

But the issue here is that all of the exceptions just get dumped onto stderr instead of being caught by waf

**Comment by ita1024** [comment]
That is not how it works, Threads should not be added (there are no threads in the example provided).

In order to *see* something in the outputs, each test must provide `msg/okmsg/errmsg` just as in the example.

If one test is optional, then `'mandatory': False` should be added.

**Comment by haasn** [comment]
Well, I tried this as well:

```
build_options = [
    {
        'name': '--cplayer',
        'desc': 'mpv CLI player',
        'default': 'enable',
        'func': check_true
    }, {
    ...
    }, {
        'name': '--html-build',
        'desc': 'html manual generation',
        'func': check_ctx_vars('RST2HTML'),
        'default': 'disable',
    }, {
    ...
    }

def configure(ctx):
    ....
    ctx.multicheck(*build_options)
```

with the same result

> If one test is optional, then 'mandatory': False should be added.

I can see why this would be the case, but what I'm curious about is this: why does it work fine when using `Dependency().check()` instead of `ctx.multicheck`?

**Comment by ita1024** [comment]
Each entry should provide `msg/okmsg/errmsg` entries. There is none in the output that you just pasted. Please follow the example as written in `demos/c/wscript`.

I am not the author of `Dependency().check()` and I have no idea how it works.

**Comment by haasn** [comment]
> I am not the author of Dependency().check() and I have no idea how it works.

Oh, well that would explain why we're having such difficulties communicating - I thought that was some function from waf.

**Comment by ita1024** [comment]
There are two levels of optional tests:
https://github.com/waf-project/waf/blob/master/demos/c/wscript#L46

The example was updated and the error reporting was improved so you should update your copy.
