### ISSUE TITLE
Question: Determine configured compiler 

### ISSUE THREAD

**Issue by GameMonkey** [waf-project/waf#1796]
Is it possible for me in Waf to access the values stored in the build.config? For example through ConfigSet?

Thanks
- Martin Kristjansen

**Comment by ita1024** [comment]
What do you mean by build.config?

**Comment by GameMonkey** [comment]
I mean the `build.config.py` that is created when `waf configure` has been run.
```
$ tree -a
|-- build_directory/ 
|   |-- c4che/ 
|   |   |-- build.config.py 
....
``` 

I am using a tool that automatically locates and chooses a compiler based on the OS and its available compilers. During the build I need to read precompiled libraries so I need to know which OS and compiler is in use. I can get the OS through `waflib.Utils` but I can see the loaded compiler is saved/noted in the `build.config.py`. So is there a way for me to access the values in `build.config.py` or would you suggest another way to see which compiler has been loaded? 

Thanks

**Comment by ita1024** [comment]
Using the configured variables such as `bld.env.DEST_OS`, bld.env.DEST_CPU and `bld.env.CC_NAME` is probably a much better idea, but if reading that particular file is needed, load it like any particular configuration set:
https://github.com/waf-project/waf/blob/master/waflib/Scripting.py#L85

**Comment by GameMonkey** [comment]
It works perfectly for me to use `bld.env.CC_NAME` and `bld.env.DEST_CPU`.

Thanks for your help. I really appreciate it.
