### ISSUE TITLE
NAG Fortran compiler (6.1) invoked incorrectly

### ISSUE THREAD

**Issue by aradi** [waf-project/waf#1797]
With current waf (1.9.1, 1.9.2) I have problems to compile my project with the NAG Fortran compiler. When waf invokes the compiler, I get:

```
NAG Fortran Compiler Release 6.1(Tozai) Build 6106
Option error: Unrecognised option -o/home/aradi/volatile/wafbug/_build/test.f90.1.o
```

Apparently, the compiler requires a whitespace between the `-o` option and the target. Putting a whitespace after `-o` on the command indeed resolves the issue, but I don't know how to get waf to insert it when calling the compiler.

**Comment by ita1024** [comment]
Update your copy
7d60c897444c0c9a89694689fe2ed0c6200df914

**Comment by aradi** [comment]
It works perfectly! Thanks Thomas. :smiley:
