### ISSUE TITLE
qt5: qt > 5.7 detection problem due to needed -std flag

### ISSUE THREAD

**Issue by fedepell** [waf-project/waf#1798]
While trying a C++ qt5 project with qt5.7 (on Linux, binary precompiled from qt.io) waf configure is not able to compile the qt5 test program (huge amount of errors in config.log, obviously due to C++ standards).

After some tests the thing seems that from 5.7 on on compilation it is strictly needed to pass a -std=c++11 flag and then it will work. (everything remaining the same but with 5.6 works fine without)
This makes sense reading:

https://wiki.qt.io/New_Features_in_Qt_5.7

This can be of course accomplished on command line (ie. define CXXFLAGS) or should we do something automatic for this in qt5 tool (as it is done for -fPIC and -fPIE for example)? 

I can contribute and test in case.

Thanks!

**Comment by ita1024** [comment]
Try or adapt adea933f1adffa92fa1cdc67880262cbf86b7d44

**Comment by fedepell** [comment]
Thanks for feedback!

I'd add just also the test with std=c++11 and no fPIC/fPIE so we are working exactly as before, but with std flag. See PR #1800 .

Tested and works fine now!
