### ISSUE TITLE
make Waf only print what I tell it to

### ISSUE THREAD

**Issue by hmijail** [waf-project/waf#1799]
Looks like at its quietest, Waf always prints messages like "Waf: Entering directory ..."
I would want it to print() something in response to my commands, but without all those logging messages.
Is there a way to do so?

The context is that I want another tool to parse Waf's output. This would be simple if I could make Waf only print what I tell it to in my wscript.

**Comment by ita1024** [comment]
The message in question is to provide IDEs with the current directory so that error messages are parsed properly. Building with `waf clean build -pp` or `-ppp` provides other types of output, but if that is insufficient, override or replace the BuildContext methods such as `execute_build`

**Comment by ita1024** [comment]
Any update? This ticket will not remain open forever.

**Comment by hmijail** [comment]
I didn't know that any update was expected.

I wanted / hoped for something that could be used by the end-user, like some command-line flag, without having to learn the internals of waf and modify the wscript. So I ended up wrapping the Waf calls with grep or awk scripts.
