### ISSUE TITLE
Task unique ID

### ISSUE THREAD

**Issue by artiomn** [waf-project/waf#1801]
`TaskGen.__init__()` uses task id, based only on the source path.
But, if I override `create_compiled_task` method to create many tasks with different result files, it doesn't work:
```python
			# provide a unique id
			try:
				self.idx = self.bld.idx[self.path] = self.bld.idx.get(self.path, 0) + 1
```

Is it possible to fix uid generation, using not only source path, but also the destination?

**Comment by ita1024** [comment]
What do you mean by destination? Are you alluding to the _target_ name?

**Comment by artiomn** [comment]
Yes, target name.

**Comment by artiomn** [comment]
What about using target path in the idx generation?

**Comment by ita1024** [comment]
The `target` attribute is not always provided. Making such changes makes the code more complicated, and will not prevent collisions in many other cases. Given that a counter can easily be incremented on the user side (either as code or as a task generator method), we have decided to avoid making any change regarding this matter.
