### ISSUE TITLE
Typo on the waf.io homepage

### ISSUE THREAD

**Issue by tmose1106** [waf-project/waf#1804]
Hello, and sorry in advance if this is not the correct place to be posting an issue like this.

For quite a while now it has been bothering me that every time I go to look at the homepage on waf.io, I notice there is this typo, which I have highlighted below:

> "Take a __lot__ at the documentation and the examples and start creating multiplatform software in no time."

While this may seem like an insanely simple fix, I have noticed this typo for months. Things like this are what drive of users. So I ask that @waf-project / @ita1024 PLEASE make a repo with the source code for their website and/or the documentation. I think it would be benefical to the entire project to open source the website and/or documentation. 

Thanks you for your time.

**Comment by ita1024** [comment]
Thanks for your report, the typo has been fixed.

The API documentation is already provided along the Waf source code. As for the website, it is provided as-is.
