### ISSUE TITLE
Task.exec_command fails to kill timed-out process

### ISSUE THREAD

**Issue by bjones1** [waf-project/waf#1807]
Per the Python docs [1] of [Popen.communicate](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate), "The child process is not killed if the timeout expires, so in order to cleanup properly a well-behaved application should kill the child process and finish communication." While `waf` does [recognize](https://github.com/waf-project/waf/blob/master/waflib/Context.py#L335) the `timeout` parameter, it doesn't provide the necessary cleanup code to kill timed-out processes. Again, quoting from the Python docs, that code is:

``` Python
proc = subprocess.Popen(...)
try:
    outs, errs = proc.communicate(timeout=15)
except TimeoutExpired:
    proc.kill()
    outs, errs = proc.communicate()
```

Would you incorporate this fix into `context.Context.exec_command`? Thanks!

[1] Except that the Python docs state [earlier](https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module) "If the timeout expires, the child process will be killed and waited for." On my platform (Windows 10, Python 3.5, waf 1.9.3) the child process is not killed.

**Comment by ita1024** [comment]
This will only work on very recent Python3 versions. Update your copy.

**Comment by bjones1** [comment]
Great! I can confirm that the timed-out processes are now correctly killed after your commit above. A minor suggestion: since the exception isn't re-raised, it's now difficult to diagnose the failure. Would you add a `raise` at the end of the `except` blocks to propagate this failure?

**Comment by bjones1** [comment]
Hmmm. On second thought, I'm also using the output from the process (`out` and `err`) for diagnostic information, and I don't want this lost either. Let me play a bit on my side to see what makes sense. Thanks again for your help.

**Comment by bjones1** [comment]
I added a `raise` in three places and that seems to work well for me. Would you like me to submit a pull request, or would you rather take care of it?

**Comment by ita1024** [comment]
Please provide a short testcase. This is not something we use a lot because it does not work on all Python interpreters.

**Comment by bjones1** [comment]
Will do! (When I can find a minute...)

**Comment by ita1024** [comment]
A description in a few lines would do, there is no need to make it complicated.

**Comment by ita1024** [comment]
I think the latest changes make sense, but re-open if you think something is not working and add a testcase.
