### ISSUE TITLE
Can't check signature: public key not found - WAF installation

### ISSUE THREAD

**Issue by jeriln** [waf-project/waf#1809]
I am trying to install WAF and all the time I get the same error public key not found. I am using Ubuntu 16.04. I first followed the download and installation from the WAF book, but it was saying no file named verify-sig.py. So I cloned the project form GitHub and done the same but this time I am getting the following error:
root@jeril-VirtualBox:~# waf/utils/verify-sig.py waf-1.9.3
-> 'gpg --verify waf-1.9.3-sig.asc'
gpg: assuming signed data in `waf-1.9.3-sig'
gpg: Signature made Sunday 21 August 2016 08:55:15 PM IST using RSA key ID 05277AAA
gpg: Can't check signature: public key not found

What might be the problem? Please help.

**Comment by ita1024** [comment]
The project public key is [linked from the project page](https://raw.githubusercontent.com/waf-project/waf/master/utils/pubkey.asc); it only needs to be imported by gnupg _once_ in your list of known public keys (`gpg --import file.pubkey`?).

**Comment by jeriln** [comment]
Okay. Thanks a lot
