### ISSUE TITLE
Restoring nodes from pickle changes their hash

### ISSUE THREAD

**Issue by tokrol** [waf-project/waf#1811]
I've noticed that first incremental build recompiles a lot of files completely unnecessarily with the reason: 'output node has no signature'. 
After some debugging I figured out that restoring nodes from DBFILE changes their hash (but this happens only at first restore and only to some files). After second build DBFILE has two entries for each node which got recompiled. All consecutive incremental builds work as expected.

Of course different hash makes it impossible for WAF to find the node's signature in bld.node_sigs.

I've added this to the Node class:
`	def __hash__(self):
		return int(hashlib.md5(self.abspath()).hexdigest(), 16)`

`	def __eq__(self, other):
		return self.abspath() == other.abspath()`
and it fixed the issue, but I guess the real problem is buried deeper and this is just a workaround.

I'm not even sure how to reproduce the issue. I'm building multiple products with WAF, all of them are built the same way and only one of them behaves like this. I don't see anything different about files which are behaving properly and those which are not with one exception: only .cpp and .cc files get recompiled (but still not all of them).

I can continue debugging to get to the root of the problem but I'd appreciate any ideas how to proceed as I'm not very familiar with WAF and python.

I'm using waf 1.9.3 and python 2.7.8 on Fedora21

Thanks

**Comment by ita1024** [comment]
Nothing in Waf uses such hashes for dependency calculation for this reason (they are not stable). Try raising exceptions in the methods that you implemented?

**Comment by ita1024** [comment]
If you felt the need to override `__eq__` it probably means that you tried mixing Node objects from distinct contexts. A Node object from a particular build context cannot be re-used in another build context or any other context object, so double-check your scripts.

**Comment by tokrol** [comment]
I've modified BuildContext.store() and BuildContext.restore() like this:
```
def restore(self):
	print('Restoring')
	[...]
	else:
		try:
			Node.pickle_lock.acquire()
			Node.Nod3 = self.node_class
			try:
				data = cPickle.loads(data)
--->			for node in sorted(data['node_sigs'], key=lambda node: node.abspath()):
--->				if node.name == 'Alarm.cpp.1.o':
--->					print(node.abspath(), hash(node), data['node_sigs'][node])
			except Exception , e:
				Logs.debug('build: Could not pickle the build cache %s: %r', dbfn, e)
	[...]
```
```
def store(self):
	print('Storing')
	[...]
	try:
		Node.pickle_lock.acquire()
		Node.Nod3 = self.node_class
		x = cPickle.dumps(data, PROTOCOL)
--->	for node in sorted(data['node_sigs'], key=lambda node: node.abspath()):
--->		if node.name == 'Alarm.cpp.1.o':
--->			print(node.abspath(), hash(node), data['node_sigs'][node])
	finally:
		Node.pickle_lock.release()
	[...]
```
All other WAF files are original, unmodified.

This is what I get during builds:
1st build, clean full build:
```
Restoring
Waf: Entering directory `/mnt/views/git/app/build/app'
[ full build here]
Storing
('/mnt/views/git/app/build/app/alarm/source/Alarm.cpp.1.o', 8750140985006, '\xb3M\t\x07z\xf18=\xfb\xfb!\xddk\xf4\x87\x80')
Waf: Leaving directory `/mnt/views/git/app/build/app'
'app' finished successfully (1m15.124s)
```
2nd build, incremental
```
Restoring
('/mnt/views/git/app/build/app/alarm/source/Alarm.cpp.1.o', -9223363250832359413, '\xb3M\t\x07z\xf18=\xfb\xfb!\xddk\xf4\x87\x80')
Waf: Entering directory `/mnt/views/git/app/build/app'
[ some files are recompiled here for no reason ]
Storing
('/mnt/views/git/app/build/app/alarm/source/Alarm.cpp.1.o', -9223363250832359413, '\xb3M\t\x07z\xf18=\xfb\xfb!\xddk\xf4\x87\x80')
('/mnt/views/git/app/build/app/alarm/source/Alarm.cpp.1.o', 8786022683297, '\xb3M\t\x07z\xf18=\xfb\xfb!\xddk\xf4\x87\x80')
Waf: Leaving directory `/mnt/views/git/app/build/app'
'app' finished successfully (36.255s)
```
3rd build, incemental
```
Restoring
('/mnt/views/git/app/build/app/alarm/source/Alarm.cpp.1.o', -9223363277099744410, '\xb3M\t\x07z\xf18=\xfb\xfb!\xddk\xf4\x87\x80')
('/mnt/views/git/app/build/app/alarm/source/Alarm.cpp.1.o', 8759754745275, '\xb3M\t\x07z\xf18=\xfb\xfb!\xddk\xf4\x87\x80')
Waf: Entering directory `/mnt/views/git/app/build/app'
Waf: Leaving directory `/mnt/views/git/app/build/app'
'app' finished successfully (5.964s)
```
I don't know, it looks like hashes are different every time, but 3rd build works properly anyway.
I think I'm looking at the wrong thing but still 2nd build restores the node but later it cannot be found and the second one is created so definitely something is wrong here.

**Comment by ita1024** [comment]
1. Waf does not use `hash()` or `__hash__` so you may be looking in the wrong place
2. If multiple Node objects corresponding to the same path are created, then you may want to check your scripts (multiple calls to low-level apis such as `make_node`?)
3. Double check if you get any warnings on `waf -v`

**Comment by tokrol** [comment]
Well I narrowed it down to a tool I wrote which generates a single cpp file. If I exclude it from my build everything works fine. 

It calls make_node on non existing cpp file and then, once the file is generated regular bld() is called to compile it. I don't know why this messes up other cpp files though. Anyway I'll rewrite it to generate this file and then call create_compiled_task() for it and add it to more_tasks. This should solve the issue.

Thanks for your help.

**Comment by tokrol** [comment]
Since the actual rootcause was different than what I suspected earlier I figured I'll update this issue one last time in case someone will have similar problem in the future.

As stated before the problem was caused by my custom cpp code generator. To fully understand what happened I'll have to describe it all, sorry :)

This generator creates a single cpp file. Let's call it log_defs.cpp.
log_defs.cpp is generated based on C headers, the same headers are also used in regular C++ code.
When I was creating generator task I put all those C headers on its inputs list. The problem was that I had to find all those headers first, so the log_defs.cpp gets regenerated if any header is changed, added or removed. All those headers are called [something]_logcode.h so naturally I used WAF's ant_glob() to find them easily and that's what caused the issue. ant_glob() calls make_node() and somehow that triggered recompiling of all source code which included those headers (that's why only C++ code was compiled, and not all of it).

I replaced ant_glob() with os.walk + fnmatch + find_node() to get a list of header nodes and now everything works properly.

**Comment by ita1024** [comment]
I tend to think that you called `ant_glob` on the build directory and somehow managed to ignore or suppress the warning on `waf -v` that says that it is dangerous.

**Comment by tokrol** [comment]
Yeah my ant_glob probably did recurse to build directory. There are no headers in there so I didn't expect this to be a problem, Anyway I'll try to create a small example reproducing the issue and I'll post it here once it's ready.

**Comment by ita1024** [comment]
I do not think that this is even necessary. Just make sure to avoid passing `remove=False` when processing the build directory and read the warnings produced by `waf -v` in the future
