### ISSUE TITLE
Utils.to_list doesn't support unicode strings

### ISSUE THREAD

**Issue by antoche** [waf-project/waf#1820]
Utils.to_list uses `isinstance(val, str)`, which returns `False` for unicode strings. As a result, `Utils.to_list( u'foo' )` returns `u'foo'` instead of `[ u'foo' ]`. 

It should be using `isinstance(val, basestring)`.

**Comment by antoche** [comment]
Doing a further grep through the code, there's quite a few other places this is happening (107 instances in 1.8.20).

**Comment by ita1024** [comment]
This is intentional: use Python3 for unicode support.
