### ISSUE TITLE
Executing code fragment in configure is broken

### ISSUE THREAD

**Issue by zberry** [waf-project/waf#1827]
Example 6 in section 10.4.1 of the waf book does not work. Waf returns the error "AttributeError: 'task_gen' object has no attribute 'link_task'"

Would like to know a workaround for this if possible

**Comment by ita1024** [comment]
Are you referring to this test?
```python
    conf.check_cc(fragment='''
          #include <stdio.h>
          int main() { printf("4"); return 0; } ''',
       define_name = "booeah",
       execute     = True,
       define_ret  = True,
       msg         = "Checking for something")
```

Try checking out the project and running it:
https://github.com/waf-project/waf/blob/book/docs/book/examples/cprog_conf/wscript#L14

**Comment by zberry** [comment]
It appears that changing the "compiler_c" to compiler_cxx causes it to break. 

Im on RHEL6 using GCC 4.4.7

**Comment by ita1024** [comment]
This is expected. If the tests are meant to be executed with the c++ compiler, use `check_cxx` not `check_cc`, or specify the exact features to use ("cxx cxxprogram" / "c cxxprogram").

**Comment by zberry** [comment]
I think I must have gotten that switched up in my implementation. Seems to be working now. Thanks for the help!
