### ISSUE TITLE
Question: support non-english msvc

### ISSUE THREAD

**Issue by artiomn** [waf-project/waf#1830]
What about support non-english MSVC?
CL.exe outputs messages on a native language (for example, on Russian):
```
cl: командная строка warning D9027: пропуск исходного файла "SDK\Include"
fse_compress.c
Примечание: включение файла:  C:\PROGRA~2\MICROS~1.0\VC\include\intrin.h
Примечание: включение файла:   C:\PROGRA~2\MICROS~1.0\VC\include\crtdefs.h
```

And waf (especially, some tools, like msvcdeps) crashes while converting messages from `ascii`.

**Comment by ita1024** [comment]
What about it? There is nothing we can do about this ticket so we will close this.

Please use the latest Waf version, and provide error messages and a way to reproduce the problem in future tickets such as testcases.
