### ISSUE TITLE
--zones=argfile doesn't work with msvcdeps

### ISSUE THREAD

**Issue by artiomn** [waf-project/waf#1831]
msvcdeps uses own `exec_command` with `cmd, args = self.split_argfile(cmd)`.
And --zones doesn't print commands (I think tests are not necessary, because it's easy to check).

P.S.:
Similar call is presented in javaw.py, but I don't use it.

**Comment by ita1024** [comment]
The file `javaw.py` is not concerned because it does not override `exec_command`.

**Comment by artiomn** [comment]
It works.
