### ISSUE TITLE
1.9 performance regression on large builds

### ISSUE THREAD

**Issue by cconverse711** [waf-project/waf#1833]
After upgrading from waf 1.8 to waf 1.9, I experienced a significant regression in performance on large builds. When using --profile (see profile report at bottom), I found that a large portion of the execution time was spent in c_preproc's cached_find_resource, much in stat calls.

It looks like this is a result of the LRU cache being used to cache nodes, which was added in 1.9. On large builds, the small cache causes a huge number of cache misses. For now I've monkey-patched cached_find_resource to get the old behavior (an unbounded cache by using a dict instead of the LRU cache), but it seems appropriate to directly patch c_preproc to allow the LRU cache size to be more easily configured (or to use an unbounded cache altogether). I can submit a pull request if you like. 

>     Tue Oct 11 07:08:16 2016    profi.txt
>
>               10034333605 function calls (9751501132 primitive calls) in 16420.840 seconds
>
>        Ordered by: internal time
>        List reduced from 3141 to 75 due to restriction <75>
>
>        ncalls  tottime  percall  cumtime  percall filename:lineno(function)
>     282853896 4400.528    0.000 4400.528    0.000 {nt.stat}
>     282682704 1328.192    0.000 12981.841    0.000 F:\Mainline\waf-1.9.3-eafa726abab2d1ba61c9ab9c6efe8d6e\waflib\Node.py:400(find_resource)
>     550165545 1059.205    0.000 14943.956    0.000 F:\Mainline\waf-1.9.3-eafa726abab2d1ba61c9ab9c6efe8d6e\waflib\Tools\c_preproc.py:458(cached_find_resource)
>     282654771  934.048    0.000 7832.760    0.000 F:\Mainline\waf-1.9.3-eafa726abab2d1ba61c9ab9c6efe8d6e\waflib\Node.py:149(find_node)
>     566135202/286326345  803.660    0.000  871.709    0.000 F:\Mainline\waf-1.9.3-eafa726abab2d1ba61c9ab9c6efe8d6e\waflib\Node.py:248(abspath)
>     282726669  789.661    0.000 1176.220    0.000 F:\Mainline\waf-1.9.3-eafa726abab2d1ba61c9ab9c6efe8d6e\waflib\Node.py:383(get_bld)
>     282651461  722.879    0.000 1076.938    0.000 F:\Mainline\waf-1.9.3-eafa726abab2d1ba61c9ab9c6efe8d6e\waflib\Node.py:369(get_src)
>     282656789  638.021    0.000 5033.400    0.000 C:\Python27\lib\genericpath.py:15(exists)
>     282656473  579.730    0.000 6482.869    0.000 F:\Mainline\waf-1.9.3-eafa726abab2d1ba61c9ab9c6efe8d6e\waflib\Node.py:96(exists)
>     282781816  511.532    0.000  511.532    0.000 {method 'split' of '_sre.SRE_Pattern' objects}
>     282739629  509.134    0.000  587.073    0.000 F:\Mainline\waf-1.9.3-eafa726abab2d1ba61c9ab9c6efe8d6e\waflib\Node.py:193(search_node)
>     553527231  505.693    0.000  505.693    0.000 F:\Mainline\waf-1.9.3-eafa726abab2d1ba61c9ab9c6efe8d6e\waflib\Utils.py:92(__getitem__)
>       7948574  426.653    0.000 15424.833    0.002 F:\Mainline\waf-1.9.3-eafa726abab2d1ba61c9ab9c6efe8d6e\waflib\Tools\c_preproc.py:477(tryfind)
>         49066  397.138    0.008  397.138    0.008 {method 'acquire' of 'thread.lock' objects}

**Comment by ita1024** [comment]
What is the optimal value of your LRU cache size? The current value was chosen after looking at a variety of workloads, and setting too high or too low values both have drawbacks.

How did the build times 1.8-1.9 compare after setting the unbounded cache size?

By the way, 800 seconds on `Node.abspath` looks like a real lot. Trying extensions such as msvcdeps.py or using Python 3.5 (for fast listdir) might ideas to try.

**Comment by cconverse711** [comment]
I'll have to get back to you on the optimal LRU cache size. Large builds are done on a beefy server where memory usage isn't an issue.

With the LRU cache size=1000, msvc builds take 4 to 4 1/2 hours, but the unbounded cache drops the build time to under 1 hour.

Node.abspath only accounts for less than 6 seconds with the unbounded cache, so I don't think that's a huge concern, but thanks for the suggestion -- I've been meaning to try out that extension.

**Comment by ita1024** [comment]
Using pre-forked processes might allow for bigger LRU cache sizes; can you try with a size of 10000 instead of 1000 for a start?

I am also curious to know the difference between 1.8 and 1.9 after you enabled the unbounded cache (https://waf.io/faster18-19.png).

**Comment by cconverse711** [comment]
The cache size of 10000 was still very slow, but 100k was about as fast as with an unbounded cache.  Pre-forked processes are used in 1.9 by default, right?

Comparing 1.8 against 1.9 with the unbounded cache, the build times appear to be equal. No huge gains, unfortunately.

**Comment by ita1024** [comment]
Pre-forked process should be enabled, so your builds are probably bound by the complexity of the build scripts and not so much by the amount of tasks to execute. The slow stats seem to indicate slow file system access, is the storage relying on spinning disks? Dependency resolution might still be a bottleneck, try to compare the build time after disabling dependency resolution completely by commenting the following line for example: https://github.com/waf-project/waf/blob/master/waflib/Tools/c_preproc.py#L1047

**Comment by cconverse711** [comment]
No, the storage is on an SSD. I tried disabling dependency resolution per your suggestion, but it didn't the build failed (I believe because some tasks generate code).

**Comment by ita1024** [comment]
I see, so your build seems to be a bit more involved than I imagined. Try commenting this line instead:
https://github.com/waf-project/waf/blob/master/waflib/Tools/cxx.py#L24

**Comment by ita1024** [comment]
Any update? Are the new constants sufficient for tuning the values in your builds?

**Comment by cconverse711** [comment]
Yes, thanks. Those new constants should do the trick.

**Comment by ita1024** [comment]
Lazy loading for the lru cache is necessary for configuration tests with such settings 8dae660ec71307a720503b75d757b9e1aee2f624
