### ISSUE TITLE
Unity tool doesn't work with MSYS2

### ISSUE THREAD

**Issue by jhasse** [waf-project/waf#1834]
The unity tool currently doesn't work with MSYS2. This has to do with Python from MSYS2 returns a Unix-like path, e. g. `/home/jhasse/project/file.cpp`, resulting in:

```
#include "/home/jhasse/project/file.cpp"
```

GCC from MinGW-w64 doesn't support that. Is it be possible that unity uses relative paths?

**Comment by ita1024** [comment]
Relative paths can fail in other contexts. Could you try that in your own project?

**Comment by jhasse** [comment]
Yes, I'll do that. Do you have any cases in mind where relative paths fail?

**Comment by ita1024** [comment]
If the build directory is setup on another drive then absolute paths may be necessary. Some testing will be necessary, but pull requests are welcome if you find the time to make one.

**Comment by jhasse** [comment]
I will work on one.

The following can be used to detect if the path is on another drive:

```python
try:
    path = os.path.relpath(abs_path, build_dir)
except ValueError:
    path = abs_path
```

**Comment by jhasse** [comment]
Okay using `node.path_from(self.outputs[0].parent)` instead of `node.abspath()` [in this line from unity.py](https://github.com/waf-project/waf/blob/f28426594ef296dac0b584dea66072d0cb7346bf/waflib/extras/unity.py#L26) works with MSYS2.

I will test later on a different machine which has multiple drives.

**Comment by ita1024** [comment]
Try the change above.

**Comment by jhasse** [comment]
Doesn't work unfortunately as the unity files are in a subfolder in my build directory `build/src/some_folder` but this way the includes seem to be added as relative to `build`.

**Comment by ita1024** [comment]
I failed, but now there is a test for it.

**Comment by jhasse** [comment]
Does the test work with `node.path_from(self.outputs[0].parent)`?

**Comment by ita1024** [comment]
Yes, update your copy.

**Comment by jhasse** [comment]
works, thanks :)
