### ISSUE TITLE
make_node concurrency issue?

### ISSUE THREAD

**Issue by Riziero** [waf-project/waf#1835]
I am using waf to run a custom compiler. When the compiler runs it may generate a number of output  files (whose names arent known beforehand) in the build folder (say D:\src\build). These outputs file are then used as input nodes for generating an other task that simply copies them over to an other folder (say D:\out).

The code is very very similar to the section "A compiler producing source files with names unknown in advance" that can be found in the waf book.

The system seems to be working fairly well expect for a WafError I randomly get in Node.py. 

Say I have an input file d:\scr\a\b\c.x, the compiler task will generate d:\scr\build\a\b\c.x, so in this context:

Then I create the task to copy the above in D:\out\a\b\c.x (not how I maintain the folder structure). Pseudo code (with file_path being d:\scr\build\a\b\c.x):

```
output_path = task_generator.bld.root.make_node(D:\out)
relative_path = file_path.parent.path_from(task_generator.bld.path)
output_node   = output_path.make_node(os.path.join(relative_path, os.path.basename(file_path.abspath())))
output_node.parent.mkdir()
tasks += [ task_generator.create_task('copy_outputs', file_path, output_node) ]
```

The third line (output_node=...) is the one that may randomly fail. When trying to create the node  D:\out\Objects\buildingsets\human\hightech\prop\box\box_0025x004x0025_a.cgf, a real case error is the following:

node **box** exists in the parent files d:\out\Objects\buildingsets\human\hightech\prop already

Effectively the node **box** may already exist. It could have been created by the same make_node call when creating the copy task for a an other file that happens to be in the same **box** folder.

Known facts:

- when I hit that, it seems to only be happening when creating the task to copy the compiled file with the same name of the source file. In general in fact c:\src\a\b.c will always create c:\src\build\a\b.c and potentially other files like c:\src\build\a\b_1.c c:\src\build\a\b_2.c and so forth.

- based on the documentaion, make_node should never fail as it should return a node if it does already exist. How can it possibly fail?

- Sometimes I do not hit this snag at all - I can generate all the tasks just ok and then run them.

Many thanks!

**Comment by ita1024** [comment]
The method `make_node` and the whole `Node` structure is not thread safe at all. This usually means that you have tasks that should not be executed in parallel or that your code is missing locks.

**Comment by Riziero** [comment]
Hi thanks for answering. That was exactly the problem.
