### ISSUE TITLE
How to add a library to a wscript ?

### ISSUE THREAD

**Issue by MatteoBertolino92** [waf-project/waf#1848]
I would like to add the c++ library cpp-netlib to a wscript.
Then if I run `dpkg -l libcppnetlib0` I obtain: 

`    libcppnetlib0: 0.11.0-1     amd64        C++ Network Library
`
Running: dpkg -L libcppnetlib0, I obtain:

   ```
 /.
    /usr
    /usr/lib
    /usr/lib/x86_64-linux-gnu
    /usr/lib/x86_64-linux-gnu/cppnetlib-uri.so.0.11.0
    /usr/lib/x86_64-linux-gnu/cppnetlib-server-parsers.so.0.11.0
    /usr/lib/x86_64-linux-gnu/cppnetlib-client-connections.so.0.11.0
    /usr/share
    /usr/share/lintian
    /usr/share/lintian/overrides
    /usr/share/lintian/overrides/libcppnetlib0
    /usr/share/doc
    /usr/share/doc/libcppnetlib0
    /usr/share/doc/libcppnetlib0/copyright
    /usr/share/doc/libcppnetlib0/changelog.Debian.gz
    /usr/lib/x86_64-linux-gnu/libcppnetlib-server-parsers.so.0
    /usr/lib/x86_64-linux-gnu/libcppnetlib-client-connections.so.0
    /usr/lib/x86_64-linux-gnu/libcppnetlib-uri.so.0

Since I need `libcppnetlib-uri, libcppnetlib-server-parsers, libcppnetlib-client-connections` , in the wscript I add the following fields:

    conf.check_cxx(lib='cppnetlib-uri',uselib_store='CPPNETLIBU', define_name='HAVE_CPPNETLIBU',mandatory=True)
    conf.check_cxx(lib='cppnetlib-server-parsers',uselib_store='CPPNETLIBS', define_name='HAVE_CPPNETLIBS',mandatory=True)
    conf.check_cxx(lib='cppnetlib-client-connections',uselib_store='CPPNETLIBC', define_name='HAVE_CPPNETLIBC',mandatory=True)
```

Then I added the three references `(CPPNETLIBU, CPPNETLIBC, CPPNETLIBS) `here:

   ```
 libndn_cxx = dict(
            target="ndn-cxx",
            name="ndn-cxx",
            source=bld.path.ant_glob('src/**/*.cpp',
                                     excl=['src/security/**/*-osx.cpp',
                                           'src/**/*-sqlite3.cpp']),
            headers='src/common-pch.hpp',
            use='version BOOST CRYPTOPP OPENSSL SQLITE3 RT PTHREAD CPPNETLIBC CPPNETLIBU CPPNETLIBS',
            includes=". src",
            export_includes="src",
            install_path='${LIBDIR}')
```

But, when I launch` ./waf configure`, it fails, it does not find the libraries that I specified.

The error is: 

```
[199/200] Linking build/examples/clientMat
    examples/clientMat.cpp.2.o: In function `construct<boost::network::http::impl::normal_delegate, asio::io_service&>':
    /usr/include/c++/4.9/ext/new_allocator.h:120: undefined reference to `boost::network::http::impl::normal_delegate::normal_delegate(asio::io_service&)'
    /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libcppnetlib-client-connections.so: undefined reference to `boost::system::system_category()'
    /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libcppnetlib-client-connections.so: undefined reference to `boost::system::generic_category()'
    collect2: error: ld returned 1 exit status
```

I (maybe?) identified the problem in the absence of any reference in` /usr/local/lib/pkgconfig`. Indeed, running: `ls /usr/local/lib/pkgconfig`, I have some `.pc` files but nothing about cppnetlib. I tried to write my own without success.

If the problem is here, actually I need an help about how to write the `.pc` files correctly.

Thank you for your help

**Comment by ita1024** [comment]
The problem seems unrelated to Waf, and I suspect that a dependency to the boost library `boost_system` is simply missing. I do not understand why you are trying to write .pc files as those are unnecessary.

Check the command-line settings by building "waf -v" and check that the library is present in the flags. If the boost libraries are static libraries, check that the order of the build flags is specified properly (in reverse order for ld). Try to write one single proper configuration test to link all required libraries at once instead of using three non-working ones :-)

**Comment by MatteoBertolino92** [comment]
Dear ita1024,
thank you. So is the syntax of my wscript correct, if I understood well?

Actually I did not follow very well your last sentence because of my poor knowledge about linkage&co, I just tried to link one of the three libraries, specifically CPPNETLIBC. I run waf -v. And the output is identical to the previous one. 

Regarding 

> I suspect that a dependency to the boost library` boost_system `is simply missing

It is possible, but when I launch `./waf configure --boost-includes=/usr/local/include --boost-libs=/usr/local/lib` I can read:
`Checking for cppnetlib-c: yes
 Checking boost includes: 1.59.0
 Checking boost libs: ok
 Checking for boost linkage: ok`

I know that if it is not a waf problem you are not supposed to help me, but I am absolutely not expert.. Have you got any idea?

Bests,
Matteo

**Comment by ita1024** [comment]
No, I have no idea. You need to learn more about how to use the compiler and the linker and understand which flags the linker might require (check the linker command and flags displayed upon running `waf -v`).

**Comment by xbreak** [comment]
@MatteoBertolino92, I think @ita1024 is right. You probably just need to add the missing boost libraries. Add the libraries with `conf.check_boost('system ...')`, c.f. the [playground example](/waf-project/waf/blob/master/playground/boost/wscript).

**Comment by MatteoBertolino92** [comment]
Thanks a lot, @ita1024  and @xbreak , I will surely try
