### ISSUE TITLE
Incorrect pydoc for ConfigSet.__delitem()

### ISSUE THREAD

**Issue by selsky** [waf-project/waf#1851]
```
                Dictionary interface: get value from key
```
Should be:
```
                Dictionary interface: delete item by key
```
or similar

**Comment by ita1024** [comment]
Fixed.

**Comment by selsky** [comment]
"set value from key" should be "set value for key"
"mark the value as missing" should be "mark the key as missing"

**Comment by ita1024** [comment]
I think this is fine, but if you want to fix the details then make a pull request.
