### ISSUE TITLE
ant_glob and single dot

### ISSUE THREAD

**Issue by antoche** [waf-project/waf#1853]
I've just found out through debugging that `bld.path.and_glob( 'path/to/files/./**' )` is not the same as `bld.path.and_glob( 'path/to/files/**' )`.

If also see that if I use '..' in the expression, I get a warning saying "'..' means 'two dots', not 'parent directory'", which is quite welcome. Could the same warning be emitted in cases where the expression starts with `./` or contains `/./`? I think it might help quite a few other unaware users.

**Comment by ita1024** [comment]
If this were an actual problem we would have received more requests over the years, but feel free to open a pull request.

**Comment by ita1024** [comment]
Nevermind

**Comment by antoche** [comment]
Hah, I pulled to start looking into that, and realized you'd already done it. Thanks!
