### ISSUE TITLE
Custom feature'd command

### ISSUE THREAD

**Issue by drahnr** [waf-project/waf#1855]
```
# extra target to fix code yada
import subprocess

from waflib import TaskGen, Task


class codestyle_cls(Task.Task):
        color = 'PINK'
        def run(self):
                print("yay!")
                node = self.inputs[0]
                cmd = "clang-format -i {}".format(node)
                subprocess.call(cmd, shell=False)
                return Task.SUCCESS




@TaskGen.feature('codestyle')
def post_codestyle_tsk(self):
        for node in self.to_list(getattr(self,'source', [])):
                tsk = self.create_task('codestyle_cls', node)


def clangfmt_fun(bld):
        nodes = bld.path.ant_glob('src/*.[ch]') + bld.path.ant_glob('src/*.[ch]pp')
        bld(features=['codestyle'], source=nodes)

class clangfmt(BuildContext):
        cmd = 'clangfmt'
        fun = 'clangfmt_fun'

```

Always results in `File path/yada.hpp has no mapping in <deque_reverse_iterator object at 0x7fadd9f2e470> (have you forgotten to load a waf tool?)`

I don't get what i am doing wrong exactly..

**Comment by ita1024** [comment]
The attribute 'source' is reserved for extension-based processing; choose another for your hpp or add a mapping for .hpp files that creates no task. See also extension-based processing in The Waf Book.

**Comment by drahnr** [comment]
I was aware of the extension based processing.

So how would I do this?

just adding `@TaskGen.feature('*')` as described in section 9.3.2 ?

**Comment by drahnr** [comment]
How can I make sure the task is then only run when I actually call `./waf codestyle` and not on configure

**Comment by ita1024** [comment]
No, Taskgen.extension('.hpp')

Check if bld.conf exists, from a task generator method such as post_codestyle_tsk: hasattr(self.bld, 'conf')

**Comment by drahnr** [comment]
Can I combine this with `TaskGen.feature('codestyle')` feature? Right now it would also pick up all the sources that I actually do not want to touch (third party lib in a subdir)

**Comment by ita1024** [comment]
I think you need to stop using the 'source' attribute for two unrelated purposes.

**Comment by drahnr** [comment]
The problem is that I do not realy want to pick up based on extension but based on the file list passed. And the extension based handling interferes with that.
I really just want to handle those files (no matter which extension) passed to `bld(features=[codestyle]`, source=....)`

**Comment by ita1024** [comment]
Then once again, stop using the 'source' attribute name because it has a very specific usage.

**Comment by drahnr** [comment]
```
import subprocess

from waflib import TaskGen, Task


class codestyle(Task.Task):
        color = 'PINK'
        def run(self):
                node = self.inputs[0]
                cmd = "clang-format -style=file -i {}".format(node.abspath())
                print("cmd:"+cmd)
                try:
                    	subprocess.call(cmd, shell=True)
                        return Task.SUCCESS
                except:
                       	return Task.CRASHED




@TaskGen.extension('.hpp')
def post_codestyle(self, node):
        tsk = self.create_task('codestyle', node)


def clangfmt_fun(bld):
        nodes = bld.path.ant_glob('src/*.[ch]') + bld.path.ant_glob('src/*.[ch]pp')
        bld(features=['codestyle'], source=nodes)
```

with an output of 


```
...
ls/c_preproc.py", line 605, in scan
    raise Errors.WafError('%r is missing a feature such as "c", "cxx" or "includes": '%task.generator)
WafError: bld(target='', idx=1, meths=['process_rule', 'process_source'], _name='', source=[/
posted=True, features=['codestyle']) in /media/pineapple/projects/CogniEvolution/B is missing a feature such as "c", "cxx" or "includes": 

```

**Comment by ita1024** [comment]
Correct. I do not understand your point.

**Comment by drahnr** [comment]
This does not work, with a different attribute than `source`, func `post_codestyle` will never be called.

**Comment by ita1024** [comment]
Could you not write post_codestyle_tsk without using the 'source' attribute?

**Comment by drahnr** [comment]
Would be bit clunky, but I guess I could.

**Comment by ita1024** [comment]
Clunky? You only need to rename 'source' to something else in two places in the initial snippet you posted.

**Comment by drahnr** [comment]
The difference is that I can't combine it anymore with the compilation steps anymore.

**Comment by ita1024** [comment]
Sure, you can have both but there are consequences.

And your method post_codestyle_tsk is not guaranteed to be processed before extension-based processing (before_method('process_source')

**Comment by drahnr** [comment]
Ok, so I guess it is not possible.

**Comment by ita1024** [comment]
The answer was already given in comment #2: the files given in `source` must have a mapping declared with `@TaskGen.extension`, or the name `source` should not be used at all.

**Comment by drahnr** [comment]
A follow up:

`return Task.SUCCESS` is failing the target where as `return 0` works.
