### ISSUE TITLE
Default python 3 interpreter for waf executable

### ISSUE THREAD

**Issue by antonlukyanov** [waf-project/waf#1856]
When building waf it is possible to specify with `--python` option python binary to be used. But it looks like it is used only for building process (though I might be wrong), because resulting executable contains python interpreter name in the following form: `#! /usr/bin/env python`. Is it possible to use waf with python 3 by default (`#! /usr/bin/env python3`)?

Possible solutions:

- Run waf directly with python 3 (`python3 waf`), but my executable lies in a separate folder: `~/path/to/waf/executable`. It would be rather inconvenient to write the full path or create an alias.
- Another option is placing executable bash script instead of waf itself in my `~/bin` folder:
    ```
    #!/usr/bin/env bash
    python3 /path/to/waf/executable/waf "$@"
    ```
- The third option is renaming default python interpreter, but it may break a lot of other things.

These possible solutions seem inconvenient to me and complicate the usage of waf since it would be a lot easier to produce waf executable with specified python interpreter through command line argument.

**Comment by ita1024** [comment]
Use the above ^^

**Comment by antonlukyanov** [comment]
Thanks for the quick response! This solved my issue.
