### ISSUE TITLE
Disable capture of stdout/stderr?

### ISSUE THREAD

**Issue by gjcarneiro** [waf-project/waf#1857]
Hello, I am trying to run a command that takes a while and would like to see output as it progresses.  It is a docker build command, along these lines:
```python
    bld(source=(["base.dockerfile", "some.hash"] +
                bld.path.ant_glob("*.py")),
        rule=("docker build -t foo -f ${SRC[0]} ../.."))
```

Is it possible to run this command without redirection? At least as an option, I'd prefer to just send normal output to the terminal.  While building a docker image it is important to get a feeling for where in the build it is taking long, so that you can optimise it.  Yes, I know that with parallel tasks this becomes messy, but...

**Comment by ita1024** [comment]
Here is one way of achieving that:

```python
from waflib import Task, TaskGen

@TaskGen.feature('force_stdout')
@TaskGen.after_method('process_rule')
def force_rule_stdout(self):
        tsk = self.tasks[-1]

        def exec_command(self, cmd, **kw):
                print "okay!"
                kw['stdout'] = kw['stderr'] = None
                return Task.Task.exec_command(self, cmd, **kw)
        tsk.__class__.exec_command = exec_command

def build(bld):
        bld(features='force_stdout', source='wscript', rule='ls -l ${SRC}', always=True)
```

**Comment by gjcarneiro** [comment]
Works perfectly, thanks!

**Comment by gjcarneiro** [comment]
I modified it slightly, from:
```python
     kw['stdout'] = kw['stderr'] = None
```
to:
```python
      if Logs.verbose > 0:
          kw['stdout'] = kw['stderr'] = None
```
So that redirection happens by default unless you run waf with -v.
