### ISSUE TITLE
Qt5 tool tries to link .dll.a files in non-existant C:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib/ dir

### ISSUE THREAD

**Issue by jhasse** [waf-project/waf#1858]
Using the Qt5 tool with MSYS2 I'm getting linker errors like:

```
g++.exe: error: C:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib/libQt5Gui.dll.a: No such file or directory
```

I think the folder `C:/repo/mingw-w64-qt5/src` is the path where Qt5 was compilied from source and `C:/repo` is https://github.com/Alexpux/MINGW-packages.

I haven't found out why this file gets added (`-lQt5Gui` is enough and works). This is my workaround for the moment:

```python
	if sys.platform == 'msys':
		ctx.env.LINKFLAGS_QT5GUI = ''
		ctx.env.LINKFLAGS_QT5CORE = ''
		ctx.env.LINKFLAGS_QT5WIDGETS = ''
```

**Comment by ita1024** [comment]
The detection uses pkg-config. Please attach the resulting config.log and _cache.py files.

**Comment by jhasse** [comment]
I've attached config.log and _cache.py from this minimal example: https://github.com/jhasse/qt-waf-example
[build.zip](https://github.com/waf-project/waf/files/611708/build.zip)

I've just found: https://github.com/Alexpux/MINGW-packages/issues/1670
So this might actually be a MSYS2 problem, feel free to close this if you think so. Sorry :(

**Comment by ita1024** [comment]
Looks like a broken pkg-config configuration.
