### ISSUE TITLE
Parallelism issue in one of our projects

### ISSUE THREAD

**Issue by hhaim** [waf-project/waf#1859]
Hi,
When we upgrade to WAF 1.9.3 in our project we observe a slow down in build time (~x2 slower)
The project has 4 independent targets and they could be done in parallel (c++ and C)

When running all targets 
./b clean build  -> total time 4 min
when running each target in a different process -> total time 1 min  

Looking into top tool shows that there is no parallelism (one two cc process)
Installing the debug_parallel shows the issue, but the question is why and if this is something we did .
How we could debug it?

The WAF with the issue: 

https://github.com/cisco-system-traffic-generator/trex-core/blob/master/linux_dpdk/ws_main.py

The WAF that works better

https://github.com/cisco-system-traffic-generator/trex-core/blob/master/linux/ws_main.py

thanks,
Hanoh

**Comment by ita1024** [comment]
Get the latest Waf from master or use the change from above.

**Comment by ybrustin** [comment]
Works, thanks.

**Comment by ita1024** [comment]
And run `waf -v`, it seems that there are a few problems to fix.

**Comment by ybrustin** [comment]
Patch | -v | time
------------ | ------------- | ------------
with | without | 54.126s
with | with | 2m14.710s
without | without | 3m27.826s
without | with | 4m43.469s

**Comment by ita1024** [comment]
Good to know, thank you.

**Comment by ita1024** [comment]
(In case this is taken out of context, one runs "waf -v" to get diagnostics that are useful for troubleshooting but slow to calculate)

**Comment by ita1024** [comment]
Lazy allocation is necessary with such settings 8dae660ec71307a720503b75d757b9e1aee2f624
