### ISSUE TITLE
.dll.a files should be installed to .../lib/ instead of .../bin/

### ISSUE THREAD

**Issue by jhasse** [waf-project/waf#1860]
When creating a shared library on Windows with MinGW Waf correctly creates a `foo.dll` and a `foo.dll.a` file. Both get installed to `${PREFIX}/bin/` though, where the compiler won't find the `.dll.a` file.

Anything I'm missing? Otherwise I'll start working on a PR for this.

**Comment by ita1024** [comment]
That works for me, so please have a look.

**Comment by jhasse** [comment]
What works for you? Are `.dll.a` files installed to `${PREFIX}/lib`?

**Comment by ita1024** [comment]
Yes, the import library gets installed to BINDIR and the import library to LIBDIR

**Comment by jhasse** [comment]
I've retried with Waf 1.9.6, still the same. I'll try to come up with a minimal example to isolate the problem. It probably has something to do with MSYS2.

**Comment by ita1024** [comment]
I have msys2 on windows10 and things work as expected. What are `bld.env.BINDIR` and `bld.env.LIBDIR` set to?

**Comment by ita1024** [comment]
Reopen if still broken.

**Comment by ita1024** [comment]
... and attach a testcase.

**Comment by jhasse** [comment]
wscript:

```python
#!/usr/bin/env python3

def options(opt):
	opt.load('compiler_c')

def configure(conf):
	conf.load('compiler_c')

def build(bld):
	print("BINDIR = {}\nLIBDIR = {}".format(bld.env.BINDIR, bld.env.LIBDIR))
```

It depends on which Python (python3 or mingw-w64-x86_64-python3) is used. See:

```
➜  /usr/bin/python3 waf configure install
Setting top to                           : /home/jhasse/test
Setting out to                           : /home/jhasse/test/build
Checking for 'clang' (C compiler)        : /mingw64/bin/clang
'configure' finished successfully (0.162s)
Waf: Entering directory `/home/jhasse/test/build'
BINDIR = /usr/local/bin
LIBDIR = /usr/local/bin
Waf: Leaving directory `/home/jhasse/test/build'
'install' finished successfully (0.005s)
➜  /mingw64/bin/python3 waf configure install
Setting top to                           : C:/msys64/home/jhasse/test
Setting out to                           : C:/msys64/home/jhasse/test/build
Checking for 'msvc' (C compiler)         : C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64/CL.exe
'configure' finished successfully (5.445s)
Waf: Entering directory `C:/msys64/home/jhasse/test/build'
BINDIR = C:/msys64/tmp/bin
LIBDIR = C:/msys64/tmp/lib
Waf: Leaving directory `C:/msys64/home/jhasse/test/build'
'install' finished successfully (0.004s)
```

PS: I can't reopen this issue.

**Comment by ita1024** [comment]
Clang which is behaving as a unix-like compiler in those settings: https://github.com/waf-project/waf/blob/master/waflib/Tools/c_config.py#L1152

**Comment by jhasse** [comment]
Would it be enough to simply remove https://github.com/waf-project/waf/blob/master/waflib/Tools/c_config.py#L1154 ?

**Comment by piem** [comment]
hi,

when cross-compiling with mingw-64 using 1.8.22, I get:

```
{destdir}/{prefix}/lib/libfoo.dll.a
{destdir}/{prefix}/bin/foo-5.dll
```

using 1.9.6, i get:

```
{destdir}/{prefix}/lib/foo-5.dll
{destdir}/{prefix}/lib/libfoo.dll.a
```

**Comment by jhasse** [comment]
That looks a slightly different issue. How do you cross-compile?

**Comment by piem** [comment]
Hi @jhasse. I use [this script for aubio](https://github.com/aubio/aubio/blob/master/scripts/build_mingw).

Thanks, piem

**Comment by piem** [comment]
should I open a new bug about this?

**Comment by ita1024** [comment]
@piem the "lib" prefix is another matter entirely.

**Comment by piem** [comment]
@ita1024 i'm not concerned about the lib prefix, only the .dll installation folder.

**Comment by ita1024** [comment]
This is not an issue we can work on at this time and we are missing a testing environment. Feel free to submit changes, but make sure that there are no further regressions.
