### ISSUE TITLE
functools.partial() not accepted as rule

### ISSUE THREAD

**Issue by gjcarneiro** [waf-project/waf#1862]
Trying partial function application gives me an error:
```python
def myfunc(arg, task):
    ...
bld(...,
        rule=partial(myfunc, "arg"))
```
```
TypeError: functools.partial(<function build.<locals>. [...] at 0x7f0578342bf8>, 'arg') is not a module, class, method, function, traceback, frame, or code object
```
Sounds like waf is checking for exact types, but instead it should check for callables:
```
callable(...)
    callable(object) -> bool
    
    Return whether the object is callable (i.e., some kind of function).
    Note that classes are callable, as are instances of classes with a
    __call__() method.
```

**Comment by ita1024** [comment]
I am not sure any verification is made anywhere.

**Comment by ita1024** [comment]
The parameter is meant to be either a string or a hashable function.

**Comment by xbreak** [comment]
If you can, use a lambda instead of partial.

Lambdas aren't hashable by `Utils.h_fun` either, but the failure will be handled by catching the resulting `IOError` as an `EnvironmentError`.

**Comment by gjcarneiro** [comment]
Oh, I see, Utils.h_fun has special code to handle functions.  I knew there had to be something handle functions especially:

```python
def h_fun(fun):
	try:
		return fun.code
	except AttributeError:
		try:
			h = inspect.getsource(fun)
		except EnvironmentError:
			h = 'nocode'
		try:
			fun.code = h
		except AttributeError:
			pass
		return h
```
In theory it should be possible to handle also `partial`, as long as the args are also hashable:
```
>>> partial(int, 2).args
(2,)
>>> partial(int, 2).func
<type 'int'>
```
If I provide a PR, will you still consider reopening?

**Comment by ita1024** [comment]
The code needs to work on Python 2.5-3+, on other Python interpreters (Pypy, Jython, ipy) and reflect the contents of the object being used.

**Comment by gjcarneiro** [comment]
The `functools` module is "New in version 2.5.".  The partial object attributes are [documented here](https://docs.python.org/2/library/functools.html#partial-objects).  If they're documented, we can rely on them to be available in any Python implementation.  I would like to be able to hash any partial func as long as its arguments are hashable (kwargs can be converted to a tuple of (key, value) pairs for hashing purposes).
