### ISSUE TITLE
Progress bar during Configure?

### ISSUE THREAD

**Issue by ryobg** [waf-project/waf#1863]
Hi!

During the configure step of my program, I check for local packages, and if not I install them. This caused me to use the Python's Request package and I use with together with the Python's TQDM for progress bar. I have troubles though to position the bar after the
```
Checking for program 'adsad'                : <progress message>
```
Now I wonder is there any progress bar like functionality already suitable?
And maybe even do there exists and functionality like Python's Request package? This is more for convenience, but what I want just is simple `download(url,save_to)` function.

If there is no progress bar, aside the one used during Build I think, any ideas how I can redirect better the streams so that I can implement one?

Thank you for your time!

**Comment by ita1024** [comment]
I am not sure of what you mean by TQDM.

The configuration phase is not meant to display a progress status because that would clutter the config.log file. If you really want to add a progress output, then you can probably take inspiration in the existing code, external dependencies are unnecessary (the last last line is overwritten at each update).

**Comment by ryobg** [comment]
Hi!

TQDM is python code for displaying progress bars: https://github.com/tqdm/tqdm
I  do not understand to what relates your statement "the last last line is overwritten at each update"? 

Anyway, I assume that there is nothing already made for this. I think I'll continue to search for solution. 

Thank you.

**Comment by ita1024** [comment]
Ah, so you are tinkering with a third-party library. I understand now.

**Comment by ryobg** [comment]
Yay! I have succeeded. Behold:
```python
def configure (ctx):
    ctx.start_msg ("STAAART!")
    bar = ProgressBar (ctx.line_just) # Tell from where to start the progress bar
    for i in range (1, 11):
        bar.progress (i, 10)
        sleep (0.2)
    bar.end () # Delete the progress bar so that only ctx.end_msg() is seen
    ctx.end_msg (True)
```

![screenshot from 2016-11-24 17 35 17](https://cloud.githubusercontent.com/assets/13996376/20603981/c1d9a6ca-b26c-11e6-8ffc-1e256824d541.png)

As you told me I breath inspiration from the existing `progress_line` code in Waf. I used the same tools and created a class with timer inside and mimicked the API of the `ctx` type. I'm now tempted to merge `ProgressBar` directly in the class.

Btw, I see no traces in the `config.log`.

♫
