### ISSUE TITLE
Unicode for find_program()

### ISSUE THREAD

**Issue by ryobg** [waf-project/waf#1864]
I'm using Waf 1.9.5 and I have something like this in my file:
```python
# -*- coding: utf-8 -*-
# ...
ctx.find_program ('git', var='git')
```
And in this case `print (type ("git"))` outputs `<type 'unicode'>`.

Now, because in `find_program()` there is a call to `', '.join (filename)` it causes result like `u'g, i, t'` and this is basically bad. I saw that  `Utils.to_list` checks for `str` and wraps it in a list, maybe to avoid such split onto chars. Is it possible to add and check for unicode strings?

**Comment by ita1024** [comment]
Why are you getting unicode types? Why do you think that this is "basically bad"?

**Comment by ryobg** [comment]
It just seems that this is my environment. By bad I meant that `find_program()` does not work when called with unicode string. Is this intentional or should this function be extended?

**Comment by ita1024** [comment]
Passing python 2 unicode type parameters is not supported. Use Python3 for proper unicode support.

**Comment by ryobg** [comment]
I strike for portability as I thought Waf does. Whether Python 2 or 3. My workaround is to either to use lists always:
```python
find_program(["git"], var="git")
```
or either to patch the `Utils.to_list(val)` method:
```python
def to_list(val):
    if isinstance(val,str) or isinstance(val,unicode):
        return val.split()
    else:
        return val
```
