### ISSUE TITLE
Not downloadable from website

### ISSUE THREAD

**Issue by dffischer** [waf-project/waf#1866]
Hopefully, this is the right place to notify you about a slip-up on [the waf webpage](https://waf.io/).

The links to [the signed executable](https://waf.io/waf-1.9.6), [the source code archive](https://waf.io/waf-1.9.6.tar.bz2) and [its signature](https://waf.io/waf-1.9.6.tar.bz2.asc) of the recently released version 1.9.6 only lead to error pages. I suspect the files were forgotten to be uploaded.

**Comment by ita1024** [comment]
Temporary glitch.

**Comment by dffischer** [comment]
Thank you for the quick fix.
