### ISSUE TITLE
Autoconfigure when waf binary updates

### ISSUE THREAD

**Issue by jhasse** [waf-project/waf#1870]
When I update Waf to a new version and run `waf` I get the error

```
Version mismatch! reconfigure the project
```

even if I set `Configure.autoconfig = True`. Also "reconfigure" should be capitalized.

**Comment by ita1024** [comment]
This works exactly as it should, changing the waf version must not silently delete old build information.

**Comment by jhasse** [comment]
I see. Do you agree though, that the error message could explain it a little better? E. g.

```
Project was configured with a different version of Waf. Please reconfigure it using
`waf configure` (this will discard old build information).
```
