### ISSUE TITLE
`Task.vars` as an instance variable

### ISSUE THREAD

**Issue by xbreak** [waf-project/waf#1873]
Could you clarify if waf is supposed to work with `Task.vars` as an instance variable? I have a similar use case to [waf_unit_test.py](https://github.com/waf-project/waf/blob/af66a27da3b3ba493450fe8aa479447ef3db5778/waflib/Tools/waf_unit_test.py#L64-L65) which updates `self.vars` after use of `Task.compile_fun()`, but I couldn't get it to work as expected (rebuild if variable change) unless I override `Task.sig_vars()` to use the instance variable instead of the `self.__class__.vars`
````
def sig_vars(self):
	sig = self.generator.bld.hash_env_vars(self.env, self.vars)
	self.m.update(sig)
````

**Comment by ita1024** [comment]
That looks like a silly mistake.

**Comment by xbreak** [comment]
Thanks!
