### ISSUE TITLE
Archive contents have weird permissions

### ISSUE THREAD

**Issue by dffischer** [waf-project/waf#1875]
Many files in [the source code archive on the webpage](https://waf.io/waf-1.9.6.tar.bz2) switched from permissions 644 to 640. A quick scan yields 233 of them.

```bash
$ wdiff <(command tree -p waf-1.9.5) <(command tree -p waf-1.9.6/) | fgrep -c '[-[-rw-r--r--]-] {+[-rw-r-----]+}'
```

This means that especially the python modules in the `waflib` directory are not readable when owned by another group, which renders waf unusable.

I could not find any explanation. Was this change intentional?

**Comment by ita1024** [comment]
The change was not intentional, and there is no need to exaggerate. Now try and download 1.9.7.
