### ISSUE TITLE
UnboundLocalErrors: local variable 'dvars' referenced before assignment

### ISSUE THREAD

**Issue by antoche** [waf-project/waf#1883]
With waf-1.9.5, raised from Task.py line 1170.

**Comment by antoche** [comment]
Happened when line was a tuple ((string,function),function). This was unintentional and arguably, may not be supported, but it still looks like the code might want to return composed_fun, dvars_lst rather than composed_fun, dvars?

**Comment by ita1024** [comment]
Nested structures are not meant to be supported.
