### ISSUE TITLE
Make waf logging more compatible with Python logging

### ISSUE THREAD

**Issue by jeberger** [waf-project/waf#1894]
Hi,

I am writing a helper module that needs to be usable in two ways:
- as a standalone script independent of waf,
- or as python module imported from my wscript.

I want to log some traces inside my module and have it work nicely in both situations. Here is what I have tried:

- `import logging as log`, then use `log.debug`, `log.info`, etc. in my module. This works when the module is standalone, but not inside waf: only warning level traces are printed for my module and waf traces are printed twice.
- `import logging; log = logging.getLogger (__name__)`. However this requires a lot of boilerplate in my wscript if I want to avoid a `No handlers could be found for logger` message and to integrate nicely with the waf logs (e.g. have the same colors for various levels). I can't use `waflib.Logs.log_handler()` because it doesn't format arguments properly (`log.debug ("foo: %s", foo)` prints `foo: %s` instead of printing the contents of variable `foo`).

Ideally, I think waf should add some default configuration to the root logger so that either `import logging as log` or `import logging; log = logging.getLogger (__name__)` will work out of the box. Users can always override this default root configuration in their wscript if they want to.

If you don't want to force a default configuration in the root logger, then I think there should be an easy way for the user to apply the waf configuration to the root logger. This is already very close to available thanks to `waflib.Logs.log_handler()`, but it needs to be fixed to enable argument formatting to work.

**Comment by ita1024** [comment]
This is fine. You might just need to get more familiar with the Python logging API.
