### ISSUE TITLE
ctx.root.path_from(ctx.path) returns '.'

### ISSUE THREAD

**Issue by antoche** [waf-project/waf#1898]
Using waf-1.9.5 and python-2.7.3, ctx.root.path_from(ctx.path) returns '.' instead of returning the actual relative path of the root from `ctx.path`. Same with root seen from any source node.

Repro case:

```
import os

top = '.'
out = 'build'

def configure(conf):
        pass

def build(ctx):
        src = ctx.path.find_resource('wscript')
        print( 'ctx.root is %s'%ctx.root.abspath() )
        print( 'src is %s'%src.abspath() )
        print( 'ctx.root seen from src, according to waf: %s'%ctx.root.path_from(src) )
        
        print( 'ctx.root is %s'%ctx.root.abspath() )
        print( 'ctx.path is %s'%ctx.path.abspath() )
        print( 'ctx.root seen from ctx.path, according to waf: %s'%ctx.root.path_from(ctx.path) )
        print( 'ctx.root seen from ctx.path, according to os: %s'%os.path.relpath( ctx.root.abspath(), ctx.path.abspath() ) )
```

Results in:

```
Setting top to                           : /tmp/abouthors/waftest 
Setting out to                           : /tmp/abouthors/waftest/build 
'configure' finished successfully (0.003s)
Waf: Entering directory `/tmp/abouthors/waftest/build'
ctx.root is /
src is /tmp/abouthors/waftest/wscript
ctx.root seen from src, according to waf: .
ctx.root is /
ctx.path is /tmp/abouthors/waftest
ctx.root seen from ctx.path, according to waf: .
ctx.root seen from ctx.path, according to os: ../../..
Waf: Leaving directory `/tmp/abouthors/waftest/build'
'build' finished successfully (0.003s)
```

**Comment by ita1024** [comment]
Waf 1.9.5? Could you use something more recent?

**Comment by antoche** [comment]
> Waf 1.9.5? Could you try a more recent version?

I can certainly try with 1.9.7, but the changelog doesn't seem to indicate anything's changed in that area.

> Note: ctx.root has no meaning, in particular on Windows systems.

According to the waf book, "ctx.root is the root of the file system". 
If it has no meaning, how do I reference a node that's outside `ctx.path`'s hierarchy?

**Comment by ita1024** [comment]
The symptom cannot be reproduced with waf 1.9.7.

Be careful when using `ctx.root` because that does not represent the drive letter on Windows systems. Relying too much on it can make your scripts system-specific.

**Comment by antoche** [comment]
Getting the exact same behaviour with waf-1.9.7 and python-2.7.6.

**Comment by ita1024** [comment]
Well, no that is not what we are getting: `ctx.root.path_from(ctx.path)` returns `/` which is consistent with what one would get on windows.

**Comment by ita1024** [comment]
And this was on the master branch, not in 1.9.7. The change will be in the next version. Does the behavior of the master branch seem acceptable?

**Comment by antoche** [comment]
As long as it returns a valid path, that's fine by me. My issue with this bug is it returns relative paths that were simply wrong. A valid absolute path is better than an invalid relative path.

The test case was taken from the waf book example (https://waf.io/book/#_path_manipulation_abspath_path_from), which shows `ctx.root.path_from(ctx.path)` returning a relative path.

**Comment by ita1024** [comment]
Thanks for the report; the change will be in waf 1.9.8.
