### ISSUE TITLE
add new intel compiler's openmp option

### ISSUE THREAD

**Issue by appleparan** [waf-project/waf#1900]
From intel compiler 2016, compile & link option `-openmp` has been deprecated, and new option `-qopenmp` introduced. Please add this option to `detect_openmp` function

You can find this on intel's documentation 
- Fortran : [https://software.intel.com/en-us/node/678114](https://software.intel.com/en-us/node/678114)
- C/C++ : [https://software.intel.com/en-us/node/682582](https://software.intel.com/en-us/node/682582)

**Comment by ita1024** [comment]
Try and update your copy
