### ISSUE TITLE
Install instructions are unclear 

### ISSUE THREAD

**Issue by DaveBGld** [waf-project/waf#1901]
In section 2.1.3 of the WAF book, The code 

`$ chmod 755 waf
$ ./waf --version
`
Needs to be instead 

`
$ chmod 755 waf-1.9.7
$ ./waf-1.9.7--version
`

And then, instead of 

`$ alias waf=$PWD/waf`

Should be changed to 

`$ alias waf=$PWD/waf-1.9.7`

**Comment by ita1024** [comment]
The version number was dropped from the instructions, I think this is fine now.

**Comment by DaveBGld** [comment]
Still the same. The way it's written, its impossible to get started with waf
