### ISSUE TITLE
winres tool is broken in 1.9.7

### ISSUE THREAD

**Issue by aloukissas** [waf-project/waf#1908]
The tool seems to be misconfigured when using rc.exe, since we're passing it wrong options. Sample error message:

`fatal error RC1106: invalid option: -o`

This works OK on 1.8.x release and before.

Most likely culprit is commit 75b1423c

**Comment by ita1024** [comment]
That commit in question has nothing to do with that option.

Is a c compiler configured before loading `winres`? Attach the config.log file.

**Comment by aloukissas** [comment]
@ita1024 yes, I call load("cxx_compiler") - this detects that I'm on Windows /w VS 2013 installed and within the msvc.py tool it loads winres.py. I'll get the config.log file for you. Without changing anything else except for waf versions (1.8.x or earlier vs 1.9.y) causes this bug to be hit.

**Comment by ita1024** [comment]
Are fortran/c tools also loaded?

**Comment by aloukissas** [comment]
I do load *both* c and c++ tools, i.e. I call load("c_compiler") and load("cxx_compiler").

**Comment by aloukissas** [comment]
The commit referenced above fixes the issue.

**Comment by ita1024** [comment]
Excellent, thanks for verifying.
