### ISSUE TITLE
qt5 broken on macOS

### ISSUE THREAD

**Issue by cawka** [waf-project/waf#1910]
Commit 823ad57b89b1b450b5c7b69323a2df5b5a33a230 effectively broke QT5 detection on macOS plaftorm for some QT5 installations.

It is already challenging to make compilation on macOS, as the distributed open-source version only ships with Qt*.framework and don't provide .pc files.  HomeBrew version made a few fixes, compiling .framework's but also providing .pc files.  So, this combination worked prior 823ad57b89b1b450b5c7b69323a2df5b5a33a230, but not since.

I tried to make a trivial fix by adjusting `set_qt5_libs_to_check`, but it is not as trivial, as frameworks for some reason don't include "5" in their names (e.g., `QtWebView.framework`, not `Qt5WebView.framework`), which breaks a bit of logic in this function.  I can probably make it work with a bit more cludges.

* * *
I want to ask for advice.  What is the expectation on how QT5-dependent project should be compiled on macOS?  Should we invent a way to deal with `.framework`?

**Comment by cawka** [comment]
This is a quick patch that fixed my immediate problem

```patch
diff --git a/waflib/Tools/qt5.py b/waflib/Tools/qt5.py
index 6bc2370..da647a2 100644
--- a/waflib/Tools/qt5.py
+++ b/waflib/Tools/qt5.py
@@ -722,11 +722,13 @@ def set_qt5_libs_to_check(self):
                        pat = pat.replace('.dll', '.lib')
                if self.environ.get('QT5_FORCE_STATIC'):
                        pat = self.env.cxxstlib_PATTERN
-           re_qt = re.compile(pat % '(?P<name>Qt5.*)' + '$')
+         if Utils.unversioned_sys_platform() == 'darwin':
+                 pat = "%s\.framework"
+         re_qt = re.compile(pat%'Qt5?(?P<name>.*)'+'$')
                for x in dirlst:
                        m = re_qt.match(x)
                        if m:
-                           self.qt5_vars.append(m.group('name'))
+                         self.qt5_vars.append("Qt5%s" % m.group('name'))
                if not self.qt5_vars:
                        self.fatal('cannot find any Qt5 library (%r)' % self.env.QTLIBS)
```

**Comment by ita1024** [comment]
The changes has been applied, so we can close this now.

**Comment by cawka** [comment]
What about my question about frameworks?  Any suggestions / guesses on how this can work?  In particular, right now, it is impossible to use waf to compile app on mac using non-homebrew version of qt5.  My suspicion that with frameworks we don't need to detect any flags, rather just use proper `-F` flag, but I don't have much experience with that.

**Comment by ita1024** [comment]
I am not familiar with frameworks either. Providing the framework name in the list FRAMEWORK_NAME and the paths as FRAMEWORKPATH can be used to add the relevant flags.

**Comment by ita1024** [comment]
@fedepell FYI ^

**Comment by Houd1ny** [comment]
Actually, waf is still not working with qt on mac
with source code 
`  ctx.load('compiler_cxx')  
    ctx.load('qt5')`
I got error "cannot find any Qt5 library ('/Users/vkdev/Qt/5.8/clang_64/lib')"
With this patch I have got error 
"Checking for 'Qt5Core'                     : not found "
"Could not build a simple Qt application"

**Comment by Houd1ny** [comment]
@ita1024 ^^

**Comment by ita1024** [comment]
@fedepell

**Comment by fedepell** [comment]
@Houd1ny  : can you post config.log and the contents of your /Users/vkdev/Qt/5.8/clang_64/lib ? Looks like the new pattern matches at least one library but not the Qt5Core one.

**Comment by Houd1ny** [comment]
@fedepell
Sorry I'm currently not near my mac machine.
Thia qt was installed using official installer 
It contains *.a files and Qt*.framework folders.
Actually  script do not find any library.
There was the list with almost all qt modules

**Comment by fedepell** [comment]
@Houd1ny : thanks for the logs!

I gave a look and:
1) Effectively in the "before" output libs are not found and after the patch they are found. So the patch seems to work just fine in this aspect to me. 

2) But what doesn't then work is pkgconfig:

```
['/usr/local/bin/pkg-config', '--cflags', '--libs', 'Qt5Core']
err: Package Qt5Core was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5Core.pc'
to the PKG_CONFIG_PATH environment variable
```

Are you sure your setup is correctly working? I would imagine that even if you get waf 1.9.7 (or any before the QT5 autodetection was changed) it would not work. Could you check this just to narrow down the problem?


Usually (in Linux) the pkgconfig files are under lib/pkgconfig. In your setup I don't see this. You should try to fix that on your system.

**Comment by cawka** [comment]
I may not have been very clear in my original report. The macOS version no longer includes pkg-config files at all (when compiled as frameworks, which is the binary version one can download).

I think to use frameworks, autodetection should simply use the found frameworks, but I'm not an expert in that.

**Comment by fedepell** [comment]
@cawka: thanks for explanation and sorry if I've been unclear. Not being a macOS user I missed some points :)

So I would say in general this:
1) The library detection itself is fixed by your patch
2) If we want to keep proper macOS support we (but somebody with macOS experience... or at least a macOS machine :) ) may add an alternative way to handle libraries if pkgconfig is not found, which seems true for all recent qt binary distributions for macOS.

**Comment by ita1024** [comment]
Use ee4d91dfce3a69287661e4236067c55bdff2021d
