### ISSUE TITLE
Add Fortran 95, Fortran 2003 and Fortran 2008 file extensions

### ISSUE THREAD

**Issue by rightfold** [waf-project/waf#1916]
Currently the following Fortran file extensions: `.f`, `.f90`, `.F`, `.F90`, `.for`, and `.FOR` are known to Waf. The file extensions `.f95`, `.f03`, `.f08` and their uppercase variants are also common, however. gfortran uses the file extension to decide which version of the language to use (though this can be overridden with command-line arguments).

**Comment by ita1024** [comment]
That should solve it.
