### ISSUE TITLE
Big project example

### ISSUE THREAD

**Issue by Houd1ny** [waf-project/waf#1917]
I`m trying to use waf for my project.
I do not understand what is the best way to use waf api just reading waf book.
My project should be build on mac, win and linux.
1. How to implement configuration which task to execute depending on os?
Example:
Only on windows, before build, I should generate *.rc (windows resource file).
Only on Mac, before build, I should generate plist file.
How to implement this? 
I already have "class GenerateWinResourceFile(Task): ", and "class GeneratePlist(Task): "
And there are other tasks that should run on all os.
2.  How to divide "def build(ctx)" on several functions?
For now I need
def generate_files(ctx) 
def build(ctx)
I want that tasks in build was depended on tasks in generate_files.

The main question is "Is there any real world project example?"
Real word project is that work on several platforms and has win installer and dmg package on mac, for example.
Thank in advance

**Comment by ita1024** [comment]
1. There are examples in `demos/c` and `demos/mac_app`
2. This is explained in the documentation. If reading it does not help, try the examples above.

Every project is different, and big ones are often very complex. Trying to imitate them is a very bad idea, but if this really is your question then you should try a search engine first.
