### ISSUE TITLE
bld.add_group() breaks tasks numbering

### ISSUE THREAD

**Issue by captainmalloc** [waf-project/waf#1918]
Hello Everyone,

I am quite new to Waf, I have been using it for the last few weeks to build a completely custom flow.

My flow needs to be split into two different subflows: the first to generate few config files (dynamically computed at Task level) and download packages (also dynamically computed at Task level); the second part to use packages according to the configs content. This is the reason why I am using the 'add_goup()' command.

Now, everything works fine from the generation point of view, what's bothering me is the Tasks numbering shown on stdout that's not coherent. 

Here is an example of the output:

```
Waf: Entering directory /path/to/build
[1/4] GenConfig build/config1.cfg
[2/4] GenConfig build/config2.cfg
[3/4] Creating build/packages.db
[4/4] Download ...
[ 5/20] ExtractBundle
...
```

I think that seeing **4** and later **20** on the total number of tasks to execute is confusing, from the flow user point of view.

I am using waf 1.9.8 with Python 2.7

**Comment by ita1024** [comment]
The behavior changed in waf 1.9 to have task generators processed lazily, group-per-group, during the build phase. To force them to be processed before the build starts, use the following:

```
from waflib import Build
def build(bld):
    bld.post_mode = Build.POST_AT_ONCE
```

We will amend the documentation to reflect this aspect.

**Comment by captainmalloc** [comment]
Thanks
