### ISSUE TITLE
cppcheck not python 3 ready?

### ISSUE THREAD

**Issue by a6a3uh** [waf-project/waf#1921]
It not works under python3 giving errors from python2 syntax like adding bytes to strings or calling has_key on dict instead of using 'in'.

**Comment by ita1024** [comment]
utf-8 is probably a better idea than us-ascii

**Comment by fedepell** [comment]
@ita1024 : i started with utf-8 too but then noticed that the default ElementTree.tostring is indeed us-ascii:

` xml.etree.ElementTree.tostring(element, encoding="us-ascii", method="xml")`

and therefore in the old versions that was used and I wanted to keep it generating exactly the same output. But if you think it's better I can easily change it to utf-8.

**Comment by ita1024** [comment]
This explains it. Thanks for the clarification!
