### ISSUE TITLE
Support the new MSVC Build Tools

### ISSUE THREAD

**Issue by bbalp** [waf-project/waf#1924]
Microsoft now provides a standalone version for C++ (without IDE) called Visual C++ Build Tools. They changed the location where they used to install all the stuff. For example, now they use `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build` to install the scripts called `vcvars32.bat`, `vcvars64.bat`, `vcvarsall.bat`, `vcvarsamd64_x86.bat`, `vcvarsx86_amd64.bat`.

Also, the Visual Studio 2017’s latest toolset version is vc141. Which, I guess, should become `msvc 14.1` ?

May the Force be with Waf :)

**Comment by ita1024** [comment]
I hope that #1925 fixes this.

**Comment by kulibali** [comment]
#1925 detects installations of Visual Studio 2017 (version 15.0).  I haven't tried it with the Visual Studio Build Tools, either 14 or 15.

**Comment by bbalp** [comment]
I tried on two machines, one with Community 2017 installed, the other with BuildTools 2017. I confirm that it is working with the new VS 2017 (v15.0), but not with the BuildTools variant which installs no registry key to find it. I investigated the problem. Microsoft wrote a fresh article about [Finding installed Visual C++ tools for Visual Studio 2017](https://blogs.msdn.microsoft.com/vcblog/2017/03/06/finding-the-visual-c-compiler-tools-in-visual-studio-2017/):

> (...) we have removed the VS150COMNTOOLS registry key to support the new world where multiple VS instances of the same product can be installed side-by-side on the same machine, we know that many build systems and tools have relied on this in the past and the new options are not an identical replacement (...)

They suggest three ways to find installed instances from now on:
- [vswhere.exe](https://github.com/Microsoft/vswhere)
- [PowerShell API](https://blogs.msdn.microsoft.com/heaths/2017/01/25/visual-studio-setup-powershell-module-available/)
- [VS Setup COM API](https://github.com/microsoft/vs-setup-samples) with a [specific example for C++](https://github.com/adamwelch/vs-setup-samples/tree/findVCtools)

So, I guess a quick fix would be to check the default installation path for VS BuildTools, which is `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools`. But writing something to use the new tools they provided is needed.

Also, to be sure that no one is confused with versions. VS 2017 (v15.0) deploys VC++ (v14.10 or vc141) which, I confirm, become `msvc 14.10`

The Boost Library seems to have chosen to use a solution "based on JIT compilation of a C# file and COM" (VS Setup COM API). #https://github.com/boostorg/build/pull/170 They use the code from @refack we can study [here](https://github.com/node4good/windows-autoconf/tree/master/tools).

**Comment by refack** [comment]
Is there interest in me doing a PR?

**Comment by ita1024** [comment]
Yes, there is.

**Comment by refack** [comment]
On it

**Comment by refack** [comment]
Sorry for the delay.
Done in #1945

**Comment by refack** [comment]
Just figured out your packing mechanism. Is there a way to add read a file as a string resources

**Comment by ita1024** [comment]
No, and I do not think this is going to be merged as it adds a lot of complexity.

**Comment by refack** [comment]
Ok, I'll figure it out

**Comment by bbalp** [comment]
Your commit 334372e739d70ebe86eb82adc0f336f69ad9f40e doesn't work for Build Tools. I tried building waf, copying in demos\c, trying to configure, and it fails at finding any compiler.

Also I checked that my installation hasn't broken since the last time running `vswhere.exe -products microsoft.visualstudio.product.buildtools` All the information displayed was correct, the installationPath is found, etc.

**Comment by refack** [comment]
@bbalp thanks for the feedback. On my machine I only have Buildtools (as it's the only SKU that makes sense, right?)
I'm trying to figure out what failed. Could you help?

Easy way to get the PR code
```
git fetch origin pull/1945/head:1945
git checkout 1924
```
Verbose call to script:
```
cd waflib\Tools
python msvs15com.py
```

I get:
```
D:\code\3party\waf\waflib\Tools>python msvs15com.py
Found VS2017 "Visual Studio Build Tools 2017" installed at "D:\bin\dev\VS\2017\BuildTools"
D:\bin\dev\VS\2017\BuildTools
```

**Comment by refack** [comment]
Is case your "Visual Studio Build Tools 2017" is missing either the `MSBuild`, `VisualCppTools` or `SDK8/10` components you will see `.... does not meet criteria "IsVcCompatible"`

**Comment by bbalp** [comment]
The code you asked me to test, works fine. But I find out what is going wrong in the waf tool `msvc.py`. `if version == '15.0':` fails. Because `gather_msvc_detected_versions()` uses the windows registry to find what are the versions installed and BuildTools installs no registry key (or at least not an easy one to test).

If we need to use the COM API, this is because Microsoft tells us to stop relying on the registry entries by now. So I guess it means that we have to run your tool without any condition.

One more thing though. This nice C# script you wrote obviously needs to be compiled to run. Alas this is not very fast to compile. It slows down a lot a `waf configure`. But at the moment, I can't think of a better way and this is necessary to have it in waf to nicely support BuildTools and future versions of Visual Studio. But if anyone have an idea ...

**Comment by refack** [comment]
> The code you asked me to test, works fine. But I find out what is going wrong in the waf tool msvc.py. if version == '15.0': fails. Because gather_msvc_detected_versions() uses the windows registry to find what are the versions installed and BuildTools installs no registry key (or at least not an easy one to test).
>If we need to use the COM API, this is because Microsoft tells us to stop relying on the registry entries by now. So I guess it means that we have to run your tool without any condition.

I'll fix that.

> One more thing though. This nice C# script you wrote obviously needs to be compiled to run. Alas this is not very fast to compile. It slows down a lot a waf configure. But at the moment, I can't think of a better way and this is necessary to have it in waf to nicely support BuildTools and future versions of Visual Studio. But if anyone have an idea ...

The `InstallationPath` value can be cached to env. Also from my experience what also takes long is the call to the new `vcvarsall.bat`, I've opened a ticket for MS to cache that process (I do that in `windows-autoconf`)

**Comment by AndrewPardoe** [comment]
The officially supported vswhere tool is now available as part of the install starting today with Visual Studio 15.2 preview 2: https://blogs.msdn.microsoft.com/heaths/2017/04/21/vswhere-is-now-installed-with-visual-studio-2017/. This doesn't fix all the existing installs of VS 2017 but going forward you can now detect the VS install locations and whether C++ tools are available from a scripted environment. I hope this helps your scenario.

**Comment by bbalp** [comment]
If this applies to the BuildTools installation (not installing any other version of Visual Studio) and vswhere is available in the PATH it sure helps a lot. :)

**Comment by refack** [comment]
> If this applies to the BuildTools installation (not installing any other version of Visual Studio) and vswhere is available in the PATH it sure helps a lot. :)

It's not in the path it's at `%ProgramFiles(x86)%\Microsoft Visual Studio\Installer` (on 32-bit operating systems before Windows 10, you should use `%ProgramFiles%\Microsoft Visual Studio\Installer`, and yes it applies to Buildtools (with `--product *` switch)

This is the "minimal" script to set `VS150COMNTOOLS`
```cmd
SETLOCAL
set VSWHERE_REQ=-requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64
set VSWHERE_PRP=-property installationPath
set VSWHERE_LMT=-version "[15.0,16.0)"
SET VSWHERE_ARGS=-latest -products * %VSWHERE_REQ% %VSWHERE_PRP% %VSWHERE_LMT%
set VSWHERE="%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist %VSWHERE% set VSWHERE="%ProgramFiles%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist %VSWHERE% EXIT /B 1
for /f "usebackq tokens=*" %%i in (`%VSWHERE% %VSWHERE_ARGS%`) do (
    ENDLOCAL & SET INSTPATH=%%i
    set "VS150COMNTOOLS=%INSTPATH%\Common7\Tools\"
    exit /B 0)
```

**Comment by refack** [comment]
https://github.com/node4good/msvs-com-helper/blob/master/vswhere_udability_wrapper.cmd

**Comment by ita1024** [comment]
@AndrewPardoe What is the download link for Visual Studio build tools 2017 preview containing vswhere.exe?

**Comment by AndrewPardoe** [comment]
Future releases of VS2017 will contain VSWhere.

**Comment by ita1024** [comment]
It is alright if it not released yet. I will need to get a proper testing environment before digging further into this matter.

**Comment by AndrewPardoe** [comment]
Oh, wait, I see that we've released a preview of VS 2107 15.2. [There's an install link in the VS blog post.]( https://blogs.msdn.microsoft.com/visualstudio/2017/04/18/visual-studio-2017-preview-15-2.) Heath Stewart said that [15.2 should contain VSWhere](https://blogs.msdn.microsoft.com/heaths/2017/04/21/vswhere-is-now-installed-with-visual-studio-2017/). 

Sorry, my team is a little separated from the VS team. I knew that a preview would be released soon, but I didn't realize it was today.

**Comment by refack** [comment]
@bbalp I'd be honored is you tested my new #1945
(to get `vswhere` you can just just download the [Installer bootstrapper](https://www.visualstudio.com/vs/preview/), and update just the installer)

**Comment by ita1024** [comment]
@AndrewPardoe Yes, I did find those links. To be more specific, I am looking for a preview build of "Build Tools for Visual Studio 2017" as highlighted in the topic of this issue.

I am not interested in the community/enterprise/professional builds, as I want to specifically test the vswhere detection for the build tools (with the vswhere version hopefully shipped with that package as highlighted in https://github.com/waf-project/waf/issues/1924#issuecomment-296213658 ?).

Does such a build exist, or shall this wait for a next release?

**Comment by refack** [comment]
@ita1024 get the [Installer bootstrapper](https://www.visualstudio.com/vs/preview/), and just update the installer (essentially they are identical between version including "Buildtools" except for the default selection of components)

**Comment by ita1024** [comment]
@refack are you certain that no registry keys are added with that scheme?

**Comment by refack** [comment]
If you just run the installer bootstrapper and click "update installer" then exit (or choose to update "Buildtools" no registry changes are made. (I traced that, I also hate registry manipulators).

**Comment by ita1024** [comment]
I have not managed to install the preview version of the build tools. If you can provide a command-line, that would be terrific.

**Comment by refack** [comment]
I'm still fighting with MS about the exact way to do command line operation.
But via GUI this is what I did https://github.com/node4good/msvs-com-helper/wiki/How-to-upgrade-the-installer
* The last screen doesn't have an "Upgrade" because I already did that.
* There is one registry change, the upgrade unregisters and re-registers the "infamous" COM server.

**Comment by bbalp** [comment]
Testing the last changes with the last VS 15.2, the commit e19d9d990f0a1e2e6e9292b5b78437efe1ab1e59 (@refack) works fine but the next one doesn't a65c7c03b7012cc6c3fb0f9c9a3be8abc06bc511 (@ita1024). Is it necessary I investigate further? (or is it an obvious fix)

```
Setting top to                           : C:\waf\demos\c
Setting out to                           : C:\waf\demos\c\build
Checking for 'msvc' (C compiler)         : Traceback (most recent call last):
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Scripting.py", line 122, in waf_entry_point
    run_commands()
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Scripting.py", line 183, in run_commands
    ctx=run_command(cmd_name)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Scripting.py", line 174, in run_command
    ctx.execute()
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Context.py", line 88, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Context.py", line 129, in recurse
    user_function(self)
  File "C:\waf\demos\c\wscript", line 21, in configure
    conf.load('compiler_c gnu_dirs')
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 155, in load
    func(self)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Tools\compiler_c.py", line 23, in configure
    conf.load(compiler)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 155, in load
    func(self)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Tools\msvc.py", line 541, in configure
    conf.autodetect(True)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 177, in fun
    return f(*k,**kw)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Tools\msvc.py", line 559, in autodetect
    compiler,version,path,includes,libdirs,cpu=conf.detect_msvc()
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 177, in fun
    return f(*k,**kw)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Tools\msvc.py", line 459, in detect_msvc
    return self.setup_msvc(self.get_msvc_versions())
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 177, in fun
    return f(*k,**kw)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Tools\msvc.py", line 467, in get_msvc_versions
    self.gather_vswhere_versions(dct)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 177, in fun
    return f(*k,**kw)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Tools\msvc.py", line 310, in gather_vswhere_versions
    arr=json.loads(txt)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 25: invalid start byte

```

**Comment by ita1024** [comment]
@bbalp check your console settings? It definitely works for us.

**Comment by bbalp** [comment]
I found out why. `vswhere` outputs a localized string. `json.loads()` tries to decode a utf-8 string. I think this fix should do it for everyone.

```
arr=json.loads(txt.decode(sys.stdout.encoding))
```

**Comment by SlamJam** [comment]
@bbalp I think it requires the OEM encoding:
```
import ctypes
oem_encoding = 'cp{}'.format(ctypes.windll.kernel32.GetOEMCP())
```
On my Windows system this code
`python -c "import sys; print(sys.stdout.encoding)"`
returns `utf-8`, but OEM encoding is `cp866`. The `vmwhere` uses `OEM`.

P.S. But  `_, locale_encoding = locale.getdefaultlocale()` is `cp1251`.

**Comment by bbalp** [comment]
@SlamJam I checked and tried what you explained. For me in the windows console, default settings (on a French Windows) ...

1. `> python -c "import sys; print(sys.stdout.encoding)"`
`cp850` (this is the windows console's encoding setting)

2. `> python -c "import ctypes; print('cp{}'.format(ctypes.windll.kernel32.GetOEMCP()))"`
`cp850` (OEM code page)

3. `> python -c "import ctypes; print(locale.getdefaultlocale())[1]"`
`cp1252` (ANSI code page)

There is an article about [vswhere's encoding](https://github.com/Microsoft/vswhere/wiki/Encoding) which explains that vswhere will output its result using the console's encoding setting.

So, it led me to think that we have to decode the vswhere's output using `sys.stdout.encoding` in Python. I tried different encoding settings for my console while running Waf to test this hypothesis and the results suggested this is working. (When `chcp` a certain code page, then decoding the vswhere's output in python with another chosen code page gave me the expected results for the combinations I tried.)

If the fix from #1965 is not working for you, just open an issue with your situation. Testing a fix related to locales is always hard as we all have different settings.

**Comment by bbalp** [comment]
@SlamJam I found out that using Python 3 I get similar results to yours.

1. `> python -c "import sys; print(sys.stdout.encoding)"`
`utf-8`

2. `> python -c "import ctypes; print('cp{}'.format(ctypes.windll.kernel32.GetOEMCP()))"`
`cp850`

3. `> python -c "import locale; print(locale.getdefaultlocale())"`
`cp1252`

Also, we are discussing about encoding issues again here #1974.

**Comment by SlamJam** [comment]
@bbalp Yes, it is. I just used python3
