### ISSUE TITLE
use waf to run waf in docker container

### ISSUE THREAD

**Issue by drahnr** [waf-project/waf#1929]
What I would like to do is the following:

`./waf configure build --dockerized`

but what it is actually supposed to do is _nothing_ except for running a command

`docker run some_prepared_image ./waf configure build`

_Background:_

The target is a very esoteric target which includes source files which require special voodoo setup, supports only a specified ubuntu version as BUILD env (which does not run on my laptop) and library paths which conflict with various other project requirements I have installed. A docker image is already available with that setup and as such I would like to use that.

*How would you approach this?* (No, not a shell scripts, I would like to handle this from within a waf tool)

**Comment by ita1024** [comment]
Just add a waf command to do that? Besides the examples of the documentation, see https://github.com/waf-project/waf/blob/master/waflib/extras/remote.py#L154

**Comment by drahnr** [comment]
Perfect! Thanks a lot.

**Comment by afeldman** [comment]
I build a docker waf container. I want to put all the tools init. At the moment it is just swig and compat.

**Comment by drahnr** [comment]
Wrong ticket, this is about launching build tasks in waf containers

**Comment by afeldman** [comment]
I don't think so. I mean My container can actually do

`docker run -ti waf waf configure build`

The problem is, that it just uses two of all the extras, so it might have a problem with some configurations in the wscript.

**Comment by drahnr** [comment]
that is exactly what I tried to avoid. the use case was still to be able to run `./waf build --dockerized` but the actual build happens in a docker container / restricted / different environment. So no, it is not the same thing.
