### ISSUE TITLE
Using x86_64-w64-mingw32-windres for cross-compiling

### ISSUE THREAD

**Issue by jhasse** [waf-project/waf#1934]
I was using

```python
conf.find_program('x86_64-w64-mingw32-windres', var='WINRC', mandatory=False)
conf.load('winres')
```
to use `x86_64-w64-mingw32-windres` for cross-compiling. https://github.com/waf-project/waf/commit/ef3b1bdcbf923947d5e48baed8a54948c7dff2fe broke this though, as I now also have to set `WINRC_TGT_F` and `WINRC_SRC_F`.

How should this be done?

**Comment by ita1024** [comment]
The change is necessary for another project that cross-compiles for both msvc and gcc. What is your suggestion?

**Comment by jhasse** [comment]
Also looking for `x86_64-w64-mingw32-windres` in addition to `windres` would work for me, but maybe another mechanism to set a prefix for all tools (`strip`, `pkg-config`, ...) would be handy for the future.

**Comment by ita1024** [comment]
Have you tried setting the environment variable WINRES before configuring the project?

**Comment by jhasse** [comment]
Yes, Waf is still looking for `windres` though.

**Comment by ita1024** [comment]
I do not understand, if the variable 'WINRC' is set, then the value is set to it. Are you alluding to the configuration outputs?

**Comment by jhasse** [comment]
I thought you were talking about OS environment variables (e. g. `export WINRC=...`).

When I set `conf.env.WINRC` it's missing `WINRC_TGT_F` and `WINRC_SRC_F`. Of course I can set those too, but I was looking for a shorter solution ;)

**Comment by ita1024** [comment]
If you are setting `conf.env.WINRC` then you must set the two others as well. Once that variable is set, there is no foolproof way of distinguishing between rc and windres. If you think that you have a better way, please open a pull request for it.

**Comment by jhasse** [comment]
What do you think about

```
if not v.WINRC_TGT_F:
	v.WINRC_TGT_F = '-o'
if not v.WINRC_SRC_F:
	v.WINRC_SRC_F = '-i'
```

at the beginning of `winres.configure`?
