### ISSUE TITLE
Unable to compile waf-launcher on windows 7 .NET v4

### ISSUE THREAD

**Issue by goriy** [waf-project/waf#1935]
I was not able to compile waf-launcher under windows 7 due to error:

    The type or namespace name 'List' could not be found (are you missing a using directive or an assembly reference?)

Platform: Windows 7 x64 Professional
Compiler: csc.exe - Microsoft (R) Visual C# Compiler version 4.6.1087.0 for C# 5
.NET Framework v4.0.30319

In my particular case, addition of one line to Main.cs fixed the problem:

    using System.Collections.Generic;

I'm not C# expert. So I don't know how this line affects build processes on different platforms and using different versions of C# compiler.

**Comment by ita1024** [comment]
As in: e77d2e1bfe7880f10696271deca4dcde36ebb315 ?

**Comment by goriy** [comment]
Yes. That's exactly what I meant.
