### ISSUE TITLE
Some link flags are lost when calling pkg-config

### ISSUE THREAD

**Issue by equeim** [waf-project/waf#1936]
When I execute pkg-config manually, it gives me following output:
```
$ pkg-config --cflags --libs sailfishapp
-fPIC -fvisibility=hidden -fvisibility-inlines-hidden -I/usr/include/sailfishapp -I/usr/include/mdeclarativecache5  -pie -rdynamic -L/usr/lib/ -lsailfishapp -lmdeclarativecache5
```

In my wscript I call it in configure function:
```python
context.check_cfg(package="sailfishapp", args="--libs --cflags")
```
However after configuring there is no LINKFLAGS_SAILFISHAPP variable in context.env, meaning that `-pie -rdynamic` link flags are lost. Is this a bug or intended behaviour? I use Waf 1.9.9.

**Comment by ita1024** [comment]
Those flags are not supported yet, but you can try the change above, or reimplement the parse_flags method in your wscript file.

**Comment by equeim** [comment]
Currently I just manually add LINKFLAGS_SAILFISHAPP variable.
Also this commit doesn not add support of `-pie` flag, or am I missing something?

**Comment by ita1024** [comment]
You are right, -pie was missing. Try the above then?

**Comment by equeim** [comment]
Works fine now.
