### ISSUE TITLE
calling get_bld().bld_dir() breaks the following builds

### ISSUE THREAD

**Issue by dbacchet** [waf-project/waf#1937]
if inside the `run` function of a Task I call `self.inputs[0].get_bld().bld_dir()`, the build only works if run from a clean state. All subsequent calls to 'waf build' fail.

Here's a wscript showing an example:
```from waflib.Task import Task
from waflib.TaskGen import extension

class nionet(Task):
    def run(self):
        self.inputs[0].get_bld().bld_dir() # commenting this line works
        pass

@extension('.myext')
def process_fbs(self, node):
    tsk = self.create_task('nionet',  node, [])

def configure(conf):
    pass

def build(bld):
    bld( target   = 'codegen',
         source   = ['template.myext'],
        )
```
this is the output of the first waf invocation:
```
[/tmp/waf_fname] $ waf configure build
Setting top to                           : /private/tmp/waf_fname
Setting out to                           : /private/tmp/waf_fname/build
'configure' finished successfully (0.039s)
Waf: Entering directory `/private/tmp/waf_fname/build'
[1/1] Processing template.myext
Waf: Leaving directory `/private/tmp/waf_fname/build'
'build' finished successfully (0.008s)
```
if now I call `waf build` again, I get the following error:
```
$ waf build
Waf: Entering directory `/private/tmp/waf_fname/build'
Waf: Leaving directory `/private/tmp/waf_fname/build'
Build failed
Traceback (most recent call last):
  File "/usr/local/bin/.waf-1.9.8-97b9b2e11bfbfc9bbde52f0db0592b3d/waflib/Runner.py", line 128, in task_status
    return tsk.runnable_status()
  File "/usr/local/bin/.waf-1.9.8-97b9b2e11bfbfc9bbde52f0db0592b3d/waflib/Task.py", line 344, in runnable_status
    new_sig=self.signature()
  File "/usr/local/bin/.waf-1.9.8-97b9b2e11bfbfc9bbde52f0db0592b3d/waflib/Task.py", line 330, in signature
    self.sig_explicit_deps()
  File "/usr/local/bin/.waf-1.9.8-97b9b2e11bfbfc9bbde52f0db0592b3d/waflib/Task.py", line 387, in sig_explicit_deps
    upd(x.get_bld_sig())
  File "/usr/local/bin/.waf-1.9.8-97b9b2e11bfbfc9bbde52f0db0592b3d/waflib/Node.py", line 466, in get_bld_sig
    ret=cache[self]=self.h_file()
  File "/usr/local/bin/.waf-1.9.8-97b9b2e11bfbfc9bbde52f0db0592b3d/waflib/Node.py", line 455, in h_file
    return Utils.h_file(self.abspath())
  File "/usr/local/bin/.waf-1.9.8-97b9b2e11bfbfc9bbde52f0db0592b3d/waflib/Utils.py", line 153, in h_file
    f=open(fname,'rb')
IOError: [Errno 2] No such file or directory: '/private/tmp/waf_fname/build/template.myext'

```

Waf is trying to open the source file from the build folder, but the file is not there (it's in the root, beside the wscript).
If the call `self.inputs[0].get_bld().bld_dir()` at line 8 is removed, the build works as expected.

Tested with version 1.9.8, 1.9.9, 2.0.0pre1. A minimal test case showing the problem is attached: [testcase.zip](https://github.com/waf-project/waf/files/887360/testcase.zip)

**Comment by ita1024** [comment]
The same thing happens with `self.inputs[0].get_bld()`: by doing that, the build is declaring an equivalent Node object in the build directory. On the next runs, the build detects that the file is meant to exist in the build directory, so it falls back to using that one. This is why `waf distclean configure build build` will succeed on the first build but not on the last one.

To lift the ambiguity, one can specify which file is expected, the one in the build directory or the one in the source directory.
```python
def build(bld):
    bld( target   = 'codegen',
         source   = [bld.path.find_node('template.myext')],
        )
```

Declaring Nodes in the build directory has several uses (file copies for example), so this is a feature that we want to keep. The best approach is to avoid creating Node objects that do not make any sense, especially in a threaded context (the method `run` is called by threads).

**Comment by dbacchet** [comment]
I see, thanks!
In my specific case I need to find a way to get the absolute path of the build folder for each input file I'm passing to a code-generation tool (that correctly creates other files in the build dir).
Can you suggest any other way to obtain the same information without creating ghost nodes?

As a general improvement, do you believe it makes sense for `node.get_bld()` to make a real copy of the file behind the scenes, so the following runs can find it? The actual behavior requires to declare differently the source files in the `source` array depending on the feature that will operate on them, and there is no way to detect the problem on the user side unless we try to build twice without `clean`ing

**Comment by ita1024** [comment]
Try using the node objects from the `self.outputs` list first, and make sure to use the parent node to get to the folder: `self.outputs[0].parent.abspath()`

**Comment by dbacchet** [comment]
using directly self.outputs in my case is not possible, because they depend on the parsed file, and are all produced in subdirs, making impossible to understand the right base folder.
Your suggestion lead me to an easy workaround though: I added `self.path.find_or_declare('.')` as first output, and `self.outputs[0].abspath()` in the Task gives me the path I need.

**Comment by dbacchet** [comment]
thanks for the explanation and for extending the waf documentation. 
Closing the issue.

**Comment by ita1024** [comment]
Using `self.path.find_or_declare('.')` is the exact same thing as `self.path.get_bld()` in that context. Task outputs are meant to be files, not folders, so passing that as a task output is nonsense. In that case, why not just use `self.inputs[0].parent.get_bld()`?

In any case, these methods should not be called from the `run()` method because they are not thread safe and because they create Node objects (the value can be bound to the task object as a new attribute though).

You should get familiar with these parts of the API:
* `some_node.path_from(some_other_node)`
* `self.generator` parent task generators from task objects
* `bld.srcnode/bld.bldnode`: Node representing the source and build folders

**Comment by dbacchet** [comment]
using `self.inputs[0].parent.get_bld().abspath()` or `self.generator.path.get_bld().abspath()` does the trick in my case, and are more elegant.
Are both those calls not thread safe (and how can I find which calls are safe inside the `run()` method)?

about `srcnode/bldnode`, any way I can access them from the `task_gen` instance or in the task itself?

**Comment by dbacchet** [comment]
calling `tsk = self.create_task('mytask'',  in,  out, bld_dir=self.path.get_bld().abspath())` in the task generator seems like the safe way of solving my problem, right?

Last question: how can I access srcnode/bldnode from the task generator or the task? 
thanks again for your support

**Comment by ita1024** [comment]
Methods that create Node objects are not safe in general. Nodes objects should be declared/created before the build starts.

Use `self.generator.bld.bldnode` from a task method or `self.bld.bldnode` from a task generator method.

**Comment by dbacchet** [comment]
`self.generator.bld.bldnode` and `self.bld.bldnode` both return the variant build dir, not the build dir corresponding to the actual script file being processed.
For example, if in the task generator i add:
```
print self.bld.bldnode.abspath()
print self.path.get_bld().abspath()
```
I get:
```
/Users/dbacchet/dev/MyProj/build/release
/Users/dbacchet/dev/MyProj/build/release/tools/sim/sandbox/sample_app
```

adding `self.path.get_bld().abspath()` as an additional attribute in `create_task` solved my problem though.
Thanks for your explanation and your support!
