### ISSUE TITLE
waf.bat does not support Python3 installations on Windows

### ISSUE THREAD

**Issue by WaffleSouffle** [waf-project/waf#1940]
Python3 does not necessarily add python.exe to the PATH on installation.
Instead there is a launcher "py.exe" for Python which the user can configure.
Amongst other things this alters how python shebang lines are handled.

The waf.bat file bypasses this mechanism by trying to invoke python directly, bypassing py.exe.

**Comment by ita1024** [comment]
Yes?

**Comment by ita1024** [comment]
Can we close this then, or?
