### ISSUE TITLE
Autoconfig doesn't work when removing only the build folder

### ISSUE THREAD

**Issue by jhasse** [waf-project/waf#1944]
wscript:
```python
from waflib import Configure
Configure.autoconfig = True
```

When I run `rm -rf build` Waf won't reconfigure the project:

```
$ ./waf
The project was not configured: run "waf configure" first!
```

I'll also have to delete the lock file.

**Comment by ita1024** [comment]
Configure.autoconfig = 'clobber'

**Comment by ita1024** [comment]
Call `waf distclean` instead.

**Comment by jhasse** [comment]
I know that `waf distclean` works, but I want it to also work when using `rm -rf build`.

Using `Configure.autoconfig = 'clobber'` seems to work, why did you delete that post?

**Comment by jhasse** [comment]
Ups, no you're right `'clobber'` doesn't fix it. Using `waf distclean` is the only way. Would you accept a patch which makes autoconfigure work when the build dir has been removed?

**Comment by ita1024** [comment]
Probably yes; it depends on the patch.
