### ISSUE TITLE
"waf install" rebuilds several files

### ISSUE THREAD

**Issue by voxik** [waf-project/waf#1948]
I am helping with packaging diorite library [[1]] into Fedora. This library is written in Vala and using waf for build.

When Fedora version of Waf is used (1.9.9), after successful call to "waf build", the "waf install" rebuilds again part of the library and I can't figure out what could be the reason. Here is the log [[2]]

This is not issue when Waf bundled with diorite (1.7.14) is used.

[1]: https://github.com/tiliado/diorite/
[2]: https://kojipkgs.fedoraproject.org//work/tasks/3415/19093415/build.log

**Comment by ita1024** [comment]
Use the version provided by the project and not the version provided by the system. Marking as invalid, unless you are the library author updating the waf file for your project.

**Comment by voxik** [comment]
I'd like to submit PR updating the waf file of the project and I'd appreciate your help. I was expecting that I might find here more insight into buildsystem then the author of the library will probably ever have (with all due respect).

**Comment by ita1024** [comment]
I have several concerns:
1. The author is not necessarily passionate about following the latest Waf version, especially if the current 1.7 version works fine
1. Usage of system-provided Waf versions has always been discouraged for this (and other) reasons
1. You may be preparing a Distro-only enhancement without even informing the concerned project maintainer

As for the technical aspects, there is a regression in the Vala processing. Unnecessary vapi include paths are added to the installation build, causing unnecessary recompilations. A fix is present on the master branch (Waf 1.9.10).

**Comment by voxik** [comment]
Thank you. I tested 3de21ec448eb42 and it fixes the issue.

**Comment by ita1024** [comment]
FYI waf 1.9.10 was released today.
