### ISSUE TITLE
Poor performance when -v is passed

### ISSUE THREAD

**Issue by jpalus** [waf-project/waf#1950]
In my Linux distribution of choice the preferred way of building packages is with verbose output so it's always clear which compiler gets invoked or what flags are used. For this reason -v is passed in waf based builds but it appears to cause major performance degradation. For example on my machine build of mpv takes 15s (waf build -j8) while with added -v it takes 85s (waf build -j8 -v) which makes pretty significant difference with -v being 5.5 times slower. Not sure though whether it is expected behavior or bug.

**Comment by ita1024** [comment]
This is somewhat expected: the -v option turns on expensive verifications to check the build scripts for errors and mistakes.

Removing some logging may impact mpv positively, but we cannot do much more than that, and builds do not all have the same performance characteristics.

**Comment by jpalus** [comment]
Just reporting back that changes in version 1.9.11 made a huge difference and now verbose output has negligible impact on performance. Thanks!
