### ISSUE TITLE
Preprocessor reads dynamically-generated source code before generation is complete

### ISSUE THREAD

**Issue by cconverse711** [waf-project/waf#1951]
We've encountered a problem where the waf C preprocessor tries to read from a generated file before the file has finished being written to disk. This causes build problems because the #endif for an include guard isn't being seen.

The generated file is being generated by an application run by a waf rule, and we have additional support code to enforce that the dependencies are set properly. This seems to work except for the problem mentioned above, which occurs inconsistently.

Here is our additional support code, below:
```
from waflib import Utils
from waflib.TaskGen import after_method
from waflib.TaskGen import before_method
from waflib.TaskGen import feature

@feature('*')
@after_method('process_rule')
@after_method('apply_link')
def AddRunsAfterDependencies(project):
    dependency_projects = []
    dependency_names = Utils.to_list(getattr(project, 'runs_after', [])
    for dependency_name in dependency_names:
        dependency_project = project.bld.get_tgen_by_name(dependency_name)
        dependency_project.post()
        dependency_projects.append(dependency_project)

    for dependency_project in dependency_projects:
        for dependency_task in dependency_project.tasks:
            for task in project.tasks:
                task.set_run_after(dependency_task)

@feature('*')
@before_method('process_rule')
def ResolveDynamicSource(project):
    dynamic_sources = getattr(project, 'dynamic_source', None)
    if not dynamic_sources:
        return

    project.runs_after = Utils.to_list(getattr(project, 'runs_after', [])
    project_names = Utils.to_list(dynamic_sources)
    project.runs_after.extend(project_names)

    for project_name in project_names:
        referenced_project = project.bld.get_tgen_by_name(project_name)
        referenced_project.post()

        referenced_outputs = []
        for task in referenced_project.tasks:
            referenced_outputs.extend(task.outputs)

        project.source.extend(referenced_outputs)
```

**Comment by ita1024** [comment]
I believe that you have set the build order incorrectly, but if you think otherwise, then please upload a small test case.

It is sometimes easier to set the build order explicitly, for example: https://github.com/waf-project/waf/blob/master/demos/c/program/wscript_build#L5 may be more efficient and less error-prone than the `n*m` tasks ordering in `AddRunsAfterDependencies`.

**Comment by ita1024** [comment]
Re-open with a testcase.
