### ISSUE TITLE
False rebuild triggered

### ISSUE THREAD

**Issue by bbalp** [waf-project/waf#1955]
(I may have misunderstood something.)

When building a second time without changing anything, envhash is computed different: the list of env vars printed is the same, but some items are in a different order. The items that may change of order seem all related to the vars provided to the buildcontext: includes, source, moc, which are "translated" in the list with relative path to each involved directory in the build.

It feels like there is a sort() missing somewhere in waf to compute this envhash...

**Comment by ita1024** [comment]
The value envhash is calculated consistently, therefore additional  sorting would be harmful. Check your scripts for mistakes (in particular with dicts).

**Comment by bbalp** [comment]
I checked my scripts from the beginning. I found my mistakes. :)
