### ISSUE TITLE
cpplint: Python 2.x import name collision

### ISSUE THREAD

**Issue by akira-baruah** [waf-project/waf#1960]
Under Python 2.x `import` semantics, the `cpplint` tool tries to import itself, rather than the upstream `cpplint` module. When run using Python 2, the tool raises `AttributeError: 'module' object has no attribute '_cpplint_state'` when it tries to access objects in the upstream `cpplint` module.

**Comment by ita1024** [comment]
Is there a way to fix this without absolute imports?

**Comment by ita1024** [comment]
I see. The mistake was to let a module named "cpplint" in in the first place.
