### ISSUE TITLE
add_group/set_group question/issue?

### ISSUE THREAD

**Issue by Riziero** [waf-project/waf#1962]
Hello,

been messing around with this problem for hours.
Say I have 3 task generators A, B and C.

What I'd like to achieve:
1 -  get waf  to only generate tasks for A (by using--targets=A)
2 -  get waf  to only generate tasks for B (by using--targets=B)
3 - get waf to also create B's tasks when using --targets=C

The closer I managed to get is 1) ok 2) ok but then 3) also causes A's tasks to be generated.

I've also tried to use the other approach suggested in the docs: making C call B.post()
This seems to work well but unfortunately it's different. B.post() does not in fact guarantee that B's tasks have run, which only seems to be doable with groups and POST_LAZY mode.

Many thanks

**Comment by ita1024** [comment]
Having a task generator method on C call B.post() does not force A to create its tasks when calling `waf --targets=C`. This is similar to calling `waf --targets=B,C`

Another similar and rather simple approach can be to call waf from a sub-folder containing a wscript with particular task generator.

Now, having task objects created does not mean that those task objects will be processed, and in particular this does not imply anything regarding the order of execution of such tasks. If you are trying to enforce a constraint on the build order, make sure to have all input/output files declared on each task object, and if necessary add explicit build order constraints between those tasks (after/before/ext_in/ext_out).

Does this answer your question?

**Comment by Riziero** [comment]
Thanks for the answer.

I will try what you say and get back to you.

**Comment by ita1024** [comment]
Try and see.

**Comment by Riziero** [comment]
Didnt get exactly what I was looking for but something good enough. Ended up using a combination of node dependencies, after/before "modifiers " and set_run_after(tsk) method.

One very last thing - is there way to get waf not to fail the build when a task fails to create an output node?

I very much appreciate your help!

**Comment by ita1024** [comment]
The point of target nodes is to stop the build when they are missing.

**Comment by Riziero** [comment]
So I guess a PR about that would be out of question right?

**Comment by ita1024** [comment]
Correct.
