### ISSUE TITLE
Update comment and docs about supportes Visual C++ / msvcr versionsd

### ISSUE THREAD

**Issue by htgoebel** [waf-project/waf#1983]
While #1925 adds support for Visual Studio 2017, the [code](https://github.com/waf-project/waf/blob/master/waflib/Tools/msvc.py#L41) and the [documentation](https://waf.io/apidocs/tools/msvc.html) say only up to Visual Studio 2013 is supported. Please update teh documentation. Thanks.

**Comment by ita1024** [comment]
Nothing concrete suggested, closing now.

**Comment by htgoebel** [comment]
> Nothing concrete suggested

Huh? I asked you to update the comments in the code and the documentation to match what is actual true – even linking to the relevant places. How could this be more concrete?

Should I have written:
> Put the correct supported versions  [here](https://github.com/waf-project/waf/blob/master/waflib/Tools/msvc.py#L41) and [here](https://waf.io/apidocs/tools/msvc.html) 

?
