### ISSUE TITLE
Break out license file

### ISSUE THREAD

**Issue by jakirkham** [waf-project/waf#1986]
While I'm aware the license is [here]( https://github.com/waf-project/waf/blob/waf-1.9.12/waf-light#L5-L31 ). Would be good to have a proper license file, which should make it easier to find as well. Thanks.

**Comment by ita1024** [comment]
https://github.com/waf-project/waf/blob/master/waf-light is simple enough

**Comment by jakirkham** [comment]
Perhaps for reference.  However we would like to include a clear license file in a packaging we are building at conda-forge. Having to extract it from `waf-light` is not great. So could we please have a license file?

**Comment by jakirkham** [comment]
Any thoughts on this given the context noted above?

**Comment by ita1024** [comment]
The answer is still no.

**Comment by jakirkham** [comment]
What about having a CLI option that prints out the license?

**Comment by ita1024** [comment]
What about doing that in your project?

**Comment by jakirkham** [comment]
I don't follow. We are a packaging ecosystem. Not a project vendoring waf. How does that help?

**Comment by ita1024** [comment]
I do not follow either. Why would you want to print the license? Is doing a "head" over the first few lines too difficult? And what is in for us aside from additional maintenance complexity?

**Comment by jakirkham** [comment]
> Why would you want to print the license?

So we can clearly communicate the licensing constraints to the end user. TBH having a command line option to print license files is pretty ubiquitous amongst CLI tools. In fact many people view clause 2 of the BSD 3-clause license as requiring this of a binary.

```
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
```

Though was only offering this as an option as it seems including a license file in the repo won't work. That said, would still be happy having a license file added to the repo as an alternative.

> Is doing a "head" over the first few lines too difficult?

So what if that section is moved? What if it is assigned it to a variable or similar? What if a docstring is added? Any of these would break this `head` strategy that you suggest. IOW the `head` strategy is fragile in a way that either having a license file or having the CLI print it would not be. Both provide standard mechanisms of accessing the license.

> And what is in for us aside from additional maintenance complexity?

As already noted, to clearly communicate the license constraints to the end user. Am merely trying to facilitate that communication so that your rights and your users rights are respected. At the end of the day, the clear communication is in all parties best interest and it is one of the few protections that BSD licenses hold dear.

I'm unclear on how adding a license option to print out the license or adding a license file in the repo substantially increase maintenance complexity. Could you please help me understand this? Again if having a license file feels less complex, that is an option we could try instead. That said, I may not understand what your requirements are. Maybe some more insight into your requirements will help us arrive at an acceptable solution.
