### ISSUE TITLE
Question: any way to get ant_glob to only consider the source folder?

### ISSUE THREAD

**Issue by Riziero** [waf-project/waf#1989]
I have to do something like

src_nodes = [node for node in tg.path.ant_glob(['Data/**/*','Engine/**/*']) if node.is_src()]

to filter them.
I looked it up and it seems like there used to be a bld=True/False param that's now gone.

**Comment by ita1024** [comment]
The `ant_glob` method can be used in more contexts that just the build phase, so it cannot hold information regarding the build directory. The change was made a long time ago (waf 1.5?).

Unless the build directory is under `Data` or `Engine`, that filter seems unnecessary. A more generic filter system could use the `excl` parameter as in `bld.path.ant_glob('**', excl=['build/*'])`.

**Comment by Riziero** [comment]
Thanks for that. This actually gave ant_glob a huge boost.
