### ISSUE TITLE
question: is waf on Windows supposed to spawn processes or threads as consumers?

### ISSUE THREAD

**Issue by Riziero** [waf-project/waf#1993]
Hello,

I always assumed it was threads. Though what I see from task manager is the following:

![image](https://user-images.githubusercontent.com/965018/28118697-611a9c62-6712-11e7-9546-472f4917d33d.png)

is that the standard behavior?
I am using waf 1.9 with python 3.52

Thanks.

**Comment by ita1024** [comment]
Yes: https://github.com/waf-project/waf/blob/master/waflib/Utils.py#L940
