### ISSUE TITLE
waflib sqrt function detection does not work with clang/libc++

### ISSUE THREAD

**Issue by m-gupta** [waf-project/waf#1997]
When clang is used with libc++ as the library, following errors are raised when checking sqrt function. libc++ is more stringent than libstdc++ regarding c++ standards and the error message appears correct.

I see two ways of fixing this issue that are stated at the end.

---- Error Msg Section -----
Checking for function sqrt
==>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdint.h>
#include <stdio.h>
#include <jpeglib.h>
#include <math.h>

        int main(int argc, char** argv) {
        void (*p)();
        (void)argc; (void)argv;
        p=(void(*)())(sqrt);
        return !p;
}

<==
[1/2] cxx: build/.conf_check_587534131e3a55f2f798deea467ce099/test.cpp -> build/.conf_check_587534131e3a55f2f798deea467ce099/testbuild/test.cpp.1.o
^[[0m
['clang++', '-O2', '-pipe', '-O2', '-pipe', '-O2', '-pipe', '-march=corei7', '-g', '-stdlib=libc++',  '-DHAVE_STDLIB_H=1', '-DHAVE_STRING_H=1', '-DHAVE_UNISTD_H=1', '-DHAVE_STDINT_H=1', '-DHAVE_STDIO_H=1', '-DHAVE_JPEGLIB_H=1', '-DHAVE_MEMSET=1', '../test.cpp', '-c', '-o', 'test.cpp.1.o']
err: ../test.cpp:12:16: error: address of overloaded function 'sqrt' does not match required type 'void ()'
        p=(void(*)())(sqrt);
                      ^~~~
../../../../../../../../../usr/include/c++/v1/math.h:934:46: note: candidate function has different number of parameters (expected 0 but has 1)
inline _LIBCPP_INLINE_VISIBILITY long double sqrt(long double __lcpp_x) _NOEXCEPT {return ::sqrtl(__lcpp_x);}
                                             ^
../../../../../../../../../usr/include/c++/v1/math.h:933:46: note: candidate function has different number of parameters (expected 0 but has 1)
inline _LIBCPP_INLINE_VISIBILITY float       sqrt(float __lcpp_x) _NOEXCEPT       {return ::sqrtf(__lcpp_x);}
                                             ^
../../../../../../../../../usr/include/bits/mathcalls.h:156:13: note: candidate function has different number of parameters (expected 0 but has 1)
__MATHCALL (sqrt,, (_Mdouble_ __x));
            ^
../../../../../../../../../usr/include/c++/v1/math.h:940:1: note: candidate template ignored: failed template argument deduction
sqrt(_A1 __lcpp_x) _NOEXCEPT {return ::sqrt((double)__lcpp_x);}
^
1 error generated.
---- End of Error Msg Section -----

How to fix:
a) Since the above code is C code, use C compiler to check for function presence.
Or
b) Special case checks for sqrt function (and similar functions) as below. 

```
--- old/waflib/Tools/c_config.py
+++ new/waflib/Tools/c_config.py

+SNIP_FUNCTION_DOUBLE='''
+       int main() {
+       double (*p)(double);
+       p=(%s);
+       return 0;
+}
+''

-               kw['code']=to_header(kw)+SNIP_FUNCTION%fu
+               if (fu == 'sqrt') :
+                       kw['code']=to_header(kw)+SNIP_FUNCTION_DOUBLE%fu
+               else:
+                       kw['code']=to_header(kw)+SNIP_FUNCTION%fu
```

**Comment by ita1024** [comment]
This functionality is being removed in waf-2.0 (which will be released in about a month) because configuration tests are essentially project-dependent. It is also not fixable in waf 1.9 without breaking some other tests so we will not take any action on this.
