### ISSUE TITLE
Autoconfigure and NO_LOCK options

### ISSUE THREAD

**Issue by shoover** [waf-project/waf#1998]
To build a specific configuration of a library for a variant of an application, I set WAFLOCK and invoked the library build external to the source, as in:

    set WAFLOCK=.lock-wafbar & waf --no-lock-in-run --no-lock-in-top --top=/foo --out=/bar --autoconfigure --foo=baz build

Autoconfigure was set via a custom --autoconfigure flag in the wscript so the application build script (an external build system) could pass flags and not require an explicit configure step.

When the above lock flags are combined with autoconfigure functionality, the result is an infinite configuration loop because the successful configuration is written to out_dir but the recursive call to build checks Context.top_dir alone.

Would it make sense to update autoconfigure to try loading the lockfile in out_dir as well (and run_dir)?

**Comment by ita1024** [comment]
How did such a twisted case arise?

**Comment by shoover** [comment]
The library is built and tested in the source directory with various configurations (x86, x64), variants (debug, release), and custom flags (depend on a third party library or not). Additionally, an application relies on one specific configuration and variant. The idea is to let the application build the library with control of its own configuration and build folder, with no effect on the source folder. Autoconfiguration of the library is a nice convenience since the application build does not require a configure step of its own (Visual Studio C#, in this case). It is ok to allow the run/top lock in this case, but it seemed worth asking.

**Comment by ita1024** [comment]
How about running the waf command from the build directory instead of from the top directory?

**Comment by shoover** [comment]
The waf command is run from an unrelated Visual Studio project directory. The build directory is known in the msbuild project but I haven't tried changing to the build directory explicitly since it would be an extra command which is not otherwise needed since the combination of the waf --out flag and WAFLOCK segregate the build directory and configuration as expected.

I have moved on by simply removing the --no-lock flags. Allowing the lock file to be written to the top dir and run dir is fine for my need. Thanks for your feedback.
