### ISSUE TITLE
Python 2 UnicodeDecodeError in emit

### ISSUE THREAD

**Issue by vedranmiletic** [waf-project/waf#2001]
I'm trying to move ns-3 from Waf 1.8 to Waf 1.9 ([wscript changes](https://gist.github.com/vedranmiletic/6b50239c2ede59e91d991fcdaed507ef)) and I believe I encountered a bug. The code:

```
def configure(conf):
    int64x64_impl = Options.options.int64x64_impl
    if int64x64_impl == 'default' or int64x64_impl == 'int128':
        have_uint128  = conf.check_nonfatal(type_name='uint128_t',
                                            define_name='HAVE_UINT128_T')
        have__uint128 = conf.check_nonfatal(type_name='__uint128_t',
                                            define_name='HAVE___UINT128_T')
        if have_uint128 or have__uint128:
            int64x64_impl = 'int128'
        else:
            int64x64_impl = 'cairo'
```

results in the following during `./waf configure`:

```
Checking for type uint128_t                                        : Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 30: ordinal not in range(128)
Logged from file Context.py, line 183
not found
```

This does not happen in Waf 1.8.19 (so I presume it would qualify as a 'regression') with Python 2 or 3 nor does it happen with Waf 1.9.12 when Python 3 is used. The only affected combination is Waf 1.9.12 (and, of course, 2.0pre4) and Python 2.

**Comment by ita1024** [comment]
Can you retry with Python2 and the latest code from the master branch?

**Comment by vedranmiletic** [comment]
I have checked latest `master` and this issue seems fixed. However, there seems to be another issue which I have to investigate (and report if it's on Waf's side), so please don't release 1.9.13 yet.

**Comment by ita1024** [comment]
You could try the branch waf-2.0 too.

**Comment by vedranmiletic** [comment]
The issue was on our side, so 1.9.13 is good to go as far as I care. As for 2.0, it has other API changes I have to adjust towards. That's the next step after I verify everything is working with 1.9.

**Comment by ita1024** [comment]
Waf 1.9.13 will be released this weekend.

**Comment by ita1024** [comment]
Waf 1.9.13 was released some time ago, so I think that this issue can be closed.
