### ISSUE TITLE
Empty def file using x86_64-w64-mingw32-gcc

### ISSUE THREAD

**Issue by 7heW4yne** [waf-project/waf#2008]
I have a Windows 10 system, running an ubuntu linux in VirtualBox (using my [aubio-Vagrant-Script](https://github.com/7heW4yne/aubio-Vagrant-Script)). In the virtual machine I cross compile [my fork of the aubio project](https://github.com/7heW4yne/aubio) (uses the syms extra of waf 1.9.13 to create a def file for the dll).

For the win32 target (using CC=i686-w64-mingw32-gcc and NM=i686-w64-mingw32-nm) everything works fine and the def file contains 416 exported symbols.
But building for win64 (CC=x86_64-w64-mingw32-gcc and NM=x86_64-w64-mingw32-nm) produces an empty def file (no symbols).

I did some testings and came to the result, that the problem is probably the combination of `x86_64-w64-mingw32-gcc` and `DEST_BINFMT == pe`. The DEST_BINFMT makes [syms expect preceding _](https://github.com/waf-project/waf/blob/master/waflib/extras/syms.py#L30). BUT if I call `nm -g ...` on the win64 version of the dll (built with `x86_64-w64-mingw32-gcc`), there is **NO** preceding _.
The problem seems to be `x86_64-w64-mingw32-gcc` specific, because all exported symbols of the win32 dll have the preceding _.

Does anybody has an advice how to fix that? Or is it possible add an exception to the syms extra to handle `x86_64-w64-mingw32-gcc` specifically?

**Comment by ita1024** [comment]
No idea.

**Comment by 7heW4yne** [comment]
Hm ... At this state the whole symbol stuff is quiet useless for cross compiling.
I need a valid def file and the cross compiled dll on my Windows machine to create an import lib using: 
`lib /DEF:<def-file> /NAME:<dll-file> /OUT:<importlib-file>`

Anyway,,, I had yet another look in the `syms.py` and now I have a question:
Is there a reason why the preceding underscore is mandatory in [syms.py @ line 31](https://github.com/waf-project/waf/blob/master/waflib/extras/syms.py#L31)?

I a short test this slightly changed regular expression worked well in win32 AND win64:
`re_nm = re.compile(r'(T|D)\s+_?(?P<symbol>' + self.generator.export_symbols_regex + r')\b')`
(I added a ? after the _)

Would it be possible to add this to syms.py or is there a reason why the _ is mandatory?

**Comment by ita1024** [comment]
This code was only meant as an example. If you believe that you have a better implementation, then please submit a pull request.

**Comment by 7heW4yne** [comment]
Sorry that I ask before I change something in a project I'm not familiar with. Sometimes things are designed as they are for a specific reason....
And I didn't know that "extras" is just another word for "examples".

We don't need waf & syms to get a valid def file. We already solved the problem. But I wanted to give it a try if it's already included in waf.

But now I think, I will stop working on that. It's not what you say, but the way you say it. And I don't have to spend my time for projects, where the owner gets stroppy with somebody who ask for context.

Bye!

**Comment by ita1024** [comment]
The "extras" folder contains a collection of modules and examples that can be useful but that are not part of waf.
