### ISSUE TITLE
Calling find_resource on string in protoc.py

### ISSUE THREAD

**Issue by RomanCPodolski** [waf-project/waf#2009]
The block that finds imported files in `.proto` files make a wrong assumption about the contents of `self.env.INCPATHS` - it assumes this list contains nodes, while it contains strings. Therefore the plugin will fail with an error message when called on a project that's useing the import feature of protobuf. 

https://github.com/waf-project/waf/blob/322f447e0aed9d6a1c8e5f59bb929239d361a0d3/waflib/extras/protoc.py#L59-L70

this issue can be solved by creating a node from the string stored in incpath

**Comment by ita1024** [comment]
It would be nice to have a better example in the folder `playground/protoc` to prevent future regressions. Could you perhaps suggest an improvement?

**Comment by RomanCPodolski** [comment]
This one should be fixed now. Still, there can be various improvements made to the protoc extra. Automatically compiling .proto files in the right order for them to be included in the c++ compile step, is just one I can think of now.

**Comment by ita1024** [comment]
I am not sure what you mean by "right order". You may want to amend the existing example.
