### ISSUE TITLE
Default implementation of 'distclean' not compatible with '--no-lock-in-top' option

### ISSUE THREAD

**Issue by captainmalloc** [waf-project/waf#2011]
Hi,

Current default implementation of the 'distclean' command in 'waflib.Scrypting.py' do nothing if no lock file is available in 'top_dir':

```
def distclean(ctx):
	'''removes the build directory'''
	lst=os.listdir('.')
	for f in lst:
		if f==Options.lockfile:
			...
		if not Options.commands:
			...
```

It would be great to enhance default implementation and make it capable of removing 'out_dir' even if the '--no-lock-in-top' is enabled.

Adriano

**Comment by ita1024** [comment]
This seems dangerous so we won't be taking any action on this matter.

**Comment by captainmalloc** [comment]
May I ask you why do you think it is dangerous? I did implement a local version of "distclean" where I am loading the out directory lock file, when it exists, instead of the one in top_dir and it seems to work fine.

**Comment by ita1024** [comment]
If you think that this is possible, then feel free to prove me wrong and to submit a pull request.
