### ISSUE TITLE
Append dependent static libraries when building a static library

### ISSUE THREAD

**Issue by dbogdanov** [waf-project/waf#2014]
When building a static library with ```stlib```, is that possible to append all the dependent static libraries? I am buiding a static libA which depends on static libX and libY. I want them all be grouped together into one static lib file.

I found a [related question on stackexchange](https://stackoverflow.com/questions/36840071/waf-combine-static-libraries).

**Comment by ita1024** [comment]
No, static libraries must be fully specified in the correct order for each target that uses them.
