### ISSUE TITLE
Error with waf 1.9.13

### ISSUE THREAD

**Issue by nowox** [waf-project/waf#2015]
I am using the GomSpace code for a nanomind shipped with a `waf` script which is not compatible with my Cygwin installation. 

So I cloned the latest `waf` version, built the `waf` script and copied it to my project with the name `waf_`

With this new version I got an error about an output target `nanomind.elf` that should not be used to create the Eclipse target. 

$ ./waf --version
waf 1.8.7 (e5056b9ade7bb224f53baab13a0ce136344ab602)
$ ./waf_ --version
waf 1.9.13 (66f1d5bc9472557082b82aced1cbf6a9d6cd1a27)

```
$ ./waf --version
waf 1.8.7 (e5056b9ade7bb224f53baab13a0ce136344ab602)
$ ./waf_ --version
waf 1.9.13 (66f1d5bc9472557082b82aced1cbf6a9d6cd1a27)

$ ./waf configure eclipse
Setting top to                           : /cygdrive/c/user/Home/git/nanomind
Setting out to                           : /cygdrive/c/user/Home/git/nanomind/build
[...]
Clients included:                        : a712, nanopower, nanopower-bpx, nanocam2, nanocom-ax, nanocom, nanohub
'configure' finished successfully (4.601s)
Generating Eclipse CDT project files
include: build/include
[...]
include: lib/libparam/src/lock
'eclipse' finished successfully (0.390s)


$ ./waf_ configure eclipse
Setting top to                           : /cygdrive/c/user/Home/git/nanomind
Setting out to                           : /cygdrive/c/user/Home/git/nanomind/build
[...]
Clients included:                        : a712, nanopower, nanopower-bpx, nanocam2, nanocom-ax, nanocom, nanohub
'configure' finished successfully (6.354s)
Generating Eclipse CDT project files
include: build/include
[...]
include: lib/libparam/src/lock
source not found: 'nanomind.elf' in bld(target=['nanomind.bin'], idx=3, meths=['process_rule', 'process_source'], rule='${OBJCOPY} -O binary -j .text -j .data -j.relocate -j.sram ${SRC}
```

What could be the issue and how can I investigate on it?

**Comment by nowox** [comment]
I've bisected and the issue appears between `waf-1.8.9` and `waf-1.9.0`

```
42622a6e523c71a47fbdc14f83797353b0812c71 is the first bad commit
commit 42622a6e523c71a47fbdc14f83797353b0812c71
Author: Thomas Nagy <tnagy@waf.io>
Date:   Mon Mar 7 23:38:14 2016 +0100

    Do not cache Waf tools in configure

:100644 100644 94305611db62960e5d0903ce49f5ab8d1a5c2835 02922ec6a0b2fd3a07e9ad37e6cec522404a5454 M      ChangeLog
:100644 100644 5b7b30b2425fb51bb1eda9e89050b6c1dffbfcf7 0580a5625116f6b3ca0769a590d51d7ecba2f5c6 M      TODO
:040000 040000 46e26adadc806ed1ffc655375d98d65b7105c86c 26dfc49fd32c098515d47d4ea461433373526f0c M      waflib
```

**Comment by ita1024** [comment]
Are you the maintainer of that project? If this is not the case, please contact the maintainer.

The project internal modules may require to be loaded in a particular order in the configuration step. Caching configuration modules is disabled starting in waf 1.9.0 because it is unsafe; so you might need to update your copy to the latest version in the 1.8.x series (1.8.17).

**Comment by nowox** [comment]
Good to hear that. I am trying to contact the maintainer to check with him. Is there a documentation on how I should order the configuration modules in the `wscript` file?

**Comment by ita1024** [comment]
Check for modules called several times and overwriting data from other modules.

**Comment by ita1024** [comment]
There does not seem any action to take here, so the case is closed.
