### ISSUE TITLE
Split Python packages problematic for unit testing

### ISSUE THREAD

**Issue by xbreak** [waf-project/waf#2017]
Hi,

This is a question on how to best deal with Python unit tests with build time dependencies that you want to execute in the waf context (no installation). I'd appreciate your input and support on this.

I started to improve the `pytest` feature to add support for library dependencies to be able to populate `LD_LIBRARY_PATH` and `PYTHONPATH` for `pyext` and normal libraries correctly so that unit tests for e.g. a Python package that depend on a C extension would work.

During this work I came across the general problem with unit testing in Python where if you create a Python extension or generate Python code that should be installed inside a Python package we currently end up with a split package where the generated parts are located in _build_ and the rest remain in _source_, only to be merged when installed. 

For example, consider a package `foo` that wraps the extension `foo.foo_ext`, this is what you could end up with (see build def [1]):

    .
    |-- build
    |   `-- src
    |       |-- foo
    |       |   `-- foo_ext.cpython-35m-x86_64-linux-gnu.so	# 'foo_ext' is correctly located inside the 'foo' package by specifying "target='src/foo/foo_ext'"
    |       `-- foo_ext.c.1.o
    |-- src
    |   |-- foo
    |   |   |-- foo.py	# "from foo import foo_ext" -> ImportError: cannot import name 'foo_ext'
    |   |   `-- __init__.py
    |   `-- foo_ext.c
    |-- test
    |   `-- test_foo.py
    `-- wscript

Since the package is split between _build_ and _source_ this does not work until they are merged. 

The project I'm working on will write unit tests in Python for code that has generated dependencies like C-extensions, Protobuf code, Qt resources/mocs to name a few, so this is something I'd really like to solve. 

How can we best support this? Could e.g. the `py` feature (optionally maybe) copy sources to _build_ to make the package complete there? This would be the simplest case for `pytest` to support since it would just be a matter of setting the correct `PYTHONPATH`.

Otherwise `pytest` would have to do it somehow. Although it's not clear to me at the moment how best to do it. Should it e.g. install its `py` dependencies to its own build node or merge "in situ"? And since the information on how to merge a package is not really explicit it might be problematic.

Thanks!

[1]:

    def build(bld):
        # Python C extension
        bld(name         = 'foo_ext',
            features     = 'c cshlib pyext',
            source       = 'src/foo_ext.c',
            target       = 'src/foo/foo_ext')

        # Python package under test
        bld(name         = 'foo',
            features     = 'py',
            use          = 'foo_ext',
            source       = bld.path.ant_glob('src/foo/*.py'),
            install_from = 'src')

        # Unit test
        bld(name          = 'foo_test',
            features      = 'pytest',
            use           = 'foo',
            pytest_source = bld.path.ant_glob('test/*.py'),
            ut_str        = '${PYTHON} -B -m unittest discover')

**Comment by ita1024** [comment]
I believe that it is up to you to come up with a solution for this particular problem. If the `py` feature is insufficient for your needs, you should either extend it or use it as a model to create your own.
