### ISSUE TITLE
dependency management with --target

### ISSUE THREAD

**Issue by dbacchet** [waf-project/waf#2025]
Hello,

in our build tree we have a rule-based task-gen that depends on outputs generated in other folders.
Calling `waf` from the root, everything works fine, but when we try to build just that target with `waf --targets=cat_hello` we get an error that says that the input file cannot be found.
If we do the same with a `program` task-gen, everything works fine even with `--targets`.
In both the `program` and the rule-based calls, we set the `use` flag to point to the target we depend from.

This archive contains a minimal test project to reproduce the problem: [waf_example.zip](https://github.com/waf-project/waf/files/1289445/waf_example.zip)

the folder structure is the following:
```
.
├── dir1
│   ├── hello_lib.c
│   └── wscript
├── dir2
│   ├── hello.c
│   └── wscript
├── waf
└── wscript
```
and the `wscript` file in dir2 is:
```python
def build(bld):
    bld.program(target='hello_exe',
                source='hello.c',
                use=['hello_lib'])
    
    bld(rule = 'cat ${SRC[0]} ${SRC[1]} > ${TGT}',
        features = 'use',
        use = 'hello_lib',
        target = 'cat_hello',
        source = [ '../dir1/libhello_lib.a', 'hello_exe'] )
```

this is the output in the different cases:
```
[~/dev/tmp/waf_example] $ ./waf
Waf: Entering directory `/Users/davide.bacchet/dev/tmp/waf_example/build'
[1/5] Compiling dir1/hello_lib.c
[2/5] Compiling dir2/hello.c
[3/5] Linking build/dir1/libhello_lib.a
[4/5] Linking build/dir2/hello_exe
[5/5] Processing cat_hello: build/dir1/libhello_lib.a build/dir2/hello_exe -> build/dir2/cat_hello
Waf: Leaving directory `/Users/davide.bacchet/dev/tmp/waf_example/build'
'build' finished successfully (0.160s)

[~/dev/tmp/waf_example] $ ./waf clean
'clean' finished successfully (0.009s)
[~/dev/tmp/waf_example] $ ./waf --target=hello_exe
Waf: Entering directory `/Users/davide.bacchet/dev/tmp/waf_example/build'
[1/4] Compiling dir1/hello_lib.c
[2/4] Compiling dir2/hello.c
[3/4] Linking build/dir1/libhello_lib.a
[4/4] Linking build/dir2/hello_exe
Waf: Leaving directory `/Users/davide.bacchet/dev/tmp/waf_example/build'
'build' finished successfully (0.646s)

[~/dev/tmp/waf_example] $ ./waf clean
'clean' finished successfully (0.009s)
[~/dev/tmp/waf_example] $ ./waf --target=cat_hello
Waf: Entering directory `/Users/davide.bacchet/dev/tmp/waf_example/build'
Waf: Leaving directory `/Users/davide.bacchet/dev/tmp/waf_example/build'
source not found: '../dir1/libhello_lib.a' in bld(use='hello_lib', target=['cat_hello'], idx=2, meths=['process_rule', 'process_source', 'process_use'], rule='cat ${SRC[0]} ${SRC[1]} > ${TGT}', _name='cat_hello', source=['../dir1/libhello_lib.a', 'hello_exe'], path=/Users/davide.bacchet/dev/tmp/waf_example/dir2, posted=True, features=['use']) in /Users/davide.bacchet/dev/tmp/waf_example/dir2
```

What's the best way to make the rule-based task-gen behave like `program`?

thanks!

**Comment by ita1024** [comment]
Have you tried the example called 'depends_on' in The Waf Book?

**Comment by dbacchet** [comment]
thanks, using that snippet the `depends_on` behavior works and is transitive also for rule-based tasks (like the `use` for C/C++).
Any reason why that is not enabled by default? would it be possible to add it for the next release?
thanks!

**Comment by ita1024** [comment]
Could you try replacing by `features="use"` in your code? This is a new thing.

**Comment by hazelnusse** [comment]
At the end of example 9.3.6 of the waf book, the execution of task A comes after that of task B. Is it possible with depends_on to enforce that all tasks from those listed in depends_on are finished before processing the dependent tasks?

**Comment by ita1024** [comment]
@hazelnusse This does not belong to this question (check the documentation for task order such as `ext_in/ext_out` or `run_after`).

**Comment by ita1024** [comment]
One month without a reply from the original requester, so this issue can be closed.

**Comment by hazelnusse** [comment]
@ita1024 Ok, I'll open the question in a separate issue.

**Comment by dbacchet** [comment]
sorry for the late answer.
I tried replacing the `depends_on` with `use` in the same code, like in the following snippet:
```python
    bld(rule = 'cat ${SRC[0]} ${SRC[1]} ${SRC[2]} > ${TGT}',
        features = 'use',
        use = ['hello_exe','hello_lib','hello2'],
        target = 'cat_hello',
        source = [ 'hello_exe', '../dir1/hello2', '../dir1/libhello_lib.a'])
```
but it does not work.
Tried with waf 2.0.1

**Comment by ita1024** [comment]
@dbacchet that works if c/c++ support is loaded, which is something you have obviously changed from your original question.

**Comment by dbacchet** [comment]
not really.
The example is the same and the main wscript file contains:
```python
def options(opt):
    opt.load('compiler_c')

def configure(cfg):
    cfg.load('compiler_c')

def build(bld):
    bld.recurse('dir1')
    bld.recurse('dir2')
```
so the c support should be loaded.

Attached the 2 updated examples:
[waf_example.zip](https://github.com/waf-project/waf/files/1389996/waf_example.zip)
[waf_example_use.zip](https://github.com/waf-project/waf/files/1389995/waf_example_use.zip)

The first one uses the `depends_on`, and seems to work fine:
```
[~/dev/tmp/waf_example] $ ./waf distclean configure
'distclean' finished successfully (0.007s)
Setting top to                           : /Users/davide.bacchet/dev/tmp/waf_example
Setting out to                           : /Users/davide.bacchet/dev/tmp/waf_example/build
Checking for 'clang' (C compiler)        : /usr/bin/clang
'configure' finished successfully (0.076s)
[~/dev/tmp/waf_example] $ ./waf --targets=cat_hello
Waf: Entering directory `/Users/davide.bacchet/dev/tmp/waf_example/build'
[0/7] Compiling dir1/hello_lib.c
[1/7] Compiling dir1/hello_lib.c
[2/7] Compiling dir2/hello.c
[3/7] Compiling build/dir1/hello1
[4/7] Linking build/dir1/libhello_lib.a
[5/7] Linking build/dir2/hello_exe
[6/7] Processing cat_hello: build/dir2/hello_exe build/dir1/hello2 build/dir1/libhello_lib.a -> build/dir2/cat_hello
Waf: Leaving directory `/Users/davide.bacchet/dev/tmp/waf_example/build'
'build' finished successfully (0.671s)
```

In the second one I replaced `depends_on` with `features = 'use', use = [...]` and I get:
```
[~/dev/tmp/waf_example_use] $ ./waf distclean configure
'distclean' finished successfully (0.003s)
Setting top to                           : /Users/davide.bacchet/dev/tmp/waf_example_use
Setting out to                           : /Users/davide.bacchet/dev/tmp/waf_example_use/build
Checking for 'clang' (C compiler)        : /usr/bin/clang
'configure' finished successfully (0.084s)
[~/dev/tmp/waf_example_use] $ ./waf --targets=cat_hello
Waf: Entering directory `/Users/davide.bacchet/dev/tmp/waf_example_use/build'
Waf: Leaving directory `/Users/davide.bacchet/dev/tmp/waf_example_use/build'
source not found: 'hello_exe' in bld(use=['hello_exe', 'hello_lib', 'hello2'], target=['cat_hello'], idx=2, tg_idx_count=5, meths=['post_the_other', 'process_rule', 'process_source', 'process_use'], rule='cat ${SRC[0]} ${SRC[1]} ${SRC[2]} > ${TGT}', _name='cat_hello', source=['hello_exe', '../dir1/hello2', '../dir1/libhello_lib.a'], path=/Users/davide.bacchet/dev/tmp/waf_example_use/dir2, posted=True, features=['use']) in /Users/davide.bacchet/dev/tmp/waf_example_use/dir2
```

What did I get wrong?

**Comment by ita1024** [comment]
Right, the order of methods does not guarantee that the tasks of the other targets are called before processing the rule attribute (`process_rule` comes before `process_use`).

You should keep your `depends_on` implementation because it is more generic than the `use` attribute processing. This is also a reason why a generic `depends_on` method is not really possible as it will need to be called before or after specific methods, and that cannot be specified in advance.
