### ISSUE TITLE
Utils.lib64() returns '' on x86_64 system, causes 64 bit libs to be installed to /usr/lib

### ISSUE THREAD

**Issue by simonvanderveldt** [waf-project/waf#2031]
When using waf on a x86_64 system which has a `/usr/lib32` directory results in `Utils.lib64()` returning `''` which is incorrect and causes 64 bit libs to be installed to `/usr/lib` which is only for 32 bit libs.

I don't know why the explicit check exists if `/usr/lib32` exists, but it seems like that check should be removed from https://github.com/waf-project/waf/blob/ad5dd18408f4150a11c2c718cc4feef310e73046/waflib/Utils.py#L818

**Comment by ita1024** [comment]
The defaults are known to work for most known setups. If you believe that the current solution is insufficient, make sure that your project sets up the relevant `conf.env.LIBDIR` variable or provide a patch with relevant system tests.

**Comment by simonvanderveldt** [comment]
@ita1024 Thanks for the quick response.

> If you believe that the current solution is insufficient,

Well, the problem is not that the current code is insufficient, it's wrong.
The only things it needs to check are if arch=x86-64 bit and if that's the case make sure that `/usr/lib64` actually exists and that's it.
But the current code also incorrectly checks if the for arch=x86-x64 non-relevant `/usr/lib32` directory doesn't exist.

I can make a PR to remove that check no problem, if there are existing tests I can check if they pass and update them.

**Comment by ita1024** [comment]
If checking if `/usr/lib64` were sufficient, then the code would not be like it is today.

There are no tests for this today, and this is a problem. If any change is made then tests must be added to prevent regressions (there are examples under the folder `tests`).

Note: a `--libdir` command-line option is already present.
