### ISSUE TITLE
Best way to handle cross-compilation of one set of sources to multiple targets

### ISSUE THREAD

**Issue by hazelnusse** [waf-project/waf#2037]
This is more of a question than an issue but since the mailing list is deprecated, I figured I'd post here.

I have a set of platform independent C and C++ source files that I need to cross compile for multiple target platforms (armv7m, x86-64, etc). These are not "variants" per say -- I need to build some programs/libraries for all these targets all the time. I am currently using a different bld.env per target platform, and have different toolchains configured per env.  I can activate the approprate env before building for each platform, and use a different target and/or name in the program/stlib/shlib but I'm wondering if there is a cleaner way that would allow something like the following:

```
bld.stlib(target = 'mylib', source = bld.path.ant_glob("mylib/*.c"),
         platforms = ['armv7m', 'x86-64'])
bld.program(target = 'myprogram', source = ['main.c'],
         use = 'mylib', 
         platforms = ['armv7m', 'x86-64'])
```

Is there a way to handle this other than creating separate targets per platform, i.e. something like:

```
env_org = bld.env
for p in ['armv7m', 'x86-64']:
    bld.env = bld.all_envs[p]
    bld.stlib(target = 'mylib' + p, source = bld.path.ant_glob("mylib/*.c"))
    bld.program(target = 'myprogram' + p, source = ['main.c'], use = 'mylib' + p)
bld.env = env_org
```

**Comment by ita1024** [comment]
Make your own task generator method to handle your `platforms` attribute.
