### ISSUE TITLE
extras/xcode6 tool stomps feature settings

### ISSUE THREAD

**Issue by rayalan** [waf-project/waf#2038]
In v2.0.0, the implementation of `def bind_fun(tgtype):` in xcode6.py (line 696) stomps on additional features being provided For example:

```
rv = bld.stlib('my_other_feature')
print(rv.features)  # This generates 'cxx cxxstlib', not 'my_other_feature cxx cxxstlib'
``` 
I suspect the fix is something replacing this line (714):
```
kw['features']=features
```
with 
```
kw['features']=Utils.to_list(kw.get('features', [])) + Utils.to_list(features)
```
The one caveat is that my proposed fix makes features a list, which I think is legal, but might cause downstream problems with interfaces that are expecting a string like the current implementation. Adding `' '.join(...)` might be better.

**Comment by ita1024** [comment]
There is no problem with downstream methods. Thank you for reporting this.

**Comment by rayalan** [comment]
This fixed the problem for me and seems to generally work.
