### ISSUE TITLE
back-recursing does not built target unless it will be reference via use statement

### ISSUE THREAD

**Issue by daniel-brosche** [waf-project/waf#2041]
Hello, 

I have figured out that recursing into another wscript will not always be processed as expected. 
I extended the use example to reproduce this issue. https://github.com/daniel-brosche/waf/commit/4f08cb343aded4721a9d51bf6a3747bd1fa8016e 

When I execute the playground/use/wscript it builts a shared object name libunused_lib.so (based on the playground/use/objects/unused_lib/wscript). This shared object will not be referenced by any other wscript / target. 
However I have created an second wscript at playground/use/objects/rel_program/ that can be executed as a top level wscript. This wscript does recurse into playground/use/objects/unused_lib/wscript. When I use it as top level wscript the target libunused_lib.so will not be built/created.
The only way to enforce the processing is to reference the unused_lib in rel_program or to call the post method as follows:
```
 bld.shlib(
        target='unused',
        source='unused.c',
        includes=INCLUDES,
        export_includes=INCLUDES,
        install_path=bld.env.LIBDIR,
        ).post()
```
We have also other bld / Task creation related calls where this behaviour is the same which means it will not be processed when recursing in a parent directory.

**Comment by ita1024** [comment]
This works exactly as designed. Use `waf --targets=*` if you want all targets to be posted.

**Comment by daniel-brosche** [comment]
Good to know that I can enforce this behaviour. The source of my confusion was that this behaviour is not consistent. When I execute `playground/use/wscript ` as top level wscript I actually don't need to use ` waf --targets=* ` but when I use `playground/use/objects/rel_program/wscript` as top level wscript it is required to get the same result. Both scripts recursing in `playground/use/objects/unused_lib/` but with different results regarding target processing.

**Comment by daniel-brosche** [comment]
I have also bld(...) calls they don't result in a target which can't be forced with ´--targets=*´.

**Comment by ita1024** [comment]
When building from a subfolder, the targets that are now below that subfolder are excluded in order to perform a simple partial build. The behaviour `--targets=*` may be set by default by setting for example `bld.targets='*'` but that is nonstandard.

All `bld()` yield a task generator object.

**Comment by daniel-brosche** [comment]
bld(.. , always=True) seems another way to force it. I found it in `playground/extern_makefile/just_make/wscript`. Thx. Now, I understand this kind of optimization.

**Comment by ita1024** [comment]
The keyword `always` is for forcing particular tasks to run (on a rule-based task generator); it does not force particular task generators to create create tasks (use the `post` method for that).
