### ISSUE TITLE
The color BLUE cannot be seen clearly on a black background.

### ISSUE THREAD

**Issue by rpuntaie** [waf-project/waf#2046]
Please use default colors that work well for WHITE AND BLACK backgrounds.
To experiment use:
https://snook.ca/technical/colour_contrast/colour.html#fg=33FF33,bg=333333
Using
https://askubuntu.com/questions/27314/script-to-display-all-terminal-colors
I've found these to work:

```sh
    for x in {0,1,2,3,4}; do 
        for i in {31,32,35,36}; do 
            for a in {40,47}; do 
                echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m "
            done
            echo
        done
    done
    echo ""
```

**Comment by ita1024** [comment]
The current color scheme works well where I looked. I will close this unless you have more specific.

**Comment by rpuntaie** [comment]
I tried to convince you to change BLUE already at my last pull request some time ago, without success :-) It is no big deal. I can't read it, but it is no important information anyway. I know, I can change it myself, but I prefer to use the main repo, if possible.
