### ISSUE TITLE
Cython playground example broken, can't build .pyx file: "*.pyx has no mapping in ['.c++', '.C', '.cxx', '.cc', '.cpp', '.c', '.py', '.obj', '.o', '.pc.in']"

### ISSUE THREAD

**Issue by simonvanderveldt** [waf-project/waf#2047]
How is one supposed to build a `.pyx` file using waf?
The example in `./playground/cython` seems to be broken. When I remove the references to `waflib.extras.cython` (so I can use waf downloaded from https://waf.io/waf-2.0.0) and try to build using waf 2.0.0 I get the following:
```
$ ./waf configure
Setting top to                           : /home/simon/src/tmp/waf/playground/cython 
Setting out to                           : /home/simon/src/tmp/waf/playground/cython/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'python'            : /usr/lib/python-exec/python3.4/python 
Checking for python version              : 3.4.5 
python-config                            : /usr/lib/python-exec/python3.4/python-config 
Asking python-config for pyembed '--cflags --libs --ldflags' flags : yes 
Testing pyembed configuration                                      : yes 
Asking python-config for pyext '--cflags --libs --ldflags' flags   : yes 
Testing pyext configuration                                        : yes 
'configure' finished successfully (0.480s)
$ ./waf          
Waf: Entering directory `/home/simon/src/tmp/waf/playground/cython/build'
Waf: Leaving directory `/home/simon/src/tmp/waf/playground/cython/build'
File /home/simon/src/tmp/waf/playground/cython/src/cy_ctest.pyx has no mapping in ['.c++', '.C', '.cxx', '.cc', '.cpp', '.c', '.py', '.obj', '.o', '.pc.in'] (load a waf tool?)

**Comment by ita1024** [comment]
If you want to build cython then you need to include `extras/cython.py` in your project. We do not include that extension.

**Comment by simonvanderveldt** [comment]
> If you want to build cython then you need to include extras/cython.py in your project. We do not include that extension.

Ah, OK. And the same goes for the cython example I guess?
How is one supposed to do so? Simply include the `cython.py` from this repo as `./extras/cython.py`?
And does one need to explicitly import/use it somehow?

**Comment by ita1024** [comment]
Either make your own waf file or include the file in your project and load it with something like `ctx.load('cython', tooldir='.')`. Does this answer your question?

**Comment by simonvanderveldt** [comment]
> Either make your own waf file or include the file in your project and load it with something like ctx.load('cython', tooldir='.'). Does this answer your question?

Thanks for the info, that does indeed answer my question:)
Might be a good idea to add some docs to the Cython playground example?

**Comment by ita1024** [comment]
The README file reads:
```
The Waf tools in waflib/extras are not added to the waf script. To add some of them, use
the --tools switch. An absolute path can be passed if the module does not exist under
the 'extras' folder:
$ ./waf-light --tools=swig
```

I am not certain that repeating the same thing in every project under the `playground/` folder would improve the situation, but thanks for asking.
