### ISSUE TITLE
WAFDIR enclosed in " not recognized

### ISSUE THREAD

**Issue by rpuntaie** [waf-project/waf#2048]
Setting `WAFDIR` in Windows `cmd` has no effect on waf.

```sh
    set WAFDIR C:\src\waf
```

A possible solution in the main waf file (waf-light):

```py
	#devs use $WAFDIR
	w=test(os.environ.get('WAFDIR', '').strip('"'))
```

but maybe one should do it only for Windows.

**Comment by ita1024** [comment]
I am not an expert, but I believe that the proper way of setting the variable in `cmd.exe` is with an equals sign:
```
set WAFDIR=C:\src\waf
```

Quote characters are unnecessary.

**Comment by rpuntaie** [comment]
`set` works with = and `setx` without. In my test the variable was set and it was with ", although I didn't type any quotes. Waf cannot handle the variable if it contains the path in quotes. I think, it should.
