### ISSUE TITLE
build cstlib, cshlib, and syms

### ISSUE THREAD

**Issue by piem** [waf-project/waf#2053]
hi,

I'm trying to figure out how to build those 3 targets. Starting from `playground/syms`, and applying these changes:

```diff
diff --git a/playground/syms/wscript b/playground/syms/wscript
index bc40f712..3740227c 100644
--- a/playground/syms/wscript
+++ b/playground/syms/wscript
@@ -7,5 +7,7 @@ def configure(ctx):
        ctx.load('compiler_c syms')
 
 def build(ctx):
-       ctx(features='c cshlib syms', source='a.c b.c', export_symbols_regex='mylib_.*', target='testlib')
+       ctx(features='c', source='a.c b.c', target='libobjs')
+       ctx(features='c cshlib syms', use = 'libobjs', export_symbols_regex='mylib_.*', target='testlib')
+       ctx(features='c cstlib', use = 'libobjs', target='testlib')
        ctx(features='c cprogram', source='main.c', target='app', use='testlib')
```

I get: `AttributeError: 'task_gen' object has no attribute 'compiled_tasks'`

If i move back the source to the static and shared lib, it works, but the source files are compiled twice.

**Comment by ita1024** [comment]
The `syms.py` file is provided as-is and seems to be designed to process a single target. You may want to extend it to support multiple targets.

**Comment by piem** [comment]
hi @ita1024 !

> The syms.py file is provided as-is

Thanks, I figured it doesn't come with coffee :-)

> and seems to be designed to process a single target. You may want to extend it to support multiple targets.

Any idea of an example I could follow that adds tasks to both objects and shared lib targets?

cheers, Paul

**Comment by ita1024** [comment]
See 210874d297147db24637e8b7751c2f0f9b98657d

**Comment by piem** [comment]
hi,

Side note: on windows/msvc, I had to use

```python
cmd = [self.env.LINK_CC, '/dump', '/symbols', binary_path]
```

instead of the original `dumpbin` command, since by default `self.env.DUMPBIN` is not defined and `dumpbin.exe` is not found in the `PATH`.

best, piem

**Comment by ita1024** [comment]
Could you write a configuration test to find the `dumpbin` program?

**Comment by piem** [comment]
Hi @ita1024 ,

sorry, I have no idea how i could do that.

As I mentioned in my previous message, using `link.exe /dump symbols` does the trick for me, so I don't need to look for `dumpbin`. Also, instead of writing a symbol file for each object file, and gather these symbols in a final step, I just generate the symbols from the `.lib` file. See [waf_gensyms.py](https://github.com/aubio/aubio/blob/master/waf_gensyms.py).

best, piem
