### ISSUE TITLE
Environment variables are not passed down to compiler checks

### ISSUE THREAD

**Issue by dschopf** [waf-project/waf#2057]
I try to use the MPI wrapper for compiling some C code. I works with the default GCC compiler but not when using a different compiler because the environment variables are not passed down to the compiler check.

This is a simple version of my wscript file
```
#!/usr/bin/env python
# encoding: utf-8

from waflib.Tools.compiler_c import c_compiler

def options(opt):
  opt.load('compiler_c')

def configure(cnf):
  cnf.env.CC = 'mpicc'
  cnf.env.OMPI_CC = 'clang'
  c_compiler['linux'] = ['clang']
  cnf.load('compiler_c')
```

Calling `./waf configure` fails with "could not configure a C compiler!" because mpicc is falling back to the default GCC compiler.

However, when calling `OMPI_CC=clang ./waf configure` everything works as expected.

I tried to debug this but I got lost in Tools/c_config.py:1012
```
env = conf.env.env or None
```
This seems strange to me, I could understand conf.env (which leads to followup issues) but conf.env.env is never set for me. As a result the env passed to cmd_and_log is actually always None.

So the question is if this is a bug or setting environment variables for compiler checks is simply not supported.

**Comment by ita1024** [comment]
`conf.env.env` is almost never set by default, but you can do it if you need to:

```python
def configure(conf):
    conf.env.env = dict(os.environ)
    ...
```
