### ISSUE TITLE
Question - node signature evaluation

### ISSUE THREAD

**Issue by Riziero** [waf-project/waf#2068]
I have a task that takes as input a node in the build directory. I could not understand why it did not re-run when the input was clearly changing. 

Until I debugged it and the following seems to be the culprit:
https://github.com/waf-project/waf/blob/waf-1.8/waflib/Node.py#L836

Input node's signature does not get evaluated again because is_bld() = True, therefore  prev_sig = new_sig ----> SKIP_ME

Could anyone elaborate on why this happens? How can I work it around?
Many thanks

**Comment by ita1024** [comment]
Have you tried updating your copy to Waf 2.0?

**Comment by Riziero** [comment]
I wish I could. Had to go back to 1.8 because 1.9 was spawning processes and not threads, which is not an option for me.

**Comment by ita1024** [comment]
Forcing a single process degrades performance, and many more processes are usually spawned during a build, so I would like to hear for the reasons to even consider that. If that is really necessary, look at the bottom of the Utils.py module to force a single process.

If you want to keep using Waf 1.8, then the build system must be informed of changes to the build directory such as file hashes changes.

**Comment by Riziero** [comment]
Hi and thanks for answering.

Reason is that I run waf through a commercial distribution tool (say DT) to distribute processes. What I am distributing is execs from inside threads. All my waf Tasks' run() function simply call cmd_and_log to spawn these processes that get then intercepted by the "Distro tool". This way, since subprocess (read cmd_and_log) releases the GIL, I can get waf to continuously pump processes into the "Distro tool" (like 100 and counting running at the same time).

To give you the idea, I actually have to tell DT to intercept processes named foo.exe, bar.exe and so forth.

I can not distribute a processes belonging to a pool.

**Comment by ita1024** [comment]
Have you forced a single process using the Utils.py hint?

**Comment by ita1024** [comment]
Ok.
