### ISSUE TITLE
[2.0.2] can not build mpv

### ISSUE THREAD

**Issue by alium** [waf-project/waf#2073]
Hi,
mpv use waf for build , but i can not build mpv with the last version 2.0.2. 
Error:
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status

* Node /tmp/makepkg/mpv/src/mpv-0.27.0/build/mpv.def is created more than once (full message on 'waf -v -v'). The task generators are:
  1. 'mpv' in /tmp/makepkg/mpv/src/mpv-0.27.0
  2. 'mpv' in /tmp/makepkg/mpv/src/mpv-0.27.0
If you think that this is an error, set no_errcheck_out on the task instance
Waf: Leaving directory `/tmp/makepkg/mpv/src/mpv-0.27.0/build'
Build failed
 -> task in 'mpv' failed with exit status 1

[mpv_build_error_waf_202.log](https://github.com/waf-project/waf/files/1463592/mpv_build_error_waf_202.log)

[mpv_build_error_waf_202_more_info.log](https://github.com/waf-project/waf/files/1463600/mpv_build_error_waf_202_more_info.log)

Waf 1.9.13 works without problems.
Archlinux x86_64, GCC 7.2.0, mpv 0.27.0

**Comment by alium** [comment]
[mpv_build_error_waf_202_more_info.log](https://github.com/waf-project/waf/files/1463600/mpv_build_error_waf_202_more_info.log)

**Comment by ita1024** [comment]
Sorry, but this is the wrong issue tracker for this.
