### ISSUE TITLE
The Waf book questions

### ISSUE THREAD

**Issue by van-de-bugger** [waf-project/waf#2075]
Is it suitable to ask questions about the Waf book here?

Up to now, I faced two issues:

1. In section "14. Further reading" link [The Waf mailing-list](http://groups.google.com/group/waf-users) is broken.

2. `wscript_build` files appear in demos ~30 times, but the Waf book does not say a word what it is. `wscript_build` appears in the Waf book once, in the list of files of `c` demo.

**Comment by ita1024** [comment]
The mailing-list was decommissioned, and the link will be removed.

The `wscript_x` files are the bodies of the `x` functions, with one level of indentation removed.

**Comment by luc-j-bourhis** [comment]
Your web site still links to that defunct mailing list, note…

**Comment by ita1024** [comment]
We consider that the question was answered.
