### ISSUE TITLE
How to generate cmake files from ready wscript?

### ISSUE THREAD

**Issue by Griffan** [waf-project/waf#2077]
I saw the function in waftools webpage that illustrated the possibility of converting wscript ready source repo to cmake files based building system. However, I could not find the cmake functions in either this waf repo or in its waflib/extras directories.
Could anyone point me to the right directions?
Thanks a lot !

**Comment by ita1024** [comment]
That is not from our project and we are not aware of where that is from.

**Comment by Griffan** [comment]
is there a plan to add this feature to convert between the two systems?

**Comment by ita1024** [comment]
That is out of the scope of this project.

**Comment by ita1024** [comment]
I believe that the question is answered.
