### ISSUE TITLE
Question: how to set the platform toolset for windows XP

### ISSUE THREAD

**Issue by xoviat** [waf-project/waf#2079]
In pyinstaller/pyinstaller#2974, we're attempting to build for Windows XP. What's the best way to set the platform toolset?

**Comment by ita1024** [comment]
While that is rather project-specific, adding compiler flags from your project wscript files looks like a good approach. What is your question exactly?

**Comment by xoviat** [comment]
Normally you can set the platform toolset to vc140_xp in MSVC. There is one mention of the platform toolset in the source code but it is not documented.

**Comment by ita1024** [comment]
There is indeed a mention but it looks wrong because such flags are for the linker only? Can we remove those?

**Comment by xoviat** [comment]
Does waf generate an msbuild project? I am actually not familiar with waf internals and the documentation is not that good (no offense).

https://github.com/waf-project/waf/blob/934b02f967d9c0fd4e3c33c4c574054452ba702b/waflib/extras/msvs.py#L116

**Comment by ita1024** [comment]
No offense taken: the files under the extras project are just extensions provided "as-is". They are not part of waf internals.

Regarding msvs, have you actually tried generating a visual studio project with it? It seems to be a makefile-based project.
