### ISSUE TITLE
waf-2.0.2: installation path for mpv binary changed

### ISSUE THREAD

**Issue by 0-wiz-0** [waf-project/waf#2081]
With waf-1.9.13, mpv-0.27.0 installed its binary into `${DESTDIR}${PREFIX}/bin/mpv`.
With waf-2.0.2 (and no change to mpv), it installs into `${DESTDIR}${SOURCEDIR}${PREFIX}/bin/mpv`.
The support files (documentation, config, man pages) are still installed correctly into `${DESTDIR}${PREFIX}`.
Is this an issue in waf or mpv?

**Comment by ita1024** [comment]
There is no concept of SOURCEDIR in waf so try and look on the mpv side. If you do not know where to look, you should probably use the waf version that comes with mpv.
