### ISSUE TITLE
How to build target under a subdirectory?

### ISSUE THREAD

**Issue by mimon** [waf-project/waf#2088]
I have the following scenario:

```
project/
  - src/
      main.cpp
  - resources/
      debug.png
      release.png
```

wscript:
```
out_dir = 'build'

def build(bld):
  bld.program(
     name = 'debug',
     target = 'debug',
     source = ...
     buildcopy_source = ant_glob('resources/debug*')
```

When I build `debug` I'd like this tree structure:
```
build/
   - debug/
      debug <--- this is the exe/target file
      resources/
           debug.png
```

I.e. I want the target to end up in its own folder in the `out_dir` folder.

Is there any way to set the bldnode for each task_gen ?

Thanks.

**Comment by ita1024** [comment]
How about `bld.program(target='just/specify/a/folder/hierarchy/for/foo.exe'..` ?

**Comment by mimon** [comment]
> How about bld.program(target='just/specify/a/folder/hierarchy/for/foo.exe'.. ?
The problems is that `buildcopy` won't pick that up, since it uses the bldnode as destination root.

**Comment by ita1024** [comment]
What do you mean by `buildcopy`?

**Comment by mimon** [comment]
Sorry for being a bit unclear. With `buildcopy` I refer to the `waflib/extras/buildcopy` tool.

**Comment by ita1024** [comment]
That extension probably needs to be modified, but that is not something that we can support, sorry.

**Comment by ita1024** [comment]
Try creating the Node object directly:
`node = bld.bldnode.make_node('debug/sub/folder/targetname')` and pass it to the extension.

Do not forget to pass `remove=False` to `ant_glob` if you want it look up the build directory (`waf -v` will show warnings).

If that is insufficient, consider adding build groups between targets and copies.

**Comment by mimon** [comment]
Thank you for the quick response. I will try that! Cheers

**Comment by xbreak** [comment]
@mimon, try something like this:

```python
def custom_bld_node(node):
	""" Return node with custom bld path"""
	bldnode = ...
	return bldnode

tg = bld.program(...) # No buildcopy feature here

# create your own custom list of (src-node, dest-node) tuple pairs
src_nodes = bld.path.ant_glob('resources/debug*')
node_pairs = [ (n, custom_bld_node(n)) for n in src_nodes]
tg.create_task('buildcopy', [n[0] for n in node_pairs],
                            [n[1] for n in node_pairs],
                            node_pairs = node_pairs)
```
