### ISSUE TITLE
header file installation question

### ISSUE THREAD

**Issue by fedepell** [waf-project/waf#2090]
In C/C++ projects we have the need to install header files by the side of dynamic libraries, which are already installed by waf. When these are not dynamically generated this can be solved in case using a classic install_files with usage of ant_globs and it works, even if they are treated as normal files. But when the header files are generated at build time, such as for example protobuffer headers generated with the protoc extra, the issue is more complicated since ant_globs cannot be generated as the files don’t exist at that point and on the other side putting explicit file names becomes ugly as you are moving parts of the feature logic to the main wscript (for the protobuffer case this may be still feasible since the rule is easy, but in general it may be not as the include names may for example depend on the content of the file that generates them).

One way would be to do it within the single feature, I implemented an example for protoc here:
https://github.com/fedepell/waf/commit/153c7a0435fa44a5c1b844baf35239313eef6da2
so the feature will generate the installation process for the header files if the user passes a feature specific attribute (in a similar fashion as install_path). But this would be per feature.

But could it make sense to have something more generic for C/C++ like features, so we have a generic attribute that instructs the header installation (for example based on the export_includes as those are the include directories where other parts of the project assume we have public headers and therefore make sense to be also public when you are delivering/installing) and then features can just add on the top additional files?

Thanks!
F.

**Comment by ita1024** [comment]
For the protobuf case, the header could be processed by another task generator method much more easily (accessing all tasks if necessary) than by changing code right in the middle of the code.

Yet, I would like to see more real-world cases before trying to create something more generic that would apply to everything. Installing generated headers it not very common.

Using patterns to match generated files looks is also a dangerous practice - uninstallation is likely to leave old files behind it on the system - but if you want to play with the idea, consider playground/dynamic_build2/wscript

Note: it seems that your text editor is mixing tabs with spaces.

**Comment by fedepell** [comment]
Hi,
The real world case are in general code generation cases. In our project we currently have three. 

One is protobuffer which uses directly the extra as described. Then we generate C++/headers for RTI DDS (a commercial implementation of DDS; I can submit this as an extra if you think someone may be interested but didn't propose since not sure someone may find it useful.. and is more or less a protoc rewrite) which is roughly same as protobuffer technically speaking but generates 3 pairs of files instead of one pair (but with quite predictable names). Finally we have an internal code generation tool (from YAML to a bunch of C++ sources and headers) which is more complex as the generated filenames depend on the content of the files as well so cannot really be guessed (and you don't know beforehand which and how many will be generated).

Of course for pure building that is not a problem as the extras extend the sources, but then we got to the problem of installing the headers as some of the artefacts are shared libraries that are then delivered outside the single waf project (until you use them internally is not a problem, as far as you add also the directory where headers are generated as export_includes).

Thanks!

And sorry for messed up editor, worked on wrong account ;)
F.

**Comment by ita1024** [comment]
There does not seem to be any action to take at this point so i am closing this ticket.
