### ISSUE TITLE
Waf tutorial doesn't work on windows ubuntu (14.04) or vanilla ubuntu (16.04)

### ISSUE THREAD

**Issue by embarrassingnewbquestions** [waf-project/waf#2093]
I don't know if it's wget or something else but the tutorial does not work. The wget command looks like it succeeds. Then, after making the wscript file as described, I do:

```sudo ./waf-2.0.0 configure build```

and the output is:

```waf-2.0.0: command not found```

Please update the tutorial.

**Comment by ita1024** [comment]
It works for me on Ubuntu. There is no `sudo` command anywhere in the tutorial. You probably want to run `python ./waf-2.0.0 configure build`
