### ISSUE TITLE
question: how to load msvs

### ISSUE THREAD

**Issue by superCleo** [waf-project/waf#2094]
Sorry this is a really newbie question, I'm just starting to learn waf. I'm trying to use waf to generate Visual Studio solution. I checked both the example and the waf book and my wscript looks like the following:

~~~python
top = '.'
out = 'build'

def options(opt_ctx):
    opt_ctx.load('msvs', tooldir='.');

def configure(conf_ctx):
    conf_ctx.load('msvs', tooldir='.');
    conf_ctx.recurse('code')

def build(bld_ctx)
    bld_ctx.recurse('code')
~~~

But I got this `ImportError: No module named msvs` error. I'm stuck here and don't know how to fix this. Any help is appreciated.

**Comment by ita1024** [comment]
The `msvs.py` file is an extension that is not shipped by default. Either use the code above and include that file in your project or create a waf file containing it (`./waf-light --tools=msvs`).
