### ISSUE TITLE
read existing object files and link them

### ISSUE THREAD

**Issue by daniel-brosche** [waf-project/waf#2097]
Is it possible to read object files similar to shared objects and link them against another target (executeable)?

**Comment by ita1024** [comment]
Have you tried https://github.com/waf-project/waf/blob/master/playground/use/objects/wscript_build#L27 or are you looking for something more exotic?

**Comment by daniel-brosche** [comment]
In my case the object files already exists (not created by waf) and I want to link against them. I was looking for something similar as `read_shlib` for object files.

**Comment by ita1024** [comment]
Can you try and add the .o files to the list of source files?

**Comment by ita1024** [comment]
The question was answered, but we have not heard from you in a long time so we will close this ticket now.

**Comment by daniel-brosche** [comment]
Thx, yes it works...

Just combined c-Files with an existing o-File like that:

```
 bld.program(
        source=['libex.c', 'lib.c.1.o'],
        target=APPNAME)
```
