### ISSUE TITLE
Cpu extension detection

### ISSUE THREAD

**Issue by bjourne** [waf-project/waf#2098]
It would be useful if the environment detection done by the C tool included cpu extensions. For example, on my machine:

    print (ctx.env.DEST_OS, ctx.env.DEST_CPU)
    ('linux', 'x86_64')
    print ctx.env.DEST_CPU_EXTS
    set(['see', 'avx2', 'avx', 'sse2', ...])

If you don't mind, I'm gonna make a pull request for it.

**Comment by ita1024** [comment]
Such detection is best done with configuration tests. Support in waf cannot support all compilers and is likely to be unusable except for a few cases.

**Comment by bjourne** [comment]
I tried that first, but I had to write one configuration check for each extension. Like this

    ctx.check(msg = 'Checking for AVX support',
              execute = True,
              fragment='''int main() {
              #ifdef __AVX__
              return 0;
              #else
              return 1;
              #endif
              }\n''', ...)

It becomes tedious if you have a whole bunch of cpu extensions you want to check for. Perhaps there is a better way I don't know about?

**Comment by ita1024** [comment]
Have you tried using a loop over the required CPU extensions?

**Comment by ita1024** [comment]
We will not apply such changes because more accurate configuration tests can be written rather easily.
