### ISSUE TITLE
waf_unit_test: Test executable re-linked but not re-run?

### ISSUE THREAD

**Issue by q-p** [waf-project/waf#2102]
In the attached repo, the unit test is not re-run (but it is correctly re-linked) when `c.hpp` is modified (e.g. when the return value of `c()` is changed to 0, which would make the initially failing test succeed if it were run).

Happens with waf master as well as 1.9.15.

(`--clear-failed` seems to make no difference here either).

[repo.zip](https://github.com/waf-project/waf/files/1660383/repo.zip)

**Comment by ita1024** [comment]
This is happening because dependencies have changed to depend on file contents due to frequent demand from end users (waf 1.8).

A crude workaround was added to deacb94c933307caa33e29717d232e8687ee12e0, please update your copy.

**Comment by q-p** [comment]
Thanks, that helped (and seems to backport cleanly to waf 1.9).
