### ISSUE TITLE
How do you include paths with spaces?

### ISSUE THREAD

**Issue by ivalylo** [waf-project/waf#2103]
I'm passing includes to bld.stlib, in which one of the paths contains spaces. The common sense says to put it in quotes. However, waf returns this:

Could not create the directory c:\project\temp\waf\x64\"c:

I can see this message is Node.py, but have no idea why including a file triggers mkdir and why the file name is chopped in such a way. This is on Windows x64 and waf 2.0.4

**Comment by ivalylo** [comment]
Ok, I found a way by passing a list of strings instead of a space separated string. I'm still interested why the space separated string is not working.

**Comment by ita1024** [comment]
Space-separated strings indicate lists of folders.
