### ISSUE TITLE
[Question] link static lib into dynamic lib in buidling

### ISSUE THREAD

**Issue by freedom0822** [waf-project/waf#2105]
Please forgive me for my poor English

I looked up some data, seems need add option '--whole-archive' when link a static lib into dynamic lib, what's the way to add this option when building?

Thanks

**Comment by ita1024** [comment]
Either add the desired flag(s) to the task generator linkflags/ldflags, or if you need to change the positions of some of them use a task generator method to do that. See for example:
https://github.com/waf-project/waf/blob/master/playground/ldscript/wscript#L28

**Comment by freedom0822** [comment]
great！Thanks for your help
