### ISSUE TITLE
Introduce tool loading with cache into context class 

### ISSUE THREAD

**Issue by daniel-brosche** [waf-project/waf#2109]
I have noticed that `ConfigurationContext` supports tool loading with caching mechanism. However, caching is not supported for `BuildContext` and `OptionsContext`. For consistency reasons I see some benefit to support this caching in general.

**Comment by ita1024** [comment]
Caching is disabled for very good reasons, and it will be removed in the future.

**Comment by daniel-brosche** [comment]
Can you explain that reasons? I see some relevance for composite scenarios where projects can be built together or idepently in a straight forward way. I have seen a comment in the code at `ConfigurationContext.load` that mentions the relevance.

```python
# avoid loading the same tool more than once with the same functions
# used by composite projects
```

I would like to use this feature somehow.

**Comment by daniel-brosche** [comment]
I have found an easy way to implement this feature scope of the Context class resp. as monkey patch.

```python
__cmd_tools_cache__ = set() 

def load_once(self, tool_list, tooldir=None, with_sys_path=True):
    """ 
    Special version of Context.load function that provides a way to load a tool by command just once.
    This function is particular helpful in composite projects where projects can be built together or indepently. 
    Over this way boilerplating can be reduced to load the tools in every wscript and to ensure that loading happens
    just once. In general each wscript loads the tools that are needed to process itself. 
    The tools are loaded in the global Context and are shared across all Context classes.
    Other similar sub-wsripts make usage of the same tools but they dosen't need to load the tools again which can have also side-effects.
    Additional tools that are not already loaded but are needed for a particular wscript can safely loaded afterwards.

    Example:
    
    def configure(conf):
        conf.load_once('compiler_c') # calls compiler_c.configure function
        conf.load_once('compiler_c') # does not call compiler_c.configure function a second time

    """
    for tool in tool_list:
        # build cache id that represent an combination of cmd-name and tool-name
        # this id will be used to identify if the call has been done before
        cache_id =  self.cmd + '_' + tool
        if cache_id in __cmd_tools_cache__:
            continue
        else:
            __cmd_tools_cache__.add(cache_id)
            self.load(tool, tooldir=tooldir, with_sys_path=with_sys_path)
```

I have tested this function several time and don't see any negative impact.
Do you see any reasons not use it?
I would prepare a pull request if there is a chance to be accepted otherwise it will become a part of our waf extensions.

**Comment by ita1024** [comment]
Among other problems: script execution order may become intractable, task classes can get registered several times, and new bugs can appear because of caching. Which benefits are you expecting from caching on that level?

**Comment by daniel-brosche** [comment]
Loading Tools multiple timesduring the recurse process does tend to do things that already has happened on the toplevel wscript. 
So, this is especially in this multiproject / composite project scenarios the case where one project does recurse into projects that can be also build individually (so the sub-wscript does also load mostly the same tools as the parent/toplevel wscipt). 
This is not critical for all tools -> it does just costs some processing time.  
In some special scenarios where tools does prepare the global ConfigSet (`conf.env`) which should be applied to all build targets I've got the case that the multiple loading of the tool does resets the global ConfigSet to some state and changes that have been done inbetween have been lost.
In this matter, there are global things in a build that should be done just once during a build phase. Also loading options multiple times that have been already added seems unnecessary (by tool). 
So I have experimented alot, tried several things and figured out that globaly loading a tool once is enough. There is no need to load it multiple times for one command (configure) because the tools seems purely global stuff. This did simplified the wscripts alot because before I've tried to figure out if a wscript is a toplevel-wscript and then just loaded the required tools which is akward when sub-wscripts are needing tools that are not loaded by the toplevel-wscript.
So over this mechanism it solved all the pain before in this multiproject/composite scenarios.
I have improved the code inbetween and I could also provide an code example.

**Comment by daniel-brosche** [comment]
One small addition: the cache that I'm using does ensure that each tool for each command will be executed exactly once in one waf process run. 
e.g. `waf configure build` will call for each tool `configure` and `build` just once regardless how often the tools are loaded in sub-wscripts again.
In the next call of `waf configure build` the cache is reset so it will call for each tool `configure` and `build` again just once.
