### ISSUE TITLE
qt5.py

### ISSUE THREAD

**Issue by sildeag** [waf-project/waf#2113]
in file `waflib/tools/qt5.py` on Ubuntu 17.10
line 741 generates an error `TypeError not all arguments converted to list or string` 
`re_qt = re.compile(pat%'Qt5?(?P<name>.*)'+'$')`

pat = ' '
dirlst = ['libgdk-3.so.0', 'libgettextlib-0.19.8.1.so', 'librevenge-0.0.so.0.0.4', 'libsmbldap.so.0', 'libfishsound.so.1.3.0', 'libjpeg.so.8', 'libopenjp2.so.2.2.0', 'libkmlbase.so.1', 'libgrlnet-0.3.so.0.0.3', 'libQt5PrintSupport.so.5.9', 'libcmis-c-0.5.so.5', 'libQtSql.so', 'libexempi.so.3.4.3', 'libLLVM-3.9.so', 'libglapi.so.0', 'libxcb-dri2.so', 'libgnome-games-support-1.so.2.0.4', 'libepoxy.so.0.0.0', 'libcrypt.a', 'gedit', 'libsvn_delta-1.so.1.0.0', 'libdbusmenu-glib.so.4.0.12', 'libpython2.7.so.1.0', 'libgthread-2.0.so.0.5400.1', 'libldap_r-2.4.so.2', 'libgtk-3.so.0.2200.25', 'libfontenc.so.1.0.0', 'mutter', 'libwinpr-sysinfo.so.0.1.0', ...]

I tried removing changing line to `re_qt = re.compile('libQt5?(?P<name>.*)'+'$')`

`Checking for 'Qt5OpenGLExtensions.prl'  : not found `
`Checking for 'Qt5Script.so.5'                     : not found `
`Checking for 'Qt5Xml.so'                          : not found `
`Checking for 'Qt5DesignerComponents.so.4.8'       : not found` 
`No CXX compiler defined: did you forget to configure compiler_cxx first?`

All of these libs are found  eg. `libQt5Open...`.  Is there some problem with the pattern resolution on Ubuntu?

**Comment by ita1024** [comment]
Most likely `self.env.cxxshlib_PATTERN` is empty. Does your project use custom compiler settings?

**Comment by sildeag** [comment]
Thank you for responding.  These are the only custom settings I know about, otherwise none.
`conf.env.CXXFLAGS += [ '-std=c++11', '-msse2','-Wall', \`
           ` '-DGAIA_QT5',  \`
           ` '-Wint-in-bool-context', \`
           ` '-Wno-misleading-indentation', \`
           ` '-Wno-unused-result',\`
           ` '-fno-strict-aliasing',\`
           ` '-fPIC', '-fvisibility=hidden']`

I am new at this so good chance I've made a mistake.  I was investigating why `-DGAIA_QT5` wasn't being used and thought it was because in the `configure(conf)` procedure `conf.load` wasn't being used as `./waf` ignored my flag setting.  Also, tried setting `pat = "lib"` and `pat = ""` in `waflib` to see what happened.  My intent to make changes only affecting `linux` platform.

**Comment by ita1024** [comment]
Our example in [demos/qt5](https://github.com/waf-project/waf/tree/master/demos/qt5) does not raise any error. Since the value of `env.cxxshlib_PATTERN` is empty, you should check that the call to `conf.load('compiler_cxx')` is performed for the required `conf.env` object.

**Comment by sildeag** [comment]
Thanks.
