### ISSUE TITLE
Node.py find_node() produces KeyError

### ISSUE THREAD

**Issue by rpuntaie** [waf-project/waf#2116]
``find_node()`` creates an entry and deletes it again, ``if not cur.exists()``.
If there is another thread that does the same you can get an error:

```
line 160, in evict
    del self.parent.children[self.name]
KeyError: 'xxx.yyy'
```

**Comment by ita1024** [comment]
The Node structure is not meant to be thread-safe, in particular in code that modifies the structure. Threads accessing the objects must ensure exclusive access (in `Task.run` for example).
