### ISSUE TITLE
Difference in number of files built from `waf 1.8.3` to `waf 1.9.15`

### ISSUE THREAD

**Issue by sildeag** [waf-project/waf#2120]
In trying to figure out a possible `wscript` issues, I've discover that between `waf 1.8.3` which was strictly python2 and `waf 1.9.15` which is both `python 2/3`  the same `wscripts` would start to build 111 files in `waf 1.8.3` and only do 84 files in later `waf` versions.  The problem persists thru `waf 2.0.6`.

Is there a python 2/3 version closer to `waf 1.8.3` that I could try?   The `waf` build tools used are `swig, qt4, qt5`.   Or are you aware of some diagnostic feature I can use that would isolate the issue?  Ordinarily, the file count difference wouldn't be a problem but the `waf` version difference causes a linking problem, `undefined reference to 'vtable' for name`, that doesn't exist in `waf 1.8.3` or using Qt Creator.  Sorry for providing so little information.  Any help would be appreciated.

**Comment by ita1024** [comment]
Try updating to the latest version in the 1.8 series such as 1.8.21, and for waf 1.9 try comparing your cases with the examples under demos/qt5.

**Comment by sildeag** [comment]
Thanks for the suggestions.  One further comment: the trouble is coming from building a networking component that uses 4 source files for the normal target and 5 files for the master target - the overlap is 3 files exactly the same.  The `1.8.3` version used an `id` to differentiate the `.o` files the `1.9.15` and later seem to use all the `.o` files.  If I could change the folder for the `.o` files, how would I do that?

The `bld` features are `qt<n=version> cxx cxxprogram <programname>` 

Besides fixing the `waf` versions to be backward compatible there is one other way:  generate the `.o` files from this phase of the build in separate folders and `use` them.  Currently the `.o` are generated in `src` folder and have an `id` inserted eg. `.409.o` for first pass and `.410.o` for second pass.  How would I change in `bld` generate and use `.o` files from different folders than `src`?

**Comment by ita1024** [comment]
Have you tried waf 2.0.6? If yes, are you able to produce a testcase to show the problem?

**Comment by sildeag** [comment]
It isn't simple - I was using ./waf 1.8.21 version - I made a mistake earlier not sure where I got 1.8.3 from being new to this doesn't excuse that.  I was working on some changes to `github.com/MTG/gaia` project for `Ubuntu 17.10`.  I've spent hours using different `waf` versions 1.9.1, 1.9.15, and 2.0.6; different file arrangements consolidating source file `virtual` methods; and slightly different `waf` builds.  Using the original project with python2.7 the project builds with no issues except c++ warnings and even builds with my c++ source changes for python2 only without `--with-cyclops`.  For my `waf` build script modifications using `waf` 2.0.6 for `qt5` everything works python2 or python3 except --with-cyclops.  The command line:
 `./waf configure --with-python-bindings --with-tests --with-asserts --with-tbb --with-cyclops`
is what I used to test.  It concerns me that the original project seems to depend on a specific `waf` version.  The problem can be shown by just changing `waf` version on original project using `--with-cyclops`.  I may isolate the code further.

**Comment by sildeag** [comment]
This may have a simple answer but this may be what is causing me this problem.
The attached files, with `.txt` removed, work correctly when `opt.load('compiler_cxx qt4')` in file `wscript` for:
`./waf configure`
`./waf`
However, introduce the possibility of Qt4 or Qt5 and `opt.load('compiler_cxx qt4 qt5')` or `opt.load('compiler_cxx qt5')` for input commands:
`./waf configure --with-gaia-qt5`
`./waf`
the output is:
` main.cpp.1.o: In function `Communicate::~Communicate()': `
`main.cpp:(.text._ZN11CommunicateD2Ev[_ZN11CommunicateD5Ev]+0xf): undefined reference to` `vtable for Communicate'`
`main.cpp:(.text._ZN11CommunicateD2Ev[_ZN11CommunicateD5Ev]+0x21): undefined reference to` `vtable for Communicate'`
`communicate.cpp.1.o: In function `Communicate::Communicate(QWidget*)':``
`communicate.cpp:(.text+0x4e): undefined reference to `vtable for Communicate'``
`communicate.cpp:(.text+0x60): undefined reference to `vtable for Communicate'``
`collect2: error: ld returned 1 exit status`
What I am looking for is `qt4` or `qt5` to be user selectable.
[communicate.cpp.txt](https://github.com/waf-project/waf/files/1798681/communicate.cpp.txt)
[communicate.h.txt](https://github.com/waf-project/waf/files/1798682/communicate.h.txt)
[main.cpp.txt](https://github.com/waf-project/waf/files/1798683/main.cpp.txt)
[wscript.txt](https://github.com/waf-project/waf/files/1798684/wscript.txt)
The above files were borrowed from `stackoverflow.com`

**Comment by ita1024** [comment]
1. `moc = 'communicate.h',` is missing
2. There is no point in including `communicate.moc` because there are no classes to process

Please think before copy-pasting and re-read the example carefully: https://github.com/waf-project/waf/blob/master/demos/qt5/wscript#L18
