### ISSUE TITLE
Qt5 moc generation from header

### ISSUE THREAD

**Issue by mclayton7** [waf-project/waf#2128]
Hi,

I recently upgraded my waf version from 1.8 to 2, and have noticed a difference with the ``qt5.py`` tool. It used to generate a ``MyClass.moc`` file _based on the header_ if the ``.moc`` was included in the cxx. Now, it passes the source (ex. ``MyClass.cxx``) to the moc compiler, which generates an empty file (since my signals and slots are in the header). I think the excerpt below from ``qt5.py`` is the issue. Because the base2 variable (which would be ``MyClass``) is always equal to prefix (which would also be ``MyClass``), the cxx file is passed to the moc compiler instead of the header. 

```
# find the source associated with the moc file
h_node = None
base2 = d[:-4]

# foo.moc from foo.cpp
prefix = node.name[:node.name.rfind('.')]
if base2 == prefix:
    h_node = node
else:
    # this deviates from the standard
    # if bar.cpp includes foo.moc, then assume it is from foo.h
    for x in include_nodes:
        for e in MOC_H:
            h_node = x.find_node(base2 + e)
            if h_node:
                break
        else:
            continue
        break
if h_node:
    m_node = h_node.change_ext('.moc')
```
Am  I doing something wrong, or is there another way to generate moc files from headers without having to specify them manually in the build node (ex: ``bld(moc='MyClass.h', ...)``)?

**Comment by ita1024** [comment]
The moc files from headers must be declared explicitly:
https://github.com/waf-project/waf/blob/master/demos/qt5/wscript#L28

**Comment by mclayton7** [comment]
@ita1024 thanks! Is there any hope of adding back that behavior where waf automatically generates the moc from the header without explicitly adding it? I'm guessing the change was due to performance reasons?

**Comment by ita1024** [comment]
The main driver for this is to avoid name clashes with similar file names. This behavior cannot be changed back, so you should decide for a waf version or include your own `qt5.py` file.
