### ISSUE TITLE
How to use Qt4 or Qt5

### ISSUE THREAD

**Issue by sildeag** [waf-project/waf#2129]
I have been using an adaption of your `waf/playground/qt5-and-pyqt5/qt5/` example code `Qt5` works but am having trouble getting `Qt4` to work.  I am using waf 2.0.6.  What am I doing wrong?

`./waf configure --qt5`
`./waf`  
works
`./waf configure`
`./waf`
generates `vtable` error.
[use_qt5.pdf](https://github.com/waf-project/waf/files/1805187/use_qt5.pdf)

**Comment by ita1024** [comment]
Try the example under `playground/qt4`?

The module `qt4.py` is under `waflib/extras/` which means that it is provided "as-is". If it is confirmed broken and no one steps in to fix it, then we would not hesitate to remove it.

**Comment by sildeag** [comment]
I think `opt.load('compiler_cxx qt5 qt4')` means that `qt4.py` is used in the build and that switching to `opt.load('compiler_cxx qt4 qt5')` uses `qt5.py` under `waflib/extras`.  Individually, no issue, the example works for one of the `qt<versions>`.  I would like `qt4` or `qt5` can you help?  I have tried several variations including `#include <foo.moc>` in `foo.cpp` suggested elsewhere and removing the build folder.  
Input: 
`./waf configure --qt5`
`./waf`
Output:
`moc_foo.1.cpp.1.o: In function `QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> >::operator->() const':
/home/gordon/waf/playground/qt4/build/moc_foo.1.cpp:66: multiple definition of `Foo::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)'
foo.cpp.1.o:/home/gordon/waf/playground/qt4/build/./foo.moc:66: first defined here
moc_foo.1.cpp.1.o: In function `Foo::test()':
/home/gordon/waf/playground/qt4/build/moc_foo.1.cpp:126: multiple definition of `Foo::test()'
foo.cpp.1.o:/home/gordon/waf/playground/qt4/build/./foo.moc:126: first defined here
moc_foo.1.cpp.1.o:(.data.rel.ro+0x0): multiple definition of `Foo::staticMetaObject'
foo.cpp.1.o:(.data.rel.ro+0x0): first defined here
moc_foo.1.cpp.1.o: In function `Foo::metaObject() const':
/home/gordon/waf/playground/qt4/build/moc_foo.1.cpp:95: multiple definition of `Foo::metaObject() const'
foo.cpp.1.o:/home/gordon/waf/playground/qt4/build/./foo.moc:95: first defined here
moc_foo.1.cpp.1.o: In function `Foo::qt_metacast(char const*)':
/home/gordon/waf/playground/qt4/build/moc_foo.1.cpp:100: multiple definition of `Foo::qt_metacast(char const*)'
foo.cpp.1.o:/home/gordon/waf/playground/qt4/build/./foo.moc:100: first defined here
moc_foo.1.cpp.1.o: In function `Foo::qt_metacall(QMetaObject::Call, int, void**)':
/home/gordon/waf/playground/qt4/build/moc_foo.1.cpp:108: multiple definition of `Foo::qt_metacall(QMetaObject::Call, int, void**)'
foo.cpp.1.o:/home/gordon/waf/playground/qt4/build/./foo.moc:108: first defined here
collect2: error: ld returned 1 exit status`
