### ISSUE TITLE
wscript problem

### ISSUE THREAD

**Issue by sildeag** [waf-project/waf#2131]
I've been keenly following all the examples scripts for `qt5`, `qt4`, and `slow_qt4` and unfortunately sometimes I get the error below - is there something I am forgetting to do when `swig` is required because otherwise everything works as it should?

`In add_includes_paths`
    `for x in self.compiled_tasks:`
`AttributeError: 'task_gen' object has no attribute 'compiled_tasks'`

`wscript` includes these lines:
`# use the following to add the include paths for generated *.moc files automatically`
`from waflib.TaskGen import feature, before, after`
`@feature('cxx')`
`@after('process_source')`
`@before('apply_incpaths')`
`def add_includes_paths(self):`
    `incs = set(self.to_list(getattr(self, 'includes', '')))`
    `for x in self.compiled_tasks:`
        `incs.add(x.inputs[0].parent.path_from(self.path))`
    `self.includes = sorted(incs)`

**Comment by ita1024** [comment]
1. Make a testcase
2. `self.compiled_paths` is only defined after at least one c/c++ file is processed by a given task generator.

**Comment by ita1024** [comment]
I guess this is due to the introduction of swig tasks. Swig tasks only create c/c++ under certain conditions, so your code should probably be rewritten to avoid relying onto self.compiled_tasks / self.tasks.
