### ISSUE TITLE
`change_ext`

### ISSUE THREAD

**Issue by sildeag** [waf-project/waf#2132]
I am trying to understand what this method does as it seems to apply to a `node` and yet I've had a message referring to object `str` not having this method.  Can you elaborate a little?  I am having trouble tracing what is happening as prior to the lines below `apply_qt4` line 316 `isinstance(rcnode, str)` seems to suggest it might be a String object `str`.

from `qt4.py` line 259
@extension(*EXT_RCC)
def create_rcc_task(self, node):
	"Create rcc and cxx tasks for *.qrc* files"
	rcnode = node.change_ext('_rc.cpp')

**Comment by ita1024** [comment]
1. Check the documentation for `@extension` and the apidocs for `process_source`
2. Only Node objects are accepted, meaning that something most likely added a non-Node object to `self.source` at the wrong moment
3. Make a testcase.
