### ISSUE TITLE
Question of build order or dependency for `swig` waf 2.0.6 github

### ISSUE THREAD

**Issue by sildeag** [waf-project/waf#2136]
The `playground/swig` works.  Scaling the example to one closer to mine works.  However, my code doesn't.  Swig is using `features = 'cxx cxxshlib pyext'` and should depend on the existence of a shared or static library.  Using `swig` directly works on my files with no errors.

In my waf build:
`def build(bld):`
`  `  ` build_library(bld)`
`  `  ` build_swig(bld)`

I would like the library to be built before `swig`.  How would I ensure that and that it is a dependency and not missing?
Currently, in waflib extras `swig.py` has a failure at `c_tsk.run_after(self)` at or about line 82.  No attribute `run_after`.  If one ignores that issue.  The next issue is at waflib tools `Task.py` line 95, object has no attribute `priority`.  What am I doing wrong?  Isolating a small test case has proven difficult.  Up until recently I reverted to well worn original build scripts and they always worked - now they too generate the same error.

**Comment by ita1024** [comment]
Also, the swig code not not contain any run_after of that kind https://github.com/waf-project/waf/blob/master/waflib/extras/swig.py#L113 - are you using the proper version of the module?

Unless testcases, traces or links are provided there is not much we can say about this matter. The functions `build_library` and `build_swig` that you mention are entirely yours.

**Comment by sildeag** [comment]
I removed `waf`, deleted app `build` folder and removed `./waf-2.0.6....` folder generated in the app folder and rebuilt from github.  This is the error message I would like to avoid getting.  Can you suggest what is likely the issue as it would greatly help.
`File ".../waflib/extras/swig.py", line 80, in swig_c`
` ` `    c_tsk.set_run_after(self)`
`AttributeError: 'NoneType' object has no attribute 'set_run_after'`

Thanking you for any help.

**Comment by ita1024** [comment]
Are you using something called `extras/slow_qt4.py`? It seems the redefined function is missing a return block.

**Comment by sildeag** [comment]
Yes.  Thank you.  I have now stop using `slow_qt4.py`.  Please close.  For backwards compatibility purposes was there a specific version of `waf` that updated to include Python 2/3 support, change to `qt4.py` from `Tools` to `extras`, and anything regarding `swig`.  I would like to document this so users know why `waf 2.0.6` is used.

**Comment by ita1024** [comment]
Can you reformulate your question? In particular, what do you mean by "was there a specific version of waf that updated to include Python 2/3 support"?

**Comment by sildeag** [comment]
I tried multiple version of `waf` in order to determine the minimum `waf` version my build scripts would work for - my builds allow python2 or python3 - and probably I didn't test thoroughly but felt `waf` 1.8.21 and below still had some features that didn't work for python3.  So for what version do you feel `waf` builds with either python2/3 presented no major issues - rare ones can be excluded?  I also noted `qt4` moved from `Tools` to `extras` so while that may cause no issue - I'd like to know the version that first happened.  `Swig` is document as having some python 2/3 issue 3.0.8 and this is not related to `waf`.

**Comment by ita1024** [comment]
All waf versions "work" in Python3, but older versions may not receive updates to work around Python compatibility issues. Those are supposed to be uncommon; if you are interested in applying updates to older branches, you are welcome to submit pull requests against them.

The `extras` modules are user-contributed and provided for convenience without any guarantee of fitness-for-purpose. Always use extra modules matching the corresponding Waf version.

The `qt4.py` module was replaced by `qt5.py` in version 1.9.

**Comment by sildeag** [comment]
Thanks.
