### ISSUE TITLE
How to set Task.weight for the c_tsk in swig extra?

### ISSUE THREAD

**Issue by q-p** [waf-project/waf#2137]
I'm trying to use the new `Task.weight` some weak ordering optimizations in my build, but I seem to have no luck for applying this to the c_tsk (i.e. compilation of the c/cxx file generated from a SWIG .i interface file).

I set the weight when the c_tsk is generated (swig.py:115), but it seems to not have an effect, the task is run at the very end of the build, no matter what I do.

A very similar approach *does* seem to work for dynamically generated cpp-files using the approach shown in the waf-book for "11.4.2. A compiler producing source files with names unknown in advance", so I'm lost why it works there, but seemingly not for swig...?

**Comment by q-p** [comment]
Hmmm... In fact, this does not seem to work for for the 11.4.2 waf-book example either, it seems. My generated .cpp files only compile as long as the (unrelated) swig-tool declares `ext_out = ['.h'] # might produce .h files although it is not mandatory`.

I'm now entirely confused.

**Comment by ita1024** [comment]
The swig extension ignores priorities by injecting tasks directly into the build instead of using `more_tasks`, hence the outcome observed. Try the change above.

Also, the `weight` attribute only applies to tasks of the same level, as opposed to `tree_weight` which applies to whole dependent trees.

**Comment by q-p** [comment]
I'll try that out tomorrow.

As noted in my second comment, the `more_tasks` approach doesn't seem to work (for the `src2c` example from chapter 11.4.2 in the book) -- or at least do what I expect -- either. Whether the `c_task`s generated by the `src2c` tool compile early seems to depend on the `ext_out` setting of the unrelated swig tool. If I temporarily comments swig's `ext_out` definition, then the files from my `src2c` tool are processed at the very end again, even though I set the `weight` of the `c_task`s being generated to `5`.

Essentially, I have 3 sets of .cpp files I'm compiling & linking

1. Normal `.cpp` files (multiple)
2. Multiple `.cpp` files with names unknown in advance being generated by a `src2c` like tool (with implementation taken nearly verbatim from the book)
3. A `.cpp` file generated by the `swig` tool

I'm attempting (because the resulting files take long to compile compared to the "normal" ones) to compile the files from 2. and 3. as early as possible. The `.src` (which generate additional `.cpp` files) and normal `.cpp` files are given as inputs to a `bld.cxxshlib` invocation, if that makes a difference.

**Comment by q-p** [comment]
Thanks, trying out 592136739b021cdcc472a9c3dfdab66eccd985a5 this now seems to work as expected if I do something like this.

```diff
@@ -26,6 +26,7 @@ class swig(Task.Task):
        color   = 'BLUE'
        run_str = '${SWIG} ${SWIGFLAGS} ${SWIGPATH_ST:INCPATHS} ${SWIGDEF_ST:DEFINES} ${SRC}'
        ext_out = ['.h'] # might produce .h files although it is not mandatory
+       weight = 4
        vars = ['SWIG_VERSION', 'SWIGDEPS']
 
        def runnable_status(self):
@@ -110,6 +111,7 @@ def swig_c(self):
        else:
                c_tsk = self.generator.c_hook(out_node)
 
+       c_tsk.weight = getattr(self, 'weight', 0)
        c_tsk.set_run_after(self)
        try:
                self.more_tasks.append(c_tsk)
```

One more question: Should the book example 11.4.2 then also include the equivalent `self.generator.bld.producer.revdeps[tsk].add(self.generator.link_task)`?

**Comment by ita1024** [comment]
Try 90c80ea1ae68d42ca3a934e7b92f309cb648a585 and tell us if you notice any performance issue.

**Comment by q-p** [comment]
Seems to work well, although I don't generate huge amounts of dynamic tasks (~10 from `src2c`-alike, +1 from `swig`). Thanks!

**Comment by q-p** [comment]
Hmmm. Trying this out on a separate build, where both the run of swig as well compilation of the generated file take a long time, this does not quite work (or at least as I would naively expect)

For this test, in `swig.py` I removed the line
```py
	# ext_out = ['.h'] # might produce .h files although it is not mandatory
```
as in my case there are no headers generated, and because otherwise (due to precedence constraints) waf will wait until that swig invocation has completed before compiling any of the normal `.cpp`-files.

If I do this then I get (running with -j8)
```
 ### starting swig invocation early, as desired ###
[  1/335] Processing FSDataManager/include/_FSDataManager.i
[  2/335] Compiling FSCommon/src/FSXMLUtil.cpp
[  3/335] Compiling FSCommon/src/FSVec4.cpp
[  4/335] Compiling FSCommon/src/FSVec3.cpp
[  5/335] Compiling FSCommon/src/FSVec2.cpp
[  6/335] Compiling FSCommon/src/FSUtil.cpp
[  7/335] Compiling FSCommon/src/FSUnits.cpp
[  8/335] Compiling FSCommon/src/FSTypes.cpp
[  9/335] Compiling FSCommon/src/FSTransformUtil.cpp
[ 10/335] Compiling FSCommon/src/FSTransform.cpp
[ 11/335] Compiling FSCommon/src/FSTimer.cpp
[ 12/335] Compiling FSCommon/src/FSTextFile.cpp
[ 13/335] Compiling FSCommon/src/FSSystemUtils.cpp
[ 14/335] Compiling FSCommon/src/FSString.cpp
[ 15/335] Compiling FSCommon/src/FSQuat.cpp
[ 16/335] Compiling FSCommon/src/FSQuadtree.cpp
[ 17/335] Compiling FSCommon/src/FSParameter.cpp
[ 18/335] Compiling FSCommon/src/FSOctree.cpp
[ 19/335] Compiling FSCommon/src/FSNetCDF.cpp
[ 20/335] Compiling FSCommon/src/FSMath.cpp
[ 21/335] Compiling FSCommon/src/FSMat4x4.cpp
[ 22/335] Compiling FSCommon/src/FSMat3x3.cpp
[ 23/335] Compiling FSCommon/src/FSMat2x2.cpp
[ 24/335] Compiling FSCommon/src/FSLog.cpp
[ 25/335] Compiling FSCommon/src/FSLinearSystem.cpp
[ 26/335] Compiling FSCommon/src/FSKDTree.cpp
[ 27/335] Compiling FSCommon/src/FSIntVec3.cpp
[ 28/335] Compiling FSCommon/src/FSError.cpp
[ 29/335] Compiling FSCommon/src/FSEnums.cpp
[ 30/335] Compiling FSCommon/src/FSDataValue.cpp
[ 31/335] Compiling FSCommon/src/FSDataSpec.cpp
[ 32/335] Compiling FSCommon/src/FSDataNameTranslator.cpp
[ 33/335] Compiling FSCommon/src/FSDataName.cpp
[ 34/335] Compiling FSCommon/src/FSCoordSys3D.cpp
[ 35/335] Compiling FSCommon/src/FSConfig.cpp
[ 36/335] Compiling FSCommon/src/FSClac_Buffer.cpp
[ 37/335] Compiling FSCommon/src/FSClac.cpp
[ 38/335] Compiling FSCommon/src/FSCStringUtil.cpp
[ 39/335] Compiling FSCommon/src/FSBinaryFile.cpp
[ 40/335] Compiling FSCommon/src/FSBase64.cpp
[ 41/335] Compiling FSCommon/src/FSBacktrace.cpp
[ 42/335] Compiling FSCommon/src/FSAttributeUtilTAU.cpp
[ 43/335] Compiling FSCommon/src/FSAttributeContainer.cpp
[ 44/335] Compiling FSCommon/src/FSArray.cpp
[ 45/335] Compiling FSBoundaryCondition/src/FSBoundaryCondition.cpp
[ 46/335] Compiling FSBoundaryCondition/src/FSBCUtilELSA.cpp
[ 47/335] Compiling FSBoundaryCondition/src/FSBCUtilCENTAUR.cpp
[ 48/335] Compiling FSBoundaryCondition/src/FSBCFactory.cpp
[ 49/335] Compiling FSBoundaryCondition/src/FSBCCFD.cpp
[ 50/335] Compiling FSBoundaryCondition/src/FSBC.cpp
[ 51/335] Compiling FSMesh/src/FSMeshConcreteSelection.cpp
[ 52/335] Compiling FSMesh/src/FSMeshCheck.cpp
[ 53/335] Compiling FSMesh/src/FSMesh.cpp
[ 54/335] Compiling FSMesh/src/HBLayerAnalyzer.cpp
[ 55/335] Compiling FSMesh/src/FSLineSectionsExtractor.cpp
[ 56/335] Compiling FSMesh/src/HBLayerAnalysisParams.cpp
[ 57/335] Compiling FSMesh/src/FSVtkEnums.cpp
[ 58/335] Compiling FSMesh/src/FSLineSectionsExtractionParams.cpp
[ 59/335] Compiling FSMesh/src/FSUnstructMeshInfo.cpp
[ 60/335] Compiling FSMesh/src/FSUnstructMeshData_RedistributeExact.cpp
[ 61/335] Compiling FSMesh/src/FSLineSectionsConverter.cpp
[ 62/335] Compiling FSMesh/src/FSUnstructMeshData_RedistributeEx.cpp
[ 63/335] Compiling FSMesh/src/FSUnstructMeshData_Redistribute.cpp
[ 64/335] Compiling FSMesh/src/FSLineSectionsConversionParams.cpp
[ 65/335] Compiling FSMesh/src/FSUnstructMeshData.cpp
[ 66/335] Compiling FSMesh/src/FSUnstructDataset.cpp
[ 67/335] Compiling FSMesh/src/FSLineSections.cpp
[ 68/335] Compiling FSMesh/src/FSUnstructConnectivityCache.cpp
[ 69/335] Compiling FSMesh/src/FSUnstructCellPool.cpp
### call to swig completes here, so now we have the generated .cxx ... ###
[ 70/336] Compiling FSMesh/src/FSInitMissingDegeneracyParams.cpp
[ 71/336] Compiling FSMesh/src/FSTECPLOTZone.cpp
[ 72/336] Compiling FSMesh/src/FSTECPLOTUtil.cpp
[ 73/336] Compiling FSMesh/src/FSInitMissingDegeneracy.cpp
[ 74/336] Compiling FSMesh/src/FSTECPLOTMesh.cpp
[ 75/336] Compiling FSMesh/src/FSTECPLOT.cpp
[ 76/336] Compiling FSMesh/src/FSInitMissingDataSpecsParams.cpp
[ 77/336] Compiling FSMesh/src/FSSurfaceNormalCalculator.cpp
[ 78/336] Compiling FSMesh/src/FSSurfaceNormalCalculationParams.cpp
[ 79/336] Compiling FSMesh/src/FSInitMissingDataSpecs.cpp
[ 80/336] Compiling FSMesh/src/FSSubmeshExtractor.cpp
[ 81/336] Compiling FSMesh/src/FSSubmeshExtractionParams.cpp
[ 82/336] Compiling FSMesh/src/FSIndexTransform.cpp
[ 83/336] Compiling FSMesh/src/FSStructWindowInfo.cpp
[ 84/336] Compiling FSMesh/src/FSStructWindowBase.cpp
[ 85/336] Compiling FSMesh/src/FSHangingFacesExtractor.cpp
[ 86/336] Compiling FSMesh/src/FSStructWindowAddr.cpp
[ 87/336] Compiling FSMesh/src/FSStructWindow.cpp
[ 88/336] Compiling FSMesh/src/FSHangingFacesExtractionParams.cpp
[ 89/336] Compiling FSMesh/src/FSStructTopoCache.cpp
[ 90/336] Compiling FSMesh/src/FSStructRind.cpp
[ 91/336] Compiling FSMesh/src/FSGraphExtractor.cpp
[ 92/336] Compiling FSMesh/src/FSStructMeshInfo.cpp
[ 93/336] Compiling FSMesh/src/FSStructMeshData.cpp
[ 94/336] Compiling FSMesh/src/FSGraphExtractionParams.cpp
[ 95/336] Compiling FSMesh/src/FSStructEntityBase.cpp
[ 96/336] Compiling FSMesh/src/FSStructDegeneratedFace.cpp
[ 97/336] Compiling FSMesh/src/FSGraph.cpp
[ 98/336] Compiling FSMesh/src/FSStructDegeneratedEdge.cpp
[ 99/336] Compiling FSMesh/src/FSStructDataset.cpp
[100/336] Compiling FSMesh/src/FSFaceBasedMeshCreator.cpp
[101/336] Compiling FSMesh/src/FSStructBlockInfo.cpp
[102/336] Compiling FSMesh/src/FSStructBlockBase.cpp
[103/336] Linking build/libFSCommon.dylib
### ... but swig generated .cxx is only started now ###
[104/336] Compiling build/FSDataManager/include/FSDataManager.swigwrap_16.cxx
```

Could it be that the high-priority .cxx task is only considered after one "group" (the one for the FSCommon shared library) is complete?

**Comment by q-p** [comment]
One additional observation: When I cancel (CTRL-C) the above build after step 70 (so after swig has generated the .cxx) and then restart it, *then* the generated, high-priority .cxx file is treated first (as hoped):
```
> ./waf # second invocation after abort
Waf: Entering directory `/Users/maven/Development/dlr/flowsim/FSDM/build'
[  2/336] Compiling build/FSDataManager/include/FSDataManager.swigwrap_16.cxx
[ 46/336] Linking build/libFSCommon.dylib
[ 65/336] Compiling FSMesh/src/FSUnstructMeshData_Redistribute.cpp
[ 69/336] Compiling FSMesh/src/FSUnstructMeshData.cpp
[ 71/336] Compiling FSMesh/src/FSUnstructCellPool.cpp
...
```

**Comment by q-p** [comment]
Ok, after some more print debugging the following seems to be the case:
- The priorities (and subsequent order) in `Parallel.outstanding` are as expected, in particular after adding the `more_tasks` from e.g. the swig-task
- The high-priority task is then processed immediately, it is ready to run, and moved to `Parallel.ready`
- But at that point, `Parallel.ready` already contains 31 entries (GAP (=5) * njobs (=8)) and therefore it takes a long while for it to be really executed
- If I replace `Parallel.ready` (which is a `Queue`) by a `PriorityQueue` (only available since Python 2.6), then it works as expected

**Comment by q-p** [comment]
As what I'm building requires Python 2.6 anyhow, I'm fine with just replacing `Queue` with `PriorityQueue` in my included waf. One probably could also replace the `Runner.Parallel.ready` instance in the class, but that doesn't seem any better than just changing it directly in my included waf.

Why would conditionally using `PriorityQueue` instead of `Queue` (for `.ready`) break the API?

**Comment by ita1024** [comment]
Changing the current type can simply break existing projects. It should be implemented in a later version such as Waf 2.1.

**Comment by ita1024** [comment]
Setting a `PriorityQueue` does not seem to impact performance negatively, and the risk of someone depending on the exact Queue type seems low enough. Update your copy.

**Comment by q-p** [comment]
Yup, that works fine for me. Thanks!

Now I'm only running a modified swig waf-tool that forwards its weight to its compilation task, the rest is "stock" waf... :)

**Comment by ita1024** [comment]
For the swig tool, there are a few concerns:

Weights can be declared in a variety of several places:
1. As a constant in the swig module
2. On the swig class (as you did)
3. On the task generator (`swig_weight`?)

And it can be applied in any of the following or as a combination:
1. To the swig task instances
2. To the c++ classes created by the swig tool
3. To the link task (most likely present)

Finally, this weight can be also applied by overwriting the existing value, or by adding to the existing value.

If you believe that one approach is better then the other, then please update your `swig.py` file and submit a pull request.

**Comment by ita1024** [comment]
Thanks.
