### ISSUE TITLE
Print include paths relative to project root dir?

### ISSUE THREAD

**Issue by mimon** [waf-project/waf#2139]
I'm trying to generate a .clang-complete file that contains all c++ include directories for my project. Clang-complete is a linter I have in my text editor and it would be neat if I could use WAF to generate that file.

My taskgen looks like this:
```
bld(rule='echo "${CXXFLAGS} ${FRAMEWORKPATH_ST:FRAMEWORKPATH} ${CPPPATH_ST:INCPATHS} ${DEFINES_ST:DEFINES} ${CXX_SRC_F}${SRC} ${CPPFLAGS}" > ${TGT}', target='../.clang_complete', use='my_app', features='cxx', name = 'clang_complete')
```

The resulting .clang-complete contains all include dirs separated by a space, but they all have a '../' too many because WAF has generated the include dirs relative to the build directory where as my .clang-complete is located in the project root. Is there any easy way to have WAF print paths relative to wscript root?

**Comment by ita1024** [comment]
Try setting the working directory: `bld(rule='pwd', cwd='/opt', always=True)`

Else, try a function instead of a rule string.

**Comment by ita1024** [comment]
The question was answered two weeks ago, closing now.
