### ISSUE TITLE
unit test fails to execute on Windows, when adding an argument

### ISSUE THREAD

**Issue by voodoo66** [waf-project/waf#2141]
Using latest waf version 2.0.7 to build an unit test using the 'waf_unit_test' tool works,
but adding an additional argument via ut_cmd, e.g.:
``ut_cmd = '%s -silent'``
the executable can not be found and execution fails.

I tried to debug the code and found that in waf_unit_test.py the following code causes the issue:
``self.ut_exec = shlex.split(ut_cmd % ' '.join(self.ut_exec))``
The function shlex.split enables posix by default, which escapes Windows paths like:
``C:\devel\tool.exe`` to ``C:develtool.exe``

The following code fixes it, but I don't know if this breaks working with other shells:
``self.ut_exec = shlex.split(ut_cmd % ' '.join(self.ut_exec), posix = not Utils.is_win32)``

I hope this helps to fix the issue.
Thanks

**Comment by ita1024** [comment]
There is no `posix` argument to `shlex.split` on Python 2.5, so such change will not happen, also the parameter `ut_cmd` is not documented anywhere in the codebase (unlike `ut_str`).

Subclass the class `utest` and implement its method `run` in your own build scripts, or use `ut_str` as in the examples?

**Comment by voodoo66** [comment]
Ok, thank you for the hint, seems I missed it in the examples.
So this is not a bug at all and I will close the ticket.
