### ISSUE TITLE
typo in find_program documentation

### ISSUE THREAD

**Issue by voodoo66** [waf-project/waf#2142]
Just noticed that the documentation for Configure.find_program states the key argument for extensions is called:
``ext``
but in the code it is:
``exts``
``exts = kw.get('exts', Utils.is_win32 and '.exe,.com,.bat,.cmd' or ',.sh,.pl,.py')``

Can you fix it for the next release?
Thanks.

**Comment by ita1024** [comment]
Or you could submit a pull request too.

**Comment by voodoo66** [comment]
Ok, I will try.
Thanks.
