### ISSUE TITLE
wrong python interpreter 

### ISSUE THREAD

**Issue by teto** [waf-project/waf#2144]
I am trying to package ns3 (www.nsnam.org) for nixos but the python bindings don't work because waf detection uses a different python interpreter than the one I specified in the command line. 

ns3-dev uses waf 1.8.19 (abi 98, python 30604f0 on linux)

basically I call `./waf configure --with-python=/nix/store/75c11202xfgpw3jdwzzxphia1v0jd5d4-python3-3.6.4-env/bin/python3.6m ...`
but then the following part of ns3 code (https://github.com/nsnam/ns-3-dev-git/blob/428199ed95e4c07bb1ecba894f0d9dff886ce1cd/bindings/python/wscript#L112) uses another python interpreter /nix/store/azw9ys2m2fpfzf730xjcxja890gpyp58-python3-3.6.4/bin/python even though ns3 wscript sets `conf.env.PYTHON`

```

    if Options.options.with_python is not None:
        conf.env.PYTHON = Options.options.with_python
# the correct value of the python interpreter (aka the one from the command line) is displayed here
        print("SETTING PYTHON to %s" % Options.options.with_python)

# starting from here, waf will use another python interpreter :s 
    try:
        conf.load('python')
    except Errors.ConfigurationError as ex:
        conf.report_optional_feature("python", "Python Bindings", False,
                                     "The python interpreter was not found")
        return


    try:
        conf.check_python_version((2,3))
    except Errors.ConfigurationError as ex:
        conf.report_optional_feature("python", "Python Bindings", False,
                                     "The python found version is too low (2.3 required)")
        return
```
Is setting `conf.env.PYTHON` not good ? how can I pass the python interpreter to waf        `conf.load('python')`

I've seen some similar issues on the tracker with older versions of waf but not the solutions really.
Thanks for the great soft

**Comment by ita1024** [comment]
Setting `conf.env.PYTHON` or passing `--python=` is usually sufficient, but the specifics of ns-3 are unknown to us. Try contacting the ns-3 folks? Else, check your `PATH` and/or try calling waf with the same interpreter. The `config.log` file may have some useful information too.
