### ISSUE TITLE
problem using with emcc

### ISSUE THREAD

**Issue by nybbs2003** [waf-project/waf#2147]
Hello!

I intend to use waf with emscripten being C complier. I see that there is a .py file with emcc support in the respo. but failed using it either with binary file from offical website, or compiled form source code.

Please show some hint on how to make it work.

Thanks!

**Comment by ita1024** [comment]
That file was user-contributed, does not feature any example and only supports linux (apparently). Try building a custom waf file that includes that file? Try looking in the config.log file? Else, you may want to get inspiration from it and write your own.

**Comment by nybbs2003** [comment]
@ita1024 Thank you for your quick reply, still keep trying....

**Comment by zougloub** [comment]
Hi @nybbs2003, I contributed this tool in 2015 as we were using emscripten at work, but everything went to hell and since then I haven't touched it, which might explain if it's not working anymore... but it would mean they greatly changed the compiler command-line interface.

Taking a look, building a hello world project on my end, and maybe I'll see something. If you have errors, please paste them.

**Comment by zougloub** [comment]
Yeah you'll have to be more precise on what you're seeing, because at least this works:
```
$ mkdir -p ~/.local/opt/emscripten
$ cd ~/.local/opt/emscripten
$ git clone https://github.com/juj/emsdk.git --depth=1 --recursive
$ cd emsdk
$ ./emsdk update
$ ./emsdk activate latest
$ . emsdk_env.sh 
$ mkdir -p ~/tmp/emcc
$ cd ~/tmp/emcc
$ touch test.c
$ cat << EOF > wscript
def options(opt):
	opt.load("compiler_c")

def configure(cfg):
	cfg.load("compiler_c")

def build(bld):
	bld(
	 features="c cshlib",
	 source = 'test.c',
	 target = 'test',
   )
EOF
$ CC=emcc waf configure
Setting top to                           : /home/cJ/tmp/emcc
Setting out to                           : /home/cJ/tmp/emcc/build
Checking for 'gcc' (C compiler)          : not found
Checking for 'clang' (C compiler)        : not found
Checking for 'icc' (C compiler)          : not found
Checking for 'c_bgxlc' (C compiler)      : not found
Checking for 'c_emscripten' (C compiler) : emcc
'configure' finished successfully (1.085s)
$ waf
Waf: Entering directory `/home/cJ/tmp/emcc/build'
[1/2] Compiling test.c
[2/2] Linking build/test.js
INFO:root:generating system library: dlmalloc.bc... (this will be cached in "/home/cJ/.emscripten_cache/asmjs/dlmalloc.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libc.bc... (this will be cached in "/home/cJ/.emscripten_cache/asmjs/libc.bc" for subsequent builds)
INFO:root: - ok

Waf: Leaving directory `/home/cJ/tmp/emcc/build'
'build' finished successfully (1m30.247s)
```

**Comment by zougloub** [comment]
I was testing using latest waf and emsdk (`emcc (Emscripten gcc/clang-like replacement) 1.37.37 (commit af66c0ce2ffe181e95987f56600f2d649ff46c16)`).

My emcc does:
```
Checking for 'clang' (C compiler)
find program=['clang'] paths=['/home/cJ/.local/opt/emsdk/emsdk', '/home/cJ/.local/opt/emsdk/emsdk/clang/e1.37.37>
['emcc', '-dM', '-E', '-']
err: ERROR:root:no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.C>
```
and then later the emcc detection catches it.

**Comment by nybbs2003** [comment]
@zougloub Thank you for your patient reply!
With the latest version of emsdk, I can run the above example successfully.

Hint for those who see this issue next: better check the ~/.emscripten file and set the right path of `LLVM_ROOT` to the uncompressed path of clang in emsdk, if `Could not determine the compiler version` is found for `c_emscripten` in config.log .
