### ISSUE TITLE
Error while trying to build conda package for waf

### ISSUE THREAD

**Issue by nicoddemus** [waf-project/waf#2158]
Hi everyone!

I'm one of the maintainers of the [`waf` package on conda-forge](https://github.com/conda-forge/waf-feedstock). We have `waf` as a conda package so that conda users can use `waf` in their projects (and some other packages also use `waf`, for example PyInstaller).

I'm writing because the package has been working fine until `1.9.12` but is failing to build on the latest versions (have tried `2.0.5` and `2.0.7` so far).

A quick introduction: conda build works in two steps, the *build* step and the *test* step. On the build step, conda will create an environment exclusive for that package construction, then will install all dependencies and execute the "build" script (we use ` python waf-light --make-waf --tool=swig,cython,boost,use_config`). The result of the build step is a conda package. After the build step, conda will start the *test* step: it will create a conda environment just with the recent built package and any runtime dependencies, and then run a series of commands to ensure things are working.

We've not been able to build `waf` again since `2.0.5`: the package is built, but when we execute `waf --help` to test it, the [build fails with](https://circleci.com/gh/conda-forge/waf-feedstock/27?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):

```
+ waf --help
  File "/feedstock_root/build_artefacts/waf_1522900890747/_t_env/bin/waf", line 165, in <module>
    Scripting.waf_entry_point(cwd, VERSION, wafdir)
  File "/feedstock_root/build_artefacts/waf_1522900890747/_t_env/bin/.waf-2.0.5-f6dd660db907c9792c60a1af40e73b25/waflib/Scripting.py", line 101, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/feedstock_root/build_artefacts/waf_1522900890747/_t_env/bin/.waf-2.0.5-f6dd660db907c9792c60a1af40e73b25/waflib/Scripting.py", line 141, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/feedstock_root/build_artefacts/waf_1522900890747/_t_env/bin/.waf-2.0.5-f6dd660db907c9792c60a1af40e73b25/waflib/Context.py", line 356, in load_module
    raise Errors.WafError('Could not read the file %r'%path)
 
Could not read the file '/feedstock_root/build_artefacts/waf_1522900890747/test_tmp/wscript'
```

I noticed that it seems `waf` now requires a `wscript` even for the `--help` option, so I went ahead and added a simple `wscript`:

```python
# simple script to test if waf is working
 
def configure(conf):
    print("configure!")
 
def build(bld):
    print("build!")
```

And changed the "test" commands to:

```yaml
  commands:
    - waf --help
    - waf configure
    - waf build
```

I tested the script manually using the commands above and they work, but when they execute under `conda-build` the last command fails with:

```
+ waf configure
------> Executing code from the top-level wscript <-----
Setting top to                           : /feedstock_root/build_artefacts/waf_1525210807516/test_tmp 
Setting out to                           : /feedstock_root/build_artefacts/waf_1525210807516/test_tmp/build 
Checking for program 'python'            : /feedstock_root/build_artefacts/waf_1525210807516/_t_env/bin/python 
'configure' finished successfully (0.024s)
+ waf build
------> Executing code from the top-level wscript <-----
Waf: Entering directory `/feedstock_root/build_artefacts/waf_1525210807516/test_tmp/build'
[1/1] Creating waf
-> preparing 'tmp-waf-2.0.7'
Waf: Leaving directory `/feedstock_root/build_artefacts/waf_1525210807516/test_tmp/build'
Build failed
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/waf_1525210807516/_t_env/bin/.waf-2.0.7-d15dfd58cb585e9f662211ef2e697e4c/waflib/Task.py", line 156, in process
    ret=self.run()
  File "/feedstock_root/build_artefacts/waf_1525210807516/test_tmp/wscript", line 263, in create_waf
    for k in os.listdir(dd):
OSError: [Errno 2] No such file or directory: 'waflib/.'
```

I don't know how waf works so I'm at a loss of what could be the problem here, or why it does work when I execute the commands manually. 

Any pointers are appreciated!

**Comment by ita1024** [comment]
1. Do not make packages of Waf, or call the result by another name. The extensions `swig cython boost and use_config` are user contributions that have no guarantee of stability whatsoever.
2. You have created a nested project, and `Executing code from the top-level wscript` indicates that the top-level folder is used. Try and run your commands from the appropriate folder.

**Comment by nicoddemus** [comment]
Thanks for the prompt reply folks!

@fedepell 

> Do you have $WAFDIR exported pointing someplace? 

No, I don't configure `$WAFDIR`.

> Or where is waf located and which are its permissions?

It is located in the `bin` (`Scripts` on Windows) directory of the conda environment, which is the `$PATH`. The script works for `waf --help` and `waf configure` commands, but fails at the end of `waf build`.

@ita1024

> Do not make packages of Waf, or call the result by another name.

Is that a license restriction? If so I apologize and we will remove the feedstock. Please notice that the name of the package is still `waf` (users install with `conda install waf`), only the repository is named as such because that's the convention for all conda-forge's feedstocks (which are repositories containing the meta information to build a package, not the source contents).

Is `waf` distributed with Windows, Linux and MacOs binaries? I ask because I could only find Linux binaries. Having it in conda makes it simple for users to install in any environment and for conda-forge to build other packages which depend on `waf`.

> You have created a nested project, and Executing code from the top-level wscript indicates that the top-level folder is used. Try and run your commands from the appropriate folder.

Hmm can you please elaborate? I'm not a `waf` user.

Just to clarify, during the *test* stage (which is currently failing), conda does roughly the following:

1. Create and activate an environment with `waf` and its dependencies.
1. Create a new temporary folder;
1. Copy the `wscript` file to the temporary folder;
1. Change the current directory to the temporary folder and run: 

   * `waf --help`
   * `waf configure`
   * `waf build`

The last step fails:

```
Build failed
Traceback (most recent call last):
  File "W:\Miniconda\conda-bld\waf_1525261417230\_test_env\Scripts\waf3-2.0.7-1368ea6f2e2303604a06f4dd78e7782e\waflib\Task.py", line 156, in process
    ret=self.run()
  File "W:\Miniconda\conda-bld\waf_1525261417230\test_tmp\wscript", line 263, in create_waf
    for k in os.listdir(dd):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'waflib\\.'
```

The temporary folder contains only these files:

```
conda_test_runner.bat  # activates the test environment and runs 'run_test.bat'
run_test.bat  # run the test commands mentioned above
wscript  # the wscript
```

If I manually activate the test environment, go to the temporary directory and try to run the commands or simply `waf`, I get the same error.

Here's an example of a temporary folder, the `python.exe` of the related testing environment and the location of the `waf` executable:

```
W:\Miniconda\conda-bld\waf_1525261417230\test_tmp
W:\Miniconda\conda-bld\waf_1525261417230\_test_env\python.exe
W:\Miniconda\conda-bld\waf_1525261417230\_test_env\Scripts\waf.exe
```

One last detail that might be relevant, we copy the `waf` binary to `$CONDA_PREFIX/bin` (Linux) or `%CONDA_PREFIX%/Scripts` (Windows) because the binary built during `python waf-light --make-waf --tool=swig,cython,boost,use_config` is left at the root of the directory. Perhaps we are missing some "install"-like command?

**Comment by ita1024** [comment]
1. That Conda package should be removed.
2. The command outputs indicate that the sub-project is never used. Run the commands from the appropriate folder, and make sure that your project defines a top-level folder (`top=..`).

**Comment by nicoddemus** [comment]
> That Conda package should be removed.

Sorry, could you elaborate on the reasons for that? I think we would like a clear reason if possible so we can justify pulling a package from conda-forge (cc @jakirkham).

Also, are there ready-to-use binaries for Windows and OS-X? I would be happy to then replace using `waf` conda-package to use the binaries directly when building dependent projects.

>The command outputs indicate that the sub-project is never used. Run the commands from the appropriate folder, and make sure that your project defines a top-level folder (top=..).

Thanks for the pointer, I will try that and failing it I will take some time to dig into the documentation.

Thanks again for taking the time to reply.

**Comment by nicoddemus** [comment]
> The waf file is a Python script that contains no platform-specific data: the same Waf file runs directly on Linux, Windows or Mac, on Python 2/3 and on cPython, IronPython or Pypy.

Oh I did not realize that, thanks.

**Comment by jakirkham** [comment]
What is the binary stuff at the end of that Python file?

**Comment by jakirkham** [comment]
Have to say I'm a bit disappointed by the outcome of this issue. We have essentially asked for help building your software so that we can share it with others and the response seems to be don't bother. I guess that is an option, but I think that is suboptimal for both of us. Is there someone who would be willing to help?

**Comment by ita1024** [comment]
@jakirkham Do not hijack this thread. The answer was provided above (the simple wscript above is most likely missing `top='.'`)

**Comment by nicoddemus** [comment]
FWIW, IMHO @jakirkham is not hijacking this thread, as he and I have been discussing about this problem in https://github.com/conda-forge/waf-feedstock/pull/11 and https://github.com/conda-forge/waf-feedstock/pull/12.

The problem doesn't seem to be the `wscript`, because executing it works fine when using the provided binaries in https://waf.io (https://github.com/conda-forge/waf-feedstock/pull/12), but the exact same `wscript` does not work when we build `waf` from source (https://github.com/conda-forge/waf-feedstock/pull/11).
