### ISSUE TITLE
support standard $PKG_CONFIG env var naming

### ISSUE THREAD

**Issue by vapier** [waf-project/waf#2160]
the waf build logic looks for `PKGCONFIG` in the environment, but the standard naming is `PKG_CONFIG`.  can you support both, or just use the standard naming ?

here's the upstream m4 code that gets bundled in all autotool based projects:
https://cgit.freedesktop.org/pkg-config/tree/pkg.m4.in?h=pkg-config-0.29#n62

```
AC_ARG_VAR([PKG_CONFIG], [path to pkg-config utility])
AC_ARG_VAR([PKG_CONFIG_PATH], [directories to add to pkg-config's search path])
AC_ARG_VAR([PKG_CONFIG_LIBDIR], [path overriding pkg-config's built-in search path])
```

**Comment by ita1024** [comment]
The variable has been named PKGCONFIG in Waf for the past 10 years, and we have no compatibility objective with autotools.

**Comment by vapier** [comment]
you misunderstand.  i'm not saying you should be compatible with autotools, i'm pointing out that the canonical pkg-config project uses the name `PKG_CONFIG`, and that's what pretty much every other build system/project has picked up so things "just work".  it's like a one line change to waf to only support `PKG_CONFIG`, and probably two to support both.
