### ISSUE TITLE
Install_files can't find source files using cwd and relative_trick arguments

### ISSUE THREAD

**Issue by flanaman** [waf-project/waf#2161]
When trying to install files in a subdirectory, the `cwd` argument is not being used to create input nodes:

```
#/src_dir/wscript
subdir_node = bld.path.find_dir('subdir')
bld.install_files(
    '/target/dir',
    ['file.txt'],
    cwd=subdir_node,
    relative_trick=True)
```
This fails saying `source not found: 'file.txt'` even though it exists in `/src_dir/wscript/subdir/file.txt`.

Should `path=self.relative_base` get passed to `to_nodes`at https://github.com/waf-project/waf/blob/master/waflib/Build.py#L1000 ? Or perhaps there is something I'm not understanding.

**Comment by flanaman** [comment]
This fails with my suggested change, saying "WafError: source not found: 'blah/blah/rel3' ..."

I guess I'm confused because the `cwd` argument for `install_files` says

>  cwd: parent node for searching srcfile, when srcfile is not an instance of waflib.Node.Node

So it seems like source file paths as a strings (not nodes) should be passed relative to `cwd`. In terms of `test/install/wscript`, I would have thought that line 44 should be
```
bld.install_files('${PREFIX}', 'blah/rel3', relative_base=bld.path.search_node('blah').get_bld(), relative_trick=True)
```
instead of
```
bld.install_files('${PREFIX}', 'blah/blah/rel3', relative_base=bld.path.search_node('blah').get_bld(), relative_trick=True)
```
and indeed the test passes with that change as well as my suggested change above.

**Comment by ita1024** [comment]
The parameter `relative_base` is of preserving a sub-tree structure when installing files (alias for cwd). It has nothing to do with searching files from a particular folder (use `ant_glob` for that).

Does this answer your question?

**Comment by flanaman** [comment]
OK, thank you.
