### ISSUE TITLE
`docker` - containerized `waf` build projects cannot build simple test program - python2 or python3

### ISSUE THREAD

**Issue by sildeag** [waf-project/waf#2167]
Does anyone understand and know how to fix this problem?  I realize this isn't a `waf` problem but am hoping someone using `waf` has come across this problem before.

This is the relevant output from my `docker` containerized application:

`Checking for program 'swig'                          : /usr/bin/swig `
`Checking for program 'python'                        : /usr/bin/python `
`Checking for program 'qmake'                         : /usr/lib/x86_64-linux-gnu/qt5/bin/qmake ` 
`Checking for uic version                             : uic 5.5.1 `
`Found the Qt5 libraries in                           : /usr/lib/x86_64-linux-gnu ` 
`Checking for pkg-config version >= '0.1'             : yes ` 
`Checking for 'Qt5Sql'                                : yes `
`Checking for 'Qt5Xml'                                : yes `
`Checking for 'Qt5Widgets'                            : yes ` 
`Checking for 'Qt5Gui'                                : yes `
`Checking for 'Qt5Core'                               : yes `
`Checking for 'Qt5Network'                            : yes `
`Checking for 'Qt5Concurrent'                         : yes ` 
`Checking for 'Qt5DBus'                               : yes `
`Checking for 'Qt5XcbQpa'                             : yes `
`Checking for 'Qt5PrintSupport'                       : yes `
`Checking for 'Qt5EglDeviceIntegration'               : yes ` 
`Checking for 'Qt5Test'                               : yes `
`Checking for 'Qt5OpenGL'                             : yes ` 
`See if Qt files compile                              : no `
`See if Qt files compile with -fPIE                   : no `
`See if Qt files compile with -fPIC                   : no `
`See if Qt files compile with -std=c++11              : no `
`See if Qt files compile with ['-std=c++11', '-fPIE'] : no `
`See if Qt files compile with ['-std=c++11', '-fPIC'] : no` 
`Checking for swig version                            : 3.0.8 `
`Checking for python version >= 2.4                   : 2.7.12 `
`python-config                                        : /usr/bin/python-config `
`Asking python-config for pyembed '--cflags --libs --ldflags' flags : yes `
`Testing pyembed configuration                                      : Could not build a python embedded interpreter` 
`Testing pyembed configuration                                      : Could not build a python embedded interpreter`

**Comment by ita1024** [comment]
Read the `config.log file`: `Python.h` is missing

**Comment by sildeag** [comment]
Part of issue was: `ENV LANG=en_US.UTF-8` required in Dockerfile.
