### ISSUE TITLE
set_run_after

### ISSUE THREAD

**Issue by sildeag** [waf-project/waf#2172]
I would like to use this functionality, possibly described below, or anything simpler because I have found that inside a Docker container the link step to creating my shlib creating `essentia.so` happens after the examples are created using the shlib `essentia.so`.  The shlib is usually created first so is not a problem in the usual Ubuntu environment.  Hopefully, for people who know `python` and `waf` this might be easier than it is for me.  Any help would be appreciated.  

`class task_build(Task):`
` `   ` def task_build_essentia (ctx, sources, bld_libs):`
` `   `    ...`
` `   `def task_build_samples (ctx):`
` `   `    ...`

` `  `bld_tsk = task_build()   # instantiate class` 
` `  `tsk1 = bld_tsk.task_build_essentia  # not sure of whether to include arguments or not`
` `  `tsk2 = bld_tsk.task_build_samples`
` `  `tsk2.set_run_after(tsk1)`    
` `  `tsk1(ctx, sources, bld_libs)`
` `  `tsk2(ctx)`

**Comment by ita1024** [comment]
There is probably another problem to fix, like examples not "using" a library but adding link flags directly (`use` keyword).

The first step is to fix that and then one can consider adding a build group with `bld.add_group()`.

You should read the documentation.

**Comment by sildeag** [comment]
Thanks.
