### ISSUE TITLE
An option to force rebuild of a target on each run

### ISSUE THREAD

**Issue by dbogdanov** [waf-project/waf#2173]
Is that possible to force rebuild of a target on each ./waf run? 

```  
def write_pcfile(task):
    open('build/mylibrary.pc', 'w').write(ctx.env.pcfile)
    ctx(rule=write_pcfile,  name='write_pcfile', target='../essentia.pc')
```

This target saves a pkg-config file for my project and its contents depend on the waf configure results. However, once written for the first time, this file is never updated on consequent configurations and builds. My workaround is to run remove it or run ./waf clean every time.

**Comment by ita1024** [comment]
The input file must be specified as source attribute. There are lots of examples:
https://github.com/waf-project/waf/blob/master/demos/subst/wscript#L16

**Comment by dbogdanov** [comment]
This answers my question, thank you!
