### ISSUE TITLE
md5 based decider mechanism

### ISSUE THREAD

**Issue by grdanny** [waf-project/waf#2177]
Hi There,

I hope I'm asking this in the right place (this isn't exactly an issue, more of a question).
We've been migrating our build systems from SCons to waf, and I was wondering if waf has functionality that is similar to the md5 decider in SCons

https://scons.org/doc/2.0.1/HTML/scons-user.html#AEN855

For example, if I have this simple wscript:

```
def build(bld):
    start = bld.path.ant_glob("src/start.txt")
    tgt1  = bld.path.find_or_declare("tgt1.txt")
    tgt2  = bld.path.find_or_declare("tgt2.txt")
    tgt3  = bld.path.find_or_declare("tgt3.txt")

    tsk = bld(
        rule         = "echo hello_world > ${TGT}",
        source       = start[0],
        target       = tgt1,
    )

    tsk = bld(
        rule         = "cp ${SRC} ${TGT}",
        source       = tgt1,
        target       = tgt2,
    )

    tsk = bld(
        rule         = "cp ${SRC} ${TGT}",
        source       = tgt2,
        target       = tgt3,
    )
```

Right now, if I change a character in "src/start.txt" then waf will rebuild all 3 builders.
But the md5 hash for tgt1.txt always stays the same, so there is no real need to run tgt2 and tgt3 again.

Is there a way to customize waf to look at the md5 hash of a build target, and if it's the same, not trigger any additional builds that depend on that target?

Thanks for the help!

- Danny

**Comment by ita1024** [comment]
> Right now, if I change a character in "src/start.txt" then waf will rebuild all 3 builders.

Not unless `deep_inputs` is specified (waf 2.x)

**Comment by grdanny** [comment]
Thanks for replying so quickly.
So sounds like the default in waf 2.x does what we need.

Thanks!
