### ISSUE TITLE
waf 2.x install step running more than once.

### ISSUE THREAD

**Issue by grdanny** [waf-project/waf#2179]
Hi There,

We noticed that on waf 2.x the install part runs all the time (regardless of whether or not the file I'm installing is freshly generated or not).

So for example, if I have the following wscript.

```
def build(bld):
    start = bld.path.ant_glob("src/start.txt")
    tgt1  = bld.path.find_or_declare("tgt1.txt")

    tsk = bld(
        rule         = "cp ${SRC} ${TGT}",
        source       = start[0],
        target       = tgt1,
        install_path   = "/tmp/myinstallpath/"
    )
```
The first time I run "waf install" it'll do the build and the install.

And then each time I run "waf install" again, it'll redo the install step (even though the build didn't run, so the file is the same file).

```

> ./waf install
Waf: Entering directory `/net/homedirs/greenstein/waf_test/build'
[1/2] Compiling src/start.txt
+ install /tmp/myinstallpath/tgt1.txt (from build/tgt1.txt)
Waf: Leaving directory `/net/homedirs/greenstein/waf_test/build'
'install' finished successfully (0.032s)

> ./waf install
Waf: Entering directory `/net/homedirs/greenstein/waf_test/build'
- install /tmp/myinstallpath/tgt1.txt (from build/tgt1.txt)
Waf: Leaving directory `/net/homedirs/greenstein/waf_test/build'
'install' finished successfully (0.012s)

> ./waf install
Waf: Entering directory `/net/homedirs/greenstein/waf_test/build'
- install /tmp/myinstallpath/tgt1.txt (from build/tgt1.txt)
Waf: Leaving directory `/net/homedirs/greenstein/waf_test/build'
'install' finished successfully (0.025s)

```

In waf 1.x it used to only trigger the install if the build task ran. Is there a way to get back to that old behavior?

Thanks again!

- Danny

**Comment by ita1024** [comment]
The `-` character at the start of the line indicates that the file is not copied again (it turns to a `+` when the file is copied). The versions 1.9 and 1.8 behave in a similar manner.

**Comment by grdanny** [comment]
Ah - that makes sense. I think we were using pre 1.8.
Thanks for explaining.

Is there a way to suppress the print in the "-" case?

**Comment by ita1024** [comment]
Subclass `waflib.Build.inst` with a class of the same name, and override the method `do_install` for example.
