### ISSUE TITLE
Unable to load specified compiler

### ISSUE THREAD

**Issue by hpk-roquette** [waf-project/waf#2180]
I am trying to have two build variants, one for compiling and building my executable for my Ubuntu PC and one for compiling and building my executable for a certain embedded system. The only difference between the two builds is the compiler to use. However, I am not able to achieve this simple idea. 

My configure function is very simple and looks something like this 

```
def configure(ctx):

ctx.setenv('PC')
ctx.env.CC = '/path/to/compiler'
ctx.load('compiler_c')

ctx.setenv('Embed')
ctx.env.CC = '/path/to/other/compiler'
ctx.load('compiler_c')

```

The CC variable is not used the way I think it is used, but I don't understand what it does... I've read a few examples and the Waf book section about build variants and cross-compiling but it is still not clear to me.

After some research on google/stackoverflow I'm still stuck on this. 

I am able to specify the CC variable on launch of the waf script, but I would like to load the two compilers in the configure function and then use one of the two _env_ (PC/Embed) in the build function to compile with the proper compiler.

The idea being that when I run`$ waf build_PC `or `$ waf build_Embed`, waf _knows_ which compiler to take.

Thanks !

**Comment by ita1024** [comment]
There are missing classes to define the commands. Read https://github.com/waf-project/waf/blob/master/demos/variants/wscript#L65

**Comment by hpk-roquette** [comment]
I have indeed pasted this block of code already, with the right env names of course. 

Then, to build, I try to use this method ::
```
     bld.env = bld.all_envs['debug']
     bld.program(source='main.c', target='app2', includes='.')
```

The only difference I see is the _includes_, I do not have this in my script, is it necessary ?

I can always share the script if you would like.

Thank you for your response !

**Comment by ita1024** [comment]
1. Check the config.log file and the contents of `build/c4che/_cache.py`, then try `print(bld.env)` to view the data contents.
2. A `git grep` can tell you where the variable is used: https://github.com/waf-project/waf/blob/master/waflib/Tools/c.py#L20
3. Cross-compilation can be achieved in a variety of ways such as: https://github.com/waf-project/waf/blob/master/waflib/extras/cross_gnu.py
4. It is up to you to decide whether **includes** are necessary.

**Comment by hpk-roquette** [comment]
Thank you for your response, I was able to achieve what I wanted to do !
